#pragma once

#include "triton_matmul_kernel_accumulate_dgelu.h"
#include "triton_matmul_kernel_accumulate_gelu.h"
#include "triton_matmul_kernel_accumulate.h"
#include "triton_matmul_kernel_accumulate_transpose_a_dgelu.h"
#include "triton_matmul_kernel_accumulate_transpose_a_gelu.h"
#include "triton_matmul_kernel_accumulate_transpose_a.h"
#include "triton_matmul_kernel_accumulate_transpose_a_transpose_b_dgelu.h"
#include "triton_matmul_kernel_accumulate_transpose_a_transpose_b_gelu.h"
#include "triton_matmul_kernel_accumulate_transpose_a_transpose_b.h"
#include "triton_matmul_kernel_accumulate_transpose_b_dgelu.h"
#include "triton_matmul_kernel_accumulate_transpose_b_gelu.h"
#include "triton_matmul_kernel_accumulate_transpose_b.h"
#include "triton_matmul_kernel_bias_accumulate_dgelu.h"
#include "triton_matmul_kernel_bias_accumulate_gelu.h"
#include "triton_matmul_kernel_bias_accumulate.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_a_dgelu.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_a_gelu.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_a.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_a_transpose_b_dgelu.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_a_transpose_b_gelu.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_a_transpose_b.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_b_dgelu.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_b_gelu.h"
#include "triton_matmul_kernel_bias_accumulate_transpose_b.h"
#include "triton_matmul_kernel_bias_dgelu.h"
#include "triton_matmul_kernel_bias_gelu.h"
#include "triton_matmul_kernel_bias.h"
#include "triton_matmul_kernel_bias_transpose_a_dgelu.h"
#include "triton_matmul_kernel_bias_transpose_a_gelu.h"
#include "triton_matmul_kernel_bias_transpose_a.h"
#include "triton_matmul_kernel_bias_transpose_a_transpose_b_dgelu.h"
#include "triton_matmul_kernel_bias_transpose_a_transpose_b_gelu.h"
#include "triton_matmul_kernel_bias_transpose_a_transpose_b.h"
#include "triton_matmul_kernel_bias_transpose_b_dgelu.h"
#include "triton_matmul_kernel_bias_transpose_b_gelu.h"
#include "triton_matmul_kernel_bias_transpose_b.h"
#include "triton_matmul_kernel_dgelu.h"
#include "triton_matmul_kernel_gelu.h"
#include "triton_matmul_kernel.h"
#include "triton_matmul_kernel_transpose_a_dgelu.h"
#include "triton_matmul_kernel_transpose_a_gelu.h"
#include "triton_matmul_kernel_transpose_a.h"
#include "triton_matmul_kernel_transpose_a_transpose_b_dgelu.h"
#include "triton_matmul_kernel_transpose_a_transpose_b_gelu.h"
#include "triton_matmul_kernel_transpose_a_transpose_b.h"
#include "triton_matmul_kernel_transpose_b_dgelu.h"
#include "triton_matmul_kernel_transpose_b_gelu.h"
#include "triton_matmul_kernel_transpose_b.h"


#define NUM_MATMUL_KERNEL_PERMUTATIONS 48

const std::string TRITON_MATMUL_KERNEL_PTX_SOURCES[NUM_MATMUL_KERNEL_PERMUTATIONS] = {
        TRITON_MATMUL_KERNEL_0_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_1_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_2_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_3_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_4_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_5_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_6_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_7_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_8_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_9_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_10_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_11_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_12_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_13_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_14_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_15_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_16_SOURCE_PTX,
        TRITON_MATMUL_KERNEL_17_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_18_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_19_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_20_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_21_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_22_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_23_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_24_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_25_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_26_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_27_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_28_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_29_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_30_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_31_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_32_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_33_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_34_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_35_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_36_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_37_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_38_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_39_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_40_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_41_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_42_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_43_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_44_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_45_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_46_SOURCE_PTX, 
        TRITON_MATMUL_KERNEL_47_SOURCE_PTX, 
};


const int TRITON_MATMUL_KERNEL_SHARED_MEMORY_SIZES[NUM_MATMUL_KERNEL_PERMUTATIONS] = {
        TRITON_MATMUL_KERNEL_0_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_1_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_2_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_3_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_4_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_5_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_6_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_7_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_8_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_9_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_10_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_11_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_12_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_13_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_14_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_15_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_16_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_17_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_18_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_19_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_20_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_21_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_22_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_23_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_24_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_25_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_26_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_27_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_28_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_29_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_30_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_31_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_32_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_33_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_34_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_35_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_36_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_37_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_38_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_39_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_40_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_41_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_42_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_43_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_44_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_45_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_46_SHARED_MEMORY_SIZE,
        TRITON_MATMUL_KERNEL_47_SHARED_MEMORY_SIZE,
};


const int TRITON_MATMUL_KERNEL_NUM_WARPS[NUM_MATMUL_KERNEL_PERMUTATIONS] = {
        TRITON_MATMUL_KERNEL_0_NUM_WARPS,
        TRITON_MATMUL_KERNEL_1_NUM_WARPS,
        TRITON_MATMUL_KERNEL_2_NUM_WARPS,
        TRITON_MATMUL_KERNEL_3_NUM_WARPS,
        TRITON_MATMUL_KERNEL_4_NUM_WARPS,
        TRITON_MATMUL_KERNEL_5_NUM_WARPS,
        TRITON_MATMUL_KERNEL_6_NUM_WARPS,
        TRITON_MATMUL_KERNEL_7_NUM_WARPS,
        TRITON_MATMUL_KERNEL_8_NUM_WARPS,
        TRITON_MATMUL_KERNEL_9_NUM_WARPS,
        TRITON_MATMUL_KERNEL_10_NUM_WARPS,
        TRITON_MATMUL_KERNEL_11_NUM_WARPS,
        TRITON_MATMUL_KERNEL_12_NUM_WARPS,
        TRITON_MATMUL_KERNEL_13_NUM_WARPS,
        TRITON_MATMUL_KERNEL_14_NUM_WARPS,
        TRITON_MATMUL_KERNEL_15_NUM_WARPS,
        TRITON_MATMUL_KERNEL_16_NUM_WARPS,
        TRITON_MATMUL_KERNEL_17_NUM_WARPS,
        TRITON_MATMUL_KERNEL_18_NUM_WARPS,
        TRITON_MATMUL_KERNEL_19_NUM_WARPS,
        TRITON_MATMUL_KERNEL_20_NUM_WARPS,
        TRITON_MATMUL_KERNEL_21_NUM_WARPS,
        TRITON_MATMUL_KERNEL_22_NUM_WARPS,
        TRITON_MATMUL_KERNEL_23_NUM_WARPS,
        TRITON_MATMUL_KERNEL_24_NUM_WARPS,
        TRITON_MATMUL_KERNEL_25_NUM_WARPS,
        TRITON_MATMUL_KERNEL_26_NUM_WARPS,
        TRITON_MATMUL_KERNEL_27_NUM_WARPS,
        TRITON_MATMUL_KERNEL_28_NUM_WARPS,
        TRITON_MATMUL_KERNEL_29_NUM_WARPS,
        TRITON_MATMUL_KERNEL_30_NUM_WARPS,
        TRITON_MATMUL_KERNEL_31_NUM_WARPS,
        TRITON_MATMUL_KERNEL_32_NUM_WARPS,
        TRITON_MATMUL_KERNEL_33_NUM_WARPS,
        TRITON_MATMUL_KERNEL_34_NUM_WARPS,
        TRITON_MATMUL_KERNEL_35_NUM_WARPS,
        TRITON_MATMUL_KERNEL_36_NUM_WARPS,
        TRITON_MATMUL_KERNEL_37_NUM_WARPS,
        TRITON_MATMUL_KERNEL_38_NUM_WARPS,
        TRITON_MATMUL_KERNEL_39_NUM_WARPS,
        TRITON_MATMUL_KERNEL_40_NUM_WARPS,
        TRITON_MATMUL_KERNEL_41_NUM_WARPS,
        TRITON_MATMUL_KERNEL_42_NUM_WARPS,
        TRITON_MATMUL_KERNEL_43_NUM_WARPS,
        TRITON_MATMUL_KERNEL_44_NUM_WARPS,
        TRITON_MATMUL_KERNEL_45_NUM_WARPS,
        TRITON_MATMUL_KERNEL_46_NUM_WARPS,
        TRITON_MATMUL_KERNEL_47_NUM_WARPS
};


const int TRITON_MATMUL_KERNEL_BLOCK_SIZES_M[NUM_MATMUL_KERNEL_PERMUTATIONS] = {
        TRITON_MATMUL_KERNEL_0_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_1_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_2_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_3_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_4_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_5_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_6_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_7_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_8_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_9_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_10_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_11_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_12_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_13_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_14_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_15_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_16_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_17_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_18_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_19_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_20_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_21_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_22_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_23_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_24_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_25_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_26_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_27_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_28_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_29_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_30_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_31_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_32_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_33_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_34_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_35_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_36_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_37_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_38_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_39_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_40_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_41_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_42_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_43_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_44_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_45_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_46_BLOCK_SIZE_M,
        TRITON_MATMUL_KERNEL_47_BLOCK_SIZE_M
};


const int TRITON_MATMUL_KERNEL_BLOCK_SIZES_N[NUM_MATMUL_KERNEL_PERMUTATIONS] = {
        TRITON_MATMUL_KERNEL_0_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_1_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_2_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_3_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_4_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_5_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_6_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_7_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_8_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_9_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_10_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_11_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_12_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_13_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_14_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_15_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_16_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_17_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_18_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_19_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_20_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_21_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_22_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_23_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_24_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_25_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_26_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_27_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_28_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_29_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_30_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_31_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_32_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_33_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_34_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_35_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_36_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_37_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_38_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_39_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_40_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_41_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_42_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_43_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_44_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_45_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_46_BLOCK_SIZE_N,
        TRITON_MATMUL_KERNEL_47_BLOCK_SIZE_N
};

const std::string TRITON_MATMUL_KERNEL_FUNCTION_NAMES[NUM_MATMUL_KERNEL_PERMUTATIONS] = {
        TRITON_MATMUL_KERNEL_0_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_1_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_2_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_3_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_4_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_5_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_6_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_7_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_8_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_9_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_10_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_11_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_12_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_13_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_14_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_15_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_16_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_17_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_18_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_19_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_20_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_21_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_22_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_23_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_24_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_25_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_26_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_27_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_28_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_29_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_30_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_31_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_32_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_33_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_34_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_35_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_36_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_37_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_38_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_39_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_40_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_41_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_42_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_43_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_44_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_45_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_46_FUNCTION_NAME,
        TRITON_MATMUL_KERNEL_47_FUNCTION_NAME
};