/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_0_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel(
	.param .u64 matmul_kernel_param_0,
	.param .u64 matmul_kernel_param_1,
	.param .u64 matmul_kernel_param_2,
	.param .u32 matmul_kernel_param_3,
	.param .u32 matmul_kernel_param_4,
	.param .u32 matmul_kernel_param_5,
	.param .u32 matmul_kernel_param_6,
	.param .u32 matmul_kernel_param_7,
	.param .u32 matmul_kernel_param_8
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<74>;
	.reg .b16 	%rs<643>;
	.reg .b32 	%r<1422>;
	.reg .b64 	%rd<107>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r145, [matmul_kernel_param_8];
	ld.param.u32 	%r144, [matmul_kernel_param_5];
	ld.param.u32 	%r143, [matmul_kernel_param_4];
	ld.param.u32 	%r142, [matmul_kernel_param_3];
	ld.param.u64 	%rd24, [matmul_kernel_param_2];
	ld.param.u64 	%rd23, [matmul_kernel_param_1];
	ld.param.u64 	%rd22, [matmul_kernel_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r146, %ctaid.x;
	// end inline asm
$L__tmp1:
	.loc	2 40 22
	add.s32 	%r211, %r142, 127;
	.loc	2 40 28
	shr.s32 	%r212, %r211, 31;
	shr.u32 	%r213, %r212, 25;
	add.s32 	%r214, %r211, %r213;
	shr.s32 	%r215, %r214, 7;
$L__tmp2:
	.loc	2 40 22
	add.s32 	%r216, %r143, 255;
	.loc	2 40 28
	shr.s32 	%r217, %r216, 31;
	shr.u32 	%r218, %r217, 24;
	add.s32 	%r219, %r216, %r218;
	shr.s32 	%r220, %r219, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r222, %r220, 3;
	ld.param.u32 	%r223, [matmul_kernel_param_6];
	ld.param.u32 	%r224, [matmul_kernel_param_7];
	.loc	1 61 22
	div.s32 	%r225, %r146, %r222;
	.loc	1 62 29
	shl.b32 	%r226, %r225, 3;
	.loc	1 63 35
	sub.s32 	%r227, %r215, %r226;
	.loc	1 63 48
	min.s32 	%r228, %r227, 8;
	.loc	1 64 33
	rem.s32 	%r229, %r146, %r228;
	.loc	1 64 27
	add.s32 	%r230, %r226, %r229;
	mul.lo.s32 	%r231, %r225, %r222;
	sub.s32 	%r232, %r146, %r231;
	.loc	1 65 40
	div.s32 	%r233, %r232, %r228;
	.loc	1 74 23
	shl.b32 	%r1, %r230, 7;
	.loc	1 74 51
	mov.u32 	%r2, %tid.x;
	and.b32  	%r3, %r2, 31;
	shr.u32 	%r234, %r2, 2;
	bfe.u32 	%r235, %r2, 2, 6;
	or.b32  	%r236, %r235, 64;
	bfe.u32 	%r4, %r2, 5, 3;
	or.b32  	%r5, %r4, 8;
	or.b32  	%r6, %r4, 16;
	or.b32  	%r7, %r4, 24;
	.loc	1 74 38
	or.b32  	%r237, %r1, %r235;
	or.b32  	%r238, %r1, %r236;
	.loc	1 74 68
	rem.s32 	%r239, %r237, %r142;
	rem.s32 	%r240, %r238, %r142;
	.loc	1 75 23
	shl.b32 	%r241, %r233, 8;
	.loc	1 75 51
	shl.b32 	%r242, %r2, 3;
	and.b32  	%r8, %r242, 24;
	and.b32  	%r243, %r242, 248;
	.loc	1 75 38
	or.b32  	%r9, %r241, %r243;
	.loc	1 75 68
	rem.s32 	%r244, %r9, %r143;
	.loc	1 77 53
	mad.lo.s32 	%r245, %r239, %r223, %r8;
	mad.lo.s32 	%r246, %r240, %r223, %r8;
	.loc	1 77 22
	mul.wide.s32 	%rd37, %r245, 2;
	add.s64 	%rd25, %rd22, %rd37;
	mul.wide.s32 	%rd38, %r246, 2;
	add.s64 	%rd26, %rd22, %rd38;
	.loc	1 78 40
	shl.b32 	%r247, %r224, 3;
	.loc	1 78 52
	mad.lo.s32 	%r248, %r4, %r224, %r244;
	add.s32 	%r249, %r248, %r247;
	add.s32 	%r250, %r249, %r247;
	add.s32 	%r251, %r250, %r247;
	.loc	1 78 22
	mul.wide.s32 	%rd39, %r248, 2;
	add.s64 	%rd27, %rd23, %rd39;
	mul.wide.s32 	%rd40, %r249, 2;
	add.s64 	%rd28, %rd23, %rd40;
	mul.wide.s32 	%rd41, %r250, 2;
	add.s64 	%rd29, %rd23, %rd41;
	mul.wide.s32 	%rd42, %r251, 2;
	add.s64 	%rd30, %rd23, %rd42;
$L__tmp4:
	.loc	2 40 22
	add.s32 	%r252, %r144, 31;
$L__tmp5:
	.loc	1 103 33
	shl.b32 	%r256, %r224, 5;
	.loc	1 93 22
	setp.lt.s32 	%p13, %r252, 32;
	setp.gt.s32 	%p14, %r252, 31;
	.loc	1 96 72
	setp.lt.s32 	%p15, %r8, %r144;
	.loc	1 96 20
	xor.b32  	%r257, %r242, %r2;
	and.b32  	%r258, %r257, 24;
	shl.b32 	%r259, %r235, 5;
	or.b32  	%r11, %r259, %r258;
	shl.b32 	%r260, %r11, 1;
	mov.u32 	%r261, global_smem;
	add.s32 	%r147, %r261, %r260;
	shl.b32 	%r262, %r236, 5;
	or.b32  	%r12, %r262, %r258;
	shl.b32 	%r263, %r12, 1;
	add.s32 	%r149, %r261, %r263;
	selp.b32 	%r264, 16, 0, %p14;
	selp.b32 	%r150, %r264, 0, %p15;
	mov.pred 	%p1, -1;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r147 + 0 ], [ %rd25 + 0 ], 0x10, %r150;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r149 + 0 ], [ %rd26 + 0 ], 0x10, %r150;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 72
	setp.lt.s32 	%p16, %r4, %r144;
	setp.lt.s32 	%p17, %r5, %r144;
	setp.lt.s32 	%p18, %r6, %r144;
	setp.lt.s32 	%p19, %r7, %r144;
	.loc	1 97 20
	and.b32  	%r265, %r234, 56;
	xor.b32  	%r266, %r265, %r243;
	shl.b32 	%r267, %r4, 8;
	or.b32  	%r13, %r266, %r267;
	shl.b32 	%r268, %r13, 1;
	add.s32 	%r269, %r261, 16384;
	add.s32 	%r151, %r269, %r268;
	shl.b32 	%r270, %r5, 8;
	or.b32  	%r14, %r266, %r270;
	shl.b32 	%r271, %r14, 1;
	add.s32 	%r153, %r269, %r271;
	shl.b32 	%r272, %r6, 8;
	or.b32  	%r15, %r266, %r272;
	shl.b32 	%r273, %r15, 1;
	add.s32 	%r155, %r269, %r273;
	shl.b32 	%r274, %r7, 8;
	or.b32  	%r16, %r266, %r274;
	shl.b32 	%r275, %r16, 1;
	add.s32 	%r157, %r269, %r275;
	selp.b32 	%r152, %r264, 0, %p16;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r151 + 0 ], [ %rd27 + 0 ], 0x10, %r152;
	// end inline asm
	selp.b32 	%r154, %r264, 0, %p17;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r153 + 0 ], [ %rd28 + 0 ], 0x10, %r154;
	// end inline asm
	selp.b32 	%r156, %r264, 0, %p18;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r155 + 0 ], [ %rd29 + 0 ], 0x10, %r156;
	// end inline asm
	selp.b32 	%r158, %r264, 0, %p19;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r157 + 0 ], [ %rd30 + 0 ], 0x10, %r158;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p20, %r252, 63;
	.loc	1 102 18
	add.s64 	%rd31, %rd25, 64;
	add.s64 	%rd32, %rd26, 64;
	.loc	1 103 18
	mul.wide.s32 	%rd43, %r256, 2;
	add.s64 	%rd33, %rd27, %rd43;
	add.s64 	%rd34, %rd28, %rd43;
	add.s64 	%rd35, %rd29, %rd43;
	add.s64 	%rd36, %rd30, %rd43;
	.loc	1 96 53
	or.b32  	%r276, %r8, 32;
	.loc	1 96 72
	setp.lt.s32 	%p21, %r276, %r144;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r277, %r261, 8192;
	add.s32 	%r159, %r277, %r260;
	add.s32 	%r161, %r277, %r263;
	selp.b32 	%r278, 16, 0, %p20;
	selp.b32 	%r162, %r278, 0, %p21;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r159 + 0 ], [ %rd31 + 0 ], 0x10, %r162;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r161 + 0 ], [ %rd32 + 0 ], 0x10, %r162;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	or.b32  	%r17, %r4, 32;
	or.b32  	%r18, %r4, 40;
	or.b32  	%r19, %r4, 48;
	or.b32  	%r20, %r4, 56;
	.loc	1 97 72
	setp.lt.s32 	%p22, %r17, %r144;
	setp.lt.s32 	%p23, %r18, %r144;
	setp.lt.s32 	%p24, %r19, %r144;
	setp.lt.s32 	%p25, %r20, %r144;
	.loc	1 97 20
	add.s32 	%r279, %r261, 32768;
	add.s32 	%r163, %r279, %r268;
	add.s32 	%r165, %r279, %r271;
	add.s32 	%r167, %r279, %r273;
	add.s32 	%r169, %r279, %r275;
	selp.b32 	%r164, %r278, 0, %p22;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r163 + 0 ], [ %rd33 + 0 ], 0x10, %r164;
	// end inline asm
	selp.b32 	%r166, %r278, 0, %p23;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r165 + 0 ], [ %rd34 + 0 ], 0x10, %r166;
	// end inline asm
	selp.b32 	%r168, %r278, 0, %p24;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r167 + 0 ], [ %rd35 + 0 ], 0x10, %r168;
	// end inline asm
	selp.b32 	%r170, %r278, 0, %p25;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r169 + 0 ], [ %rd36 + 0 ], 0x10, %r170;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	and.b32  	%r280, %r2, 7;
	bfe.u32 	%r21, %r2, 4, 1;
	bfe.u32 	%r22, %r2, 1, 2;
	shr.u32 	%r281, %r2, 3;
	and.b32  	%r23, %r281, 16;
	and.b32  	%r282, %r2, 15;
	or.b32  	%r283, %r282, %r23;
	xor.b32  	%r284, %r21, %r22;
	shl.b32 	%r285, %r284, 3;
	shl.b32 	%r24, %r283, 5;
	or.b32  	%r25, %r24, %r285;
	shl.b32 	%r286, %r25, 1;
	add.s32 	%r175, %r261, %r286;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1413, %r1414, %r1415, %r1416 }, [ %r175 + 0 ];
	// end inline asm
	add.s32 	%r180, %r175, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1409, %r1410, %r1411, %r1412 }, [ %r180 + 0 ];
	// end inline asm
	add.s32 	%r185, %r175, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1405, %r1406, %r1407, %r1408 }, [ %r185 + 0 ];
	// end inline asm
	add.s32 	%r190, %r175, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1401, %r1402, %r1403, %r1404 }, [ %r190 + 0 ];
	// end inline asm
	.loc	1 97 20
	bfe.u32 	%r42, %r2, 5, 2;
	shl.b32 	%r287, %r21, 2;
	or.b32  	%r288, %r287, %r42;
	xor.b32  	%r289, %r288, %r280;
	shl.b32 	%r290, %r289, 3;
	shl.b32 	%r291, %r282, 8;
	or.b32  	%r43, %r290, %r291;
	shl.b32 	%r292, %r43, 1;
	add.s32 	%r195, %r269, %r292;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1397, %r1398, %r1399, %r1400 }, [ %r195 + 0 ];
	// end inline asm
	or.b32  	%r293, %r288, 8;
	xor.b32  	%r294, %r293, %r280;
	shl.b32 	%r295, %r294, 3;
	add.s32 	%r48, %r295, %r291;
	shl.b32 	%r296, %r48, 1;
	add.s32 	%r200, %r269, %r296;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1393, %r1394, %r1395, %r1396 }, [ %r200 + 0 ];
	// end inline asm
	or.b32  	%r297, %r288, 16;
	xor.b32  	%r298, %r297, %r280;
	shl.b32 	%r299, %r298, 3;
	add.s32 	%r53, %r299, %r291;
	shl.b32 	%r300, %r53, 1;
	add.s32 	%r205, %r269, %r300;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1389, %r1390, %r1391, %r1392 }, [ %r205 + 0 ];
	// end inline asm
	or.b32  	%r301, %r288, 24;
	xor.b32  	%r302, %r301, %r280;
	shl.b32 	%r303, %r302, 3;
	add.s32 	%r58, %r303, %r291;
	shl.b32 	%r304, %r58, 1;
	add.s32 	%r210, %r269, %r304;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1385, %r1386, %r1387, %r1388 }, [ %r210 + 0 ];
	// end inline asm
	mov.b16 	%rs515, 0x0000;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	.loc	1 93 22
	@%p13 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd1, %r245;
	cvt.s64.s32 	%rd2, %r246;
	cvt.s64.s32 	%rd3, %r248;
	cvt.s64.s32 	%rd4, %r249;
	cvt.s64.s32 	%rd5, %r250;
	cvt.s64.s32 	%rd6, %r251;
	shr.s32 	%r253, %r252, 31;
	shr.u32 	%r254, %r253, 27;
	add.s32 	%r255, %r252, %r254;
	shr.s32 	%r10, %r255, 5;
	cvt.s64.s32 	%rd7, %r256;
	add.s32 	%r63, %r10, -2;
	or.b32  	%r309, %r21, 2;
	xor.b32  	%r310, %r309, %r22;
	shl.b32 	%r311, %r310, 3;
	or.b32  	%r64, %r24, %r311;
	.loc	1 93 22
	shl.b64 	%rd8, %rd6, 1;
	shl.b64 	%rd44, %rd7, 2;
	add.s64 	%rd106, %rd23, %rd44;
	shl.b64 	%rd10, %rd7, 1;
	shl.b64 	%rd11, %rd5, 1;
	shl.b64 	%rd12, %rd4, 1;
	shl.b64 	%rd13, %rd3, 1;
	shl.b64 	%rd45, %rd2, 1;
	add.s64 	%rd46, %rd45, %rd22;
	add.s64 	%rd105, %rd46, 128;
	shl.b64 	%rd47, %rd1, 1;
	add.s64 	%rd48, %rd47, %rd22;
	add.s64 	%rd104, %rd48, 128;
	or.b32  	%r65, %r8, 64;
	mov.b16 	%rs515, 0x0000;
	mov.b32 	%r1420, 1;
	mov.b32 	%r1384, 0;
	shl.b32 	%r1044, %r64, 1;
	mov.u32 	%r1417, %r269;
	mov.u32 	%r1418, %r261;
	mov.u32 	%r1419, %r1384;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	mov.u32 	%r1421, %r1384;
$L__BB0_2:
	setp.lt.s32 	%p32, %r1421, %r63;
	.loc	1 96 20
	add.s32 	%r316, %r1418, %r1044;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r728, %r729, %r730, %r731 }, [ %r316 + 0 ];
	// end inline asm
	add.s32 	%r321, %r316, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r808, %r809, %r810, %r811 }, [ %r321 + 0 ];
	// end inline asm
	add.s32 	%r326, %r316, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r888, %r889, %r890, %r891 }, [ %r326 + 0 ];
	// end inline asm
	add.s32 	%r331, %r316, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r968, %r969, %r970, %r971 }, [ %r331 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r1046, %r1417, %r292;
	add.s32 	%r336, %r1046, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r732, %r733, %r742, %r743 }, [ %r336 + 0 ];
	// end inline asm
	add.s32 	%r1048, %r1417, %r296;
	add.s32 	%r341, %r1048, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r752, %r753, %r762, %r763 }, [ %r341 + 0 ];
	// end inline asm
	add.s32 	%r1050, %r1417, %r300;
	add.s32 	%r346, %r1050, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r772, %r773, %r782, %r783 }, [ %r346 + 0 ];
	// end inline asm
	add.s32 	%r1052, %r1417, %r304;
	add.s32 	%r351, %r1052, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r792, %r793, %r802, %r803 }, [ %r351 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r724, {%rs515, %rs516};
	mov.b32 	%r725, {%rs517, %rs518};
	mov.b32 	%r734, {%rs519, %rs520};
	mov.b32 	%r735, {%rs521, %rs522};
	mov.b32 	%r744, {%rs523, %rs524};
	mov.b32 	%r745, {%rs525, %rs526};
	mov.b32 	%r754, {%rs527, %rs528};
	mov.b32 	%r755, {%rs529, %rs530};
	mov.b32 	%r764, {%rs531, %rs532};
	mov.b32 	%r765, {%rs533, %rs534};
	mov.b32 	%r774, {%rs535, %rs536};
	mov.b32 	%r775, {%rs537, %rs538};
	mov.b32 	%r784, {%rs539, %rs540};
	mov.b32 	%r785, {%rs541, %rs542};
	mov.b32 	%r794, {%rs543, %rs544};
	mov.b32 	%r795, {%rs545, %rs546};
	mov.b32 	%r804, {%rs547, %rs548};
	mov.b32 	%r805, {%rs549, %rs550};
	mov.b32 	%r814, {%rs551, %rs552};
	mov.b32 	%r815, {%rs553, %rs554};
	mov.b32 	%r824, {%rs555, %rs556};
	mov.b32 	%r825, {%rs557, %rs558};
	mov.b32 	%r834, {%rs559, %rs560};
	mov.b32 	%r835, {%rs561, %rs562};
	mov.b32 	%r844, {%rs563, %rs564};
	mov.b32 	%r845, {%rs565, %rs566};
	mov.b32 	%r854, {%rs567, %rs568};
	mov.b32 	%r855, {%rs569, %rs570};
	mov.b32 	%r864, {%rs571, %rs572};
	mov.b32 	%r865, {%rs573, %rs574};
	mov.b32 	%r874, {%rs575, %rs576};
	mov.b32 	%r875, {%rs577, %rs578};
	mov.b32 	%r884, {%rs579, %rs580};
	mov.b32 	%r885, {%rs581, %rs582};
	mov.b32 	%r894, {%rs583, %rs584};
	mov.b32 	%r895, {%rs585, %rs586};
	mov.b32 	%r904, {%rs587, %rs588};
	mov.b32 	%r905, {%rs589, %rs590};
	mov.b32 	%r914, {%rs591, %rs592};
	mov.b32 	%r915, {%rs593, %rs594};
	mov.b32 	%r924, {%rs595, %rs596};
	mov.b32 	%r925, {%rs597, %rs598};
	mov.b32 	%r934, {%rs599, %rs600};
	mov.b32 	%r935, {%rs601, %rs602};
	mov.b32 	%r944, {%rs603, %rs604};
	mov.b32 	%r945, {%rs605, %rs606};
	mov.b32 	%r954, {%rs607, %rs608};
	mov.b32 	%r955, {%rs609, %rs610};
	mov.b32 	%r964, {%rs611, %rs612};
	mov.b32 	%r965, {%rs613, %rs614};
	mov.b32 	%r974, {%rs615, %rs616};
	mov.b32 	%r975, {%rs617, %rs618};
	mov.b32 	%r984, {%rs619, %rs620};
	mov.b32 	%r985, {%rs621, %rs622};
	mov.b32 	%r994, {%rs623, %rs624};
	mov.b32 	%r995, {%rs625, %rs626};
	mov.b32 	%r1004, {%rs627, %rs628};
	mov.b32 	%r1005, {%rs629, %rs630};
	mov.b32 	%r1014, {%rs631, %rs632};
	mov.b32 	%r1015, {%rs633, %rs634};
	mov.b32 	%r1024, {%rs635, %rs636};
	mov.b32 	%r1025, {%rs637, %rs638};
	mov.b32 	%r1034, {%rs639, %rs640};
	mov.b32 	%r1035, {%rs641, %rs642};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r724, %r725 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1397, %r1398 }, { %r724, %r725 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r734, %r735 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1399, %r1400 }, { %r734, %r735 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r744, %r745 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1393, %r1394 }, { %r744, %r745 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r754, %r755 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1395, %r1396 }, { %r754, %r755 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r764, %r765 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1389, %r1390 }, { %r764, %r765 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r774, %r775 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1391, %r1392 }, { %r774, %r775 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r784, %r785 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1385, %r1386 }, { %r784, %r785 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r794, %r795 }, { %r1413, %r1414, %r1415, %r1416 }, { %r1387, %r1388 }, { %r794, %r795 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r804, %r805 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1397, %r1398 }, { %r804, %r805 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r814, %r815 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1399, %r1400 }, { %r814, %r815 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r824, %r825 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1393, %r1394 }, { %r824, %r825 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r834, %r835 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1395, %r1396 }, { %r834, %r835 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r844, %r845 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1389, %r1390 }, { %r844, %r845 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r854, %r855 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1391, %r1392 }, { %r854, %r855 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r864, %r865 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1385, %r1386 }, { %r864, %r865 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r874, %r875 }, { %r1409, %r1410, %r1411, %r1412 }, { %r1387, %r1388 }, { %r874, %r875 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r884, %r885 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1397, %r1398 }, { %r884, %r885 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r894, %r895 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1399, %r1400 }, { %r894, %r895 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r904, %r905 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1393, %r1394 }, { %r904, %r905 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r914, %r915 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1395, %r1396 }, { %r914, %r915 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r924, %r925 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1389, %r1390 }, { %r924, %r925 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r934, %r935 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1391, %r1392 }, { %r934, %r935 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r944, %r945 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1385, %r1386 }, { %r944, %r945 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r954, %r955 }, { %r1405, %r1406, %r1407, %r1408 }, { %r1387, %r1388 }, { %r954, %r955 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r964, %r965 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1397, %r1398 }, { %r964, %r965 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r974, %r975 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1399, %r1400 }, { %r974, %r975 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r984, %r985 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1393, %r1394 }, { %r984, %r985 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r994, %r995 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1395, %r1396 }, { %r994, %r995 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1004, %r1005 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1389, %r1390 }, { %r1004, %r1005 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1014, %r1015 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1391, %r1392 }, { %r1014, %r1015 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1024, %r1025 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1385, %r1386 }, { %r1024, %r1025 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1034, %r1035 }, { %r1401, %r1402, %r1403, %r1404 }, { %r1387, %r1388 }, { %r1034, %r1035 };
	// end inline asm
	.loc	1 103 18
	add.s64 	%rd51, %rd106, %rd13;
	add.s64 	%rd52, %rd106, %rd12;
	add.s64 	%rd53, %rd106, %rd11;
	.loc	1 93 22
	add.s64 	%rd54, %rd106, %rd8;
	add.s32 	%r1117, %r1420, 1;
	setp.lt.s32 	%p33, %r1117, 2;
	selp.b32 	%r1420, %r1117, 0, %p33;
	.loc	1 96 72
	add.s32 	%r1118, %r65, %r1384;
	setp.lt.s32 	%p34, %r1118, %r144;
	.loc	1 96 20
	shl.b32 	%r1119, %r1420, 13;
	add.s32 	%r1121, %r261, %r1119;
	bar.sync 	0;
	add.s32 	%r672, %r1121, %r260;
	add.s32 	%r674, %r1121, %r263;
	selp.b32 	%r1124, 16, 0, %p34;
	selp.b32 	%r675, %r1124, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r672 + 0 ], [ %rd104 + 0 ], 0x10, %r675;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r674 + 0 ], [ %rd105 + 0 ], 0x10, %r675;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	add.s32 	%r1125, %r4, %r1384;
	add.s32 	%r1126, %r1125, 64;
	add.s32 	%r1127, %r1125, 72;
	add.s32 	%r1128, %r1125, 80;
	.loc	1 97 72
	add.s32 	%r1129, %r1125, 88;
	setp.lt.s32 	%p35, %r1126, %r144;
	setp.lt.s32 	%p36, %r1127, %r144;
	setp.lt.s32 	%p37, %r1128, %r144;
	setp.lt.s32 	%p38, %r1129, %r144;
	.loc	1 97 20
	shl.b32 	%r1130, %r1420, 14;
	add.s32 	%r1132, %r269, %r1130;
	add.s32 	%r676, %r1132, %r268;
	add.s32 	%r678, %r1132, %r271;
	add.s32 	%r680, %r1132, %r273;
	add.s32 	%r682, %r1132, %r275;
	selp.b32 	%r1137, 16, 0, %p35;
	selp.b32 	%r677, %r1137, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r676 + 0 ], [ %rd51 + 0 ], 0x10, %r677;
	// end inline asm
	selp.b32 	%r1138, 16, 0, %p36;
	selp.b32 	%r679, %r1138, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r678 + 0 ], [ %rd52 + 0 ], 0x10, %r679;
	// end inline asm
	selp.b32 	%r1139, 16, 0, %p37;
	selp.b32 	%r681, %r1139, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r680 + 0 ], [ %rd53 + 0 ], 0x10, %r681;
	// end inline asm
	selp.b32 	%r1140, 16, 0, %p38;
	selp.b32 	%r683, %r1140, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r682 + 0 ], [ %rd54 + 0 ], 0x10, %r683;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1141, %r1419, 1;
	setp.lt.s32 	%p39, %r1141, 2;
	selp.b32 	%r1419, %r1141, 0, %p39;
	.loc	1 96 20
	shl.b32 	%r1142, %r1419, 13;
	add.s32 	%r1418, %r261, %r1142;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1143, %r1419, 14;
	add.s32 	%r1417, %r269, %r1143;
	.loc	1 96 20
	add.s32 	%r688, %r1418, %r286;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1413, %r1414, %r1415, %r1416 }, [ %r688 + 0 ];
	// end inline asm
	add.s32 	%r693, %r688, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1409, %r1410, %r1411, %r1412 }, [ %r693 + 0 ];
	// end inline asm
	add.s32 	%r698, %r688, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1405, %r1406, %r1407, %r1408 }, [ %r698 + 0 ];
	// end inline asm
	add.s32 	%r703, %r688, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1401, %r1402, %r1403, %r1404 }, [ %r703 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r708, %r1417, %r292;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1397, %r1398, %r1399, %r1400 }, [ %r708 + 0 ];
	// end inline asm
	add.s32 	%r713, %r1417, %r296;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1393, %r1394, %r1395, %r1396 }, [ %r713 + 0 ];
	// end inline asm
	add.s32 	%r718, %r1417, %r300;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1389, %r1390, %r1391, %r1392 }, [ %r718 + 0 ];
	// end inline asm
	add.s32 	%r723, %r1417, %r304;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1385, %r1386, %r1387, %r1388 }, [ %r723 + 0 ];
	// end inline asm
	.loc	1 100 35
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r724, %r725 }, { %r728, %r729, %r730, %r731 }, { %r732, %r733 }, { %r724, %r725 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r734, %r735 }, { %r728, %r729, %r730, %r731 }, { %r742, %r743 }, { %r734, %r735 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r744, %r745 }, { %r728, %r729, %r730, %r731 }, { %r752, %r753 }, { %r744, %r745 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r754, %r755 }, { %r728, %r729, %r730, %r731 }, { %r762, %r763 }, { %r754, %r755 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r764, %r765 }, { %r728, %r729, %r730, %r731 }, { %r772, %r773 }, { %r764, %r765 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r774, %r775 }, { %r728, %r729, %r730, %r731 }, { %r782, %r783 }, { %r774, %r775 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r784, %r785 }, { %r728, %r729, %r730, %r731 }, { %r792, %r793 }, { %r784, %r785 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r794, %r795 }, { %r728, %r729, %r730, %r731 }, { %r802, %r803 }, { %r794, %r795 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r804, %r805 }, { %r808, %r809, %r810, %r811 }, { %r732, %r733 }, { %r804, %r805 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r814, %r815 }, { %r808, %r809, %r810, %r811 }, { %r742, %r743 }, { %r814, %r815 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r824, %r825 }, { %r808, %r809, %r810, %r811 }, { %r752, %r753 }, { %r824, %r825 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r834, %r835 }, { %r808, %r809, %r810, %r811 }, { %r762, %r763 }, { %r834, %r835 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r844, %r845 }, { %r808, %r809, %r810, %r811 }, { %r772, %r773 }, { %r844, %r845 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r854, %r855 }, { %r808, %r809, %r810, %r811 }, { %r782, %r783 }, { %r854, %r855 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r864, %r865 }, { %r808, %r809, %r810, %r811 }, { %r792, %r793 }, { %r864, %r865 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r874, %r875 }, { %r808, %r809, %r810, %r811 }, { %r802, %r803 }, { %r874, %r875 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r884, %r885 }, { %r888, %r889, %r890, %r891 }, { %r732, %r733 }, { %r884, %r885 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r894, %r895 }, { %r888, %r889, %r890, %r891 }, { %r742, %r743 }, { %r894, %r895 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r904, %r905 }, { %r888, %r889, %r890, %r891 }, { %r752, %r753 }, { %r904, %r905 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r914, %r915 }, { %r888, %r889, %r890, %r891 }, { %r762, %r763 }, { %r914, %r915 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r924, %r925 }, { %r888, %r889, %r890, %r891 }, { %r772, %r773 }, { %r924, %r925 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r934, %r935 }, { %r888, %r889, %r890, %r891 }, { %r782, %r783 }, { %r934, %r935 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r944, %r945 }, { %r888, %r889, %r890, %r891 }, { %r792, %r793 }, { %r944, %r945 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r954, %r955 }, { %r888, %r889, %r890, %r891 }, { %r802, %r803 }, { %r954, %r955 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r964, %r965 }, { %r968, %r969, %r970, %r971 }, { %r732, %r733 }, { %r964, %r965 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r974, %r975 }, { %r968, %r969, %r970, %r971 }, { %r742, %r743 }, { %r974, %r975 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r984, %r985 }, { %r968, %r969, %r970, %r971 }, { %r752, %r753 }, { %r984, %r985 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r994, %r995 }, { %r968, %r969, %r970, %r971 }, { %r762, %r763 }, { %r994, %r995 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1004, %r1005 }, { %r968, %r969, %r970, %r971 }, { %r772, %r773 }, { %r1004, %r1005 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1014, %r1015 }, { %r968, %r969, %r970, %r971 }, { %r782, %r783 }, { %r1014, %r1015 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1024, %r1025 }, { %r968, %r969, %r970, %r971 }, { %r792, %r793 }, { %r1024, %r1025 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1034, %r1035 }, { %r968, %r969, %r970, %r971 }, { %r802, %r803 }, { %r1034, %r1035 };
	// end inline asm
	mov.b32 	{%rs515, %rs516}, %r724;
	mov.b32 	{%rs517, %rs518}, %r725;
	mov.b32 	{%rs519, %rs520}, %r734;
	mov.b32 	{%rs521, %rs522}, %r735;
	mov.b32 	{%rs523, %rs524}, %r744;
	mov.b32 	{%rs525, %rs526}, %r745;
	mov.b32 	{%rs527, %rs528}, %r754;
	mov.b32 	{%rs529, %rs530}, %r755;
	mov.b32 	{%rs531, %rs532}, %r764;
	mov.b32 	{%rs533, %rs534}, %r765;
	mov.b32 	{%rs535, %rs536}, %r774;
	mov.b32 	{%rs537, %rs538}, %r775;
	mov.b32 	{%rs539, %rs540}, %r784;
	mov.b32 	{%rs541, %rs542}, %r785;
	mov.b32 	{%rs543, %rs544}, %r794;
	mov.b32 	{%rs545, %rs546}, %r795;
	mov.b32 	{%rs547, %rs548}, %r804;
	mov.b32 	{%rs549, %rs550}, %r805;
	mov.b32 	{%rs551, %rs552}, %r814;
	mov.b32 	{%rs553, %rs554}, %r815;
	mov.b32 	{%rs555, %rs556}, %r824;
	mov.b32 	{%rs557, %rs558}, %r825;
	mov.b32 	{%rs559, %rs560}, %r834;
	mov.b32 	{%rs561, %rs562}, %r835;
	mov.b32 	{%rs563, %rs564}, %r844;
	mov.b32 	{%rs565, %rs566}, %r845;
	mov.b32 	{%rs567, %rs568}, %r854;
	mov.b32 	{%rs569, %rs570}, %r855;
	mov.b32 	{%rs571, %rs572}, %r864;
	mov.b32 	{%rs573, %rs574}, %r865;
	mov.b32 	{%rs575, %rs576}, %r874;
	mov.b32 	{%rs577, %rs578}, %r875;
	mov.b32 	{%rs579, %rs580}, %r884;
	mov.b32 	{%rs581, %rs582}, %r885;
	mov.b32 	{%rs583, %rs584}, %r894;
	mov.b32 	{%rs585, %rs586}, %r895;
	mov.b32 	{%rs587, %rs588}, %r904;
	mov.b32 	{%rs589, %rs590}, %r905;
	mov.b32 	{%rs591, %rs592}, %r914;
	mov.b32 	{%rs593, %rs594}, %r915;
	mov.b32 	{%rs595, %rs596}, %r924;
	mov.b32 	{%rs597, %rs598}, %r925;
	mov.b32 	{%rs599, %rs600}, %r934;
	mov.b32 	{%rs601, %rs602}, %r935;
	mov.b32 	{%rs603, %rs604}, %r944;
	mov.b32 	{%rs605, %rs606}, %r945;
	mov.b32 	{%rs607, %rs608}, %r954;
	mov.b32 	{%rs609, %rs610}, %r955;
	mov.b32 	{%rs611, %rs612}, %r964;
	mov.b32 	{%rs613, %rs614}, %r965;
	mov.b32 	{%rs615, %rs616}, %r974;
	mov.b32 	{%rs617, %rs618}, %r975;
	mov.b32 	{%rs619, %rs620}, %r984;
	mov.b32 	{%rs621, %rs622}, %r985;
	mov.b32 	{%rs623, %rs624}, %r994;
	mov.b32 	{%rs625, %rs626}, %r995;
	mov.b32 	{%rs627, %rs628}, %r1004;
	mov.b32 	{%rs629, %rs630}, %r1005;
	mov.b32 	{%rs631, %rs632}, %r1014;
	mov.b32 	{%rs633, %rs634}, %r1015;
	mov.b32 	{%rs635, %rs636}, %r1024;
	mov.b32 	{%rs637, %rs638}, %r1025;
	mov.b32 	{%rs639, %rs640}, %r1034;
	mov.b32 	{%rs641, %rs642}, %r1035;
	.loc	1 93 22
	add.s32 	%r1421, %r1421, 1;
	add.s64 	%rd106, %rd106, %rd10;
	add.s64 	%rd105, %rd105, 64;
	add.s64 	%rd104, %rd104, 64;
	add.s32 	%r1384, %r1384, 32;
	setp.lt.s32 	%p40, %r1421, %r10;
	@%p40 bra 	$L__BB0_2;
$L__BB0_3:
	.loc	1 74 51
	or.b32  	%r1273, %r1, %r4;
	.loc	1 74 38
	or.b32  	%r1274, %r1273, 120;
	.loc	1 83 33
	setp.lt.s32 	%p57, %r1274, %r142;
	.loc	1 83 58
	setp.lt.s32 	%p58, %r9, %r143;
	.loc	1 83 39
	and.pred  	%p56, %p57, %p58;
	.loc	1 74 38
	or.b32  	%r1275, %r1273, 112;
	.loc	1 83 33
	setp.lt.s32 	%p59, %r1275, %r142;
	.loc	1 83 39
	and.pred  	%p55, %p59, %p58;
	.loc	1 74 38
	or.b32  	%r1276, %r1273, 104;
	.loc	1 83 33
	setp.lt.s32 	%p60, %r1276, %r142;
	.loc	1 83 39
	and.pred  	%p54, %p60, %p58;
	.loc	1 74 38
	or.b32  	%r1277, %r1273, 96;
	.loc	1 83 33
	setp.lt.s32 	%p61, %r1277, %r142;
	.loc	1 83 39
	and.pred  	%p53, %p61, %p58;
	.loc	1 74 38
	or.b32  	%r1278, %r1273, 88;
	.loc	1 83 33
	setp.lt.s32 	%p62, %r1278, %r142;
	.loc	1 83 39
	and.pred  	%p52, %p62, %p58;
	.loc	1 74 38
	or.b32  	%r1279, %r1273, 80;
	.loc	1 83 33
	setp.lt.s32 	%p63, %r1279, %r142;
	.loc	1 83 39
	and.pred  	%p51, %p63, %p58;
	.loc	1 74 38
	or.b32  	%r1280, %r1273, 72;
	.loc	1 83 33
	setp.lt.s32 	%p64, %r1280, %r142;
	.loc	1 83 39
	and.pred  	%p50, %p64, %p58;
	.loc	1 74 38
	or.b32  	%r1281, %r1273, 64;
	.loc	1 83 33
	setp.lt.s32 	%p65, %r1281, %r142;
	.loc	1 83 39
	and.pred  	%p49, %p65, %p58;
	.loc	1 74 38
	or.b32  	%r1282, %r1, %r20;
	.loc	1 83 33
	setp.lt.s32 	%p66, %r1282, %r142;
	.loc	1 83 39
	and.pred  	%p48, %p66, %p58;
	.loc	1 74 38
	or.b32  	%r1283, %r1, %r19;
	.loc	1 83 33
	setp.lt.s32 	%p67, %r1283, %r142;
	.loc	1 83 39
	and.pred  	%p47, %p67, %p58;
	.loc	1 74 38
	or.b32  	%r1284, %r1, %r18;
	.loc	1 83 33
	setp.lt.s32 	%p68, %r1284, %r142;
	.loc	1 83 39
	and.pred  	%p46, %p68, %p58;
	.loc	1 74 38
	or.b32  	%r1285, %r1, %r17;
	.loc	1 83 33
	setp.lt.s32 	%p69, %r1285, %r142;
	.loc	1 83 39
	and.pred  	%p45, %p69, %p58;
	.loc	1 74 38
	or.b32  	%r1286, %r1, %r7;
	.loc	1 83 33
	setp.lt.s32 	%p70, %r1286, %r142;
	.loc	1 83 39
	and.pred  	%p44, %p70, %p58;
	.loc	1 74 38
	or.b32  	%r1287, %r1, %r6;
	.loc	1 83 33
	setp.lt.s32 	%p71, %r1287, %r142;
	.loc	1 83 39
	and.pred  	%p43, %p71, %p58;
	.loc	1 74 38
	or.b32  	%r1288, %r1, %r5;
	.loc	1 83 33
	setp.lt.s32 	%p72, %r1288, %r142;
	.loc	1 83 39
	and.pred  	%p42, %p72, %p58;
	.loc	1 83 33
	setp.lt.s32 	%p73, %r1273, %r142;
	.loc	1 83 39
	and.pred  	%p41, %p73, %p58;
	.loc	1 82 33
	mul.lo.s32 	%r1289, %r1274, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd71, %r1289, 2;
	add.s64 	%rd72, %rd24, %rd71;
	.loc	1 82 52
	mul.wide.s32 	%rd73, %r9, 2;
	add.s64 	%rd70, %rd72, %rd73;
	.loc	1 82 33
	shl.b32 	%r1290, %r145, 3;
	sub.s32 	%r1291, %r1289, %r1290;
	.loc	1 82 21
	mul.wide.s32 	%rd74, %r1291, 2;
	add.s64 	%rd75, %rd24, %rd74;
	.loc	1 82 52
	add.s64 	%rd69, %rd75, %rd73;
	.loc	1 82 33
	sub.s32 	%r1292, %r1291, %r1290;
	.loc	1 82 21
	mul.wide.s32 	%rd76, %r1292, 2;
	add.s64 	%rd77, %rd24, %rd76;
	.loc	1 82 52
	add.s64 	%rd68, %rd77, %rd73;
	.loc	1 82 33
	sub.s32 	%r1293, %r1292, %r1290;
	.loc	1 82 21
	mul.wide.s32 	%rd78, %r1293, 2;
	add.s64 	%rd79, %rd24, %rd78;
	.loc	1 82 52
	add.s64 	%rd67, %rd79, %rd73;
	.loc	1 82 33
	sub.s32 	%r1294, %r1293, %r1290;
	.loc	1 82 21
	mul.wide.s32 	%rd80, %r1294, 2;
	add.s64 	%rd81, %rd24, %rd80;
	.loc	1 82 52
	add.s64 	%rd66, %rd81, %rd73;
	.loc	1 82 33
	sub.s32 	%r1295, %r1294, %r1290;
	.loc	1 82 21
	mul.wide.s32 	%rd82, %r1295, 2;
	add.s64 	%rd83, %rd24, %rd82;
	.loc	1 82 52
	add.s64 	%rd65, %rd83, %rd73;
	.loc	1 82 33
	sub.s32 	%r1296, %r1295, %r1290;
	.loc	1 82 21
	mul.wide.s32 	%rd84, %r1296, 2;
	add.s64 	%rd85, %rd24, %rd84;
	.loc	1 82 52
	add.s64 	%rd64, %rd85, %rd73;
	.loc	1 82 33
	sub.s32 	%r1297, %r1296, %r1290;
	.loc	1 82 21
	mul.wide.s32 	%rd86, %r1297, 2;
	add.s64 	%rd87, %rd24, %rd86;
	.loc	1 82 52
	add.s64 	%rd63, %rd87, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1298, %r1282, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd88, %r1298, 2;
	add.s64 	%rd89, %rd24, %rd88;
	.loc	1 82 52
	add.s64 	%rd62, %rd89, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1299, %r1283, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd90, %r1299, 2;
	add.s64 	%rd91, %rd24, %rd90;
	.loc	1 82 52
	add.s64 	%rd61, %rd91, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1300, %r1284, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd92, %r1300, 2;
	add.s64 	%rd93, %rd24, %rd92;
	.loc	1 82 52
	add.s64 	%rd60, %rd93, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1301, %r1285, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd94, %r1301, 2;
	add.s64 	%rd95, %rd24, %rd94;
	.loc	1 82 52
	add.s64 	%rd59, %rd95, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1302, %r1286, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd96, %r1302, 2;
	add.s64 	%rd97, %rd24, %rd96;
	.loc	1 82 52
	add.s64 	%rd58, %rd97, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1303, %r1287, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd98, %r1303, 2;
	add.s64 	%rd99, %rd24, %rd98;
	.loc	1 82 52
	add.s64 	%rd57, %rd99, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1304, %r1288, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd100, %r1304, 2;
	add.s64 	%rd101, %rd24, %rd100;
	.loc	1 82 52
	add.s64 	%rd56, %rd101, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1305, %r1273, %r145;
	.loc	1 82 21
	mul.wide.s32 	%rd102, %r1305, 2;
	add.s64 	%rd103, %rd24, %rd102;
	.loc	1 82 52
	add.s64 	%rd55, %rd103, %rd73;
	.loc	1 93 22
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	.loc	1 129 21
	shr.u32 	%r1306, %r3, 2;
	shl.b32 	%r1307, %r2, 1;
	and.b32  	%r1308, %r1307, 6;
	or.b32  	%r1309, %r1306, %r23;
	shl.b32 	%r1310, %r42, 3;
	or.b32  	%r1311, %r1310, %r1308;
	mad.lo.s32 	%r1312, %r1309, 264, %r1311;
	shl.b32 	%r1313, %r1312, 1;
	add.s32 	%r1315, %r261, %r1313;
	mov.b32 	%r1316, {%rs515, %rs516};
	st.shared.b32 	[%r1315], %r1316;
	mov.b32 	%r1317, {%rs517, %rs518};
	st.shared.b32 	[%r1315+4224], %r1317;
	mov.b32 	%r1318, {%rs519, %rs520};
	st.shared.b32 	[%r1315+64], %r1318;
	mov.b32 	%r1319, {%rs521, %rs522};
	st.shared.b32 	[%r1315+4288], %r1319;
	mov.b32 	%r1320, {%rs523, %rs524};
	st.shared.b32 	[%r1315+128], %r1320;
	mov.b32 	%r1321, {%rs525, %rs526};
	st.shared.b32 	[%r1315+4352], %r1321;
	mov.b32 	%r1322, {%rs527, %rs528};
	st.shared.b32 	[%r1315+192], %r1322;
	mov.b32 	%r1323, {%rs529, %rs530};
	st.shared.b32 	[%r1315+4416], %r1323;
	mov.b32 	%r1324, {%rs531, %rs532};
	st.shared.b32 	[%r1315+256], %r1324;
	mov.b32 	%r1325, {%rs533, %rs534};
	st.shared.b32 	[%r1315+4480], %r1325;
	mov.b32 	%r1326, {%rs535, %rs536};
	st.shared.b32 	[%r1315+320], %r1326;
	mov.b32 	%r1327, {%rs537, %rs538};
	st.shared.b32 	[%r1315+4544], %r1327;
	mov.b32 	%r1328, {%rs539, %rs540};
	st.shared.b32 	[%r1315+384], %r1328;
	mov.b32 	%r1329, {%rs541, %rs542};
	st.shared.b32 	[%r1315+4608], %r1329;
	mov.b32 	%r1330, {%rs543, %rs544};
	st.shared.b32 	[%r1315+448], %r1330;
	mov.b32 	%r1331, {%rs545, %rs546};
	st.shared.b32 	[%r1315+4672], %r1331;
	bar.sync 	0;
	shl.b32 	%r1332, %r3, 3;
	mad.lo.s32 	%r1333, %r4, 264, %r1332;
	shl.b32 	%r1334, %r1333, 1;
	add.s32 	%r1335, %r261, %r1334;
	ld.shared.v4.u32 	{%r1209, %r1210, %r1211, %r1212}, [%r1335];
	ld.shared.v4.u32 	{%r1213, %r1214, %r1215, %r1216}, [%r1335+4224];
	ld.shared.v4.u32 	{%r1217, %r1218, %r1219, %r1220}, [%r1335+8448];
	ld.shared.v4.u32 	{%r1221, %r1222, %r1223, %r1224}, [%r1335+12672];
	bar.sync 	0;
	mov.b32 	%r1336, {%rs547, %rs548};
	st.shared.b32 	[%r1315], %r1336;
	mov.b32 	%r1337, {%rs549, %rs550};
	st.shared.b32 	[%r1315+4224], %r1337;
	mov.b32 	%r1338, {%rs551, %rs552};
	st.shared.b32 	[%r1315+64], %r1338;
	mov.b32 	%r1339, {%rs553, %rs554};
	st.shared.b32 	[%r1315+4288], %r1339;
	mov.b32 	%r1340, {%rs555, %rs556};
	st.shared.b32 	[%r1315+128], %r1340;
	mov.b32 	%r1341, {%rs557, %rs558};
	st.shared.b32 	[%r1315+4352], %r1341;
	mov.b32 	%r1342, {%rs559, %rs560};
	st.shared.b32 	[%r1315+192], %r1342;
	mov.b32 	%r1343, {%rs561, %rs562};
	st.shared.b32 	[%r1315+4416], %r1343;
	mov.b32 	%r1344, {%rs563, %rs564};
	st.shared.b32 	[%r1315+256], %r1344;
	mov.b32 	%r1345, {%rs565, %rs566};
	st.shared.b32 	[%r1315+4480], %r1345;
	mov.b32 	%r1346, {%rs567, %rs568};
	st.shared.b32 	[%r1315+320], %r1346;
	mov.b32 	%r1347, {%rs569, %rs570};
	st.shared.b32 	[%r1315+4544], %r1347;
	mov.b32 	%r1348, {%rs571, %rs572};
	st.shared.b32 	[%r1315+384], %r1348;
	mov.b32 	%r1349, {%rs573, %rs574};
	st.shared.b32 	[%r1315+4608], %r1349;
	mov.b32 	%r1350, {%rs575, %rs576};
	st.shared.b32 	[%r1315+448], %r1350;
	mov.b32 	%r1351, {%rs577, %rs578};
	st.shared.b32 	[%r1315+4672], %r1351;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1225, %r1226, %r1227, %r1228}, [%r1335];
	ld.shared.v4.u32 	{%r1229, %r1230, %r1231, %r1232}, [%r1335+4224];
	ld.shared.v4.u32 	{%r1233, %r1234, %r1235, %r1236}, [%r1335+8448];
	ld.shared.v4.u32 	{%r1237, %r1238, %r1239, %r1240}, [%r1335+12672];
	bar.sync 	0;
	mov.b32 	%r1352, {%rs579, %rs580};
	st.shared.b32 	[%r1315], %r1352;
	mov.b32 	%r1353, {%rs581, %rs582};
	st.shared.b32 	[%r1315+4224], %r1353;
	mov.b32 	%r1354, {%rs583, %rs584};
	st.shared.b32 	[%r1315+64], %r1354;
	mov.b32 	%r1355, {%rs585, %rs586};
	st.shared.b32 	[%r1315+4288], %r1355;
	mov.b32 	%r1356, {%rs587, %rs588};
	st.shared.b32 	[%r1315+128], %r1356;
	mov.b32 	%r1357, {%rs589, %rs590};
	st.shared.b32 	[%r1315+4352], %r1357;
	mov.b32 	%r1358, {%rs591, %rs592};
	st.shared.b32 	[%r1315+192], %r1358;
	mov.b32 	%r1359, {%rs593, %rs594};
	st.shared.b32 	[%r1315+4416], %r1359;
	mov.b32 	%r1360, {%rs595, %rs596};
	st.shared.b32 	[%r1315+256], %r1360;
	mov.b32 	%r1361, {%rs597, %rs598};
	st.shared.b32 	[%r1315+4480], %r1361;
	mov.b32 	%r1362, {%rs599, %rs600};
	st.shared.b32 	[%r1315+320], %r1362;
	mov.b32 	%r1363, {%rs601, %rs602};
	st.shared.b32 	[%r1315+4544], %r1363;
	mov.b32 	%r1364, {%rs603, %rs604};
	st.shared.b32 	[%r1315+384], %r1364;
	mov.b32 	%r1365, {%rs605, %rs606};
	st.shared.b32 	[%r1315+4608], %r1365;
	mov.b32 	%r1366, {%rs607, %rs608};
	st.shared.b32 	[%r1315+448], %r1366;
	mov.b32 	%r1367, {%rs609, %rs610};
	st.shared.b32 	[%r1315+4672], %r1367;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1241, %r1242, %r1243, %r1244}, [%r1335];
	ld.shared.v4.u32 	{%r1245, %r1246, %r1247, %r1248}, [%r1335+4224];
	ld.shared.v4.u32 	{%r1249, %r1250, %r1251, %r1252}, [%r1335+8448];
	ld.shared.v4.u32 	{%r1253, %r1254, %r1255, %r1256}, [%r1335+12672];
	bar.sync 	0;
	mov.b32 	%r1368, {%rs611, %rs612};
	st.shared.b32 	[%r1315], %r1368;
	mov.b32 	%r1369, {%rs613, %rs614};
	st.shared.b32 	[%r1315+4224], %r1369;
	mov.b32 	%r1370, {%rs615, %rs616};
	st.shared.b32 	[%r1315+64], %r1370;
	mov.b32 	%r1371, {%rs617, %rs618};
	st.shared.b32 	[%r1315+4288], %r1371;
	mov.b32 	%r1372, {%rs619, %rs620};
	st.shared.b32 	[%r1315+128], %r1372;
	mov.b32 	%r1373, {%rs621, %rs622};
	st.shared.b32 	[%r1315+4352], %r1373;
	mov.b32 	%r1374, {%rs623, %rs624};
	st.shared.b32 	[%r1315+192], %r1374;
	mov.b32 	%r1375, {%rs625, %rs626};
	st.shared.b32 	[%r1315+4416], %r1375;
	mov.b32 	%r1376, {%rs627, %rs628};
	st.shared.b32 	[%r1315+256], %r1376;
	mov.b32 	%r1377, {%rs629, %rs630};
	st.shared.b32 	[%r1315+4480], %r1377;
	mov.b32 	%r1378, {%rs631, %rs632};
	st.shared.b32 	[%r1315+320], %r1378;
	mov.b32 	%r1379, {%rs633, %rs634};
	st.shared.b32 	[%r1315+4544], %r1379;
	mov.b32 	%r1380, {%rs635, %rs636};
	st.shared.b32 	[%r1315+384], %r1380;
	mov.b32 	%r1381, {%rs637, %rs638};
	st.shared.b32 	[%r1315+4608], %r1381;
	mov.b32 	%r1382, {%rs639, %rs640};
	st.shared.b32 	[%r1315+448], %r1382;
	mov.b32 	%r1383, {%rs641, %rs642};
	st.shared.b32 	[%r1315+4672], %r1383;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1257, %r1258, %r1259, %r1260}, [%r1335];
	ld.shared.v4.u32 	{%r1261, %r1262, %r1263, %r1264}, [%r1335+4224];
	ld.shared.v4.u32 	{%r1265, %r1266, %r1267, %r1268}, [%r1335+8448];
	ld.shared.v4.u32 	{%r1269, %r1270, %r1271, %r1272}, [%r1335+12672];
	// begin inline asm
	@%p41 st.global.v4.b32 [ %rd55 + 0 ], { %r1209, %r1210, %r1211, %r1212 };
	// end inline asm
	// begin inline asm
	@%p42 st.global.v4.b32 [ %rd56 + 0 ], { %r1213, %r1214, %r1215, %r1216 };
	// end inline asm
	// begin inline asm
	@%p43 st.global.v4.b32 [ %rd57 + 0 ], { %r1217, %r1218, %r1219, %r1220 };
	// end inline asm
	// begin inline asm
	@%p44 st.global.v4.b32 [ %rd58 + 0 ], { %r1221, %r1222, %r1223, %r1224 };
	// end inline asm
	// begin inline asm
	@%p45 st.global.v4.b32 [ %rd59 + 0 ], { %r1225, %r1226, %r1227, %r1228 };
	// end inline asm
	// begin inline asm
	@%p46 st.global.v4.b32 [ %rd60 + 0 ], { %r1229, %r1230, %r1231, %r1232 };
	// end inline asm
	// begin inline asm
	@%p47 st.global.v4.b32 [ %rd61 + 0 ], { %r1233, %r1234, %r1235, %r1236 };
	// end inline asm
	// begin inline asm
	@%p48 st.global.v4.b32 [ %rd62 + 0 ], { %r1237, %r1238, %r1239, %r1240 };
	// end inline asm
	// begin inline asm
	@%p49 st.global.v4.b32 [ %rd63 + 0 ], { %r1241, %r1242, %r1243, %r1244 };
	// end inline asm
	// begin inline asm
	@%p50 st.global.v4.b32 [ %rd64 + 0 ], { %r1245, %r1246, %r1247, %r1248 };
	// end inline asm
	// begin inline asm
	@%p51 st.global.v4.b32 [ %rd65 + 0 ], { %r1249, %r1250, %r1251, %r1252 };
	// end inline asm
	// begin inline asm
	@%p52 st.global.v4.b32 [ %rd66 + 0 ], { %r1253, %r1254, %r1255, %r1256 };
	// end inline asm
	// begin inline asm
	@%p53 st.global.v4.b32 [ %rd67 + 0 ], { %r1257, %r1258, %r1259, %r1260 };
	// end inline asm
	// begin inline asm
	@%p54 st.global.v4.b32 [ %rd68 + 0 ], { %r1261, %r1262, %r1263, %r1264 };
	// end inline asm
	// begin inline asm
	@%p55 st.global.v4.b32 [ %rd69 + 0 ], { %r1265, %r1266, %r1267, %r1268 };
	// end inline asm
	// begin inline asm
	@%p56 st.global.v4.b32 [ %rd70 + 0 ], { %r1269, %r1270, %r1271, %r1272 };
	// end inline asm
	.loc	1 129 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/PycharmProjects/tritontest/compile_matmul_kernel.py"
	.file	2 "/home/mike/PycharmProjects/tritontest/.venv/lib/python3.11/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 211
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 80
.b8 121
.b8 99
.b8 104
.b8 97
.b8 114
.b8 109
.b8 80
.b8 114
.b8 111
.b8 106
.b8 101
.b8 99
.b8 116
.b8 115
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 116
.b8 101
.b8 115
.b8 116
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 104
.b8 4
.b32 104
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 104
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 104
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_0_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_0_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_0_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_0_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_0_FUNCTION_NAME "matmul_kernel"
