/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_5_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel_accumulate_transpose_b
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel_accumulate_transpose_b(
	.param .u64 matmul_kernel_accumulate_transpose_b_param_0,
	.param .u64 matmul_kernel_accumulate_transpose_b_param_1,
	.param .u64 matmul_kernel_accumulate_transpose_b_param_2,
	.param .u32 matmul_kernel_accumulate_transpose_b_param_3,
	.param .u32 matmul_kernel_accumulate_transpose_b_param_4,
	.param .u32 matmul_kernel_accumulate_transpose_b_param_5,
	.param .u32 matmul_kernel_accumulate_transpose_b_param_6,
	.param .u32 matmul_kernel_accumulate_transpose_b_param_7,
	.param .u32 matmul_kernel_accumulate_transpose_b_param_8
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<158>;
	.reg .b16 	%rs<643>;
	.reg .b32 	%r<1771>;
	.reg .b64 	%rd<137>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r195, [matmul_kernel_accumulate_transpose_b_param_5];
	ld.param.u64 	%rd32, [matmul_kernel_accumulate_transpose_b_param_1];
	ld.param.u64 	%rd31, [matmul_kernel_accumulate_transpose_b_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r196, %ctaid.x;
	// end inline asm
	ld.param.u32 	%r389, [matmul_kernel_accumulate_transpose_b_param_3];
$L__tmp1:
	.loc	2 40 22
	add.s32 	%r390, %r389, 127;
	ld.param.u64 	%rd61, [matmul_kernel_accumulate_transpose_b_param_2];
	.loc	2 40 28
	shr.s32 	%r391, %r390, 31;
	shr.u32 	%r392, %r391, 25;
	add.s32 	%r393, %r390, %r392;
	shr.s32 	%r394, %r393, 7;
	ld.param.u32 	%r395, [matmul_kernel_accumulate_transpose_b_param_4];
$L__tmp2:
	.loc	2 40 22
	add.s32 	%r396, %r395, 255;
	.loc	2 40 28
	shr.s32 	%r397, %r396, 31;
	shr.u32 	%r398, %r397, 24;
	add.s32 	%r399, %r396, %r398;
	shr.s32 	%r400, %r399, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r402, %r400, 3;
	ld.param.u32 	%r403, [matmul_kernel_accumulate_transpose_b_param_6];
	ld.param.u32 	%r404, [matmul_kernel_accumulate_transpose_b_param_7];
	ld.param.u32 	%r405, [matmul_kernel_accumulate_transpose_b_param_8];
	.loc	1 61 22
	div.s32 	%r406, %r196, %r402;
	.loc	1 62 29
	shl.b32 	%r407, %r406, 3;
	.loc	1 63 35
	sub.s32 	%r408, %r394, %r407;
	.loc	1 63 48
	min.s32 	%r409, %r408, 8;
	.loc	1 64 33
	rem.s32 	%r410, %r196, %r409;
	.loc	1 64 27
	add.s32 	%r411, %r407, %r410;
	mul.lo.s32 	%r412, %r406, %r402;
	sub.s32 	%r413, %r196, %r412;
	.loc	1 65 40
	div.s32 	%r414, %r413, %r409;
	.loc	1 74 23
	shl.b32 	%r415, %r411, 7;
	.loc	1 74 51
	mov.u32 	%r1, %tid.x;
	and.b32  	%r2, %r1, 31;
	shr.u32 	%r416, %r1, 2;
	bfe.u32 	%r417, %r1, 2, 6;
	or.b32  	%r418, %r417, 64;
	bfe.u32 	%r3, %r1, 5, 3;
	.loc	1 74 38
	or.b32  	%r419, %r415, %r417;
	or.b32  	%r420, %r415, %r418;
	or.b32  	%r421, %r415, %r3;
	or.b32  	%r422, %r421, 8;
	or.b32  	%r423, %r421, 16;
	or.b32  	%r424, %r421, 24;
	or.b32  	%r425, %r421, 32;
	or.b32  	%r426, %r421, 40;
	or.b32  	%r427, %r421, 48;
	or.b32  	%r428, %r421, 56;
	or.b32  	%r429, %r421, 64;
	or.b32  	%r430, %r421, 72;
	or.b32  	%r431, %r421, 80;
	or.b32  	%r432, %r421, 88;
	or.b32  	%r433, %r421, 96;
	or.b32  	%r434, %r421, 104;
	or.b32  	%r435, %r421, 112;
	or.b32  	%r436, %r421, 120;
	.loc	1 74 68
	rem.s32 	%r437, %r419, %r389;
	rem.s32 	%r438, %r420, %r389;
	.loc	1 75 23
	shl.b32 	%r439, %r414, 8;
	.loc	1 75 51
	shl.b32 	%r440, %r1, 3;
	and.b32  	%r4, %r440, 24;
	and.b32  	%r441, %r440, 248;
	or.b32  	%r442, %r417, 128;
	or.b32  	%r443, %r417, 192;
	.loc	1 75 38
	or.b32  	%r444, %r439, %r441;
	or.b32  	%r445, %r439, %r417;
	or.b32  	%r446, %r439, %r418;
	or.b32  	%r447, %r439, %r442;
	or.b32  	%r448, %r439, %r443;
	.loc	1 75 68
	rem.s32 	%r449, %r445, %r395;
	rem.s32 	%r450, %r446, %r395;
	rem.s32 	%r451, %r447, %r395;
	rem.s32 	%r452, %r448, %r395;
	.loc	1 77 53
	mad.lo.s32 	%r453, %r437, %r403, %r4;
	mad.lo.s32 	%r454, %r438, %r403, %r4;
	.loc	1 77 22
	mul.wide.s32 	%rd62, %r453, 2;
	add.s64 	%rd49, %rd31, %rd62;
	mul.wide.s32 	%rd63, %r454, 2;
	add.s64 	%rd50, %rd31, %rd63;
	.loc	1 78 52
	mad.lo.s32 	%r455, %r449, %r404, %r4;
	mad.lo.s32 	%r456, %r450, %r404, %r4;
	mad.lo.s32 	%r457, %r451, %r404, %r4;
	mad.lo.s32 	%r458, %r452, %r404, %r4;
	.loc	1 78 22
	mul.wide.s32 	%rd64, %r455, 2;
	add.s64 	%rd51, %rd32, %rd64;
	mul.wide.s32 	%rd65, %r456, 2;
	add.s64 	%rd52, %rd32, %rd65;
	mul.wide.s32 	%rd66, %r457, 2;
	add.s64 	%rd53, %rd32, %rd66;
	mul.wide.s32 	%rd67, %r458, 2;
	add.s64 	%rd54, %rd32, %rd67;
	.loc	1 82 33
	mul.lo.s32 	%r459, %r421, %r405;
	shl.b32 	%r460, %r405, 3;
	add.s32 	%r461, %r459, %r460;
	add.s32 	%r462, %r461, %r460;
	add.s32 	%r463, %r462, %r460;
	add.s32 	%r464, %r463, %r460;
	add.s32 	%r465, %r464, %r460;
	add.s32 	%r466, %r465, %r460;
	add.s32 	%r467, %r466, %r460;
	add.s32 	%r468, %r467, %r460;
	add.s32 	%r469, %r468, %r460;
	add.s32 	%r470, %r469, %r460;
	add.s32 	%r471, %r470, %r460;
	add.s32 	%r472, %r471, %r460;
	add.s32 	%r473, %r472, %r460;
	add.s32 	%r474, %r473, %r460;
	add.s32 	%r475, %r474, %r460;
	.loc	1 82 21
	mul.wide.s32 	%rd68, %r459, 2;
	add.s64 	%rd69, %rd61, %rd68;
	mul.wide.s32 	%rd70, %r461, 2;
	add.s64 	%rd71, %rd61, %rd70;
	mul.wide.s32 	%rd72, %r462, 2;
	add.s64 	%rd73, %rd61, %rd72;
	mul.wide.s32 	%rd74, %r463, 2;
	add.s64 	%rd75, %rd61, %rd74;
	mul.wide.s32 	%rd76, %r464, 2;
	add.s64 	%rd77, %rd61, %rd76;
	mul.wide.s32 	%rd78, %r465, 2;
	add.s64 	%rd79, %rd61, %rd78;
	mul.wide.s32 	%rd80, %r466, 2;
	add.s64 	%rd81, %rd61, %rd80;
	mul.wide.s32 	%rd82, %r467, 2;
	add.s64 	%rd83, %rd61, %rd82;
	mul.wide.s32 	%rd84, %r468, 2;
	add.s64 	%rd85, %rd61, %rd84;
	mul.wide.s32 	%rd86, %r469, 2;
	add.s64 	%rd87, %rd61, %rd86;
	mul.wide.s32 	%rd88, %r470, 2;
	add.s64 	%rd89, %rd61, %rd88;
	mul.wide.s32 	%rd90, %r471, 2;
	add.s64 	%rd91, %rd61, %rd90;
	mul.wide.s32 	%rd92, %r472, 2;
	add.s64 	%rd93, %rd61, %rd92;
	mul.wide.s32 	%rd94, %r473, 2;
	add.s64 	%rd95, %rd61, %rd94;
	mul.wide.s32 	%rd96, %r474, 2;
	add.s64 	%rd97, %rd61, %rd96;
	mul.wide.s32 	%rd98, %r475, 2;
	add.s64 	%rd99, %rd61, %rd98;
	.loc	1 82 52
	mul.wide.s32 	%rd100, %r444, 2;
	add.s64 	%rd120, %rd69, %rd100;
	add.s64 	%rd121, %rd71, %rd100;
	add.s64 	%rd122, %rd73, %rd100;
	add.s64 	%rd123, %rd75, %rd100;
	add.s64 	%rd124, %rd77, %rd100;
	add.s64 	%rd125, %rd79, %rd100;
	add.s64 	%rd126, %rd81, %rd100;
	add.s64 	%rd127, %rd83, %rd100;
	add.s64 	%rd128, %rd85, %rd100;
	add.s64 	%rd129, %rd87, %rd100;
	add.s64 	%rd130, %rd89, %rd100;
	add.s64 	%rd131, %rd91, %rd100;
	add.s64 	%rd132, %rd93, %rd100;
	add.s64 	%rd133, %rd95, %rd100;
	add.s64 	%rd134, %rd97, %rd100;
	add.s64 	%rd135, %rd99, %rd100;
	.loc	1 83 33
	setp.lt.s32 	%p109, %r421, %r389;
	setp.lt.s32 	%p110, %r422, %r389;
	setp.lt.s32 	%p111, %r423, %r389;
	setp.lt.s32 	%p112, %r424, %r389;
	setp.lt.s32 	%p113, %r425, %r389;
	setp.lt.s32 	%p114, %r426, %r389;
	setp.lt.s32 	%p115, %r427, %r389;
	setp.lt.s32 	%p116, %r428, %r389;
	setp.lt.s32 	%p117, %r429, %r389;
	setp.lt.s32 	%p118, %r430, %r389;
	setp.lt.s32 	%p119, %r431, %r389;
	setp.lt.s32 	%p120, %r432, %r389;
	setp.lt.s32 	%p121, %r433, %r389;
	setp.lt.s32 	%p122, %r434, %r389;
	setp.lt.s32 	%p123, %r435, %r389;
	setp.lt.s32 	%p124, %r436, %r389;
	.loc	1 83 58
	setp.lt.s32 	%p125, %r444, %r395;
	.loc	1 83 39
	and.pred  	%p142, %p109, %p125;
	and.pred  	%p143, %p110, %p125;
	and.pred  	%p144, %p111, %p125;
	and.pred  	%p145, %p112, %p125;
	and.pred  	%p146, %p113, %p125;
	and.pred  	%p147, %p114, %p125;
	and.pred  	%p148, %p115, %p125;
	and.pred  	%p149, %p116, %p125;
	and.pred  	%p150, %p117, %p125;
	and.pred  	%p151, %p118, %p125;
	and.pred  	%p152, %p119, %p125;
	and.pred  	%p153, %p120, %p125;
	and.pred  	%p154, %p121, %p125;
	and.pred  	%p155, %p122, %p125;
	and.pred  	%p156, %p123, %p125;
	and.pred  	%p157, %p124, %p125;
	mov.b32 	%r1768, 0;
	.loc	1 89 30
	// begin inline asm
	mov.u32 %r197, 0x0;
	mov.u32 %r198, 0x0;
	mov.u32 %r199, 0x0;
	mov.u32 %r200, 0x0;
	@%p142 ld.global.v4.b32 { %r197, %r198, %r199, %r200 }, [ %rd120 + 0 ];
	@!%p142 mov.u32 %r197, %r1768;
	@!%p142 mov.u32 %r198, %r1768;
	@!%p142 mov.u32 %r199, %r1768;
	@!%p142 mov.u32 %r200, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r205, 0x0;
	mov.u32 %r206, 0x0;
	mov.u32 %r207, 0x0;
	mov.u32 %r208, 0x0;
	@%p143 ld.global.v4.b32 { %r205, %r206, %r207, %r208 }, [ %rd121 + 0 ];
	@!%p143 mov.u32 %r205, %r1768;
	@!%p143 mov.u32 %r206, %r1768;
	@!%p143 mov.u32 %r207, %r1768;
	@!%p143 mov.u32 %r208, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r213, 0x0;
	mov.u32 %r214, 0x0;
	mov.u32 %r215, 0x0;
	mov.u32 %r216, 0x0;
	@%p144 ld.global.v4.b32 { %r213, %r214, %r215, %r216 }, [ %rd122 + 0 ];
	@!%p144 mov.u32 %r213, %r1768;
	@!%p144 mov.u32 %r214, %r1768;
	@!%p144 mov.u32 %r215, %r1768;
	@!%p144 mov.u32 %r216, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r221, 0x0;
	mov.u32 %r222, 0x0;
	mov.u32 %r223, 0x0;
	mov.u32 %r224, 0x0;
	@%p145 ld.global.v4.b32 { %r221, %r222, %r223, %r224 }, [ %rd123 + 0 ];
	@!%p145 mov.u32 %r221, %r1768;
	@!%p145 mov.u32 %r222, %r1768;
	@!%p145 mov.u32 %r223, %r1768;
	@!%p145 mov.u32 %r224, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r229, 0x0;
	mov.u32 %r230, 0x0;
	mov.u32 %r231, 0x0;
	mov.u32 %r232, 0x0;
	@%p146 ld.global.v4.b32 { %r229, %r230, %r231, %r232 }, [ %rd124 + 0 ];
	@!%p146 mov.u32 %r229, %r1768;
	@!%p146 mov.u32 %r230, %r1768;
	@!%p146 mov.u32 %r231, %r1768;
	@!%p146 mov.u32 %r232, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r237, 0x0;
	mov.u32 %r238, 0x0;
	mov.u32 %r239, 0x0;
	mov.u32 %r240, 0x0;
	@%p147 ld.global.v4.b32 { %r237, %r238, %r239, %r240 }, [ %rd125 + 0 ];
	@!%p147 mov.u32 %r237, %r1768;
	@!%p147 mov.u32 %r238, %r1768;
	@!%p147 mov.u32 %r239, %r1768;
	@!%p147 mov.u32 %r240, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r245, 0x0;
	mov.u32 %r246, 0x0;
	mov.u32 %r247, 0x0;
	mov.u32 %r248, 0x0;
	@%p148 ld.global.v4.b32 { %r245, %r246, %r247, %r248 }, [ %rd126 + 0 ];
	@!%p148 mov.u32 %r245, %r1768;
	@!%p148 mov.u32 %r246, %r1768;
	@!%p148 mov.u32 %r247, %r1768;
	@!%p148 mov.u32 %r248, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r253, 0x0;
	mov.u32 %r254, 0x0;
	mov.u32 %r255, 0x0;
	mov.u32 %r256, 0x0;
	@%p149 ld.global.v4.b32 { %r253, %r254, %r255, %r256 }, [ %rd127 + 0 ];
	@!%p149 mov.u32 %r253, %r1768;
	@!%p149 mov.u32 %r254, %r1768;
	@!%p149 mov.u32 %r255, %r1768;
	@!%p149 mov.u32 %r256, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r261, 0x0;
	mov.u32 %r262, 0x0;
	mov.u32 %r263, 0x0;
	mov.u32 %r264, 0x0;
	@%p150 ld.global.v4.b32 { %r261, %r262, %r263, %r264 }, [ %rd128 + 0 ];
	@!%p150 mov.u32 %r261, %r1768;
	@!%p150 mov.u32 %r262, %r1768;
	@!%p150 mov.u32 %r263, %r1768;
	@!%p150 mov.u32 %r264, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r269, 0x0;
	mov.u32 %r270, 0x0;
	mov.u32 %r271, 0x0;
	mov.u32 %r272, 0x0;
	@%p151 ld.global.v4.b32 { %r269, %r270, %r271, %r272 }, [ %rd129 + 0 ];
	@!%p151 mov.u32 %r269, %r1768;
	@!%p151 mov.u32 %r270, %r1768;
	@!%p151 mov.u32 %r271, %r1768;
	@!%p151 mov.u32 %r272, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r277, 0x0;
	mov.u32 %r278, 0x0;
	mov.u32 %r279, 0x0;
	mov.u32 %r280, 0x0;
	@%p152 ld.global.v4.b32 { %r277, %r278, %r279, %r280 }, [ %rd130 + 0 ];
	@!%p152 mov.u32 %r277, %r1768;
	@!%p152 mov.u32 %r278, %r1768;
	@!%p152 mov.u32 %r279, %r1768;
	@!%p152 mov.u32 %r280, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r285, 0x0;
	mov.u32 %r286, 0x0;
	mov.u32 %r287, 0x0;
	mov.u32 %r288, 0x0;
	@%p153 ld.global.v4.b32 { %r285, %r286, %r287, %r288 }, [ %rd131 + 0 ];
	@!%p153 mov.u32 %r285, %r1768;
	@!%p153 mov.u32 %r286, %r1768;
	@!%p153 mov.u32 %r287, %r1768;
	@!%p153 mov.u32 %r288, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r293, 0x0;
	mov.u32 %r294, 0x0;
	mov.u32 %r295, 0x0;
	mov.u32 %r296, 0x0;
	@%p154 ld.global.v4.b32 { %r293, %r294, %r295, %r296 }, [ %rd132 + 0 ];
	@!%p154 mov.u32 %r293, %r1768;
	@!%p154 mov.u32 %r294, %r1768;
	@!%p154 mov.u32 %r295, %r1768;
	@!%p154 mov.u32 %r296, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r301, 0x0;
	mov.u32 %r302, 0x0;
	mov.u32 %r303, 0x0;
	mov.u32 %r304, 0x0;
	@%p155 ld.global.v4.b32 { %r301, %r302, %r303, %r304 }, [ %rd133 + 0 ];
	@!%p155 mov.u32 %r301, %r1768;
	@!%p155 mov.u32 %r302, %r1768;
	@!%p155 mov.u32 %r303, %r1768;
	@!%p155 mov.u32 %r304, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r309, 0x0;
	mov.u32 %r310, 0x0;
	mov.u32 %r311, 0x0;
	mov.u32 %r312, 0x0;
	@%p156 ld.global.v4.b32 { %r309, %r310, %r311, %r312 }, [ %rd134 + 0 ];
	@!%p156 mov.u32 %r309, %r1768;
	@!%p156 mov.u32 %r310, %r1768;
	@!%p156 mov.u32 %r311, %r1768;
	@!%p156 mov.u32 %r312, %r1768;
	// end inline asm
	// begin inline asm
	mov.u32 %r317, 0x0;
	mov.u32 %r318, 0x0;
	mov.u32 %r319, 0x0;
	mov.u32 %r320, 0x0;
	@%p157 ld.global.v4.b32 { %r317, %r318, %r319, %r320 }, [ %rd135 + 0 ];
	@!%p157 mov.u32 %r317, %r1768;
	@!%p157 mov.u32 %r318, %r1768;
	@!%p157 mov.u32 %r319, %r1768;
	@!%p157 mov.u32 %r320, %r1768;
	// end inline asm
$L__tmp4:
	.loc	2 40 22
	add.s32 	%r476, %r195, 31;
$L__tmp5:
	.loc	1 93 22
	setp.lt.s32 	%p126, %r476, 32;
	setp.gt.s32 	%p127, %r476, 31;
	.loc	1 96 72
	setp.lt.s32 	%p128, %r4, %r195;
	.loc	1 96 20
	xor.b32  	%r480, %r440, %r1;
	and.b32  	%r481, %r480, 24;
	shl.b32 	%r482, %r417, 5;
	or.b32  	%r70, %r482, %r481;
	shl.b32 	%r483, %r70, 1;
	mov.u32 	%r484, global_smem;
	add.s32 	%r325, %r484, %r483;
	shl.b32 	%r485, %r418, 5;
	or.b32  	%r71, %r485, %r481;
	shl.b32 	%r486, %r71, 1;
	add.s32 	%r327, %r484, %r486;
	selp.b32 	%r487, 16, 0, %p127;
	selp.b32 	%r328, %r487, 0, %p128;
	mov.pred 	%p97, -1;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r325 + 0 ], [ %rd49 + 0 ], 0x10, %r328;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r327 + 0 ], [ %rd50 + 0 ], 0x10, %r328;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	add.s32 	%r488, %r484, 16384;
	add.s32 	%r329, %r488, %r483;
	add.s32 	%r331, %r488, %r486;
	shl.b32 	%r489, %r442, 5;
	or.b32  	%r72, %r489, %r481;
	shl.b32 	%r490, %r72, 1;
	add.s32 	%r333, %r488, %r490;
	shl.b32 	%r491, %r443, 5;
	or.b32  	%r73, %r491, %r481;
	shl.b32 	%r492, %r73, 1;
	add.s32 	%r335, %r488, %r492;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r329 + 0 ], [ %rd51 + 0 ], 0x10, %r328;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r331 + 0 ], [ %rd52 + 0 ], 0x10, %r328;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r333 + 0 ], [ %rd53 + 0 ], 0x10, %r328;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r335 + 0 ], [ %rd54 + 0 ], 0x10, %r328;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p129, %r476, 63;
	.loc	1 102 18
	add.s64 	%rd55, %rd49, 64;
	add.s64 	%rd56, %rd50, 64;
	.loc	1 103 18
	add.s64 	%rd57, %rd51, 64;
	add.s64 	%rd58, %rd52, 64;
	add.s64 	%rd59, %rd53, 64;
	add.s64 	%rd60, %rd54, 64;
	.loc	1 96 53
	or.b32  	%r493, %r4, 32;
	.loc	1 96 72
	setp.lt.s32 	%p130, %r493, %r195;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r494, %r484, 8192;
	add.s32 	%r337, %r494, %r483;
	add.s32 	%r339, %r494, %r486;
	selp.b32 	%r495, 16, 0, %p129;
	selp.b32 	%r340, %r495, 0, %p130;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r337 + 0 ], [ %rd55 + 0 ], 0x10, %r340;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r339 + 0 ], [ %rd56 + 0 ], 0x10, %r340;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	add.s32 	%r496, %r484, 32768;
	add.s32 	%r341, %r496, %r483;
	add.s32 	%r343, %r496, %r486;
	add.s32 	%r345, %r496, %r490;
	add.s32 	%r347, %r496, %r492;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r341 + 0 ], [ %rd57 + 0 ], 0x10, %r340;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r343 + 0 ], [ %rd58 + 0 ], 0x10, %r340;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r345 + 0 ], [ %rd59 + 0 ], 0x10, %r340;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r347 + 0 ], [ %rd60 + 0 ], 0x10, %r340;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	and.b32  	%r497, %r1, 7;
	shr.u32 	%r498, %r1, 3;
	bfe.u32 	%r74, %r1, 3, 1;
	bfe.u32 	%r75, %r1, 4, 1;
	bfe.u32 	%r76, %r1, 1, 2;
	and.b32  	%r77, %r498, 16;
	shl.b32 	%r499, %r74, 3;
	or.b32  	%r500, %r499, %r77;
	or.b32  	%r501, %r500, %r497;
	xor.b32  	%r502, %r75, %r76;
	shl.b32 	%r503, %r502, 3;
	shl.b32 	%r78, %r501, 5;
	or.b32  	%r79, %r78, %r503;
	shl.b32 	%r504, %r79, 1;
	add.s32 	%r353, %r484, %r504;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1762, %r1763, %r1764, %r1765 }, [ %r353 + 0 ];
	// end inline asm
	add.s32 	%r358, %r353, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1758, %r1759, %r1760, %r1761 }, [ %r358 + 0 ];
	// end inline asm
	add.s32 	%r363, %r353, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1754, %r1755, %r1756, %r1757 }, [ %r363 + 0 ];
	// end inline asm
	add.s32 	%r368, %r353, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1750, %r1751, %r1752, %r1753 }, [ %r368 + 0 ];
	// end inline asm
	.loc	1 97 20
	shl.b32 	%r505, %r75, 5;
	and.b32  	%r96, %r416, 24;
	or.b32  	%r506, %r505, %r96;
	or.b32  	%r507, %r506, %r497;
	xor.b32  	%r508, %r74, %r76;
	shl.b32 	%r509, %r508, 3;
	shl.b32 	%r97, %r507, 5;
	or.b32  	%r98, %r97, %r509;
	shl.b32 	%r510, %r98, 1;
	add.s32 	%r373, %r488, %r510;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1746, %r1747, %r1748, %r1749 }, [ %r373 + 0 ];
	// end inline asm
	add.s32 	%r378, %r373, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1742, %r1743, %r1744, %r1745 }, [ %r378 + 0 ];
	// end inline asm
	add.s32 	%r383, %r373, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1738, %r1739, %r1740, %r1741 }, [ %r383 + 0 ];
	// end inline asm
	add.s32 	%r388, %r373, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1734, %r1735, %r1736, %r1737 }, [ %r388 + 0 ];
	// end inline asm
	mov.b16 	%rs515, 0x0000;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	.loc	1 93 22
	@%p126 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd1, %r453;
	cvt.s64.s32 	%rd2, %r454;
	cvt.s64.s32 	%rd3, %r455;
	cvt.s64.s32 	%rd4, %r456;
	cvt.s64.s32 	%rd5, %r457;
	cvt.s64.s32 	%rd6, %r458;
	shr.s32 	%r477, %r476, 31;
	shr.u32 	%r478, %r477, 27;
	add.s32 	%r479, %r476, %r478;
	shr.s32 	%r69, %r479, 5;
	add.s32 	%r115, %r69, -2;
	or.b32  	%r515, %r75, 2;
	xor.b32  	%r516, %r515, %r76;
	shl.b32 	%r517, %r516, 3;
	or.b32  	%r518, %r74, 2;
	xor.b32  	%r519, %r518, %r76;
	shl.b32 	%r520, %r519, 3;
	or.b32  	%r116, %r78, %r517;
	or.b32  	%r117, %r97, %r520;
	.loc	1 93 22
	shl.b64 	%rd102, %rd6, 1;
	add.s64 	%rd103, %rd102, %rd32;
	add.s64 	%rd23, %rd103, 128;
	shl.b64 	%rd104, %rd5, 1;
	add.s64 	%rd105, %rd104, %rd32;
	add.s64 	%rd24, %rd105, 128;
	shl.b64 	%rd106, %rd4, 1;
	add.s64 	%rd107, %rd106, %rd32;
	add.s64 	%rd25, %rd107, 128;
	shl.b64 	%rd108, %rd3, 1;
	add.s64 	%rd109, %rd108, %rd32;
	add.s64 	%rd26, %rd109, 128;
	shl.b64 	%rd110, %rd2, 1;
	add.s64 	%rd111, %rd110, %rd31;
	add.s64 	%rd27, %rd111, 128;
	shl.b64 	%rd112, %rd1, 1;
	add.s64 	%rd113, %rd112, %rd31;
	add.s64 	%rd28, %rd113, 128;
	or.b32  	%r1733, %r4, 64;
	mov.b16 	%rs515, 0x0000;
	mov.b32 	%r1769, 1;
	mov.u64 	%rd136, 0;
	shl.b32 	%r1253, %r116, 1;
	shl.b32 	%r1254, %r117, 1;
	mov.u32 	%r1766, %r488;
	mov.u32 	%r1767, %r484;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	mov.u32 	%r1770, %r1768;
$L__BB0_2:
	setp.lt.s32 	%p137, %r1770, %r115;
	.loc	1 96 20
	add.s32 	%r525, %r1767, %r1253;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r937, %r938, %r939, %r940 }, [ %r525 + 0 ];
	// end inline asm
	add.s32 	%r530, %r525, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1017, %r1018, %r1019, %r1020 }, [ %r530 + 0 ];
	// end inline asm
	add.s32 	%r535, %r525, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1097, %r1098, %r1099, %r1100 }, [ %r535 + 0 ];
	// end inline asm
	add.s32 	%r540, %r525, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1177, %r1178, %r1179, %r1180 }, [ %r540 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r545, %r1766, %r1254;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r941, %r942, %r951, %r952 }, [ %r545 + 0 ];
	// end inline asm
	add.s32 	%r550, %r545, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r961, %r962, %r971, %r972 }, [ %r550 + 0 ];
	// end inline asm
	add.s32 	%r555, %r545, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r981, %r982, %r991, %r992 }, [ %r555 + 0 ];
	// end inline asm
	add.s32 	%r560, %r545, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1001, %r1002, %r1011, %r1012 }, [ %r560 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r933, {%rs515, %rs516};
	mov.b32 	%r934, {%rs517, %rs518};
	mov.b32 	%r943, {%rs519, %rs520};
	mov.b32 	%r944, {%rs521, %rs522};
	mov.b32 	%r953, {%rs523, %rs524};
	mov.b32 	%r954, {%rs525, %rs526};
	mov.b32 	%r963, {%rs527, %rs528};
	mov.b32 	%r964, {%rs529, %rs530};
	mov.b32 	%r973, {%rs531, %rs532};
	mov.b32 	%r974, {%rs533, %rs534};
	mov.b32 	%r983, {%rs535, %rs536};
	mov.b32 	%r984, {%rs537, %rs538};
	mov.b32 	%r993, {%rs539, %rs540};
	mov.b32 	%r994, {%rs541, %rs542};
	mov.b32 	%r1003, {%rs543, %rs544};
	mov.b32 	%r1004, {%rs545, %rs546};
	mov.b32 	%r1013, {%rs547, %rs548};
	mov.b32 	%r1014, {%rs549, %rs550};
	mov.b32 	%r1023, {%rs551, %rs552};
	mov.b32 	%r1024, {%rs553, %rs554};
	mov.b32 	%r1033, {%rs555, %rs556};
	mov.b32 	%r1034, {%rs557, %rs558};
	mov.b32 	%r1043, {%rs559, %rs560};
	mov.b32 	%r1044, {%rs561, %rs562};
	mov.b32 	%r1053, {%rs563, %rs564};
	mov.b32 	%r1054, {%rs565, %rs566};
	mov.b32 	%r1063, {%rs567, %rs568};
	mov.b32 	%r1064, {%rs569, %rs570};
	mov.b32 	%r1073, {%rs571, %rs572};
	mov.b32 	%r1074, {%rs573, %rs574};
	mov.b32 	%r1083, {%rs575, %rs576};
	mov.b32 	%r1084, {%rs577, %rs578};
	mov.b32 	%r1093, {%rs579, %rs580};
	mov.b32 	%r1094, {%rs581, %rs582};
	mov.b32 	%r1103, {%rs583, %rs584};
	mov.b32 	%r1104, {%rs585, %rs586};
	mov.b32 	%r1113, {%rs587, %rs588};
	mov.b32 	%r1114, {%rs589, %rs590};
	mov.b32 	%r1123, {%rs591, %rs592};
	mov.b32 	%r1124, {%rs593, %rs594};
	mov.b32 	%r1133, {%rs595, %rs596};
	mov.b32 	%r1134, {%rs597, %rs598};
	mov.b32 	%r1143, {%rs599, %rs600};
	mov.b32 	%r1144, {%rs601, %rs602};
	mov.b32 	%r1153, {%rs603, %rs604};
	mov.b32 	%r1154, {%rs605, %rs606};
	mov.b32 	%r1163, {%rs607, %rs608};
	mov.b32 	%r1164, {%rs609, %rs610};
	mov.b32 	%r1173, {%rs611, %rs612};
	mov.b32 	%r1174, {%rs613, %rs614};
	mov.b32 	%r1183, {%rs615, %rs616};
	mov.b32 	%r1184, {%rs617, %rs618};
	mov.b32 	%r1193, {%rs619, %rs620};
	mov.b32 	%r1194, {%rs621, %rs622};
	mov.b32 	%r1203, {%rs623, %rs624};
	mov.b32 	%r1204, {%rs625, %rs626};
	mov.b32 	%r1213, {%rs627, %rs628};
	mov.b32 	%r1214, {%rs629, %rs630};
	mov.b32 	%r1223, {%rs631, %rs632};
	mov.b32 	%r1224, {%rs633, %rs634};
	mov.b32 	%r1233, {%rs635, %rs636};
	mov.b32 	%r1234, {%rs637, %rs638};
	mov.b32 	%r1243, {%rs639, %rs640};
	mov.b32 	%r1244, {%rs641, %rs642};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r933, %r934 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1746, %r1747 }, { %r933, %r934 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r943, %r944 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1748, %r1749 }, { %r943, %r944 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r953, %r954 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1742, %r1743 }, { %r953, %r954 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r963, %r964 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1744, %r1745 }, { %r963, %r964 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r973, %r974 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1738, %r1739 }, { %r973, %r974 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r983, %r984 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1740, %r1741 }, { %r983, %r984 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r993, %r994 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1734, %r1735 }, { %r993, %r994 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1003, %r1004 }, { %r1762, %r1763, %r1764, %r1765 }, { %r1736, %r1737 }, { %r1003, %r1004 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1013, %r1014 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1746, %r1747 }, { %r1013, %r1014 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1023, %r1024 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1748, %r1749 }, { %r1023, %r1024 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1033, %r1034 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1742, %r1743 }, { %r1033, %r1034 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1043, %r1044 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1744, %r1745 }, { %r1043, %r1044 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1053, %r1054 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1738, %r1739 }, { %r1053, %r1054 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1063, %r1064 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1740, %r1741 }, { %r1063, %r1064 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1073, %r1074 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1734, %r1735 }, { %r1073, %r1074 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1083, %r1084 }, { %r1758, %r1759, %r1760, %r1761 }, { %r1736, %r1737 }, { %r1083, %r1084 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1093, %r1094 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1746, %r1747 }, { %r1093, %r1094 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1103, %r1104 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1748, %r1749 }, { %r1103, %r1104 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1113, %r1114 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1742, %r1743 }, { %r1113, %r1114 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1123, %r1124 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1744, %r1745 }, { %r1123, %r1124 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1133, %r1134 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1738, %r1739 }, { %r1133, %r1134 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1143, %r1144 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1740, %r1741 }, { %r1143, %r1144 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1153, %r1154 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1734, %r1735 }, { %r1153, %r1154 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1163, %r1164 }, { %r1754, %r1755, %r1756, %r1757 }, { %r1736, %r1737 }, { %r1163, %r1164 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1173, %r1174 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1746, %r1747 }, { %r1173, %r1174 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1183, %r1184 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1748, %r1749 }, { %r1183, %r1184 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1193, %r1194 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1742, %r1743 }, { %r1193, %r1194 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1203, %r1204 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1744, %r1745 }, { %r1203, %r1204 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1213, %r1214 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1738, %r1739 }, { %r1213, %r1214 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1223, %r1224 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1740, %r1741 }, { %r1223, %r1224 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1233, %r1234 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1734, %r1735 }, { %r1233, %r1234 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1243, %r1244 }, { %r1750, %r1751, %r1752, %r1753 }, { %r1736, %r1737 }, { %r1243, %r1244 };
	// end inline asm
	.loc	1 102 18
	add.s64 	%rd114, %rd28, %rd136;
	.loc	1 103 18
	add.s64 	%rd115, %rd27, %rd136;
	add.s64 	%rd116, %rd26, %rd136;
	add.s64 	%rd117, %rd25, %rd136;
	add.s64 	%rd118, %rd24, %rd136;
	.loc	1 93 22
	add.s64 	%rd119, %rd23, %rd136;
	add.s32 	%r1319, %r1769, 1;
	setp.lt.s32 	%p138, %r1319, 2;
	selp.b32 	%r1769, %r1319, 0, %p138;
	.loc	1 96 72
	setp.lt.s32 	%p139, %r1733, %r195;
	.loc	1 96 20
	shl.b32 	%r1320, %r1769, 13;
	add.s32 	%r1322, %r484, %r1320;
	bar.sync 	0;
	add.s32 	%r881, %r1322, %r483;
	add.s32 	%r883, %r1322, %r486;
	selp.b32 	%r1325, 16, 0, %p139;
	selp.b32 	%r884, %r1325, 0, %p137;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r881 + 0 ], [ %rd114 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r883 + 0 ], [ %rd115 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	shl.b32 	%r1326, %r1769, 14;
	add.s32 	%r1328, %r488, %r1326;
	add.s32 	%r885, %r1328, %r483;
	add.s32 	%r887, %r1328, %r486;
	add.s32 	%r889, %r1328, %r490;
	add.s32 	%r891, %r1328, %r492;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r885 + 0 ], [ %rd116 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r887 + 0 ], [ %rd117 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r889 + 0 ], [ %rd118 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r891 + 0 ], [ %rd119 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1331, %r1768, 1;
	setp.lt.s32 	%p140, %r1331, 2;
	selp.b32 	%r1768, %r1331, 0, %p140;
	.loc	1 96 20
	shl.b32 	%r1332, %r1768, 13;
	add.s32 	%r1767, %r484, %r1332;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1333, %r1768, 14;
	add.s32 	%r1766, %r488, %r1333;
	.loc	1 96 20
	add.s32 	%r897, %r1767, %r504;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1762, %r1763, %r1764, %r1765 }, [ %r897 + 0 ];
	// end inline asm
	add.s32 	%r902, %r897, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1758, %r1759, %r1760, %r1761 }, [ %r902 + 0 ];
	// end inline asm
	add.s32 	%r907, %r897, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1754, %r1755, %r1756, %r1757 }, [ %r907 + 0 ];
	// end inline asm
	add.s32 	%r912, %r897, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1750, %r1751, %r1752, %r1753 }, [ %r912 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r917, %r1766, %r510;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1746, %r1747, %r1748, %r1749 }, [ %r917 + 0 ];
	// end inline asm
	add.s32 	%r922, %r917, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1742, %r1743, %r1744, %r1745 }, [ %r922 + 0 ];
	// end inline asm
	add.s32 	%r927, %r917, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1738, %r1739, %r1740, %r1741 }, [ %r927 + 0 ];
	// end inline asm
	add.s32 	%r932, %r917, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1734, %r1735, %r1736, %r1737 }, [ %r932 + 0 ];
	// end inline asm
	.loc	1 100 35
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r933, %r934 }, { %r937, %r938, %r939, %r940 }, { %r941, %r942 }, { %r933, %r934 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r943, %r944 }, { %r937, %r938, %r939, %r940 }, { %r951, %r952 }, { %r943, %r944 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r953, %r954 }, { %r937, %r938, %r939, %r940 }, { %r961, %r962 }, { %r953, %r954 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r963, %r964 }, { %r937, %r938, %r939, %r940 }, { %r971, %r972 }, { %r963, %r964 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r973, %r974 }, { %r937, %r938, %r939, %r940 }, { %r981, %r982 }, { %r973, %r974 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r983, %r984 }, { %r937, %r938, %r939, %r940 }, { %r991, %r992 }, { %r983, %r984 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r993, %r994 }, { %r937, %r938, %r939, %r940 }, { %r1001, %r1002 }, { %r993, %r994 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1003, %r1004 }, { %r937, %r938, %r939, %r940 }, { %r1011, %r1012 }, { %r1003, %r1004 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1013, %r1014 }, { %r1017, %r1018, %r1019, %r1020 }, { %r941, %r942 }, { %r1013, %r1014 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1023, %r1024 }, { %r1017, %r1018, %r1019, %r1020 }, { %r951, %r952 }, { %r1023, %r1024 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1033, %r1034 }, { %r1017, %r1018, %r1019, %r1020 }, { %r961, %r962 }, { %r1033, %r1034 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1043, %r1044 }, { %r1017, %r1018, %r1019, %r1020 }, { %r971, %r972 }, { %r1043, %r1044 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1053, %r1054 }, { %r1017, %r1018, %r1019, %r1020 }, { %r981, %r982 }, { %r1053, %r1054 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1063, %r1064 }, { %r1017, %r1018, %r1019, %r1020 }, { %r991, %r992 }, { %r1063, %r1064 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1073, %r1074 }, { %r1017, %r1018, %r1019, %r1020 }, { %r1001, %r1002 }, { %r1073, %r1074 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1083, %r1084 }, { %r1017, %r1018, %r1019, %r1020 }, { %r1011, %r1012 }, { %r1083, %r1084 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1093, %r1094 }, { %r1097, %r1098, %r1099, %r1100 }, { %r941, %r942 }, { %r1093, %r1094 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1103, %r1104 }, { %r1097, %r1098, %r1099, %r1100 }, { %r951, %r952 }, { %r1103, %r1104 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1113, %r1114 }, { %r1097, %r1098, %r1099, %r1100 }, { %r961, %r962 }, { %r1113, %r1114 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1123, %r1124 }, { %r1097, %r1098, %r1099, %r1100 }, { %r971, %r972 }, { %r1123, %r1124 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1133, %r1134 }, { %r1097, %r1098, %r1099, %r1100 }, { %r981, %r982 }, { %r1133, %r1134 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1143, %r1144 }, { %r1097, %r1098, %r1099, %r1100 }, { %r991, %r992 }, { %r1143, %r1144 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1153, %r1154 }, { %r1097, %r1098, %r1099, %r1100 }, { %r1001, %r1002 }, { %r1153, %r1154 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1163, %r1164 }, { %r1097, %r1098, %r1099, %r1100 }, { %r1011, %r1012 }, { %r1163, %r1164 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1173, %r1174 }, { %r1177, %r1178, %r1179, %r1180 }, { %r941, %r942 }, { %r1173, %r1174 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1183, %r1184 }, { %r1177, %r1178, %r1179, %r1180 }, { %r951, %r952 }, { %r1183, %r1184 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1193, %r1194 }, { %r1177, %r1178, %r1179, %r1180 }, { %r961, %r962 }, { %r1193, %r1194 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1203, %r1204 }, { %r1177, %r1178, %r1179, %r1180 }, { %r971, %r972 }, { %r1203, %r1204 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1213, %r1214 }, { %r1177, %r1178, %r1179, %r1180 }, { %r981, %r982 }, { %r1213, %r1214 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1223, %r1224 }, { %r1177, %r1178, %r1179, %r1180 }, { %r991, %r992 }, { %r1223, %r1224 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1233, %r1234 }, { %r1177, %r1178, %r1179, %r1180 }, { %r1001, %r1002 }, { %r1233, %r1234 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1243, %r1244 }, { %r1177, %r1178, %r1179, %r1180 }, { %r1011, %r1012 }, { %r1243, %r1244 };
	// end inline asm
	mov.b32 	{%rs515, %rs516}, %r933;
	mov.b32 	{%rs517, %rs518}, %r934;
	mov.b32 	{%rs519, %rs520}, %r943;
	mov.b32 	{%rs521, %rs522}, %r944;
	mov.b32 	{%rs523, %rs524}, %r953;
	mov.b32 	{%rs525, %rs526}, %r954;
	mov.b32 	{%rs527, %rs528}, %r963;
	mov.b32 	{%rs529, %rs530}, %r964;
	mov.b32 	{%rs531, %rs532}, %r973;
	mov.b32 	{%rs533, %rs534}, %r974;
	mov.b32 	{%rs535, %rs536}, %r983;
	mov.b32 	{%rs537, %rs538}, %r984;
	mov.b32 	{%rs539, %rs540}, %r993;
	mov.b32 	{%rs541, %rs542}, %r994;
	mov.b32 	{%rs543, %rs544}, %r1003;
	mov.b32 	{%rs545, %rs546}, %r1004;
	mov.b32 	{%rs547, %rs548}, %r1013;
	mov.b32 	{%rs549, %rs550}, %r1014;
	mov.b32 	{%rs551, %rs552}, %r1023;
	mov.b32 	{%rs553, %rs554}, %r1024;
	mov.b32 	{%rs555, %rs556}, %r1033;
	mov.b32 	{%rs557, %rs558}, %r1034;
	mov.b32 	{%rs559, %rs560}, %r1043;
	mov.b32 	{%rs561, %rs562}, %r1044;
	mov.b32 	{%rs563, %rs564}, %r1053;
	mov.b32 	{%rs565, %rs566}, %r1054;
	mov.b32 	{%rs567, %rs568}, %r1063;
	mov.b32 	{%rs569, %rs570}, %r1064;
	mov.b32 	{%rs571, %rs572}, %r1073;
	mov.b32 	{%rs573, %rs574}, %r1074;
	mov.b32 	{%rs575, %rs576}, %r1083;
	mov.b32 	{%rs577, %rs578}, %r1084;
	mov.b32 	{%rs579, %rs580}, %r1093;
	mov.b32 	{%rs581, %rs582}, %r1094;
	mov.b32 	{%rs583, %rs584}, %r1103;
	mov.b32 	{%rs585, %rs586}, %r1104;
	mov.b32 	{%rs587, %rs588}, %r1113;
	mov.b32 	{%rs589, %rs590}, %r1114;
	mov.b32 	{%rs591, %rs592}, %r1123;
	mov.b32 	{%rs593, %rs594}, %r1124;
	mov.b32 	{%rs595, %rs596}, %r1133;
	mov.b32 	{%rs597, %rs598}, %r1134;
	mov.b32 	{%rs599, %rs600}, %r1143;
	mov.b32 	{%rs601, %rs602}, %r1144;
	mov.b32 	{%rs603, %rs604}, %r1153;
	mov.b32 	{%rs605, %rs606}, %r1154;
	mov.b32 	{%rs607, %rs608}, %r1163;
	mov.b32 	{%rs609, %rs610}, %r1164;
	mov.b32 	{%rs611, %rs612}, %r1173;
	mov.b32 	{%rs613, %rs614}, %r1174;
	mov.b32 	{%rs615, %rs616}, %r1183;
	mov.b32 	{%rs617, %rs618}, %r1184;
	mov.b32 	{%rs619, %rs620}, %r1193;
	mov.b32 	{%rs621, %rs622}, %r1194;
	mov.b32 	{%rs623, %rs624}, %r1203;
	mov.b32 	{%rs625, %rs626}, %r1204;
	mov.b32 	{%rs627, %rs628}, %r1213;
	mov.b32 	{%rs629, %rs630}, %r1214;
	mov.b32 	{%rs631, %rs632}, %r1223;
	mov.b32 	{%rs633, %rs634}, %r1224;
	mov.b32 	{%rs635, %rs636}, %r1233;
	mov.b32 	{%rs637, %rs638}, %r1234;
	mov.b32 	{%rs639, %rs640}, %r1243;
	mov.b32 	{%rs641, %rs642}, %r1244;
	.loc	1 93 22
	add.s32 	%r1770, %r1770, 1;
	add.s64 	%rd136, %rd136, 64;
	add.s32 	%r1733, %r1733, 32;
	setp.lt.s32 	%p141, %r1770, %r69;
	@%p141 bra 	$L__BB0_2;
$L__BB0_3:
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	shr.u32 	%r1528, %r2, 2;
	shl.b32 	%r1529, %r1, 1;
	and.b32  	%r1530, %r1529, 6;
	or.b32  	%r1531, %r1528, %r77;
	or.b32  	%r1532, %r96, %r1530;
	mad.lo.s32 	%r1533, %r1531, 264, %r1532;
	shl.b32 	%r1534, %r1533, 1;
	add.s32 	%r1536, %r484, %r1534;
	mov.b32 	%r1537, {%rs515, %rs516};
	st.shared.b32 	[%r1536], %r1537;
	mov.b32 	%r1538, {%rs517, %rs518};
	st.shared.b32 	[%r1536+4224], %r1538;
	mov.b32 	%r1539, {%rs519, %rs520};
	st.shared.b32 	[%r1536+64], %r1539;
	mov.b32 	%r1540, {%rs521, %rs522};
	st.shared.b32 	[%r1536+4288], %r1540;
	mov.b32 	%r1541, {%rs523, %rs524};
	st.shared.b32 	[%r1536+128], %r1541;
	mov.b32 	%r1542, {%rs525, %rs526};
	st.shared.b32 	[%r1536+4352], %r1542;
	mov.b32 	%r1543, {%rs527, %rs528};
	st.shared.b32 	[%r1536+192], %r1543;
	mov.b32 	%r1544, {%rs529, %rs530};
	st.shared.b32 	[%r1536+4416], %r1544;
	mov.b32 	%r1545, {%rs531, %rs532};
	st.shared.b32 	[%r1536+256], %r1545;
	mov.b32 	%r1546, {%rs533, %rs534};
	st.shared.b32 	[%r1536+4480], %r1546;
	mov.b32 	%r1547, {%rs535, %rs536};
	st.shared.b32 	[%r1536+320], %r1547;
	mov.b32 	%r1548, {%rs537, %rs538};
	st.shared.b32 	[%r1536+4544], %r1548;
	mov.b32 	%r1549, {%rs539, %rs540};
	st.shared.b32 	[%r1536+384], %r1549;
	mov.b32 	%r1550, {%rs541, %rs542};
	st.shared.b32 	[%r1536+4608], %r1550;
	mov.b32 	%r1551, {%rs543, %rs544};
	st.shared.b32 	[%r1536+448], %r1551;
	mov.b32 	%r1552, {%rs545, %rs546};
	st.shared.b32 	[%r1536+4672], %r1552;
	bar.sync 	0;
	shl.b32 	%r1553, %r2, 3;
	mad.lo.s32 	%r1554, %r3, 264, %r1553;
	shl.b32 	%r1555, %r1554, 1;
	add.s32 	%r1556, %r484, %r1555;
	mov.b32 	%r1557, {%rs547, %rs548};
	mov.b32 	%r1558, {%rs549, %rs550};
	mov.b32 	%r1559, {%rs551, %rs552};
	mov.b32 	%r1560, {%rs553, %rs554};
	mov.b32 	%r1561, {%rs555, %rs556};
	mov.b32 	%r1562, {%rs557, %rs558};
	mov.b32 	%r1563, {%rs559, %rs560};
	mov.b32 	%r1564, {%rs561, %rs562};
	mov.b32 	%r1565, {%rs563, %rs564};
	mov.b32 	%r1566, {%rs565, %rs566};
	mov.b32 	%r1567, {%rs567, %rs568};
	mov.b32 	%r1568, {%rs569, %rs570};
	mov.b32 	%r1569, {%rs571, %rs572};
	mov.b32 	%r1570, {%rs573, %rs574};
	mov.b32 	%r1571, {%rs575, %rs576};
	mov.b32 	%r1572, {%rs577, %rs578};
	mov.b32 	%r1573, {%rs579, %rs580};
	mov.b32 	%r1574, {%rs581, %rs582};
	mov.b32 	%r1575, {%rs583, %rs584};
	mov.b32 	%r1576, {%rs585, %rs586};
	mov.b32 	%r1577, {%rs587, %rs588};
	mov.b32 	%r1578, {%rs589, %rs590};
	mov.b32 	%r1579, {%rs591, %rs592};
	mov.b32 	%r1580, {%rs593, %rs594};
	mov.b32 	%r1581, {%rs595, %rs596};
	mov.b32 	%r1582, {%rs597, %rs598};
	mov.b32 	%r1583, {%rs599, %rs600};
	mov.b32 	%r1584, {%rs601, %rs602};
	mov.b32 	%r1585, {%rs603, %rs604};
	mov.b32 	%r1586, {%rs605, %rs606};
	mov.b32 	%r1587, {%rs607, %rs608};
	mov.b32 	%r1588, {%rs609, %rs610};
	mov.b32 	%r1589, {%rs611, %rs612};
	mov.b32 	%r1590, {%rs613, %rs614};
	mov.b32 	%r1591, {%rs615, %rs616};
	mov.b32 	%r1592, {%rs617, %rs618};
	mov.b32 	%r1593, {%rs619, %rs620};
	mov.b32 	%r1594, {%rs621, %rs622};
	mov.b32 	%r1595, {%rs623, %rs624};
	mov.b32 	%r1596, {%rs625, %rs626};
	mov.b32 	%r1597, {%rs627, %rs628};
	mov.b32 	%r1598, {%rs629, %rs630};
	mov.b32 	%r1599, {%rs631, %rs632};
	mov.b32 	%r1600, {%rs633, %rs634};
	mov.b32 	%r1601, {%rs635, %rs636};
	mov.b32 	%r1602, {%rs637, %rs638};
	mov.b32 	%r1603, {%rs639, %rs640};
	mov.b32 	%r1604, {%rs641, %rs642};
	ld.shared.v4.b32 	{%r1605, %r1606, %r1607, %r1608}, [%r1556];
	.loc	1 127 23
	add.f16x2 	%r1609, %r1605, %r197;
	add.f16x2 	%r1610, %r1606, %r198;
	add.f16x2 	%r1611, %r1607, %r199;
	add.f16x2 	%r1612, %r1608, %r200;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1613, %r1614, %r1615, %r1616}, [%r1556+4224];
	.loc	1 127 23
	add.f16x2 	%r1617, %r1613, %r205;
	add.f16x2 	%r1618, %r1614, %r206;
	add.f16x2 	%r1619, %r1615, %r207;
	add.f16x2 	%r1620, %r1616, %r208;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1621, %r1622, %r1623, %r1624}, [%r1556+8448];
	.loc	1 127 23
	add.f16x2 	%r1625, %r1621, %r213;
	add.f16x2 	%r1626, %r1622, %r214;
	add.f16x2 	%r1627, %r1623, %r215;
	add.f16x2 	%r1628, %r1624, %r216;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1629, %r1630, %r1631, %r1632}, [%r1556+12672];
	.loc	1 127 23
	add.f16x2 	%r1633, %r1629, %r221;
	add.f16x2 	%r1634, %r1630, %r222;
	add.f16x2 	%r1635, %r1631, %r223;
	.loc	1 93 22
	bar.sync 	0;
	st.shared.b32 	[%r1536], %r1557;
	st.shared.b32 	[%r1536+4224], %r1558;
	st.shared.b32 	[%r1536+64], %r1559;
	st.shared.b32 	[%r1536+4288], %r1560;
	st.shared.b32 	[%r1536+128], %r1561;
	st.shared.b32 	[%r1536+4352], %r1562;
	st.shared.b32 	[%r1536+192], %r1563;
	st.shared.b32 	[%r1536+4416], %r1564;
	st.shared.b32 	[%r1536+256], %r1565;
	st.shared.b32 	[%r1536+4480], %r1566;
	st.shared.b32 	[%r1536+320], %r1567;
	st.shared.b32 	[%r1536+4544], %r1568;
	st.shared.b32 	[%r1536+384], %r1569;
	st.shared.b32 	[%r1536+4608], %r1570;
	st.shared.b32 	[%r1536+448], %r1571;
	st.shared.b32 	[%r1536+4672], %r1572;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1636, %r1632, %r224;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1637, %r1638, %r1639, %r1640}, [%r1556];
	.loc	1 127 23
	add.f16x2 	%r1641, %r1637, %r229;
	add.f16x2 	%r1642, %r1638, %r230;
	add.f16x2 	%r1643, %r1639, %r231;
	add.f16x2 	%r1644, %r1640, %r232;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1645, %r1646, %r1647, %r1648}, [%r1556+4224];
	.loc	1 127 23
	add.f16x2 	%r1649, %r1645, %r237;
	add.f16x2 	%r1650, %r1646, %r238;
	add.f16x2 	%r1651, %r1647, %r239;
	add.f16x2 	%r1652, %r1648, %r240;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1653, %r1654, %r1655, %r1656}, [%r1556+8448];
	.loc	1 127 23
	add.f16x2 	%r1657, %r1653, %r245;
	add.f16x2 	%r1658, %r1654, %r246;
	add.f16x2 	%r1659, %r1655, %r247;
	add.f16x2 	%r1660, %r1656, %r248;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1661, %r1662, %r1663, %r1664}, [%r1556+12672];
	.loc	1 127 23
	add.f16x2 	%r1665, %r1661, %r253;
	add.f16x2 	%r1666, %r1662, %r254;
	add.f16x2 	%r1667, %r1663, %r255;
	.loc	1 93 22
	bar.sync 	0;
	st.shared.b32 	[%r1536], %r1573;
	st.shared.b32 	[%r1536+4224], %r1574;
	st.shared.b32 	[%r1536+64], %r1575;
	st.shared.b32 	[%r1536+4288], %r1576;
	st.shared.b32 	[%r1536+128], %r1577;
	st.shared.b32 	[%r1536+4352], %r1578;
	st.shared.b32 	[%r1536+192], %r1579;
	st.shared.b32 	[%r1536+4416], %r1580;
	st.shared.b32 	[%r1536+256], %r1581;
	st.shared.b32 	[%r1536+4480], %r1582;
	st.shared.b32 	[%r1536+320], %r1583;
	st.shared.b32 	[%r1536+4544], %r1584;
	st.shared.b32 	[%r1536+384], %r1585;
	st.shared.b32 	[%r1536+4608], %r1586;
	st.shared.b32 	[%r1536+448], %r1587;
	st.shared.b32 	[%r1536+4672], %r1588;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1668, %r1664, %r256;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1669, %r1670, %r1671, %r1672}, [%r1556];
	.loc	1 127 23
	add.f16x2 	%r1673, %r1669, %r261;
	add.f16x2 	%r1674, %r1670, %r262;
	add.f16x2 	%r1675, %r1671, %r263;
	add.f16x2 	%r1676, %r1672, %r264;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1677, %r1678, %r1679, %r1680}, [%r1556+4224];
	.loc	1 127 23
	add.f16x2 	%r1681, %r1677, %r269;
	add.f16x2 	%r1682, %r1678, %r270;
	add.f16x2 	%r1683, %r1679, %r271;
	add.f16x2 	%r1684, %r1680, %r272;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1685, %r1686, %r1687, %r1688}, [%r1556+8448];
	.loc	1 127 23
	add.f16x2 	%r1689, %r1685, %r277;
	add.f16x2 	%r1690, %r1686, %r278;
	add.f16x2 	%r1691, %r1687, %r279;
	add.f16x2 	%r1692, %r1688, %r280;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1693, %r1694, %r1695, %r1696}, [%r1556+12672];
	.loc	1 127 23
	add.f16x2 	%r1697, %r1693, %r285;
	add.f16x2 	%r1698, %r1694, %r286;
	add.f16x2 	%r1699, %r1695, %r287;
	.loc	1 93 22
	bar.sync 	0;
	st.shared.b32 	[%r1536], %r1589;
	st.shared.b32 	[%r1536+4224], %r1590;
	st.shared.b32 	[%r1536+64], %r1591;
	st.shared.b32 	[%r1536+4288], %r1592;
	st.shared.b32 	[%r1536+128], %r1593;
	st.shared.b32 	[%r1536+4352], %r1594;
	st.shared.b32 	[%r1536+192], %r1595;
	st.shared.b32 	[%r1536+4416], %r1596;
	st.shared.b32 	[%r1536+256], %r1597;
	st.shared.b32 	[%r1536+4480], %r1598;
	st.shared.b32 	[%r1536+320], %r1599;
	st.shared.b32 	[%r1536+4544], %r1600;
	st.shared.b32 	[%r1536+384], %r1601;
	st.shared.b32 	[%r1536+4608], %r1602;
	st.shared.b32 	[%r1536+448], %r1603;
	st.shared.b32 	[%r1536+4672], %r1604;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1700, %r1696, %r288;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1701, %r1702, %r1703, %r1704}, [%r1556];
	.loc	1 127 23
	add.f16x2 	%r1705, %r1701, %r293;
	add.f16x2 	%r1706, %r1702, %r294;
	add.f16x2 	%r1707, %r1703, %r295;
	add.f16x2 	%r1708, %r1704, %r296;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1709, %r1710, %r1711, %r1712}, [%r1556+4224];
	.loc	1 127 23
	add.f16x2 	%r1713, %r1709, %r301;
	add.f16x2 	%r1714, %r1710, %r302;
	add.f16x2 	%r1715, %r1711, %r303;
	add.f16x2 	%r1716, %r1712, %r304;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1717, %r1718, %r1719, %r1720}, [%r1556+8448];
	.loc	1 127 23
	add.f16x2 	%r1721, %r1717, %r309;
	add.f16x2 	%r1722, %r1718, %r310;
	add.f16x2 	%r1723, %r1719, %r311;
	add.f16x2 	%r1724, %r1720, %r312;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1725, %r1726, %r1727, %r1728}, [%r1556+12672];
	.loc	1 127 23
	add.f16x2 	%r1729, %r1725, %r317;
	add.f16x2 	%r1730, %r1726, %r318;
	add.f16x2 	%r1731, %r1727, %r319;
	add.f16x2 	%r1732, %r1728, %r320;
	.loc	1 129 21
	// begin inline asm
	@%p142 st.global.v4.b32 [ %rd120 + 0 ], { %r1609, %r1610, %r1611, %r1612 };
	// end inline asm
	// begin inline asm
	@%p143 st.global.v4.b32 [ %rd121 + 0 ], { %r1617, %r1618, %r1619, %r1620 };
	// end inline asm
	// begin inline asm
	@%p144 st.global.v4.b32 [ %rd122 + 0 ], { %r1625, %r1626, %r1627, %r1628 };
	// end inline asm
	// begin inline asm
	@%p145 st.global.v4.b32 [ %rd123 + 0 ], { %r1633, %r1634, %r1635, %r1636 };
	// end inline asm
	// begin inline asm
	@%p146 st.global.v4.b32 [ %rd124 + 0 ], { %r1641, %r1642, %r1643, %r1644 };
	// end inline asm
	// begin inline asm
	@%p147 st.global.v4.b32 [ %rd125 + 0 ], { %r1649, %r1650, %r1651, %r1652 };
	// end inline asm
	// begin inline asm
	@%p148 st.global.v4.b32 [ %rd126 + 0 ], { %r1657, %r1658, %r1659, %r1660 };
	// end inline asm
	// begin inline asm
	@%p149 st.global.v4.b32 [ %rd127 + 0 ], { %r1665, %r1666, %r1667, %r1668 };
	// end inline asm
	// begin inline asm
	@%p150 st.global.v4.b32 [ %rd128 + 0 ], { %r1673, %r1674, %r1675, %r1676 };
	// end inline asm
	// begin inline asm
	@%p151 st.global.v4.b32 [ %rd129 + 0 ], { %r1681, %r1682, %r1683, %r1684 };
	// end inline asm
	// begin inline asm
	@%p152 st.global.v4.b32 [ %rd130 + 0 ], { %r1689, %r1690, %r1691, %r1692 };
	// end inline asm
	// begin inline asm
	@%p153 st.global.v4.b32 [ %rd131 + 0 ], { %r1697, %r1698, %r1699, %r1700 };
	// end inline asm
	// begin inline asm
	@%p154 st.global.v4.b32 [ %rd132 + 0 ], { %r1705, %r1706, %r1707, %r1708 };
	// end inline asm
	// begin inline asm
	@%p155 st.global.v4.b32 [ %rd133 + 0 ], { %r1713, %r1714, %r1715, %r1716 };
	// end inline asm
	// begin inline asm
	@%p156 st.global.v4.b32 [ %rd134 + 0 ], { %r1721, %r1722, %r1723, %r1724 };
	// end inline asm
	// begin inline asm
	@%p157 st.global.v4.b32 [ %rd135 + 0 ], { %r1729, %r1730, %r1731, %r1732 };
	// end inline asm
	.loc	1 129 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/PycharmProjects/tritontest/compile_matmul_kernel_accumulate_transpose_b.py"
	.file	2 "/home/mike/PycharmProjects/tritontest/.venv/lib/python3.11/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 211
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 80
.b8 121
.b8 99
.b8 104
.b8 97
.b8 114
.b8 109
.b8 80
.b8 114
.b8 111
.b8 106
.b8 101
.b8 99
.b8 116
.b8 115
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 116
.b8 101
.b8 115
.b8 116
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 104
.b8 4
.b32 104
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 104
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 104
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_5_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_5_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_5_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_5_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_5_FUNCTION_NAME "matmul_kernel_accumulate_transpose_b"
