/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_11_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel_bias_accumulate_transpose_a
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel_bias_accumulate_transpose_a(
	.param .u64 matmul_kernel_bias_accumulate_transpose_a_param_0,
	.param .u64 matmul_kernel_bias_accumulate_transpose_a_param_1,
	.param .u64 matmul_kernel_bias_accumulate_transpose_a_param_2,
	.param .u64 matmul_kernel_bias_accumulate_transpose_a_param_3,
	.param .u32 matmul_kernel_bias_accumulate_transpose_a_param_4,
	.param .u32 matmul_kernel_bias_accumulate_transpose_a_param_5,
	.param .u32 matmul_kernel_bias_accumulate_transpose_a_param_6,
	.param .u32 matmul_kernel_bias_accumulate_transpose_a_param_7,
	.param .u32 matmul_kernel_bias_accumulate_transpose_a_param_8,
	.param .u32 matmul_kernel_bias_accumulate_transpose_a_param_9
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<175>;
	.reg .b16 	%rs<789>;
	.reg .b32 	%r<1857>;
	.reg .b64 	%rd<137>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r197, [matmul_kernel_bias_accumulate_transpose_a_param_6];
	ld.param.u32 	%r196, [matmul_kernel_bias_accumulate_transpose_a_param_5];
	ld.param.u64 	%rd38, [matmul_kernel_bias_accumulate_transpose_a_param_3];
	ld.param.u64 	%rd37, [matmul_kernel_bias_accumulate_transpose_a_param_1];
	ld.param.u64 	%rd67, [matmul_kernel_bias_accumulate_transpose_a_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r198, %ctaid.x;
	// end inline asm
	ld.param.u32 	%r391, [matmul_kernel_bias_accumulate_transpose_a_param_4];
$L__tmp1:
	.loc	2 40 22
	add.s32 	%r392, %r391, 127;
	ld.param.u64 	%rd68, [matmul_kernel_bias_accumulate_transpose_a_param_2];
	.loc	2 40 28
	shr.s32 	%r393, %r392, 31;
	shr.u32 	%r394, %r393, 25;
	add.s32 	%r395, %r392, %r394;
	shr.s32 	%r396, %r395, 7;
$L__tmp2:
	.loc	2 40 22
	add.s32 	%r397, %r196, 255;
	.loc	2 40 28
	shr.s32 	%r398, %r397, 31;
	shr.u32 	%r399, %r398, 24;
	add.s32 	%r400, %r397, %r399;
	shr.s32 	%r401, %r400, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r403, %r401, 3;
	ld.param.u32 	%r404, [matmul_kernel_bias_accumulate_transpose_a_param_7];
	ld.param.u32 	%r405, [matmul_kernel_bias_accumulate_transpose_a_param_8];
	.loc	1 61 22
	div.s32 	%r406, %r198, %r403;
	ld.param.u32 	%r407, [matmul_kernel_bias_accumulate_transpose_a_param_9];
	.loc	1 62 29
	shl.b32 	%r408, %r406, 3;
	.loc	1 63 35
	sub.s32 	%r409, %r396, %r408;
	.loc	1 63 48
	min.s32 	%r410, %r409, 8;
	.loc	1 64 33
	rem.s32 	%r411, %r198, %r410;
	.loc	1 64 27
	add.s32 	%r412, %r408, %r411;
	mul.lo.s32 	%r413, %r406, %r403;
	sub.s32 	%r414, %r198, %r413;
	.loc	1 65 40
	div.s32 	%r415, %r414, %r410;
	.loc	1 74 23
	shl.b32 	%r416, %r412, 7;
	.loc	1 74 51
	mov.u32 	%r1, %tid.x;
	and.b32  	%r2, %r1, 31;
	shl.b32 	%r417, %r1, 3;
	and.b32  	%r418, %r417, 120;
	bfe.u32 	%r3, %r1, 5, 3;
	or.b32  	%r419, %r3, 8;
	or.b32  	%r420, %r3, 16;
	or.b32  	%r421, %r3, 24;
	or.b32  	%r422, %r3, 32;
	or.b32  	%r423, %r3, 40;
	or.b32  	%r424, %r3, 48;
	or.b32  	%r425, %r3, 56;
	.loc	1 74 38
	or.b32  	%r426, %r416, %r418;
	or.b32  	%r427, %r416, %r3;
	or.b32  	%r428, %r416, %r419;
	or.b32  	%r429, %r416, %r420;
	or.b32  	%r430, %r416, %r421;
	or.b32  	%r431, %r416, %r422;
	or.b32  	%r432, %r416, %r423;
	or.b32  	%r433, %r416, %r424;
	or.b32  	%r434, %r416, %r425;
	or.b32  	%r435, %r427, 64;
	or.b32  	%r436, %r427, 72;
	or.b32  	%r437, %r427, 80;
	or.b32  	%r438, %r427, 88;
	or.b32  	%r439, %r427, 96;
	or.b32  	%r440, %r427, 104;
	or.b32  	%r441, %r427, 112;
	or.b32  	%r442, %r427, 120;
	.loc	1 74 68
	rem.s32 	%r443, %r426, %r391;
	.loc	1 75 23
	shl.b32 	%r4, %r415, 8;
	.loc	1 75 51
	and.b32  	%r444, %r417, 248;
	.loc	1 75 38
	or.b32  	%r445, %r4, %r444;
	.loc	1 75 68
	rem.s32 	%r446, %r445, %r196;
	.loc	1 77 60
	bfe.u32 	%r5, %r1, 4, 4;
	or.b32  	%r447, %r5, 16;
	.loc	1 77 71
	shl.b32 	%r448, %r404, 4;
	.loc	1 77 53
	mad.lo.s32 	%r449, %r5, %r404, %r443;
	add.s32 	%r450, %r449, %r448;
	.loc	1 77 22
	mul.wide.s32 	%rd69, %r449, 2;
	add.s64 	%rd55, %rd67, %rd69;
	mul.wide.s32 	%rd70, %r450, 2;
	add.s64 	%rd56, %rd67, %rd70;
	.loc	1 78 40
	shl.b32 	%r451, %r405, 3;
	.loc	1 78 52
	mad.lo.s32 	%r452, %r3, %r405, %r446;
	add.s32 	%r453, %r452, %r451;
	add.s32 	%r454, %r453, %r451;
	add.s32 	%r455, %r454, %r451;
	.loc	1 78 22
	mul.wide.s32 	%rd71, %r452, 2;
	add.s64 	%rd57, %rd37, %rd71;
	mul.wide.s32 	%rd72, %r453, 2;
	add.s64 	%rd58, %rd37, %rd72;
	mul.wide.s32 	%rd73, %r454, 2;
	add.s64 	%rd59, %rd37, %rd73;
	mul.wide.s32 	%rd74, %r455, 2;
	add.s64 	%rd60, %rd37, %rd74;
	.loc	1 82 33
	mul.lo.s32 	%r456, %r427, %r407;
	mul.lo.s32 	%r457, %r428, %r407;
	mul.lo.s32 	%r458, %r429, %r407;
	mul.lo.s32 	%r459, %r430, %r407;
	mul.lo.s32 	%r460, %r431, %r407;
	mul.lo.s32 	%r461, %r432, %r407;
	mul.lo.s32 	%r462, %r433, %r407;
	mul.lo.s32 	%r463, %r434, %r407;
	shl.b32 	%r464, %r407, 6;
	add.s32 	%r465, %r456, %r464;
	shl.b32 	%r466, %r407, 3;
	add.s32 	%r467, %r465, %r466;
	add.s32 	%r468, %r467, %r466;
	add.s32 	%r469, %r468, %r466;
	add.s32 	%r470, %r469, %r466;
	add.s32 	%r471, %r470, %r466;
	add.s32 	%r472, %r471, %r466;
	add.s32 	%r473, %r472, %r466;
	.loc	1 82 21
	mul.wide.s32 	%rd75, %r456, 2;
	add.s64 	%rd76, %rd68, %rd75;
	mul.wide.s32 	%rd77, %r457, 2;
	add.s64 	%rd78, %rd68, %rd77;
	mul.wide.s32 	%rd79, %r458, 2;
	add.s64 	%rd80, %rd68, %rd79;
	mul.wide.s32 	%rd81, %r459, 2;
	add.s64 	%rd82, %rd68, %rd81;
	mul.wide.s32 	%rd83, %r460, 2;
	add.s64 	%rd84, %rd68, %rd83;
	mul.wide.s32 	%rd85, %r461, 2;
	add.s64 	%rd86, %rd68, %rd85;
	mul.wide.s32 	%rd87, %r462, 2;
	add.s64 	%rd88, %rd68, %rd87;
	mul.wide.s32 	%rd89, %r463, 2;
	add.s64 	%rd90, %rd68, %rd89;
	mul.wide.s32 	%rd91, %r465, 2;
	add.s64 	%rd92, %rd68, %rd91;
	mul.wide.s32 	%rd93, %r467, 2;
	add.s64 	%rd94, %rd68, %rd93;
	mul.wide.s32 	%rd95, %r468, 2;
	add.s64 	%rd96, %rd68, %rd95;
	mul.wide.s32 	%rd97, %r469, 2;
	add.s64 	%rd98, %rd68, %rd97;
	mul.wide.s32 	%rd99, %r470, 2;
	add.s64 	%rd100, %rd68, %rd99;
	mul.wide.s32 	%rd101, %r471, 2;
	add.s64 	%rd102, %rd68, %rd101;
	mul.wide.s32 	%rd103, %r472, 2;
	add.s64 	%rd104, %rd68, %rd103;
	mul.wide.s32 	%rd105, %r473, 2;
	add.s64 	%rd106, %rd68, %rd105;
	.loc	1 82 52
	mul.wide.s32 	%rd107, %r445, 2;
	add.s64 	%rd118, %rd76, %rd107;
	add.s64 	%rd119, %rd78, %rd107;
	add.s64 	%rd120, %rd80, %rd107;
	add.s64 	%rd121, %rd82, %rd107;
	add.s64 	%rd122, %rd84, %rd107;
	add.s64 	%rd123, %rd86, %rd107;
	add.s64 	%rd124, %rd88, %rd107;
	add.s64 	%rd125, %rd90, %rd107;
	add.s64 	%rd126, %rd92, %rd107;
	add.s64 	%rd127, %rd94, %rd107;
	add.s64 	%rd128, %rd96, %rd107;
	add.s64 	%rd129, %rd98, %rd107;
	add.s64 	%rd130, %rd100, %rd107;
	add.s64 	%rd131, %rd102, %rd107;
	add.s64 	%rd132, %rd104, %rd107;
	add.s64 	%rd133, %rd106, %rd107;
	.loc	1 83 33
	setp.lt.s32 	%p109, %r427, %r391;
	setp.lt.s32 	%p110, %r428, %r391;
	setp.lt.s32 	%p111, %r429, %r391;
	setp.lt.s32 	%p112, %r430, %r391;
	setp.lt.s32 	%p113, %r431, %r391;
	setp.lt.s32 	%p114, %r432, %r391;
	setp.lt.s32 	%p115, %r433, %r391;
	setp.lt.s32 	%p116, %r434, %r391;
	setp.lt.s32 	%p117, %r435, %r391;
	setp.lt.s32 	%p118, %r436, %r391;
	setp.lt.s32 	%p119, %r437, %r391;
	setp.lt.s32 	%p120, %r438, %r391;
	setp.lt.s32 	%p121, %r439, %r391;
	setp.lt.s32 	%p122, %r440, %r391;
	setp.lt.s32 	%p123, %r441, %r391;
	setp.lt.s32 	%p124, %r442, %r391;
	.loc	1 83 58
	setp.lt.s32 	%p125, %r445, %r196;
	.loc	1 83 39
	and.pred  	%p159, %p109, %p125;
	and.pred  	%p160, %p110, %p125;
	and.pred  	%p161, %p111, %p125;
	and.pred  	%p162, %p112, %p125;
	and.pred  	%p163, %p113, %p125;
	and.pred  	%p164, %p114, %p125;
	and.pred  	%p165, %p115, %p125;
	and.pred  	%p166, %p116, %p125;
	and.pred  	%p167, %p117, %p125;
	and.pred  	%p168, %p118, %p125;
	and.pred  	%p169, %p119, %p125;
	and.pred  	%p170, %p120, %p125;
	and.pred  	%p171, %p121, %p125;
	and.pred  	%p172, %p122, %p125;
	and.pred  	%p173, %p123, %p125;
	and.pred  	%p174, %p124, %p125;
	mov.b32 	%r1819, 0;
	.loc	1 89 30
	// begin inline asm
	mov.u32 %r199, 0x0;
	mov.u32 %r200, 0x0;
	mov.u32 %r201, 0x0;
	mov.u32 %r202, 0x0;
	@%p159 ld.global.v4.b32 { %r199, %r200, %r201, %r202 }, [ %rd118 + 0 ];
	@!%p159 mov.u32 %r199, %r1819;
	@!%p159 mov.u32 %r200, %r1819;
	@!%p159 mov.u32 %r201, %r1819;
	@!%p159 mov.u32 %r202, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r207, 0x0;
	mov.u32 %r208, 0x0;
	mov.u32 %r209, 0x0;
	mov.u32 %r210, 0x0;
	@%p160 ld.global.v4.b32 { %r207, %r208, %r209, %r210 }, [ %rd119 + 0 ];
	@!%p160 mov.u32 %r207, %r1819;
	@!%p160 mov.u32 %r208, %r1819;
	@!%p160 mov.u32 %r209, %r1819;
	@!%p160 mov.u32 %r210, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r215, 0x0;
	mov.u32 %r216, 0x0;
	mov.u32 %r217, 0x0;
	mov.u32 %r218, 0x0;
	@%p161 ld.global.v4.b32 { %r215, %r216, %r217, %r218 }, [ %rd120 + 0 ];
	@!%p161 mov.u32 %r215, %r1819;
	@!%p161 mov.u32 %r216, %r1819;
	@!%p161 mov.u32 %r217, %r1819;
	@!%p161 mov.u32 %r218, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r223, 0x0;
	mov.u32 %r224, 0x0;
	mov.u32 %r225, 0x0;
	mov.u32 %r226, 0x0;
	@%p162 ld.global.v4.b32 { %r223, %r224, %r225, %r226 }, [ %rd121 + 0 ];
	@!%p162 mov.u32 %r223, %r1819;
	@!%p162 mov.u32 %r224, %r1819;
	@!%p162 mov.u32 %r225, %r1819;
	@!%p162 mov.u32 %r226, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r231, 0x0;
	mov.u32 %r232, 0x0;
	mov.u32 %r233, 0x0;
	mov.u32 %r234, 0x0;
	@%p163 ld.global.v4.b32 { %r231, %r232, %r233, %r234 }, [ %rd122 + 0 ];
	@!%p163 mov.u32 %r231, %r1819;
	@!%p163 mov.u32 %r232, %r1819;
	@!%p163 mov.u32 %r233, %r1819;
	@!%p163 mov.u32 %r234, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r239, 0x0;
	mov.u32 %r240, 0x0;
	mov.u32 %r241, 0x0;
	mov.u32 %r242, 0x0;
	@%p164 ld.global.v4.b32 { %r239, %r240, %r241, %r242 }, [ %rd123 + 0 ];
	@!%p164 mov.u32 %r239, %r1819;
	@!%p164 mov.u32 %r240, %r1819;
	@!%p164 mov.u32 %r241, %r1819;
	@!%p164 mov.u32 %r242, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r247, 0x0;
	mov.u32 %r248, 0x0;
	mov.u32 %r249, 0x0;
	mov.u32 %r250, 0x0;
	@%p165 ld.global.v4.b32 { %r247, %r248, %r249, %r250 }, [ %rd124 + 0 ];
	@!%p165 mov.u32 %r247, %r1819;
	@!%p165 mov.u32 %r248, %r1819;
	@!%p165 mov.u32 %r249, %r1819;
	@!%p165 mov.u32 %r250, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r255, 0x0;
	mov.u32 %r256, 0x0;
	mov.u32 %r257, 0x0;
	mov.u32 %r258, 0x0;
	@%p166 ld.global.v4.b32 { %r255, %r256, %r257, %r258 }, [ %rd125 + 0 ];
	@!%p166 mov.u32 %r255, %r1819;
	@!%p166 mov.u32 %r256, %r1819;
	@!%p166 mov.u32 %r257, %r1819;
	@!%p166 mov.u32 %r258, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r263, 0x0;
	mov.u32 %r264, 0x0;
	mov.u32 %r265, 0x0;
	mov.u32 %r266, 0x0;
	@%p167 ld.global.v4.b32 { %r263, %r264, %r265, %r266 }, [ %rd126 + 0 ];
	@!%p167 mov.u32 %r263, %r1819;
	@!%p167 mov.u32 %r264, %r1819;
	@!%p167 mov.u32 %r265, %r1819;
	@!%p167 mov.u32 %r266, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r271, 0x0;
	mov.u32 %r272, 0x0;
	mov.u32 %r273, 0x0;
	mov.u32 %r274, 0x0;
	@%p168 ld.global.v4.b32 { %r271, %r272, %r273, %r274 }, [ %rd127 + 0 ];
	@!%p168 mov.u32 %r271, %r1819;
	@!%p168 mov.u32 %r272, %r1819;
	@!%p168 mov.u32 %r273, %r1819;
	@!%p168 mov.u32 %r274, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r279, 0x0;
	mov.u32 %r280, 0x0;
	mov.u32 %r281, 0x0;
	mov.u32 %r282, 0x0;
	@%p169 ld.global.v4.b32 { %r279, %r280, %r281, %r282 }, [ %rd128 + 0 ];
	@!%p169 mov.u32 %r279, %r1819;
	@!%p169 mov.u32 %r280, %r1819;
	@!%p169 mov.u32 %r281, %r1819;
	@!%p169 mov.u32 %r282, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r287, 0x0;
	mov.u32 %r288, 0x0;
	mov.u32 %r289, 0x0;
	mov.u32 %r290, 0x0;
	@%p170 ld.global.v4.b32 { %r287, %r288, %r289, %r290 }, [ %rd129 + 0 ];
	@!%p170 mov.u32 %r287, %r1819;
	@!%p170 mov.u32 %r288, %r1819;
	@!%p170 mov.u32 %r289, %r1819;
	@!%p170 mov.u32 %r290, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r295, 0x0;
	mov.u32 %r296, 0x0;
	mov.u32 %r297, 0x0;
	mov.u32 %r298, 0x0;
	@%p171 ld.global.v4.b32 { %r295, %r296, %r297, %r298 }, [ %rd130 + 0 ];
	@!%p171 mov.u32 %r295, %r1819;
	@!%p171 mov.u32 %r296, %r1819;
	@!%p171 mov.u32 %r297, %r1819;
	@!%p171 mov.u32 %r298, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r303, 0x0;
	mov.u32 %r304, 0x0;
	mov.u32 %r305, 0x0;
	mov.u32 %r306, 0x0;
	@%p172 ld.global.v4.b32 { %r303, %r304, %r305, %r306 }, [ %rd131 + 0 ];
	@!%p172 mov.u32 %r303, %r1819;
	@!%p172 mov.u32 %r304, %r1819;
	@!%p172 mov.u32 %r305, %r1819;
	@!%p172 mov.u32 %r306, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r311, 0x0;
	mov.u32 %r312, 0x0;
	mov.u32 %r313, 0x0;
	mov.u32 %r314, 0x0;
	@%p173 ld.global.v4.b32 { %r311, %r312, %r313, %r314 }, [ %rd132 + 0 ];
	@!%p173 mov.u32 %r311, %r1819;
	@!%p173 mov.u32 %r312, %r1819;
	@!%p173 mov.u32 %r313, %r1819;
	@!%p173 mov.u32 %r314, %r1819;
	// end inline asm
	// begin inline asm
	mov.u32 %r319, 0x0;
	mov.u32 %r320, 0x0;
	mov.u32 %r321, 0x0;
	mov.u32 %r322, 0x0;
	@%p174 ld.global.v4.b32 { %r319, %r320, %r321, %r322 }, [ %rd133 + 0 ];
	@!%p174 mov.u32 %r319, %r1819;
	@!%p174 mov.u32 %r320, %r1819;
	@!%p174 mov.u32 %r321, %r1819;
	@!%p174 mov.u32 %r322, %r1819;
	// end inline asm
$L__tmp4:
	.loc	2 40 22
	add.s32 	%r474, %r197, 31;
$L__tmp5:
	.loc	1 102 33
	shl.b32 	%r478, %r404, 5;
	.loc	1 103 33
	shl.b32 	%r479, %r405, 5;
	.loc	1 93 22
	setp.lt.s32 	%p126, %r474, 32;
	setp.gt.s32 	%p127, %r474, 31;
	.loc	1 96 72
	setp.lt.s32 	%p128, %r5, %r197;
	setp.lt.s32 	%p129, %r447, %r197;
	.loc	1 96 20
	shr.u32 	%r480, %r1, 1;
	and.b32  	%r481, %r480, 56;
	xor.b32  	%r482, %r481, %r418;
	shl.b32 	%r483, %r5, 7;
	or.b32  	%r71, %r483, %r482;
	shl.b32 	%r484, %r71, 1;
	mov.u32 	%r485, global_smem;
	add.s32 	%r327, %r485, %r484;
	shl.b32 	%r486, %r447, 7;
	or.b32  	%r72, %r486, %r482;
	shl.b32 	%r487, %r72, 1;
	add.s32 	%r329, %r485, %r487;
	selp.b32 	%r488, 16, 0, %p127;
	selp.b32 	%r328, %r488, 0, %p128;
	mov.pred 	%p97, -1;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r327 + 0 ], [ %rd55 + 0 ], 0x10, %r328;
	// end inline asm
	selp.b32 	%r330, %r488, 0, %p129;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r329 + 0 ], [ %rd56 + 0 ], 0x10, %r330;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 72
	setp.lt.s32 	%p130, %r3, %r197;
	setp.lt.s32 	%p131, %r419, %r197;
	setp.lt.s32 	%p132, %r420, %r197;
	setp.lt.s32 	%p133, %r421, %r197;
	.loc	1 97 20
	shr.u32 	%r489, %r1, 2;
	and.b32  	%r490, %r489, 56;
	xor.b32  	%r491, %r490, %r444;
	shl.b32 	%r492, %r3, 8;
	or.b32  	%r73, %r491, %r492;
	shl.b32 	%r493, %r73, 1;
	add.s32 	%r494, %r485, 16384;
	add.s32 	%r331, %r494, %r493;
	shl.b32 	%r495, %r419, 8;
	or.b32  	%r74, %r495, %r491;
	shl.b32 	%r496, %r74, 1;
	add.s32 	%r333, %r494, %r496;
	shl.b32 	%r497, %r420, 8;
	or.b32  	%r75, %r497, %r491;
	shl.b32 	%r498, %r75, 1;
	add.s32 	%r335, %r494, %r498;
	shl.b32 	%r499, %r421, 8;
	or.b32  	%r76, %r499, %r491;
	shl.b32 	%r500, %r76, 1;
	add.s32 	%r337, %r494, %r500;
	selp.b32 	%r332, %r488, 0, %p130;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r331 + 0 ], [ %rd57 + 0 ], 0x10, %r332;
	// end inline asm
	selp.b32 	%r334, %r488, 0, %p131;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r333 + 0 ], [ %rd58 + 0 ], 0x10, %r334;
	// end inline asm
	selp.b32 	%r336, %r488, 0, %p132;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r335 + 0 ], [ %rd59 + 0 ], 0x10, %r336;
	// end inline asm
	selp.b32 	%r338, %r488, 0, %p133;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r337 + 0 ], [ %rd60 + 0 ], 0x10, %r338;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p134, %r474, 63;
	.loc	1 102 18
	mul.wide.s32 	%rd108, %r478, 2;
	add.s64 	%rd61, %rd55, %rd108;
	add.s64 	%rd62, %rd56, %rd108;
	.loc	1 103 18
	mul.wide.s32 	%rd109, %r479, 2;
	add.s64 	%rd63, %rd57, %rd109;
	add.s64 	%rd64, %rd58, %rd109;
	add.s64 	%rd65, %rd59, %rd109;
	add.s64 	%rd66, %rd60, %rd109;
	.loc	1 96 53
	or.b32  	%r501, %r5, 32;
	or.b32  	%r502, %r5, 48;
	.loc	1 96 72
	setp.lt.s32 	%p135, %r501, %r197;
	setp.lt.s32 	%p136, %r502, %r197;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r503, %r485, 8192;
	add.s32 	%r339, %r503, %r484;
	add.s32 	%r341, %r503, %r487;
	selp.b32 	%r504, 16, 0, %p134;
	selp.b32 	%r340, %r504, 0, %p135;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r339 + 0 ], [ %rd61 + 0 ], 0x10, %r340;
	// end inline asm
	selp.b32 	%r342, %r504, 0, %p136;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r341 + 0 ], [ %rd62 + 0 ], 0x10, %r342;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 72
	setp.lt.s32 	%p137, %r422, %r197;
	setp.lt.s32 	%p138, %r423, %r197;
	setp.lt.s32 	%p139, %r424, %r197;
	setp.lt.s32 	%p140, %r425, %r197;
	.loc	1 97 20
	add.s32 	%r505, %r485, 32768;
	add.s32 	%r343, %r505, %r493;
	add.s32 	%r345, %r505, %r496;
	add.s32 	%r347, %r505, %r498;
	add.s32 	%r349, %r505, %r500;
	selp.b32 	%r344, %r504, 0, %p137;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r343 + 0 ], [ %rd63 + 0 ], 0x10, %r344;
	// end inline asm
	selp.b32 	%r346, %r504, 0, %p138;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r345 + 0 ], [ %rd64 + 0 ], 0x10, %r346;
	// end inline asm
	selp.b32 	%r348, %r504, 0, %p139;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r347 + 0 ], [ %rd65 + 0 ], 0x10, %r348;
	// end inline asm
	selp.b32 	%r350, %r504, 0, %p140;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r349 + 0 ], [ %rd66 + 0 ], 0x10, %r350;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	bfe.u32 	%r77, %r1, 7, 1;
	and.b32  	%r506, %r1, 7;
	bfe.u32 	%r507, %r1, 3, 1;
	bfe.u32 	%r508, %r1, 4, 1;
	shl.b32 	%r509, %r77, 1;
	or.b32  	%r510, %r509, %r507;
	xor.b32  	%r511, %r510, %r506;
	shl.b32 	%r512, %r511, 3;
	shl.b32 	%r513, %r506, 7;
	shl.b32 	%r514, %r508, 10;
	or.b32  	%r515, %r514, %r513;
	or.b32  	%r78, %r512, %r515;
	shl.b32 	%r516, %r78, 1;
	add.s32 	%r355, %r485, %r516;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1848, %r1849, %r1850, %r1851 }, [ %r355 + 0 ];
	// end inline asm
	or.b32  	%r517, %r510, 4;
	xor.b32  	%r518, %r517, %r506;
	shl.b32 	%r519, %r518, 3;
	or.b32  	%r83, %r519, %r515;
	shl.b32 	%r520, %r83, 1;
	add.s32 	%r360, %r485, %r520;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1844, %r1845, %r1846, %r1847 }, [ %r360 + 0 ];
	// end inline asm
	or.b32  	%r521, %r510, 8;
	xor.b32  	%r522, %r521, %r506;
	shl.b32 	%r523, %r522, 3;
	or.b32  	%r88, %r523, %r515;
	shl.b32 	%r524, %r88, 1;
	add.s32 	%r365, %r485, %r524;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1840, %r1841, %r1842, %r1843 }, [ %r365 + 0 ];
	// end inline asm
	or.b32  	%r525, %r510, 12;
	xor.b32  	%r526, %r525, %r506;
	shl.b32 	%r527, %r526, 3;
	or.b32  	%r93, %r527, %r515;
	shl.b32 	%r528, %r93, 1;
	add.s32 	%r370, %r485, %r528;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1836, %r1837, %r1838, %r1839 }, [ %r370 + 0 ];
	// end inline asm
	.loc	1 97 20
	bfe.u32 	%r98, %r1, 5, 2;
	shl.b32 	%r529, %r508, 2;
	or.b32  	%r530, %r529, %r98;
	and.b32  	%r531, %r1, 15;
	xor.b32  	%r532, %r530, %r506;
	shl.b32 	%r533, %r532, 3;
	shl.b32 	%r534, %r531, 8;
	or.b32  	%r99, %r533, %r534;
	shl.b32 	%r535, %r99, 1;
	add.s32 	%r375, %r494, %r535;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1832, %r1833, %r1834, %r1835 }, [ %r375 + 0 ];
	// end inline asm
	or.b32  	%r536, %r530, 8;
	xor.b32  	%r537, %r536, %r506;
	shl.b32 	%r538, %r537, 3;
	add.s32 	%r104, %r538, %r534;
	shl.b32 	%r539, %r104, 1;
	add.s32 	%r380, %r494, %r539;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1828, %r1829, %r1830, %r1831 }, [ %r380 + 0 ];
	// end inline asm
	or.b32  	%r540, %r530, 16;
	xor.b32  	%r541, %r540, %r506;
	shl.b32 	%r542, %r541, 3;
	add.s32 	%r109, %r542, %r534;
	shl.b32 	%r543, %r109, 1;
	add.s32 	%r385, %r494, %r543;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1824, %r1825, %r1826, %r1827 }, [ %r385 + 0 ];
	// end inline asm
	or.b32  	%r544, %r530, 24;
	xor.b32  	%r545, %r544, %r506;
	shl.b32 	%r546, %r545, 3;
	add.s32 	%r114, %r546, %r534;
	shl.b32 	%r547, %r114, 1;
	add.s32 	%r390, %r494, %r547;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1820, %r1821, %r1822, %r1823 }, [ %r390 + 0 ];
	// end inline asm
	mov.b16 	%rs661, 0x0000;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	.loc	1 93 22
	@%p126 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd3, %r452;
	cvt.s64.s32 	%rd4, %r453;
	cvt.s64.s32 	%rd5, %r454;
	cvt.s64.s32 	%rd6, %r455;
	shr.s32 	%r475, %r474, 31;
	shr.u32 	%r476, %r475, 27;
	add.s32 	%r477, %r474, %r476;
	shr.s32 	%r70, %r477, 5;
	cvt.s64.s32 	%rd23, %r478;
	cvt.s64.s32 	%rd24, %r479;
	add.s32 	%r119, %r70, -2;
	.loc	1 93 22
	shl.b64 	%rd25, %rd6, 1;
	shl.b64 	%rd110, %rd24, 2;
	add.s64 	%rd136, %rd37, %rd110;
	shl.b64 	%rd27, %rd24, 1;
	shl.b64 	%rd28, %rd5, 1;
	shl.b64 	%rd29, %rd4, 1;
	shl.b64 	%rd30, %rd3, 1;
	shl.b64 	%rd135, %rd23, 2;
	shl.b64 	%rd32, %rd23, 1;
	mov.b16 	%rs661, 0x0000;
	mov.b32 	%r1855, 1;
	mov.u32 	%r1852, %r494;
	mov.u32 	%r1853, %r485;
	mov.u32 	%r1854, %r1819;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	mov.u32 	%r1856, %r1819;
$L__BB0_2:
	setp.lt.s32 	%p147, %r1856, %r119;
	.loc	1 96 20
	add.s32 	%r1285, %r1853, %r516;
	add.s32 	%r556, %r1285, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r968, %r969, %r970, %r971 }, [ %r556 + 0 ];
	// end inline asm
	add.s32 	%r1287, %r1853, %r520;
	add.s32 	%r561, %r1287, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1048, %r1049, %r1050, %r1051 }, [ %r561 + 0 ];
	// end inline asm
	add.s32 	%r1289, %r1853, %r524;
	add.s32 	%r566, %r1289, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1128, %r1129, %r1130, %r1131 }, [ %r566 + 0 ];
	// end inline asm
	add.s32 	%r1291, %r1853, %r528;
	add.s32 	%r571, %r1291, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1208, %r1209, %r1210, %r1211 }, [ %r571 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r1293, %r1852, %r535;
	add.s32 	%r576, %r1293, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r972, %r973, %r982, %r983 }, [ %r576 + 0 ];
	// end inline asm
	add.s32 	%r1295, %r1852, %r539;
	add.s32 	%r581, %r1295, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r992, %r993, %r1002, %r1003 }, [ %r581 + 0 ];
	// end inline asm
	add.s32 	%r1297, %r1852, %r543;
	add.s32 	%r586, %r1297, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1012, %r1013, %r1022, %r1023 }, [ %r586 + 0 ];
	// end inline asm
	add.s32 	%r1299, %r1852, %r547;
	add.s32 	%r591, %r1299, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1032, %r1033, %r1042, %r1043 }, [ %r591 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r964, {%rs661, %rs662};
	mov.b32 	%r965, {%rs663, %rs664};
	mov.b32 	%r974, {%rs665, %rs666};
	mov.b32 	%r975, {%rs667, %rs668};
	mov.b32 	%r984, {%rs669, %rs670};
	mov.b32 	%r985, {%rs671, %rs672};
	mov.b32 	%r994, {%rs673, %rs674};
	mov.b32 	%r995, {%rs675, %rs676};
	mov.b32 	%r1004, {%rs677, %rs678};
	mov.b32 	%r1005, {%rs679, %rs680};
	mov.b32 	%r1014, {%rs681, %rs682};
	mov.b32 	%r1015, {%rs683, %rs684};
	mov.b32 	%r1024, {%rs685, %rs686};
	mov.b32 	%r1025, {%rs687, %rs688};
	mov.b32 	%r1034, {%rs689, %rs690};
	mov.b32 	%r1035, {%rs691, %rs692};
	mov.b32 	%r1044, {%rs693, %rs694};
	mov.b32 	%r1045, {%rs695, %rs696};
	mov.b32 	%r1054, {%rs697, %rs698};
	mov.b32 	%r1055, {%rs699, %rs700};
	mov.b32 	%r1064, {%rs701, %rs702};
	mov.b32 	%r1065, {%rs703, %rs704};
	mov.b32 	%r1074, {%rs705, %rs706};
	mov.b32 	%r1075, {%rs707, %rs708};
	mov.b32 	%r1084, {%rs709, %rs710};
	mov.b32 	%r1085, {%rs711, %rs712};
	mov.b32 	%r1094, {%rs713, %rs714};
	mov.b32 	%r1095, {%rs715, %rs716};
	mov.b32 	%r1104, {%rs717, %rs718};
	mov.b32 	%r1105, {%rs719, %rs720};
	mov.b32 	%r1114, {%rs721, %rs722};
	mov.b32 	%r1115, {%rs723, %rs724};
	mov.b32 	%r1124, {%rs725, %rs726};
	mov.b32 	%r1125, {%rs727, %rs728};
	mov.b32 	%r1134, {%rs729, %rs730};
	mov.b32 	%r1135, {%rs731, %rs732};
	mov.b32 	%r1144, {%rs733, %rs734};
	mov.b32 	%r1145, {%rs735, %rs736};
	mov.b32 	%r1154, {%rs737, %rs738};
	mov.b32 	%r1155, {%rs739, %rs740};
	mov.b32 	%r1164, {%rs741, %rs742};
	mov.b32 	%r1165, {%rs743, %rs744};
	mov.b32 	%r1174, {%rs745, %rs746};
	mov.b32 	%r1175, {%rs747, %rs748};
	mov.b32 	%r1184, {%rs749, %rs750};
	mov.b32 	%r1185, {%rs751, %rs752};
	mov.b32 	%r1194, {%rs753, %rs754};
	mov.b32 	%r1195, {%rs755, %rs756};
	mov.b32 	%r1204, {%rs757, %rs758};
	mov.b32 	%r1205, {%rs759, %rs760};
	mov.b32 	%r1214, {%rs761, %rs762};
	mov.b32 	%r1215, {%rs763, %rs764};
	mov.b32 	%r1224, {%rs765, %rs766};
	mov.b32 	%r1225, {%rs767, %rs768};
	mov.b32 	%r1234, {%rs769, %rs770};
	mov.b32 	%r1235, {%rs771, %rs772};
	mov.b32 	%r1244, {%rs773, %rs774};
	mov.b32 	%r1245, {%rs775, %rs776};
	mov.b32 	%r1254, {%rs777, %rs778};
	mov.b32 	%r1255, {%rs779, %rs780};
	mov.b32 	%r1264, {%rs781, %rs782};
	mov.b32 	%r1265, {%rs783, %rs784};
	mov.b32 	%r1274, {%rs785, %rs786};
	mov.b32 	%r1275, {%rs787, %rs788};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r964, %r965 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1832, %r1833 }, { %r964, %r965 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r974, %r975 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1834, %r1835 }, { %r974, %r975 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r984, %r985 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1828, %r1829 }, { %r984, %r985 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r994, %r995 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1830, %r1831 }, { %r994, %r995 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1004, %r1005 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1824, %r1825 }, { %r1004, %r1005 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1014, %r1015 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1826, %r1827 }, { %r1014, %r1015 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1024, %r1025 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1820, %r1821 }, { %r1024, %r1025 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1034, %r1035 }, { %r1848, %r1849, %r1850, %r1851 }, { %r1822, %r1823 }, { %r1034, %r1035 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1044, %r1045 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1832, %r1833 }, { %r1044, %r1045 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1054, %r1055 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1834, %r1835 }, { %r1054, %r1055 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1064, %r1065 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1828, %r1829 }, { %r1064, %r1065 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1074, %r1075 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1830, %r1831 }, { %r1074, %r1075 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1084, %r1085 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1824, %r1825 }, { %r1084, %r1085 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1094, %r1095 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1826, %r1827 }, { %r1094, %r1095 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1104, %r1105 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1820, %r1821 }, { %r1104, %r1105 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1114, %r1115 }, { %r1844, %r1845, %r1846, %r1847 }, { %r1822, %r1823 }, { %r1114, %r1115 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1124, %r1125 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1832, %r1833 }, { %r1124, %r1125 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1134, %r1135 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1834, %r1835 }, { %r1134, %r1135 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1144, %r1145 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1828, %r1829 }, { %r1144, %r1145 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1154, %r1155 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1830, %r1831 }, { %r1154, %r1155 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1164, %r1165 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1824, %r1825 }, { %r1164, %r1165 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1174, %r1175 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1826, %r1827 }, { %r1174, %r1175 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1184, %r1185 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1820, %r1821 }, { %r1184, %r1185 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1194, %r1195 }, { %r1840, %r1841, %r1842, %r1843 }, { %r1822, %r1823 }, { %r1194, %r1195 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1204, %r1205 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1832, %r1833 }, { %r1204, %r1205 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1214, %r1215 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1834, %r1835 }, { %r1214, %r1215 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1224, %r1225 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1828, %r1829 }, { %r1224, %r1225 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1234, %r1235 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1830, %r1831 }, { %r1234, %r1235 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1244, %r1245 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1824, %r1825 }, { %r1244, %r1245 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1254, %r1255 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1826, %r1827 }, { %r1254, %r1255 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1264, %r1265 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1820, %r1821 }, { %r1264, %r1265 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1274, %r1275 }, { %r1836, %r1837, %r1838, %r1839 }, { %r1822, %r1823 }, { %r1274, %r1275 };
	// end inline asm
	.loc	1 102 18
	add.s64 	%rd111, %rd55, %rd135;
	.loc	1 103 18
	add.s64 	%rd112, %rd56, %rd135;
	add.s64 	%rd113, %rd136, %rd30;
	add.s64 	%rd114, %rd136, %rd29;
	add.s64 	%rd115, %rd136, %rd28;
	.loc	1 93 22
	add.s64 	%rd116, %rd136, %rd25;
	add.s32 	%r1364, %r1855, 1;
	setp.lt.s32 	%p148, %r1364, 2;
	selp.b32 	%r1855, %r1364, 0, %p148;
	.loc	1 96 53
	add.s32 	%r1365, %r5, %r1819;
	add.s32 	%r1366, %r1365, 64;
	.loc	1 96 72
	add.s32 	%r1367, %r1365, 80;
	setp.lt.s32 	%p149, %r1366, %r197;
	setp.lt.s32 	%p150, %r1367, %r197;
	.loc	1 96 20
	shl.b32 	%r1368, %r1855, 13;
	add.s32 	%r1370, %r485, %r1368;
	bar.sync 	0;
	add.s32 	%r912, %r1370, %r484;
	add.s32 	%r914, %r1370, %r487;
	selp.b32 	%r1373, 16, 0, %p149;
	selp.b32 	%r913, %r1373, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r912 + 0 ], [ %rd111 + 0 ], 0x10, %r913;
	// end inline asm
	selp.b32 	%r1374, 16, 0, %p150;
	selp.b32 	%r915, %r1374, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r914 + 0 ], [ %rd112 + 0 ], 0x10, %r915;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	add.s32 	%r1375, %r3, %r1819;
	add.s32 	%r1376, %r1375, 64;
	add.s32 	%r1377, %r1375, 72;
	add.s32 	%r1378, %r1375, 80;
	.loc	1 97 72
	add.s32 	%r1379, %r1375, 88;
	setp.lt.s32 	%p151, %r1376, %r197;
	setp.lt.s32 	%p152, %r1377, %r197;
	setp.lt.s32 	%p153, %r1378, %r197;
	setp.lt.s32 	%p154, %r1379, %r197;
	.loc	1 97 20
	shl.b32 	%r1380, %r1855, 14;
	add.s32 	%r1382, %r494, %r1380;
	add.s32 	%r916, %r1382, %r493;
	add.s32 	%r918, %r1382, %r496;
	add.s32 	%r920, %r1382, %r498;
	add.s32 	%r922, %r1382, %r500;
	selp.b32 	%r1387, 16, 0, %p151;
	selp.b32 	%r917, %r1387, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r916 + 0 ], [ %rd113 + 0 ], 0x10, %r917;
	// end inline asm
	selp.b32 	%r1388, 16, 0, %p152;
	selp.b32 	%r919, %r1388, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r918 + 0 ], [ %rd114 + 0 ], 0x10, %r919;
	// end inline asm
	selp.b32 	%r1389, 16, 0, %p153;
	selp.b32 	%r921, %r1389, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r920 + 0 ], [ %rd115 + 0 ], 0x10, %r921;
	// end inline asm
	selp.b32 	%r1390, 16, 0, %p154;
	selp.b32 	%r923, %r1390, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r922 + 0 ], [ %rd116 + 0 ], 0x10, %r923;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1391, %r1854, 1;
	setp.lt.s32 	%p155, %r1391, 2;
	selp.b32 	%r1854, %r1391, 0, %p155;
	.loc	1 96 20
	shl.b32 	%r1392, %r1854, 13;
	add.s32 	%r1853, %r485, %r1392;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1393, %r1854, 14;
	add.s32 	%r1852, %r494, %r1393;
	.loc	1 96 20
	add.s32 	%r928, %r1853, %r516;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1848, %r1849, %r1850, %r1851 }, [ %r928 + 0 ];
	// end inline asm
	add.s32 	%r933, %r1853, %r520;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1844, %r1845, %r1846, %r1847 }, [ %r933 + 0 ];
	// end inline asm
	add.s32 	%r938, %r1853, %r524;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1840, %r1841, %r1842, %r1843 }, [ %r938 + 0 ];
	// end inline asm
	add.s32 	%r943, %r1853, %r528;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1836, %r1837, %r1838, %r1839 }, [ %r943 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r948, %r1852, %r535;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1832, %r1833, %r1834, %r1835 }, [ %r948 + 0 ];
	// end inline asm
	add.s32 	%r953, %r1852, %r539;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1828, %r1829, %r1830, %r1831 }, [ %r953 + 0 ];
	// end inline asm
	add.s32 	%r958, %r1852, %r543;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1824, %r1825, %r1826, %r1827 }, [ %r958 + 0 ];
	// end inline asm
	add.s32 	%r963, %r1852, %r547;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1820, %r1821, %r1822, %r1823 }, [ %r963 + 0 ];
	// end inline asm
	.loc	1 100 35
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r964, %r965 }, { %r968, %r969, %r970, %r971 }, { %r972, %r973 }, { %r964, %r965 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r974, %r975 }, { %r968, %r969, %r970, %r971 }, { %r982, %r983 }, { %r974, %r975 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r984, %r985 }, { %r968, %r969, %r970, %r971 }, { %r992, %r993 }, { %r984, %r985 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r994, %r995 }, { %r968, %r969, %r970, %r971 }, { %r1002, %r1003 }, { %r994, %r995 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1004, %r1005 }, { %r968, %r969, %r970, %r971 }, { %r1012, %r1013 }, { %r1004, %r1005 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1014, %r1015 }, { %r968, %r969, %r970, %r971 }, { %r1022, %r1023 }, { %r1014, %r1015 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1024, %r1025 }, { %r968, %r969, %r970, %r971 }, { %r1032, %r1033 }, { %r1024, %r1025 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1034, %r1035 }, { %r968, %r969, %r970, %r971 }, { %r1042, %r1043 }, { %r1034, %r1035 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1044, %r1045 }, { %r1048, %r1049, %r1050, %r1051 }, { %r972, %r973 }, { %r1044, %r1045 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1054, %r1055 }, { %r1048, %r1049, %r1050, %r1051 }, { %r982, %r983 }, { %r1054, %r1055 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1064, %r1065 }, { %r1048, %r1049, %r1050, %r1051 }, { %r992, %r993 }, { %r1064, %r1065 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1074, %r1075 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1002, %r1003 }, { %r1074, %r1075 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1084, %r1085 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1012, %r1013 }, { %r1084, %r1085 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1094, %r1095 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1022, %r1023 }, { %r1094, %r1095 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1104, %r1105 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1032, %r1033 }, { %r1104, %r1105 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1114, %r1115 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1042, %r1043 }, { %r1114, %r1115 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1124, %r1125 }, { %r1128, %r1129, %r1130, %r1131 }, { %r972, %r973 }, { %r1124, %r1125 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1134, %r1135 }, { %r1128, %r1129, %r1130, %r1131 }, { %r982, %r983 }, { %r1134, %r1135 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1144, %r1145 }, { %r1128, %r1129, %r1130, %r1131 }, { %r992, %r993 }, { %r1144, %r1145 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1154, %r1155 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1002, %r1003 }, { %r1154, %r1155 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1164, %r1165 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1012, %r1013 }, { %r1164, %r1165 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1174, %r1175 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1022, %r1023 }, { %r1174, %r1175 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1184, %r1185 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1032, %r1033 }, { %r1184, %r1185 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1194, %r1195 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1042, %r1043 }, { %r1194, %r1195 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1204, %r1205 }, { %r1208, %r1209, %r1210, %r1211 }, { %r972, %r973 }, { %r1204, %r1205 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1214, %r1215 }, { %r1208, %r1209, %r1210, %r1211 }, { %r982, %r983 }, { %r1214, %r1215 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1224, %r1225 }, { %r1208, %r1209, %r1210, %r1211 }, { %r992, %r993 }, { %r1224, %r1225 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1234, %r1235 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1002, %r1003 }, { %r1234, %r1235 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1244, %r1245 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1012, %r1013 }, { %r1244, %r1245 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1254, %r1255 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1022, %r1023 }, { %r1254, %r1255 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1264, %r1265 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1032, %r1033 }, { %r1264, %r1265 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1274, %r1275 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1042, %r1043 }, { %r1274, %r1275 };
	// end inline asm
	mov.b32 	{%rs661, %rs662}, %r964;
	mov.b32 	{%rs663, %rs664}, %r965;
	mov.b32 	{%rs665, %rs666}, %r974;
	mov.b32 	{%rs667, %rs668}, %r975;
	mov.b32 	{%rs669, %rs670}, %r984;
	mov.b32 	{%rs671, %rs672}, %r985;
	mov.b32 	{%rs673, %rs674}, %r994;
	mov.b32 	{%rs675, %rs676}, %r995;
	mov.b32 	{%rs677, %rs678}, %r1004;
	mov.b32 	{%rs679, %rs680}, %r1005;
	mov.b32 	{%rs681, %rs682}, %r1014;
	mov.b32 	{%rs683, %rs684}, %r1015;
	mov.b32 	{%rs685, %rs686}, %r1024;
	mov.b32 	{%rs687, %rs688}, %r1025;
	mov.b32 	{%rs689, %rs690}, %r1034;
	mov.b32 	{%rs691, %rs692}, %r1035;
	mov.b32 	{%rs693, %rs694}, %r1044;
	mov.b32 	{%rs695, %rs696}, %r1045;
	mov.b32 	{%rs697, %rs698}, %r1054;
	mov.b32 	{%rs699, %rs700}, %r1055;
	mov.b32 	{%rs701, %rs702}, %r1064;
	mov.b32 	{%rs703, %rs704}, %r1065;
	mov.b32 	{%rs705, %rs706}, %r1074;
	mov.b32 	{%rs707, %rs708}, %r1075;
	mov.b32 	{%rs709, %rs710}, %r1084;
	mov.b32 	{%rs711, %rs712}, %r1085;
	mov.b32 	{%rs713, %rs714}, %r1094;
	mov.b32 	{%rs715, %rs716}, %r1095;
	mov.b32 	{%rs717, %rs718}, %r1104;
	mov.b32 	{%rs719, %rs720}, %r1105;
	mov.b32 	{%rs721, %rs722}, %r1114;
	mov.b32 	{%rs723, %rs724}, %r1115;
	mov.b32 	{%rs725, %rs726}, %r1124;
	mov.b32 	{%rs727, %rs728}, %r1125;
	mov.b32 	{%rs729, %rs730}, %r1134;
	mov.b32 	{%rs731, %rs732}, %r1135;
	mov.b32 	{%rs733, %rs734}, %r1144;
	mov.b32 	{%rs735, %rs736}, %r1145;
	mov.b32 	{%rs737, %rs738}, %r1154;
	mov.b32 	{%rs739, %rs740}, %r1155;
	mov.b32 	{%rs741, %rs742}, %r1164;
	mov.b32 	{%rs743, %rs744}, %r1165;
	mov.b32 	{%rs745, %rs746}, %r1174;
	mov.b32 	{%rs747, %rs748}, %r1175;
	mov.b32 	{%rs749, %rs750}, %r1184;
	mov.b32 	{%rs751, %rs752}, %r1185;
	mov.b32 	{%rs753, %rs754}, %r1194;
	mov.b32 	{%rs755, %rs756}, %r1195;
	mov.b32 	{%rs757, %rs758}, %r1204;
	mov.b32 	{%rs759, %rs760}, %r1205;
	mov.b32 	{%rs761, %rs762}, %r1214;
	mov.b32 	{%rs763, %rs764}, %r1215;
	mov.b32 	{%rs765, %rs766}, %r1224;
	mov.b32 	{%rs767, %rs768}, %r1225;
	mov.b32 	{%rs769, %rs770}, %r1234;
	mov.b32 	{%rs771, %rs772}, %r1235;
	mov.b32 	{%rs773, %rs774}, %r1244;
	mov.b32 	{%rs775, %rs776}, %r1245;
	mov.b32 	{%rs777, %rs778}, %r1254;
	mov.b32 	{%rs779, %rs780}, %r1255;
	mov.b32 	{%rs781, %rs782}, %r1264;
	mov.b32 	{%rs783, %rs784}, %r1265;
	mov.b32 	{%rs785, %rs786}, %r1274;
	mov.b32 	{%rs787, %rs788}, %r1275;
	.loc	1 93 22
	add.s32 	%r1856, %r1856, 1;
	add.s64 	%rd136, %rd136, %rd27;
	add.s64 	%rd135, %rd135, %rd32;
	add.s32 	%r1819, %r1819, 32;
	setp.lt.s32 	%p156, %r1856, %r70;
	@%p156 bra 	$L__BB0_2;
$L__BB0_3:
	.loc	1 75 51
	and.b32  	%r1586, %r1, 255;
	.loc	1 75 38
	or.b32  	%r1587, %r4, %r1586;
	.loc	1 93 22
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	.loc	1 107 31
	mul.wide.s32 	%rd134, %r1587, 2;
	add.s64 	%rd117, %rd38, %rd134;
	.loc	1 108 32
	setp.lt.s32 	%p157, %r1587, %r196;
	mov.u16 	%rs388, 0;
	.loc	1 109 23
	// begin inline asm
	mov.u16 %rs387, 0x0;
	@%p157 ld.global.b16 { %rs387 }, [ %rd117 + 0 ];
	@!%p157 mov.u16 %rs387, %rs388;
	// end inline asm
	.loc	1 110 30
	shl.b32 	%r1588, %r1586, 1;
	add.s32 	%r1590, %r485, %r1588;
	st.shared.u16 	[%r1590], %rs387;
	bar.sync 	0;
	shl.b32 	%r1591, %r98, 4;
	shl.b32 	%r1592, %r1, 2;
	and.b32  	%r1593, %r1592, 12;
	or.b32  	%r1594, %r1591, %r1593;
	add.s32 	%r1595, %r485, %r1594;
	ld.shared.b32 	%r1596, [%r1595];
	mov.b32 	{%rs389, %rs390}, %r1596;
	add.s32 	%r1597, %r1595, 64;
	ld.shared.b32 	%r1598, [%r1595+64];
	mov.b32 	{%rs391, %rs392}, %r1598;
	add.s32 	%r1599, %r1595, 128;
	ld.shared.b32 	%r1600, [%r1595+128];
	mov.b32 	{%rs393, %rs394}, %r1600;
	add.s32 	%r1601, %r1595, 192;
	ld.shared.b32 	%r1602, [%r1595+192];
	mov.b32 	{%rs395, %rs396}, %r1602;
	add.s32 	%r1603, %r1595, 256;
	ld.shared.b32 	%r1604, [%r1595+256];
	mov.b32 	{%rs397, %rs398}, %r1604;
	add.s32 	%r1605, %r1595, 320;
	ld.shared.b32 	%r1606, [%r1595+320];
	mov.b32 	{%rs399, %rs400}, %r1606;
	add.s32 	%r1607, %r1595, 384;
	ld.shared.b32 	%r1608, [%r1595+384];
	mov.b32 	{%rs401, %rs402}, %r1608;
	add.s32 	%r1609, %r1595, 448;
	ld.shared.b32 	%r1610, [%r1595+448];
	mov.b32 	{%rs403, %rs404}, %r1610;
	.loc	1 111 23
	add.f16 	%rs405, %rs661, %rs389;
	add.f16 	%rs406, %rs662, %rs390;
	add.f16 	%rs407, %rs663, %rs389;
	add.f16 	%rs408, %rs664, %rs390;
	add.f16 	%rs409, %rs665, %rs391;
	add.f16 	%rs410, %rs666, %rs392;
	add.f16 	%rs411, %rs667, %rs391;
	add.f16 	%rs412, %rs668, %rs392;
	add.f16 	%rs413, %rs669, %rs393;
	add.f16 	%rs414, %rs670, %rs394;
	add.f16 	%rs415, %rs671, %rs393;
	add.f16 	%rs416, %rs672, %rs394;
	add.f16 	%rs417, %rs673, %rs395;
	add.f16 	%rs418, %rs674, %rs396;
	add.f16 	%rs419, %rs675, %rs395;
	add.f16 	%rs420, %rs676, %rs396;
	add.f16 	%rs421, %rs677, %rs397;
	add.f16 	%rs422, %rs678, %rs398;
	add.f16 	%rs423, %rs679, %rs397;
	add.f16 	%rs424, %rs680, %rs398;
	add.f16 	%rs425, %rs681, %rs399;
	add.f16 	%rs426, %rs682, %rs400;
	add.f16 	%rs427, %rs683, %rs399;
	add.f16 	%rs428, %rs684, %rs400;
	add.f16 	%rs429, %rs685, %rs401;
	add.f16 	%rs430, %rs686, %rs402;
	add.f16 	%rs431, %rs687, %rs401;
	add.f16 	%rs432, %rs688, %rs402;
	add.f16 	%rs433, %rs689, %rs403;
	add.f16 	%rs434, %rs690, %rs404;
	add.f16 	%rs435, %rs691, %rs403;
	add.f16 	%rs436, %rs692, %rs404;
	add.f16 	%rs437, %rs693, %rs389;
	add.f16 	%rs438, %rs694, %rs390;
	add.f16 	%rs439, %rs695, %rs389;
	add.f16 	%rs440, %rs696, %rs390;
	add.f16 	%rs441, %rs697, %rs391;
	add.f16 	%rs442, %rs698, %rs392;
	add.f16 	%rs443, %rs699, %rs391;
	add.f16 	%rs444, %rs700, %rs392;
	add.f16 	%rs445, %rs701, %rs393;
	add.f16 	%rs446, %rs702, %rs394;
	add.f16 	%rs447, %rs703, %rs393;
	add.f16 	%rs448, %rs704, %rs394;
	add.f16 	%rs449, %rs705, %rs395;
	add.f16 	%rs450, %rs706, %rs396;
	add.f16 	%rs451, %rs707, %rs395;
	add.f16 	%rs452, %rs708, %rs396;
	add.f16 	%rs453, %rs709, %rs397;
	add.f16 	%rs454, %rs710, %rs398;
	add.f16 	%rs455, %rs711, %rs397;
	add.f16 	%rs456, %rs712, %rs398;
	add.f16 	%rs457, %rs713, %rs399;
	add.f16 	%rs458, %rs714, %rs400;
	add.f16 	%rs459, %rs715, %rs399;
	add.f16 	%rs460, %rs716, %rs400;
	add.f16 	%rs461, %rs717, %rs401;
	add.f16 	%rs462, %rs718, %rs402;
	add.f16 	%rs463, %rs719, %rs401;
	add.f16 	%rs464, %rs720, %rs402;
	add.f16 	%rs465, %rs721, %rs403;
	add.f16 	%rs466, %rs722, %rs404;
	add.f16 	%rs467, %rs723, %rs403;
	add.f16 	%rs468, %rs724, %rs404;
	add.f16 	%rs469, %rs725, %rs389;
	add.f16 	%rs470, %rs726, %rs390;
	add.f16 	%rs471, %rs727, %rs389;
	add.f16 	%rs472, %rs728, %rs390;
	add.f16 	%rs473, %rs729, %rs391;
	add.f16 	%rs474, %rs730, %rs392;
	add.f16 	%rs475, %rs731, %rs391;
	add.f16 	%rs476, %rs732, %rs392;
	add.f16 	%rs477, %rs733, %rs393;
	add.f16 	%rs478, %rs734, %rs394;
	add.f16 	%rs479, %rs735, %rs393;
	add.f16 	%rs480, %rs736, %rs394;
	add.f16 	%rs481, %rs737, %rs395;
	add.f16 	%rs482, %rs738, %rs396;
	add.f16 	%rs483, %rs739, %rs395;
	add.f16 	%rs484, %rs740, %rs396;
	add.f16 	%rs485, %rs741, %rs397;
	add.f16 	%rs486, %rs742, %rs398;
	add.f16 	%rs487, %rs743, %rs397;
	add.f16 	%rs488, %rs744, %rs398;
	add.f16 	%rs489, %rs745, %rs399;
	add.f16 	%rs490, %rs746, %rs400;
	add.f16 	%rs491, %rs747, %rs399;
	add.f16 	%rs492, %rs748, %rs400;
	add.f16 	%rs493, %rs749, %rs401;
	add.f16 	%rs494, %rs750, %rs402;
	add.f16 	%rs495, %rs751, %rs401;
	add.f16 	%rs496, %rs752, %rs402;
	add.f16 	%rs497, %rs753, %rs403;
	add.f16 	%rs498, %rs754, %rs404;
	add.f16 	%rs499, %rs755, %rs403;
	add.f16 	%rs500, %rs756, %rs404;
	add.f16 	%rs501, %rs757, %rs389;
	add.f16 	%rs502, %rs758, %rs390;
	add.f16 	%rs503, %rs759, %rs389;
	add.f16 	%rs504, %rs760, %rs390;
	add.f16 	%rs505, %rs761, %rs391;
	add.f16 	%rs506, %rs762, %rs392;
	add.f16 	%rs507, %rs763, %rs391;
	add.f16 	%rs508, %rs764, %rs392;
	add.f16 	%rs509, %rs765, %rs393;
	add.f16 	%rs510, %rs766, %rs394;
	add.f16 	%rs511, %rs767, %rs393;
	add.f16 	%rs512, %rs768, %rs394;
	add.f16 	%rs513, %rs769, %rs395;
	add.f16 	%rs514, %rs770, %rs396;
	add.f16 	%rs515, %rs771, %rs395;
	add.f16 	%rs516, %rs772, %rs396;
	add.f16 	%rs517, %rs773, %rs397;
	add.f16 	%rs518, %rs774, %rs398;
	add.f16 	%rs519, %rs775, %rs397;
	add.f16 	%rs520, %rs776, %rs398;
	add.f16 	%rs521, %rs777, %rs399;
	add.f16 	%rs522, %rs778, %rs400;
	add.f16 	%rs523, %rs779, %rs399;
	add.f16 	%rs524, %rs780, %rs400;
	add.f16 	%rs525, %rs781, %rs401;
	add.f16 	%rs526, %rs782, %rs402;
	add.f16 	%rs527, %rs783, %rs401;
	add.f16 	%rs528, %rs784, %rs402;
	add.f16 	%rs529, %rs785, %rs403;
	add.f16 	%rs530, %rs786, %rs404;
	add.f16 	%rs531, %rs787, %rs403;
	add.f16 	%rs532, %rs788, %rs404;
	bar.sync 	0;
	shr.u32 	%r1611, %r2, 2;
	shl.b32 	%r1612, %r77, 4;
	or.b32  	%r1613, %r1612, %r1611;
	mul.lo.s32 	%r1614, %r1613, 528;
	add.s32 	%r1615, %r1595, %r1614;
	mov.b32 	%r1616, {%rs405, %rs406};
	st.shared.b32 	[%r1615], %r1616;
	mov.b32 	%r1617, {%rs407, %rs408};
	st.shared.b32 	[%r1615+4224], %r1617;
	mov.b32 	%r1618, {%rs409, %rs410};
	st.shared.b32 	[%r1615+64], %r1618;
	add.s32 	%r1619, %r1597, %r1614;
	mov.b32 	%r1620, {%rs411, %rs412};
	st.shared.b32 	[%r1619+4224], %r1620;
	mov.b32 	%r1621, {%rs413, %rs414};
	st.shared.b32 	[%r1615+128], %r1621;
	add.s32 	%r1622, %r1599, %r1614;
	mov.b32 	%r1623, {%rs415, %rs416};
	st.shared.b32 	[%r1622+4224], %r1623;
	mov.b32 	%r1624, {%rs417, %rs418};
	st.shared.b32 	[%r1615+192], %r1624;
	add.s32 	%r1625, %r1601, %r1614;
	mov.b32 	%r1626, {%rs419, %rs420};
	st.shared.b32 	[%r1625+4224], %r1626;
	mov.b32 	%r1627, {%rs421, %rs422};
	st.shared.b32 	[%r1615+256], %r1627;
	add.s32 	%r1628, %r1603, %r1614;
	mov.b32 	%r1629, {%rs423, %rs424};
	st.shared.b32 	[%r1628+4224], %r1629;
	mov.b32 	%r1630, {%rs425, %rs426};
	st.shared.b32 	[%r1615+320], %r1630;
	add.s32 	%r1631, %r1605, %r1614;
	mov.b32 	%r1632, {%rs427, %rs428};
	st.shared.b32 	[%r1631+4224], %r1632;
	mov.b32 	%r1633, {%rs429, %rs430};
	st.shared.b32 	[%r1615+384], %r1633;
	add.s32 	%r1634, %r1607, %r1614;
	mov.b32 	%r1635, {%rs431, %rs432};
	st.shared.b32 	[%r1634+4224], %r1635;
	mov.b32 	%r1636, {%rs433, %rs434};
	st.shared.b32 	[%r1615+448], %r1636;
	add.s32 	%r1637, %r1609, %r1614;
	mov.b32 	%r1638, {%rs435, %rs436};
	st.shared.b32 	[%r1637+4224], %r1638;
	bar.sync 	0;
	shl.b32 	%r1639, %r2, 3;
	mad.lo.s32 	%r1640, %r3, 264, %r1639;
	shl.b32 	%r1641, %r1640, 1;
	add.s32 	%r1642, %r485, %r1641;
	mov.b32 	%r1643, {%rs437, %rs438};
	mov.b32 	%r1644, {%rs439, %rs440};
	mov.b32 	%r1645, {%rs441, %rs442};
	mov.b32 	%r1646, {%rs443, %rs444};
	mov.b32 	%r1647, {%rs445, %rs446};
	mov.b32 	%r1648, {%rs447, %rs448};
	mov.b32 	%r1649, {%rs449, %rs450};
	mov.b32 	%r1650, {%rs451, %rs452};
	mov.b32 	%r1651, {%rs453, %rs454};
	mov.b32 	%r1652, {%rs455, %rs456};
	mov.b32 	%r1653, {%rs457, %rs458};
	mov.b32 	%r1654, {%rs459, %rs460};
	mov.b32 	%r1655, {%rs461, %rs462};
	mov.b32 	%r1656, {%rs463, %rs464};
	mov.b32 	%r1657, {%rs465, %rs466};
	mov.b32 	%r1658, {%rs467, %rs468};
	mov.b32 	%r1659, {%rs469, %rs470};
	mov.b32 	%r1660, {%rs471, %rs472};
	mov.b32 	%r1661, {%rs473, %rs474};
	mov.b32 	%r1662, {%rs475, %rs476};
	mov.b32 	%r1663, {%rs477, %rs478};
	mov.b32 	%r1664, {%rs479, %rs480};
	mov.b32 	%r1665, {%rs481, %rs482};
	mov.b32 	%r1666, {%rs483, %rs484};
	mov.b32 	%r1667, {%rs485, %rs486};
	mov.b32 	%r1668, {%rs487, %rs488};
	mov.b32 	%r1669, {%rs489, %rs490};
	mov.b32 	%r1670, {%rs491, %rs492};
	mov.b32 	%r1671, {%rs493, %rs494};
	mov.b32 	%r1672, {%rs495, %rs496};
	mov.b32 	%r1673, {%rs497, %rs498};
	mov.b32 	%r1674, {%rs499, %rs500};
	mov.b32 	%r1675, {%rs501, %rs502};
	mov.b32 	%r1676, {%rs503, %rs504};
	mov.b32 	%r1677, {%rs505, %rs506};
	mov.b32 	%r1678, {%rs507, %rs508};
	mov.b32 	%r1679, {%rs509, %rs510};
	mov.b32 	%r1680, {%rs511, %rs512};
	mov.b32 	%r1681, {%rs513, %rs514};
	mov.b32 	%r1682, {%rs515, %rs516};
	mov.b32 	%r1683, {%rs517, %rs518};
	mov.b32 	%r1684, {%rs519, %rs520};
	mov.b32 	%r1685, {%rs521, %rs522};
	mov.b32 	%r1686, {%rs523, %rs524};
	mov.b32 	%r1687, {%rs525, %rs526};
	mov.b32 	%r1688, {%rs527, %rs528};
	mov.b32 	%r1689, {%rs529, %rs530};
	mov.b32 	%r1690, {%rs531, %rs532};
	ld.shared.v4.b32 	{%r1691, %r1692, %r1693, %r1694}, [%r1642];
	.loc	1 127 23
	add.f16x2 	%r1695, %r1691, %r199;
	add.f16x2 	%r1696, %r1692, %r200;
	add.f16x2 	%r1697, %r1693, %r201;
	add.f16x2 	%r1698, %r1694, %r202;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1699, %r1700, %r1701, %r1702}, [%r1642+4224];
	.loc	1 127 23
	add.f16x2 	%r1703, %r1699, %r207;
	add.f16x2 	%r1704, %r1700, %r208;
	add.f16x2 	%r1705, %r1701, %r209;
	add.f16x2 	%r1706, %r1702, %r210;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1707, %r1708, %r1709, %r1710}, [%r1642+8448];
	.loc	1 127 23
	add.f16x2 	%r1711, %r1707, %r215;
	add.f16x2 	%r1712, %r1708, %r216;
	add.f16x2 	%r1713, %r1709, %r217;
	add.f16x2 	%r1714, %r1710, %r218;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1715, %r1716, %r1717, %r1718}, [%r1642+12672];
	.loc	1 127 23
	add.f16x2 	%r1719, %r1715, %r223;
	add.f16x2 	%r1720, %r1716, %r224;
	add.f16x2 	%r1721, %r1717, %r225;
	.loc	1 111 23
	bar.sync 	0;
	st.shared.b32 	[%r1615], %r1643;
	st.shared.b32 	[%r1615+4224], %r1644;
	st.shared.b32 	[%r1615+64], %r1645;
	st.shared.b32 	[%r1619+4224], %r1646;
	st.shared.b32 	[%r1615+128], %r1647;
	st.shared.b32 	[%r1622+4224], %r1648;
	st.shared.b32 	[%r1615+192], %r1649;
	st.shared.b32 	[%r1625+4224], %r1650;
	st.shared.b32 	[%r1615+256], %r1651;
	st.shared.b32 	[%r1628+4224], %r1652;
	st.shared.b32 	[%r1615+320], %r1653;
	st.shared.b32 	[%r1631+4224], %r1654;
	st.shared.b32 	[%r1615+384], %r1655;
	st.shared.b32 	[%r1634+4224], %r1656;
	st.shared.b32 	[%r1615+448], %r1657;
	st.shared.b32 	[%r1637+4224], %r1658;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1722, %r1718, %r226;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1723, %r1724, %r1725, %r1726}, [%r1642];
	.loc	1 127 23
	add.f16x2 	%r1727, %r1723, %r231;
	add.f16x2 	%r1728, %r1724, %r232;
	add.f16x2 	%r1729, %r1725, %r233;
	add.f16x2 	%r1730, %r1726, %r234;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1731, %r1732, %r1733, %r1734}, [%r1642+4224];
	.loc	1 127 23
	add.f16x2 	%r1735, %r1731, %r239;
	add.f16x2 	%r1736, %r1732, %r240;
	add.f16x2 	%r1737, %r1733, %r241;
	add.f16x2 	%r1738, %r1734, %r242;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1739, %r1740, %r1741, %r1742}, [%r1642+8448];
	.loc	1 127 23
	add.f16x2 	%r1743, %r1739, %r247;
	add.f16x2 	%r1744, %r1740, %r248;
	add.f16x2 	%r1745, %r1741, %r249;
	add.f16x2 	%r1746, %r1742, %r250;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1747, %r1748, %r1749, %r1750}, [%r1642+12672];
	.loc	1 127 23
	add.f16x2 	%r1751, %r1747, %r255;
	add.f16x2 	%r1752, %r1748, %r256;
	add.f16x2 	%r1753, %r1749, %r257;
	.loc	1 111 23
	bar.sync 	0;
	st.shared.b32 	[%r1615], %r1659;
	st.shared.b32 	[%r1615+4224], %r1660;
	st.shared.b32 	[%r1615+64], %r1661;
	st.shared.b32 	[%r1619+4224], %r1662;
	st.shared.b32 	[%r1615+128], %r1663;
	st.shared.b32 	[%r1622+4224], %r1664;
	st.shared.b32 	[%r1615+192], %r1665;
	st.shared.b32 	[%r1625+4224], %r1666;
	st.shared.b32 	[%r1615+256], %r1667;
	st.shared.b32 	[%r1628+4224], %r1668;
	st.shared.b32 	[%r1615+320], %r1669;
	st.shared.b32 	[%r1631+4224], %r1670;
	st.shared.b32 	[%r1615+384], %r1671;
	st.shared.b32 	[%r1634+4224], %r1672;
	st.shared.b32 	[%r1615+448], %r1673;
	st.shared.b32 	[%r1637+4224], %r1674;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1754, %r1750, %r258;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1755, %r1756, %r1757, %r1758}, [%r1642];
	.loc	1 127 23
	add.f16x2 	%r1759, %r1755, %r263;
	add.f16x2 	%r1760, %r1756, %r264;
	add.f16x2 	%r1761, %r1757, %r265;
	add.f16x2 	%r1762, %r1758, %r266;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1763, %r1764, %r1765, %r1766}, [%r1642+4224];
	.loc	1 127 23
	add.f16x2 	%r1767, %r1763, %r271;
	add.f16x2 	%r1768, %r1764, %r272;
	add.f16x2 	%r1769, %r1765, %r273;
	add.f16x2 	%r1770, %r1766, %r274;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1771, %r1772, %r1773, %r1774}, [%r1642+8448];
	.loc	1 127 23
	add.f16x2 	%r1775, %r1771, %r279;
	add.f16x2 	%r1776, %r1772, %r280;
	add.f16x2 	%r1777, %r1773, %r281;
	add.f16x2 	%r1778, %r1774, %r282;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1779, %r1780, %r1781, %r1782}, [%r1642+12672];
	.loc	1 127 23
	add.f16x2 	%r1783, %r1779, %r287;
	add.f16x2 	%r1784, %r1780, %r288;
	add.f16x2 	%r1785, %r1781, %r289;
	.loc	1 111 23
	bar.sync 	0;
	st.shared.b32 	[%r1615], %r1675;
	st.shared.b32 	[%r1615+4224], %r1676;
	st.shared.b32 	[%r1615+64], %r1677;
	st.shared.b32 	[%r1619+4224], %r1678;
	st.shared.b32 	[%r1615+128], %r1679;
	st.shared.b32 	[%r1622+4224], %r1680;
	st.shared.b32 	[%r1615+192], %r1681;
	st.shared.b32 	[%r1625+4224], %r1682;
	st.shared.b32 	[%r1615+256], %r1683;
	st.shared.b32 	[%r1628+4224], %r1684;
	st.shared.b32 	[%r1615+320], %r1685;
	st.shared.b32 	[%r1631+4224], %r1686;
	st.shared.b32 	[%r1615+384], %r1687;
	st.shared.b32 	[%r1634+4224], %r1688;
	st.shared.b32 	[%r1615+448], %r1689;
	st.shared.b32 	[%r1637+4224], %r1690;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1786, %r1782, %r290;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1787, %r1788, %r1789, %r1790}, [%r1642];
	.loc	1 127 23
	add.f16x2 	%r1791, %r1787, %r295;
	add.f16x2 	%r1792, %r1788, %r296;
	add.f16x2 	%r1793, %r1789, %r297;
	add.f16x2 	%r1794, %r1790, %r298;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1795, %r1796, %r1797, %r1798}, [%r1642+4224];
	.loc	1 127 23
	add.f16x2 	%r1799, %r1795, %r303;
	add.f16x2 	%r1800, %r1796, %r304;
	add.f16x2 	%r1801, %r1797, %r305;
	add.f16x2 	%r1802, %r1798, %r306;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1803, %r1804, %r1805, %r1806}, [%r1642+8448];
	.loc	1 127 23
	add.f16x2 	%r1807, %r1803, %r311;
	add.f16x2 	%r1808, %r1804, %r312;
	add.f16x2 	%r1809, %r1805, %r313;
	add.f16x2 	%r1810, %r1806, %r314;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1811, %r1812, %r1813, %r1814}, [%r1642+12672];
	.loc	1 127 23
	add.f16x2 	%r1815, %r1811, %r319;
	add.f16x2 	%r1816, %r1812, %r320;
	add.f16x2 	%r1817, %r1813, %r321;
	add.f16x2 	%r1818, %r1814, %r322;
	.loc	1 129 21
	// begin inline asm
	@%p159 st.global.v4.b32 [ %rd118 + 0 ], { %r1695, %r1696, %r1697, %r1698 };
	// end inline asm
	// begin inline asm
	@%p160 st.global.v4.b32 [ %rd119 + 0 ], { %r1703, %r1704, %r1705, %r1706 };
	// end inline asm
	// begin inline asm
	@%p161 st.global.v4.b32 [ %rd120 + 0 ], { %r1711, %r1712, %r1713, %r1714 };
	// end inline asm
	// begin inline asm
	@%p162 st.global.v4.b32 [ %rd121 + 0 ], { %r1719, %r1720, %r1721, %r1722 };
	// end inline asm
	// begin inline asm
	@%p163 st.global.v4.b32 [ %rd122 + 0 ], { %r1727, %r1728, %r1729, %r1730 };
	// end inline asm
	// begin inline asm
	@%p164 st.global.v4.b32 [ %rd123 + 0 ], { %r1735, %r1736, %r1737, %r1738 };
	// end inline asm
	// begin inline asm
	@%p165 st.global.v4.b32 [ %rd124 + 0 ], { %r1743, %r1744, %r1745, %r1746 };
	// end inline asm
	// begin inline asm
	@%p166 st.global.v4.b32 [ %rd125 + 0 ], { %r1751, %r1752, %r1753, %r1754 };
	// end inline asm
	// begin inline asm
	@%p167 st.global.v4.b32 [ %rd126 + 0 ], { %r1759, %r1760, %r1761, %r1762 };
	// end inline asm
	// begin inline asm
	@%p168 st.global.v4.b32 [ %rd127 + 0 ], { %r1767, %r1768, %r1769, %r1770 };
	// end inline asm
	// begin inline asm
	@%p169 st.global.v4.b32 [ %rd128 + 0 ], { %r1775, %r1776, %r1777, %r1778 };
	// end inline asm
	// begin inline asm
	@%p170 st.global.v4.b32 [ %rd129 + 0 ], { %r1783, %r1784, %r1785, %r1786 };
	// end inline asm
	// begin inline asm
	@%p171 st.global.v4.b32 [ %rd130 + 0 ], { %r1791, %r1792, %r1793, %r1794 };
	// end inline asm
	// begin inline asm
	@%p172 st.global.v4.b32 [ %rd131 + 0 ], { %r1799, %r1800, %r1801, %r1802 };
	// end inline asm
	// begin inline asm
	@%p173 st.global.v4.b32 [ %rd132 + 0 ], { %r1807, %r1808, %r1809, %r1810 };
	// end inline asm
	// begin inline asm
	@%p174 st.global.v4.b32 [ %rd133 + 0 ], { %r1815, %r1816, %r1817, %r1818 };
	// end inline asm
	.loc	1 129 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/PycharmProjects/tritontest/compile_matmul_kernel_bias_accumulate_transpose_a.py"
	.file	2 "/home/mike/PycharmProjects/tritontest/.venv/lib/python3.11/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 211
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 80
.b8 121
.b8 99
.b8 104
.b8 97
.b8 114
.b8 109
.b8 80
.b8 114
.b8 111
.b8 106
.b8 101
.b8 99
.b8 116
.b8 115
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 116
.b8 101
.b8 115
.b8 116
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 104
.b8 4
.b32 104
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 104
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 104
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_11_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_11_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_11_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_11_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_11_FUNCTION_NAME "matmul_kernel_bias_accumulate_transpose_a"
