/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_3_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel_accumulate_transpose_a
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel_accumulate_transpose_a(
	.param .u64 matmul_kernel_accumulate_transpose_a_param_0,
	.param .u64 matmul_kernel_accumulate_transpose_a_param_1,
	.param .u64 matmul_kernel_accumulate_transpose_a_param_2,
	.param .u32 matmul_kernel_accumulate_transpose_a_param_3,
	.param .u32 matmul_kernel_accumulate_transpose_a_param_4,
	.param .u32 matmul_kernel_accumulate_transpose_a_param_5,
	.param .u32 matmul_kernel_accumulate_transpose_a_param_6,
	.param .u32 matmul_kernel_accumulate_transpose_a_param_7,
	.param .u32 matmul_kernel_accumulate_transpose_a_param_8
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<173>;
	.reg .b16 	%rs<643>;
	.reg .b32 	%r<1831>;
	.reg .b64 	%rd<134>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r195, [matmul_kernel_accumulate_transpose_a_param_5];
	ld.param.u64 	%rd37, [matmul_kernel_accumulate_transpose_a_param_1];
	ld.param.u64 	%rd66, [matmul_kernel_accumulate_transpose_a_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r196, %ctaid.x;
	// end inline asm
	ld.param.u32 	%r389, [matmul_kernel_accumulate_transpose_a_param_3];
$L__tmp1:
	.loc	2 40 22
	add.s32 	%r390, %r389, 127;
	ld.param.u64 	%rd67, [matmul_kernel_accumulate_transpose_a_param_2];
	.loc	2 40 28
	shr.s32 	%r391, %r390, 31;
	shr.u32 	%r392, %r391, 25;
	add.s32 	%r393, %r390, %r392;
	shr.s32 	%r394, %r393, 7;
	ld.param.u32 	%r395, [matmul_kernel_accumulate_transpose_a_param_4];
$L__tmp2:
	.loc	2 40 22
	add.s32 	%r396, %r395, 255;
	.loc	2 40 28
	shr.s32 	%r397, %r396, 31;
	shr.u32 	%r398, %r397, 24;
	add.s32 	%r399, %r396, %r398;
	shr.s32 	%r400, %r399, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r402, %r400, 3;
	ld.param.u32 	%r403, [matmul_kernel_accumulate_transpose_a_param_6];
	ld.param.u32 	%r404, [matmul_kernel_accumulate_transpose_a_param_7];
	ld.param.u32 	%r405, [matmul_kernel_accumulate_transpose_a_param_8];
	.loc	1 61 22
	div.s32 	%r406, %r196, %r402;
	.loc	1 62 29
	shl.b32 	%r407, %r406, 3;
	.loc	1 63 35
	sub.s32 	%r408, %r394, %r407;
	.loc	1 63 48
	min.s32 	%r409, %r408, 8;
	.loc	1 64 33
	rem.s32 	%r410, %r196, %r409;
	.loc	1 64 27
	add.s32 	%r411, %r407, %r410;
	mul.lo.s32 	%r412, %r406, %r402;
	sub.s32 	%r413, %r196, %r412;
	.loc	1 65 40
	div.s32 	%r414, %r413, %r409;
	.loc	1 74 23
	shl.b32 	%r415, %r411, 7;
	.loc	1 74 51
	mov.u32 	%r1, %tid.x;
	and.b32  	%r2, %r1, 31;
	shl.b32 	%r416, %r1, 3;
	and.b32  	%r417, %r416, 120;
	bfe.u32 	%r3, %r1, 5, 3;
	or.b32  	%r418, %r3, 8;
	or.b32  	%r419, %r3, 16;
	or.b32  	%r420, %r3, 24;
	or.b32  	%r421, %r3, 32;
	or.b32  	%r422, %r3, 40;
	or.b32  	%r423, %r3, 48;
	or.b32  	%r424, %r3, 56;
	.loc	1 74 38
	or.b32  	%r425, %r415, %r417;
	or.b32  	%r426, %r415, %r3;
	or.b32  	%r427, %r415, %r418;
	or.b32  	%r428, %r415, %r419;
	or.b32  	%r429, %r415, %r420;
	or.b32  	%r430, %r415, %r421;
	or.b32  	%r431, %r415, %r422;
	or.b32  	%r432, %r415, %r423;
	or.b32  	%r433, %r415, %r424;
	or.b32  	%r434, %r426, 64;
	or.b32  	%r435, %r426, 72;
	or.b32  	%r436, %r426, 80;
	or.b32  	%r437, %r426, 88;
	or.b32  	%r438, %r426, 96;
	or.b32  	%r439, %r426, 104;
	or.b32  	%r440, %r426, 112;
	or.b32  	%r441, %r426, 120;
	.loc	1 74 68
	rem.s32 	%r442, %r425, %r389;
	.loc	1 75 23
	shl.b32 	%r443, %r414, 8;
	.loc	1 75 51
	and.b32  	%r444, %r416, 248;
	.loc	1 75 38
	or.b32  	%r445, %r443, %r444;
	.loc	1 75 68
	rem.s32 	%r446, %r445, %r395;
	.loc	1 77 60
	bfe.u32 	%r4, %r1, 4, 4;
	or.b32  	%r447, %r4, 16;
	.loc	1 77 71
	shl.b32 	%r448, %r403, 4;
	.loc	1 77 53
	mad.lo.s32 	%r449, %r4, %r403, %r442;
	add.s32 	%r450, %r449, %r448;
	.loc	1 77 22
	mul.wide.s32 	%rd68, %r449, 2;
	add.s64 	%rd54, %rd66, %rd68;
	mul.wide.s32 	%rd69, %r450, 2;
	add.s64 	%rd55, %rd66, %rd69;
	.loc	1 78 40
	shl.b32 	%r451, %r404, 3;
	.loc	1 78 52
	mad.lo.s32 	%r452, %r3, %r404, %r446;
	add.s32 	%r453, %r452, %r451;
	add.s32 	%r454, %r453, %r451;
	add.s32 	%r455, %r454, %r451;
	.loc	1 78 22
	mul.wide.s32 	%rd70, %r452, 2;
	add.s64 	%rd56, %rd37, %rd70;
	mul.wide.s32 	%rd71, %r453, 2;
	add.s64 	%rd57, %rd37, %rd71;
	mul.wide.s32 	%rd72, %r454, 2;
	add.s64 	%rd58, %rd37, %rd72;
	mul.wide.s32 	%rd73, %r455, 2;
	add.s64 	%rd59, %rd37, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r456, %r426, %r405;
	mul.lo.s32 	%r457, %r427, %r405;
	mul.lo.s32 	%r458, %r428, %r405;
	mul.lo.s32 	%r459, %r429, %r405;
	mul.lo.s32 	%r460, %r430, %r405;
	mul.lo.s32 	%r461, %r431, %r405;
	mul.lo.s32 	%r462, %r432, %r405;
	mul.lo.s32 	%r463, %r433, %r405;
	shl.b32 	%r464, %r405, 6;
	add.s32 	%r465, %r456, %r464;
	shl.b32 	%r466, %r405, 3;
	add.s32 	%r467, %r465, %r466;
	add.s32 	%r468, %r467, %r466;
	add.s32 	%r469, %r468, %r466;
	add.s32 	%r470, %r469, %r466;
	add.s32 	%r471, %r470, %r466;
	add.s32 	%r472, %r471, %r466;
	add.s32 	%r473, %r472, %r466;
	.loc	1 82 21
	mul.wide.s32 	%rd74, %r456, 2;
	add.s64 	%rd75, %rd67, %rd74;
	mul.wide.s32 	%rd76, %r457, 2;
	add.s64 	%rd77, %rd67, %rd76;
	mul.wide.s32 	%rd78, %r458, 2;
	add.s64 	%rd79, %rd67, %rd78;
	mul.wide.s32 	%rd80, %r459, 2;
	add.s64 	%rd81, %rd67, %rd80;
	mul.wide.s32 	%rd82, %r460, 2;
	add.s64 	%rd83, %rd67, %rd82;
	mul.wide.s32 	%rd84, %r461, 2;
	add.s64 	%rd85, %rd67, %rd84;
	mul.wide.s32 	%rd86, %r462, 2;
	add.s64 	%rd87, %rd67, %rd86;
	mul.wide.s32 	%rd88, %r463, 2;
	add.s64 	%rd89, %rd67, %rd88;
	mul.wide.s32 	%rd90, %r465, 2;
	add.s64 	%rd91, %rd67, %rd90;
	mul.wide.s32 	%rd92, %r467, 2;
	add.s64 	%rd93, %rd67, %rd92;
	mul.wide.s32 	%rd94, %r468, 2;
	add.s64 	%rd95, %rd67, %rd94;
	mul.wide.s32 	%rd96, %r469, 2;
	add.s64 	%rd97, %rd67, %rd96;
	mul.wide.s32 	%rd98, %r470, 2;
	add.s64 	%rd99, %rd67, %rd98;
	mul.wide.s32 	%rd100, %r471, 2;
	add.s64 	%rd101, %rd67, %rd100;
	mul.wide.s32 	%rd102, %r472, 2;
	add.s64 	%rd103, %rd67, %rd102;
	mul.wide.s32 	%rd104, %r473, 2;
	add.s64 	%rd105, %rd67, %rd104;
	.loc	1 82 52
	mul.wide.s32 	%rd106, %r445, 2;
	add.s64 	%rd116, %rd75, %rd106;
	add.s64 	%rd117, %rd77, %rd106;
	add.s64 	%rd118, %rd79, %rd106;
	add.s64 	%rd119, %rd81, %rd106;
	add.s64 	%rd120, %rd83, %rd106;
	add.s64 	%rd121, %rd85, %rd106;
	add.s64 	%rd122, %rd87, %rd106;
	add.s64 	%rd123, %rd89, %rd106;
	add.s64 	%rd124, %rd91, %rd106;
	add.s64 	%rd125, %rd93, %rd106;
	add.s64 	%rd126, %rd95, %rd106;
	add.s64 	%rd127, %rd97, %rd106;
	add.s64 	%rd128, %rd99, %rd106;
	add.s64 	%rd129, %rd101, %rd106;
	add.s64 	%rd130, %rd103, %rd106;
	add.s64 	%rd131, %rd105, %rd106;
	.loc	1 83 33
	setp.lt.s32 	%p109, %r426, %r389;
	setp.lt.s32 	%p110, %r427, %r389;
	setp.lt.s32 	%p111, %r428, %r389;
	setp.lt.s32 	%p112, %r429, %r389;
	setp.lt.s32 	%p113, %r430, %r389;
	setp.lt.s32 	%p114, %r431, %r389;
	setp.lt.s32 	%p115, %r432, %r389;
	setp.lt.s32 	%p116, %r433, %r389;
	setp.lt.s32 	%p117, %r434, %r389;
	setp.lt.s32 	%p118, %r435, %r389;
	setp.lt.s32 	%p119, %r436, %r389;
	setp.lt.s32 	%p120, %r437, %r389;
	setp.lt.s32 	%p121, %r438, %r389;
	setp.lt.s32 	%p122, %r439, %r389;
	setp.lt.s32 	%p123, %r440, %r389;
	setp.lt.s32 	%p124, %r441, %r389;
	.loc	1 83 58
	setp.lt.s32 	%p125, %r445, %r395;
	.loc	1 83 39
	and.pred  	%p157, %p109, %p125;
	and.pred  	%p158, %p110, %p125;
	and.pred  	%p159, %p111, %p125;
	and.pred  	%p160, %p112, %p125;
	and.pred  	%p161, %p113, %p125;
	and.pred  	%p162, %p114, %p125;
	and.pred  	%p163, %p115, %p125;
	and.pred  	%p164, %p116, %p125;
	and.pred  	%p165, %p117, %p125;
	and.pred  	%p166, %p118, %p125;
	and.pred  	%p167, %p119, %p125;
	and.pred  	%p168, %p120, %p125;
	and.pred  	%p169, %p121, %p125;
	and.pred  	%p170, %p122, %p125;
	and.pred  	%p171, %p123, %p125;
	and.pred  	%p172, %p124, %p125;
	mov.b32 	%r1793, 0;
	.loc	1 89 30
	// begin inline asm
	mov.u32 %r197, 0x0;
	mov.u32 %r198, 0x0;
	mov.u32 %r199, 0x0;
	mov.u32 %r200, 0x0;
	@%p157 ld.global.v4.b32 { %r197, %r198, %r199, %r200 }, [ %rd116 + 0 ];
	@!%p157 mov.u32 %r197, %r1793;
	@!%p157 mov.u32 %r198, %r1793;
	@!%p157 mov.u32 %r199, %r1793;
	@!%p157 mov.u32 %r200, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r205, 0x0;
	mov.u32 %r206, 0x0;
	mov.u32 %r207, 0x0;
	mov.u32 %r208, 0x0;
	@%p158 ld.global.v4.b32 { %r205, %r206, %r207, %r208 }, [ %rd117 + 0 ];
	@!%p158 mov.u32 %r205, %r1793;
	@!%p158 mov.u32 %r206, %r1793;
	@!%p158 mov.u32 %r207, %r1793;
	@!%p158 mov.u32 %r208, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r213, 0x0;
	mov.u32 %r214, 0x0;
	mov.u32 %r215, 0x0;
	mov.u32 %r216, 0x0;
	@%p159 ld.global.v4.b32 { %r213, %r214, %r215, %r216 }, [ %rd118 + 0 ];
	@!%p159 mov.u32 %r213, %r1793;
	@!%p159 mov.u32 %r214, %r1793;
	@!%p159 mov.u32 %r215, %r1793;
	@!%p159 mov.u32 %r216, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r221, 0x0;
	mov.u32 %r222, 0x0;
	mov.u32 %r223, 0x0;
	mov.u32 %r224, 0x0;
	@%p160 ld.global.v4.b32 { %r221, %r222, %r223, %r224 }, [ %rd119 + 0 ];
	@!%p160 mov.u32 %r221, %r1793;
	@!%p160 mov.u32 %r222, %r1793;
	@!%p160 mov.u32 %r223, %r1793;
	@!%p160 mov.u32 %r224, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r229, 0x0;
	mov.u32 %r230, 0x0;
	mov.u32 %r231, 0x0;
	mov.u32 %r232, 0x0;
	@%p161 ld.global.v4.b32 { %r229, %r230, %r231, %r232 }, [ %rd120 + 0 ];
	@!%p161 mov.u32 %r229, %r1793;
	@!%p161 mov.u32 %r230, %r1793;
	@!%p161 mov.u32 %r231, %r1793;
	@!%p161 mov.u32 %r232, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r237, 0x0;
	mov.u32 %r238, 0x0;
	mov.u32 %r239, 0x0;
	mov.u32 %r240, 0x0;
	@%p162 ld.global.v4.b32 { %r237, %r238, %r239, %r240 }, [ %rd121 + 0 ];
	@!%p162 mov.u32 %r237, %r1793;
	@!%p162 mov.u32 %r238, %r1793;
	@!%p162 mov.u32 %r239, %r1793;
	@!%p162 mov.u32 %r240, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r245, 0x0;
	mov.u32 %r246, 0x0;
	mov.u32 %r247, 0x0;
	mov.u32 %r248, 0x0;
	@%p163 ld.global.v4.b32 { %r245, %r246, %r247, %r248 }, [ %rd122 + 0 ];
	@!%p163 mov.u32 %r245, %r1793;
	@!%p163 mov.u32 %r246, %r1793;
	@!%p163 mov.u32 %r247, %r1793;
	@!%p163 mov.u32 %r248, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r253, 0x0;
	mov.u32 %r254, 0x0;
	mov.u32 %r255, 0x0;
	mov.u32 %r256, 0x0;
	@%p164 ld.global.v4.b32 { %r253, %r254, %r255, %r256 }, [ %rd123 + 0 ];
	@!%p164 mov.u32 %r253, %r1793;
	@!%p164 mov.u32 %r254, %r1793;
	@!%p164 mov.u32 %r255, %r1793;
	@!%p164 mov.u32 %r256, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r261, 0x0;
	mov.u32 %r262, 0x0;
	mov.u32 %r263, 0x0;
	mov.u32 %r264, 0x0;
	@%p165 ld.global.v4.b32 { %r261, %r262, %r263, %r264 }, [ %rd124 + 0 ];
	@!%p165 mov.u32 %r261, %r1793;
	@!%p165 mov.u32 %r262, %r1793;
	@!%p165 mov.u32 %r263, %r1793;
	@!%p165 mov.u32 %r264, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r269, 0x0;
	mov.u32 %r270, 0x0;
	mov.u32 %r271, 0x0;
	mov.u32 %r272, 0x0;
	@%p166 ld.global.v4.b32 { %r269, %r270, %r271, %r272 }, [ %rd125 + 0 ];
	@!%p166 mov.u32 %r269, %r1793;
	@!%p166 mov.u32 %r270, %r1793;
	@!%p166 mov.u32 %r271, %r1793;
	@!%p166 mov.u32 %r272, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r277, 0x0;
	mov.u32 %r278, 0x0;
	mov.u32 %r279, 0x0;
	mov.u32 %r280, 0x0;
	@%p167 ld.global.v4.b32 { %r277, %r278, %r279, %r280 }, [ %rd126 + 0 ];
	@!%p167 mov.u32 %r277, %r1793;
	@!%p167 mov.u32 %r278, %r1793;
	@!%p167 mov.u32 %r279, %r1793;
	@!%p167 mov.u32 %r280, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r285, 0x0;
	mov.u32 %r286, 0x0;
	mov.u32 %r287, 0x0;
	mov.u32 %r288, 0x0;
	@%p168 ld.global.v4.b32 { %r285, %r286, %r287, %r288 }, [ %rd127 + 0 ];
	@!%p168 mov.u32 %r285, %r1793;
	@!%p168 mov.u32 %r286, %r1793;
	@!%p168 mov.u32 %r287, %r1793;
	@!%p168 mov.u32 %r288, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r293, 0x0;
	mov.u32 %r294, 0x0;
	mov.u32 %r295, 0x0;
	mov.u32 %r296, 0x0;
	@%p169 ld.global.v4.b32 { %r293, %r294, %r295, %r296 }, [ %rd128 + 0 ];
	@!%p169 mov.u32 %r293, %r1793;
	@!%p169 mov.u32 %r294, %r1793;
	@!%p169 mov.u32 %r295, %r1793;
	@!%p169 mov.u32 %r296, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r301, 0x0;
	mov.u32 %r302, 0x0;
	mov.u32 %r303, 0x0;
	mov.u32 %r304, 0x0;
	@%p170 ld.global.v4.b32 { %r301, %r302, %r303, %r304 }, [ %rd129 + 0 ];
	@!%p170 mov.u32 %r301, %r1793;
	@!%p170 mov.u32 %r302, %r1793;
	@!%p170 mov.u32 %r303, %r1793;
	@!%p170 mov.u32 %r304, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r309, 0x0;
	mov.u32 %r310, 0x0;
	mov.u32 %r311, 0x0;
	mov.u32 %r312, 0x0;
	@%p171 ld.global.v4.b32 { %r309, %r310, %r311, %r312 }, [ %rd130 + 0 ];
	@!%p171 mov.u32 %r309, %r1793;
	@!%p171 mov.u32 %r310, %r1793;
	@!%p171 mov.u32 %r311, %r1793;
	@!%p171 mov.u32 %r312, %r1793;
	// end inline asm
	// begin inline asm
	mov.u32 %r317, 0x0;
	mov.u32 %r318, 0x0;
	mov.u32 %r319, 0x0;
	mov.u32 %r320, 0x0;
	@%p172 ld.global.v4.b32 { %r317, %r318, %r319, %r320 }, [ %rd131 + 0 ];
	@!%p172 mov.u32 %r317, %r1793;
	@!%p172 mov.u32 %r318, %r1793;
	@!%p172 mov.u32 %r319, %r1793;
	@!%p172 mov.u32 %r320, %r1793;
	// end inline asm
$L__tmp4:
	.loc	2 40 22
	add.s32 	%r474, %r195, 31;
$L__tmp5:
	.loc	1 102 33
	shl.b32 	%r478, %r403, 5;
	.loc	1 103 33
	shl.b32 	%r479, %r404, 5;
	.loc	1 93 22
	setp.lt.s32 	%p126, %r474, 32;
	setp.gt.s32 	%p127, %r474, 31;
	.loc	1 96 72
	setp.lt.s32 	%p128, %r4, %r195;
	setp.lt.s32 	%p129, %r447, %r195;
	.loc	1 96 20
	shr.u32 	%r480, %r1, 1;
	and.b32  	%r481, %r480, 56;
	xor.b32  	%r482, %r481, %r417;
	shl.b32 	%r483, %r4, 7;
	or.b32  	%r70, %r483, %r482;
	shl.b32 	%r484, %r70, 1;
	mov.u32 	%r485, global_smem;
	add.s32 	%r325, %r485, %r484;
	shl.b32 	%r486, %r447, 7;
	or.b32  	%r71, %r486, %r482;
	shl.b32 	%r487, %r71, 1;
	add.s32 	%r327, %r485, %r487;
	selp.b32 	%r488, 16, 0, %p127;
	selp.b32 	%r326, %r488, 0, %p128;
	mov.pred 	%p97, -1;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r325 + 0 ], [ %rd54 + 0 ], 0x10, %r326;
	// end inline asm
	selp.b32 	%r328, %r488, 0, %p129;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r327 + 0 ], [ %rd55 + 0 ], 0x10, %r328;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 72
	setp.lt.s32 	%p130, %r3, %r195;
	setp.lt.s32 	%p131, %r418, %r195;
	setp.lt.s32 	%p132, %r419, %r195;
	setp.lt.s32 	%p133, %r420, %r195;
	.loc	1 97 20
	shr.u32 	%r489, %r1, 2;
	and.b32  	%r490, %r489, 56;
	xor.b32  	%r491, %r490, %r444;
	shl.b32 	%r492, %r3, 8;
	or.b32  	%r72, %r491, %r492;
	shl.b32 	%r493, %r72, 1;
	add.s32 	%r494, %r485, 16384;
	add.s32 	%r329, %r494, %r493;
	shl.b32 	%r495, %r418, 8;
	or.b32  	%r73, %r495, %r491;
	shl.b32 	%r496, %r73, 1;
	add.s32 	%r331, %r494, %r496;
	shl.b32 	%r497, %r419, 8;
	or.b32  	%r74, %r497, %r491;
	shl.b32 	%r498, %r74, 1;
	add.s32 	%r333, %r494, %r498;
	shl.b32 	%r499, %r420, 8;
	or.b32  	%r75, %r499, %r491;
	shl.b32 	%r500, %r75, 1;
	add.s32 	%r335, %r494, %r500;
	selp.b32 	%r330, %r488, 0, %p130;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r329 + 0 ], [ %rd56 + 0 ], 0x10, %r330;
	// end inline asm
	selp.b32 	%r332, %r488, 0, %p131;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r331 + 0 ], [ %rd57 + 0 ], 0x10, %r332;
	// end inline asm
	selp.b32 	%r334, %r488, 0, %p132;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r333 + 0 ], [ %rd58 + 0 ], 0x10, %r334;
	// end inline asm
	selp.b32 	%r336, %r488, 0, %p133;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r335 + 0 ], [ %rd59 + 0 ], 0x10, %r336;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p134, %r474, 63;
	.loc	1 102 18
	mul.wide.s32 	%rd107, %r478, 2;
	add.s64 	%rd60, %rd54, %rd107;
	add.s64 	%rd61, %rd55, %rd107;
	.loc	1 103 18
	mul.wide.s32 	%rd108, %r479, 2;
	add.s64 	%rd62, %rd56, %rd108;
	add.s64 	%rd63, %rd57, %rd108;
	add.s64 	%rd64, %rd58, %rd108;
	add.s64 	%rd65, %rd59, %rd108;
	.loc	1 96 53
	or.b32  	%r501, %r4, 32;
	or.b32  	%r502, %r4, 48;
	.loc	1 96 72
	setp.lt.s32 	%p135, %r501, %r195;
	setp.lt.s32 	%p136, %r502, %r195;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r503, %r485, 8192;
	add.s32 	%r337, %r503, %r484;
	add.s32 	%r339, %r503, %r487;
	selp.b32 	%r504, 16, 0, %p134;
	selp.b32 	%r338, %r504, 0, %p135;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r337 + 0 ], [ %rd60 + 0 ], 0x10, %r338;
	// end inline asm
	selp.b32 	%r340, %r504, 0, %p136;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r339 + 0 ], [ %rd61 + 0 ], 0x10, %r340;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 72
	setp.lt.s32 	%p137, %r421, %r195;
	setp.lt.s32 	%p138, %r422, %r195;
	setp.lt.s32 	%p139, %r423, %r195;
	setp.lt.s32 	%p140, %r424, %r195;
	.loc	1 97 20
	add.s32 	%r505, %r485, 32768;
	add.s32 	%r341, %r505, %r493;
	add.s32 	%r343, %r505, %r496;
	add.s32 	%r345, %r505, %r498;
	add.s32 	%r347, %r505, %r500;
	selp.b32 	%r342, %r504, 0, %p137;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r341 + 0 ], [ %rd62 + 0 ], 0x10, %r342;
	// end inline asm
	selp.b32 	%r344, %r504, 0, %p138;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r343 + 0 ], [ %rd63 + 0 ], 0x10, %r344;
	// end inline asm
	selp.b32 	%r346, %r504, 0, %p139;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r345 + 0 ], [ %rd64 + 0 ], 0x10, %r346;
	// end inline asm
	selp.b32 	%r348, %r504, 0, %p140;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r347 + 0 ], [ %rd65 + 0 ], 0x10, %r348;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	bfe.u32 	%r76, %r1, 7, 1;
	and.b32  	%r506, %r1, 7;
	bfe.u32 	%r507, %r1, 3, 1;
	bfe.u32 	%r508, %r1, 4, 1;
	shl.b32 	%r509, %r76, 1;
	or.b32  	%r510, %r509, %r507;
	xor.b32  	%r511, %r510, %r506;
	shl.b32 	%r512, %r511, 3;
	shl.b32 	%r513, %r506, 7;
	shl.b32 	%r514, %r508, 10;
	or.b32  	%r515, %r514, %r513;
	or.b32  	%r77, %r512, %r515;
	shl.b32 	%r516, %r77, 1;
	add.s32 	%r353, %r485, %r516;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1822, %r1823, %r1824, %r1825 }, [ %r353 + 0 ];
	// end inline asm
	or.b32  	%r517, %r510, 4;
	xor.b32  	%r518, %r517, %r506;
	shl.b32 	%r519, %r518, 3;
	or.b32  	%r82, %r519, %r515;
	shl.b32 	%r520, %r82, 1;
	add.s32 	%r358, %r485, %r520;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1818, %r1819, %r1820, %r1821 }, [ %r358 + 0 ];
	// end inline asm
	or.b32  	%r521, %r510, 8;
	xor.b32  	%r522, %r521, %r506;
	shl.b32 	%r523, %r522, 3;
	or.b32  	%r87, %r523, %r515;
	shl.b32 	%r524, %r87, 1;
	add.s32 	%r363, %r485, %r524;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1814, %r1815, %r1816, %r1817 }, [ %r363 + 0 ];
	// end inline asm
	or.b32  	%r525, %r510, 12;
	xor.b32  	%r526, %r525, %r506;
	shl.b32 	%r527, %r526, 3;
	or.b32  	%r92, %r527, %r515;
	shl.b32 	%r528, %r92, 1;
	add.s32 	%r368, %r485, %r528;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1810, %r1811, %r1812, %r1813 }, [ %r368 + 0 ];
	// end inline asm
	.loc	1 97 20
	bfe.u32 	%r97, %r1, 5, 2;
	shl.b32 	%r529, %r508, 2;
	or.b32  	%r530, %r529, %r97;
	and.b32  	%r531, %r1, 15;
	xor.b32  	%r532, %r530, %r506;
	shl.b32 	%r533, %r532, 3;
	shl.b32 	%r534, %r531, 8;
	or.b32  	%r98, %r533, %r534;
	shl.b32 	%r535, %r98, 1;
	add.s32 	%r373, %r494, %r535;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1806, %r1807, %r1808, %r1809 }, [ %r373 + 0 ];
	// end inline asm
	or.b32  	%r536, %r530, 8;
	xor.b32  	%r537, %r536, %r506;
	shl.b32 	%r538, %r537, 3;
	add.s32 	%r103, %r538, %r534;
	shl.b32 	%r539, %r103, 1;
	add.s32 	%r378, %r494, %r539;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1802, %r1803, %r1804, %r1805 }, [ %r378 + 0 ];
	// end inline asm
	or.b32  	%r540, %r530, 16;
	xor.b32  	%r541, %r540, %r506;
	shl.b32 	%r542, %r541, 3;
	add.s32 	%r108, %r542, %r534;
	shl.b32 	%r543, %r108, 1;
	add.s32 	%r383, %r494, %r543;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1798, %r1799, %r1800, %r1801 }, [ %r383 + 0 ];
	// end inline asm
	or.b32  	%r544, %r530, 24;
	xor.b32  	%r545, %r544, %r506;
	shl.b32 	%r546, %r545, 3;
	add.s32 	%r113, %r546, %r534;
	shl.b32 	%r547, %r113, 1;
	add.s32 	%r388, %r494, %r547;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1794, %r1795, %r1796, %r1797 }, [ %r388 + 0 ];
	// end inline asm
	mov.b16 	%rs515, 0x0000;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	.loc	1 93 22
	@%p126 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd3, %r452;
	cvt.s64.s32 	%rd4, %r453;
	cvt.s64.s32 	%rd5, %r454;
	cvt.s64.s32 	%rd6, %r455;
	shr.s32 	%r475, %r474, 31;
	shr.u32 	%r476, %r475, 27;
	add.s32 	%r477, %r474, %r476;
	shr.s32 	%r69, %r477, 5;
	cvt.s64.s32 	%rd23, %r478;
	cvt.s64.s32 	%rd24, %r479;
	add.s32 	%r118, %r69, -2;
	.loc	1 93 22
	shl.b64 	%rd25, %rd6, 1;
	shl.b64 	%rd109, %rd24, 2;
	add.s64 	%rd133, %rd37, %rd109;
	shl.b64 	%rd27, %rd24, 1;
	shl.b64 	%rd28, %rd5, 1;
	shl.b64 	%rd29, %rd4, 1;
	shl.b64 	%rd30, %rd3, 1;
	shl.b64 	%rd132, %rd23, 2;
	shl.b64 	%rd32, %rd23, 1;
	mov.b16 	%rs515, 0x0000;
	mov.b32 	%r1829, 1;
	mov.u32 	%r1826, %r494;
	mov.u32 	%r1827, %r485;
	mov.u32 	%r1828, %r1793;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	mov.u32 	%r1830, %r1793;
$L__BB0_2:
	setp.lt.s32 	%p147, %r1830, %r118;
	.loc	1 96 20
	add.s32 	%r1285, %r1827, %r516;
	add.s32 	%r556, %r1285, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r968, %r969, %r970, %r971 }, [ %r556 + 0 ];
	// end inline asm
	add.s32 	%r1287, %r1827, %r520;
	add.s32 	%r561, %r1287, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1048, %r1049, %r1050, %r1051 }, [ %r561 + 0 ];
	// end inline asm
	add.s32 	%r1289, %r1827, %r524;
	add.s32 	%r566, %r1289, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1128, %r1129, %r1130, %r1131 }, [ %r566 + 0 ];
	// end inline asm
	add.s32 	%r1291, %r1827, %r528;
	add.s32 	%r571, %r1291, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1208, %r1209, %r1210, %r1211 }, [ %r571 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r1293, %r1826, %r535;
	add.s32 	%r576, %r1293, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r972, %r973, %r982, %r983 }, [ %r576 + 0 ];
	// end inline asm
	add.s32 	%r1295, %r1826, %r539;
	add.s32 	%r581, %r1295, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r992, %r993, %r1002, %r1003 }, [ %r581 + 0 ];
	// end inline asm
	add.s32 	%r1297, %r1826, %r543;
	add.s32 	%r586, %r1297, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1012, %r1013, %r1022, %r1023 }, [ %r586 + 0 ];
	// end inline asm
	add.s32 	%r1299, %r1826, %r547;
	add.s32 	%r591, %r1299, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1032, %r1033, %r1042, %r1043 }, [ %r591 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r964, {%rs515, %rs516};
	mov.b32 	%r965, {%rs517, %rs518};
	mov.b32 	%r974, {%rs519, %rs520};
	mov.b32 	%r975, {%rs521, %rs522};
	mov.b32 	%r984, {%rs523, %rs524};
	mov.b32 	%r985, {%rs525, %rs526};
	mov.b32 	%r994, {%rs527, %rs528};
	mov.b32 	%r995, {%rs529, %rs530};
	mov.b32 	%r1004, {%rs531, %rs532};
	mov.b32 	%r1005, {%rs533, %rs534};
	mov.b32 	%r1014, {%rs535, %rs536};
	mov.b32 	%r1015, {%rs537, %rs538};
	mov.b32 	%r1024, {%rs539, %rs540};
	mov.b32 	%r1025, {%rs541, %rs542};
	mov.b32 	%r1034, {%rs543, %rs544};
	mov.b32 	%r1035, {%rs545, %rs546};
	mov.b32 	%r1044, {%rs547, %rs548};
	mov.b32 	%r1045, {%rs549, %rs550};
	mov.b32 	%r1054, {%rs551, %rs552};
	mov.b32 	%r1055, {%rs553, %rs554};
	mov.b32 	%r1064, {%rs555, %rs556};
	mov.b32 	%r1065, {%rs557, %rs558};
	mov.b32 	%r1074, {%rs559, %rs560};
	mov.b32 	%r1075, {%rs561, %rs562};
	mov.b32 	%r1084, {%rs563, %rs564};
	mov.b32 	%r1085, {%rs565, %rs566};
	mov.b32 	%r1094, {%rs567, %rs568};
	mov.b32 	%r1095, {%rs569, %rs570};
	mov.b32 	%r1104, {%rs571, %rs572};
	mov.b32 	%r1105, {%rs573, %rs574};
	mov.b32 	%r1114, {%rs575, %rs576};
	mov.b32 	%r1115, {%rs577, %rs578};
	mov.b32 	%r1124, {%rs579, %rs580};
	mov.b32 	%r1125, {%rs581, %rs582};
	mov.b32 	%r1134, {%rs583, %rs584};
	mov.b32 	%r1135, {%rs585, %rs586};
	mov.b32 	%r1144, {%rs587, %rs588};
	mov.b32 	%r1145, {%rs589, %rs590};
	mov.b32 	%r1154, {%rs591, %rs592};
	mov.b32 	%r1155, {%rs593, %rs594};
	mov.b32 	%r1164, {%rs595, %rs596};
	mov.b32 	%r1165, {%rs597, %rs598};
	mov.b32 	%r1174, {%rs599, %rs600};
	mov.b32 	%r1175, {%rs601, %rs602};
	mov.b32 	%r1184, {%rs603, %rs604};
	mov.b32 	%r1185, {%rs605, %rs606};
	mov.b32 	%r1194, {%rs607, %rs608};
	mov.b32 	%r1195, {%rs609, %rs610};
	mov.b32 	%r1204, {%rs611, %rs612};
	mov.b32 	%r1205, {%rs613, %rs614};
	mov.b32 	%r1214, {%rs615, %rs616};
	mov.b32 	%r1215, {%rs617, %rs618};
	mov.b32 	%r1224, {%rs619, %rs620};
	mov.b32 	%r1225, {%rs621, %rs622};
	mov.b32 	%r1234, {%rs623, %rs624};
	mov.b32 	%r1235, {%rs625, %rs626};
	mov.b32 	%r1244, {%rs627, %rs628};
	mov.b32 	%r1245, {%rs629, %rs630};
	mov.b32 	%r1254, {%rs631, %rs632};
	mov.b32 	%r1255, {%rs633, %rs634};
	mov.b32 	%r1264, {%rs635, %rs636};
	mov.b32 	%r1265, {%rs637, %rs638};
	mov.b32 	%r1274, {%rs639, %rs640};
	mov.b32 	%r1275, {%rs641, %rs642};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r964, %r965 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1806, %r1807 }, { %r964, %r965 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r974, %r975 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1808, %r1809 }, { %r974, %r975 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r984, %r985 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1802, %r1803 }, { %r984, %r985 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r994, %r995 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1804, %r1805 }, { %r994, %r995 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1004, %r1005 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1798, %r1799 }, { %r1004, %r1005 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1014, %r1015 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1800, %r1801 }, { %r1014, %r1015 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1024, %r1025 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1794, %r1795 }, { %r1024, %r1025 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1034, %r1035 }, { %r1822, %r1823, %r1824, %r1825 }, { %r1796, %r1797 }, { %r1034, %r1035 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1044, %r1045 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1806, %r1807 }, { %r1044, %r1045 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1054, %r1055 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1808, %r1809 }, { %r1054, %r1055 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1064, %r1065 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1802, %r1803 }, { %r1064, %r1065 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1074, %r1075 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1804, %r1805 }, { %r1074, %r1075 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1084, %r1085 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1798, %r1799 }, { %r1084, %r1085 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1094, %r1095 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1800, %r1801 }, { %r1094, %r1095 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1104, %r1105 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1794, %r1795 }, { %r1104, %r1105 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1114, %r1115 }, { %r1818, %r1819, %r1820, %r1821 }, { %r1796, %r1797 }, { %r1114, %r1115 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1124, %r1125 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1806, %r1807 }, { %r1124, %r1125 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1134, %r1135 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1808, %r1809 }, { %r1134, %r1135 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1144, %r1145 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1802, %r1803 }, { %r1144, %r1145 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1154, %r1155 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1804, %r1805 }, { %r1154, %r1155 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1164, %r1165 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1798, %r1799 }, { %r1164, %r1165 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1174, %r1175 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1800, %r1801 }, { %r1174, %r1175 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1184, %r1185 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1794, %r1795 }, { %r1184, %r1185 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1194, %r1195 }, { %r1814, %r1815, %r1816, %r1817 }, { %r1796, %r1797 }, { %r1194, %r1195 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1204, %r1205 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1806, %r1807 }, { %r1204, %r1205 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1214, %r1215 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1808, %r1809 }, { %r1214, %r1215 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1224, %r1225 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1802, %r1803 }, { %r1224, %r1225 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1234, %r1235 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1804, %r1805 }, { %r1234, %r1235 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1244, %r1245 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1798, %r1799 }, { %r1244, %r1245 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1254, %r1255 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1800, %r1801 }, { %r1254, %r1255 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1264, %r1265 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1794, %r1795 }, { %r1264, %r1265 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1274, %r1275 }, { %r1810, %r1811, %r1812, %r1813 }, { %r1796, %r1797 }, { %r1274, %r1275 };
	// end inline asm
	.loc	1 102 18
	add.s64 	%rd110, %rd54, %rd132;
	.loc	1 103 18
	add.s64 	%rd111, %rd55, %rd132;
	add.s64 	%rd112, %rd133, %rd30;
	add.s64 	%rd113, %rd133, %rd29;
	add.s64 	%rd114, %rd133, %rd28;
	.loc	1 93 22
	add.s64 	%rd115, %rd133, %rd25;
	add.s32 	%r1364, %r1829, 1;
	setp.lt.s32 	%p148, %r1364, 2;
	selp.b32 	%r1829, %r1364, 0, %p148;
	.loc	1 96 53
	add.s32 	%r1365, %r4, %r1793;
	add.s32 	%r1366, %r1365, 64;
	.loc	1 96 72
	add.s32 	%r1367, %r1365, 80;
	setp.lt.s32 	%p149, %r1366, %r195;
	setp.lt.s32 	%p150, %r1367, %r195;
	.loc	1 96 20
	shl.b32 	%r1368, %r1829, 13;
	add.s32 	%r1370, %r485, %r1368;
	bar.sync 	0;
	add.s32 	%r912, %r1370, %r484;
	add.s32 	%r914, %r1370, %r487;
	selp.b32 	%r1373, 16, 0, %p149;
	selp.b32 	%r913, %r1373, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r912 + 0 ], [ %rd110 + 0 ], 0x10, %r913;
	// end inline asm
	selp.b32 	%r1374, 16, 0, %p150;
	selp.b32 	%r915, %r1374, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r914 + 0 ], [ %rd111 + 0 ], 0x10, %r915;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	add.s32 	%r1375, %r3, %r1793;
	add.s32 	%r1376, %r1375, 64;
	add.s32 	%r1377, %r1375, 72;
	add.s32 	%r1378, %r1375, 80;
	.loc	1 97 72
	add.s32 	%r1379, %r1375, 88;
	setp.lt.s32 	%p151, %r1376, %r195;
	setp.lt.s32 	%p152, %r1377, %r195;
	setp.lt.s32 	%p153, %r1378, %r195;
	setp.lt.s32 	%p154, %r1379, %r195;
	.loc	1 97 20
	shl.b32 	%r1380, %r1829, 14;
	add.s32 	%r1382, %r494, %r1380;
	add.s32 	%r916, %r1382, %r493;
	add.s32 	%r918, %r1382, %r496;
	add.s32 	%r920, %r1382, %r498;
	add.s32 	%r922, %r1382, %r500;
	selp.b32 	%r1387, 16, 0, %p151;
	selp.b32 	%r917, %r1387, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r916 + 0 ], [ %rd112 + 0 ], 0x10, %r917;
	// end inline asm
	selp.b32 	%r1388, 16, 0, %p152;
	selp.b32 	%r919, %r1388, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r918 + 0 ], [ %rd113 + 0 ], 0x10, %r919;
	// end inline asm
	selp.b32 	%r1389, 16, 0, %p153;
	selp.b32 	%r921, %r1389, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r920 + 0 ], [ %rd114 + 0 ], 0x10, %r921;
	// end inline asm
	selp.b32 	%r1390, 16, 0, %p154;
	selp.b32 	%r923, %r1390, 0, %p147;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r922 + 0 ], [ %rd115 + 0 ], 0x10, %r923;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1391, %r1828, 1;
	setp.lt.s32 	%p155, %r1391, 2;
	selp.b32 	%r1828, %r1391, 0, %p155;
	.loc	1 96 20
	shl.b32 	%r1392, %r1828, 13;
	add.s32 	%r1827, %r485, %r1392;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1393, %r1828, 14;
	add.s32 	%r1826, %r494, %r1393;
	.loc	1 96 20
	add.s32 	%r928, %r1827, %r516;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1822, %r1823, %r1824, %r1825 }, [ %r928 + 0 ];
	// end inline asm
	add.s32 	%r933, %r1827, %r520;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1818, %r1819, %r1820, %r1821 }, [ %r933 + 0 ];
	// end inline asm
	add.s32 	%r938, %r1827, %r524;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1814, %r1815, %r1816, %r1817 }, [ %r938 + 0 ];
	// end inline asm
	add.s32 	%r943, %r1827, %r528;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1810, %r1811, %r1812, %r1813 }, [ %r943 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r948, %r1826, %r535;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1806, %r1807, %r1808, %r1809 }, [ %r948 + 0 ];
	// end inline asm
	add.s32 	%r953, %r1826, %r539;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1802, %r1803, %r1804, %r1805 }, [ %r953 + 0 ];
	// end inline asm
	add.s32 	%r958, %r1826, %r543;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1798, %r1799, %r1800, %r1801 }, [ %r958 + 0 ];
	// end inline asm
	add.s32 	%r963, %r1826, %r547;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1794, %r1795, %r1796, %r1797 }, [ %r963 + 0 ];
	// end inline asm
	.loc	1 100 35
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r964, %r965 }, { %r968, %r969, %r970, %r971 }, { %r972, %r973 }, { %r964, %r965 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r974, %r975 }, { %r968, %r969, %r970, %r971 }, { %r982, %r983 }, { %r974, %r975 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r984, %r985 }, { %r968, %r969, %r970, %r971 }, { %r992, %r993 }, { %r984, %r985 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r994, %r995 }, { %r968, %r969, %r970, %r971 }, { %r1002, %r1003 }, { %r994, %r995 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1004, %r1005 }, { %r968, %r969, %r970, %r971 }, { %r1012, %r1013 }, { %r1004, %r1005 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1014, %r1015 }, { %r968, %r969, %r970, %r971 }, { %r1022, %r1023 }, { %r1014, %r1015 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1024, %r1025 }, { %r968, %r969, %r970, %r971 }, { %r1032, %r1033 }, { %r1024, %r1025 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1034, %r1035 }, { %r968, %r969, %r970, %r971 }, { %r1042, %r1043 }, { %r1034, %r1035 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1044, %r1045 }, { %r1048, %r1049, %r1050, %r1051 }, { %r972, %r973 }, { %r1044, %r1045 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1054, %r1055 }, { %r1048, %r1049, %r1050, %r1051 }, { %r982, %r983 }, { %r1054, %r1055 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1064, %r1065 }, { %r1048, %r1049, %r1050, %r1051 }, { %r992, %r993 }, { %r1064, %r1065 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1074, %r1075 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1002, %r1003 }, { %r1074, %r1075 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1084, %r1085 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1012, %r1013 }, { %r1084, %r1085 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1094, %r1095 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1022, %r1023 }, { %r1094, %r1095 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1104, %r1105 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1032, %r1033 }, { %r1104, %r1105 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1114, %r1115 }, { %r1048, %r1049, %r1050, %r1051 }, { %r1042, %r1043 }, { %r1114, %r1115 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1124, %r1125 }, { %r1128, %r1129, %r1130, %r1131 }, { %r972, %r973 }, { %r1124, %r1125 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1134, %r1135 }, { %r1128, %r1129, %r1130, %r1131 }, { %r982, %r983 }, { %r1134, %r1135 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1144, %r1145 }, { %r1128, %r1129, %r1130, %r1131 }, { %r992, %r993 }, { %r1144, %r1145 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1154, %r1155 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1002, %r1003 }, { %r1154, %r1155 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1164, %r1165 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1012, %r1013 }, { %r1164, %r1165 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1174, %r1175 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1022, %r1023 }, { %r1174, %r1175 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1184, %r1185 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1032, %r1033 }, { %r1184, %r1185 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1194, %r1195 }, { %r1128, %r1129, %r1130, %r1131 }, { %r1042, %r1043 }, { %r1194, %r1195 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1204, %r1205 }, { %r1208, %r1209, %r1210, %r1211 }, { %r972, %r973 }, { %r1204, %r1205 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1214, %r1215 }, { %r1208, %r1209, %r1210, %r1211 }, { %r982, %r983 }, { %r1214, %r1215 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1224, %r1225 }, { %r1208, %r1209, %r1210, %r1211 }, { %r992, %r993 }, { %r1224, %r1225 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1234, %r1235 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1002, %r1003 }, { %r1234, %r1235 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1244, %r1245 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1012, %r1013 }, { %r1244, %r1245 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1254, %r1255 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1022, %r1023 }, { %r1254, %r1255 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1264, %r1265 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1032, %r1033 }, { %r1264, %r1265 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1274, %r1275 }, { %r1208, %r1209, %r1210, %r1211 }, { %r1042, %r1043 }, { %r1274, %r1275 };
	// end inline asm
	mov.b32 	{%rs515, %rs516}, %r964;
	mov.b32 	{%rs517, %rs518}, %r965;
	mov.b32 	{%rs519, %rs520}, %r974;
	mov.b32 	{%rs521, %rs522}, %r975;
	mov.b32 	{%rs523, %rs524}, %r984;
	mov.b32 	{%rs525, %rs526}, %r985;
	mov.b32 	{%rs527, %rs528}, %r994;
	mov.b32 	{%rs529, %rs530}, %r995;
	mov.b32 	{%rs531, %rs532}, %r1004;
	mov.b32 	{%rs533, %rs534}, %r1005;
	mov.b32 	{%rs535, %rs536}, %r1014;
	mov.b32 	{%rs537, %rs538}, %r1015;
	mov.b32 	{%rs539, %rs540}, %r1024;
	mov.b32 	{%rs541, %rs542}, %r1025;
	mov.b32 	{%rs543, %rs544}, %r1034;
	mov.b32 	{%rs545, %rs546}, %r1035;
	mov.b32 	{%rs547, %rs548}, %r1044;
	mov.b32 	{%rs549, %rs550}, %r1045;
	mov.b32 	{%rs551, %rs552}, %r1054;
	mov.b32 	{%rs553, %rs554}, %r1055;
	mov.b32 	{%rs555, %rs556}, %r1064;
	mov.b32 	{%rs557, %rs558}, %r1065;
	mov.b32 	{%rs559, %rs560}, %r1074;
	mov.b32 	{%rs561, %rs562}, %r1075;
	mov.b32 	{%rs563, %rs564}, %r1084;
	mov.b32 	{%rs565, %rs566}, %r1085;
	mov.b32 	{%rs567, %rs568}, %r1094;
	mov.b32 	{%rs569, %rs570}, %r1095;
	mov.b32 	{%rs571, %rs572}, %r1104;
	mov.b32 	{%rs573, %rs574}, %r1105;
	mov.b32 	{%rs575, %rs576}, %r1114;
	mov.b32 	{%rs577, %rs578}, %r1115;
	mov.b32 	{%rs579, %rs580}, %r1124;
	mov.b32 	{%rs581, %rs582}, %r1125;
	mov.b32 	{%rs583, %rs584}, %r1134;
	mov.b32 	{%rs585, %rs586}, %r1135;
	mov.b32 	{%rs587, %rs588}, %r1144;
	mov.b32 	{%rs589, %rs590}, %r1145;
	mov.b32 	{%rs591, %rs592}, %r1154;
	mov.b32 	{%rs593, %rs594}, %r1155;
	mov.b32 	{%rs595, %rs596}, %r1164;
	mov.b32 	{%rs597, %rs598}, %r1165;
	mov.b32 	{%rs599, %rs600}, %r1174;
	mov.b32 	{%rs601, %rs602}, %r1175;
	mov.b32 	{%rs603, %rs604}, %r1184;
	mov.b32 	{%rs605, %rs606}, %r1185;
	mov.b32 	{%rs607, %rs608}, %r1194;
	mov.b32 	{%rs609, %rs610}, %r1195;
	mov.b32 	{%rs611, %rs612}, %r1204;
	mov.b32 	{%rs613, %rs614}, %r1205;
	mov.b32 	{%rs615, %rs616}, %r1214;
	mov.b32 	{%rs617, %rs618}, %r1215;
	mov.b32 	{%rs619, %rs620}, %r1224;
	mov.b32 	{%rs621, %rs622}, %r1225;
	mov.b32 	{%rs623, %rs624}, %r1234;
	mov.b32 	{%rs625, %rs626}, %r1235;
	mov.b32 	{%rs627, %rs628}, %r1244;
	mov.b32 	{%rs629, %rs630}, %r1245;
	mov.b32 	{%rs631, %rs632}, %r1254;
	mov.b32 	{%rs633, %rs634}, %r1255;
	mov.b32 	{%rs635, %rs636}, %r1264;
	mov.b32 	{%rs637, %rs638}, %r1265;
	mov.b32 	{%rs639, %rs640}, %r1274;
	mov.b32 	{%rs641, %rs642}, %r1275;
	.loc	1 93 22
	add.s32 	%r1830, %r1830, 1;
	add.s64 	%rd133, %rd133, %rd27;
	add.s64 	%rd132, %rd132, %rd32;
	add.s32 	%r1793, %r1793, 32;
	setp.lt.s32 	%p156, %r1830, %r69;
	@%p156 bra 	$L__BB0_2;
$L__BB0_3:
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	shr.u32 	%r1586, %r2, 2;
	shl.b32 	%r1587, %r1, 1;
	and.b32  	%r1588, %r1587, 6;
	shl.b32 	%r1589, %r76, 4;
	or.b32  	%r1590, %r1589, %r1586;
	shl.b32 	%r1591, %r97, 3;
	or.b32  	%r1592, %r1591, %r1588;
	mad.lo.s32 	%r1593, %r1590, 264, %r1592;
	shl.b32 	%r1594, %r1593, 1;
	add.s32 	%r1596, %r485, %r1594;
	mov.b32 	%r1597, {%rs515, %rs516};
	st.shared.b32 	[%r1596], %r1597;
	mov.b32 	%r1598, {%rs517, %rs518};
	st.shared.b32 	[%r1596+4224], %r1598;
	mov.b32 	%r1599, {%rs519, %rs520};
	st.shared.b32 	[%r1596+64], %r1599;
	mov.b32 	%r1600, {%rs521, %rs522};
	st.shared.b32 	[%r1596+4288], %r1600;
	mov.b32 	%r1601, {%rs523, %rs524};
	st.shared.b32 	[%r1596+128], %r1601;
	mov.b32 	%r1602, {%rs525, %rs526};
	st.shared.b32 	[%r1596+4352], %r1602;
	mov.b32 	%r1603, {%rs527, %rs528};
	st.shared.b32 	[%r1596+192], %r1603;
	mov.b32 	%r1604, {%rs529, %rs530};
	st.shared.b32 	[%r1596+4416], %r1604;
	mov.b32 	%r1605, {%rs531, %rs532};
	st.shared.b32 	[%r1596+256], %r1605;
	mov.b32 	%r1606, {%rs533, %rs534};
	st.shared.b32 	[%r1596+4480], %r1606;
	mov.b32 	%r1607, {%rs535, %rs536};
	st.shared.b32 	[%r1596+320], %r1607;
	mov.b32 	%r1608, {%rs537, %rs538};
	st.shared.b32 	[%r1596+4544], %r1608;
	mov.b32 	%r1609, {%rs539, %rs540};
	st.shared.b32 	[%r1596+384], %r1609;
	mov.b32 	%r1610, {%rs541, %rs542};
	st.shared.b32 	[%r1596+4608], %r1610;
	mov.b32 	%r1611, {%rs543, %rs544};
	st.shared.b32 	[%r1596+448], %r1611;
	mov.b32 	%r1612, {%rs545, %rs546};
	st.shared.b32 	[%r1596+4672], %r1612;
	bar.sync 	0;
	shl.b32 	%r1613, %r2, 3;
	mad.lo.s32 	%r1614, %r3, 264, %r1613;
	shl.b32 	%r1615, %r1614, 1;
	add.s32 	%r1616, %r485, %r1615;
	mov.b32 	%r1617, {%rs547, %rs548};
	mov.b32 	%r1618, {%rs549, %rs550};
	mov.b32 	%r1619, {%rs551, %rs552};
	mov.b32 	%r1620, {%rs553, %rs554};
	mov.b32 	%r1621, {%rs555, %rs556};
	mov.b32 	%r1622, {%rs557, %rs558};
	mov.b32 	%r1623, {%rs559, %rs560};
	mov.b32 	%r1624, {%rs561, %rs562};
	mov.b32 	%r1625, {%rs563, %rs564};
	mov.b32 	%r1626, {%rs565, %rs566};
	mov.b32 	%r1627, {%rs567, %rs568};
	mov.b32 	%r1628, {%rs569, %rs570};
	mov.b32 	%r1629, {%rs571, %rs572};
	mov.b32 	%r1630, {%rs573, %rs574};
	mov.b32 	%r1631, {%rs575, %rs576};
	mov.b32 	%r1632, {%rs577, %rs578};
	mov.b32 	%r1633, {%rs579, %rs580};
	mov.b32 	%r1634, {%rs581, %rs582};
	mov.b32 	%r1635, {%rs583, %rs584};
	mov.b32 	%r1636, {%rs585, %rs586};
	mov.b32 	%r1637, {%rs587, %rs588};
	mov.b32 	%r1638, {%rs589, %rs590};
	mov.b32 	%r1639, {%rs591, %rs592};
	mov.b32 	%r1640, {%rs593, %rs594};
	mov.b32 	%r1641, {%rs595, %rs596};
	mov.b32 	%r1642, {%rs597, %rs598};
	mov.b32 	%r1643, {%rs599, %rs600};
	mov.b32 	%r1644, {%rs601, %rs602};
	mov.b32 	%r1645, {%rs603, %rs604};
	mov.b32 	%r1646, {%rs605, %rs606};
	mov.b32 	%r1647, {%rs607, %rs608};
	mov.b32 	%r1648, {%rs609, %rs610};
	mov.b32 	%r1649, {%rs611, %rs612};
	mov.b32 	%r1650, {%rs613, %rs614};
	mov.b32 	%r1651, {%rs615, %rs616};
	mov.b32 	%r1652, {%rs617, %rs618};
	mov.b32 	%r1653, {%rs619, %rs620};
	mov.b32 	%r1654, {%rs621, %rs622};
	mov.b32 	%r1655, {%rs623, %rs624};
	mov.b32 	%r1656, {%rs625, %rs626};
	mov.b32 	%r1657, {%rs627, %rs628};
	mov.b32 	%r1658, {%rs629, %rs630};
	mov.b32 	%r1659, {%rs631, %rs632};
	mov.b32 	%r1660, {%rs633, %rs634};
	mov.b32 	%r1661, {%rs635, %rs636};
	mov.b32 	%r1662, {%rs637, %rs638};
	mov.b32 	%r1663, {%rs639, %rs640};
	mov.b32 	%r1664, {%rs641, %rs642};
	ld.shared.v4.b32 	{%r1665, %r1666, %r1667, %r1668}, [%r1616];
	.loc	1 127 23
	add.f16x2 	%r1669, %r1665, %r197;
	add.f16x2 	%r1670, %r1666, %r198;
	add.f16x2 	%r1671, %r1667, %r199;
	add.f16x2 	%r1672, %r1668, %r200;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1673, %r1674, %r1675, %r1676}, [%r1616+4224];
	.loc	1 127 23
	add.f16x2 	%r1677, %r1673, %r205;
	add.f16x2 	%r1678, %r1674, %r206;
	add.f16x2 	%r1679, %r1675, %r207;
	add.f16x2 	%r1680, %r1676, %r208;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1681, %r1682, %r1683, %r1684}, [%r1616+8448];
	.loc	1 127 23
	add.f16x2 	%r1685, %r1681, %r213;
	add.f16x2 	%r1686, %r1682, %r214;
	add.f16x2 	%r1687, %r1683, %r215;
	add.f16x2 	%r1688, %r1684, %r216;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1689, %r1690, %r1691, %r1692}, [%r1616+12672];
	.loc	1 127 23
	add.f16x2 	%r1693, %r1689, %r221;
	add.f16x2 	%r1694, %r1690, %r222;
	add.f16x2 	%r1695, %r1691, %r223;
	.loc	1 93 22
	bar.sync 	0;
	st.shared.b32 	[%r1596], %r1617;
	st.shared.b32 	[%r1596+4224], %r1618;
	st.shared.b32 	[%r1596+64], %r1619;
	st.shared.b32 	[%r1596+4288], %r1620;
	st.shared.b32 	[%r1596+128], %r1621;
	st.shared.b32 	[%r1596+4352], %r1622;
	st.shared.b32 	[%r1596+192], %r1623;
	st.shared.b32 	[%r1596+4416], %r1624;
	st.shared.b32 	[%r1596+256], %r1625;
	st.shared.b32 	[%r1596+4480], %r1626;
	st.shared.b32 	[%r1596+320], %r1627;
	st.shared.b32 	[%r1596+4544], %r1628;
	st.shared.b32 	[%r1596+384], %r1629;
	st.shared.b32 	[%r1596+4608], %r1630;
	st.shared.b32 	[%r1596+448], %r1631;
	st.shared.b32 	[%r1596+4672], %r1632;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1696, %r1692, %r224;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1697, %r1698, %r1699, %r1700}, [%r1616];
	.loc	1 127 23
	add.f16x2 	%r1701, %r1697, %r229;
	add.f16x2 	%r1702, %r1698, %r230;
	add.f16x2 	%r1703, %r1699, %r231;
	add.f16x2 	%r1704, %r1700, %r232;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1705, %r1706, %r1707, %r1708}, [%r1616+4224];
	.loc	1 127 23
	add.f16x2 	%r1709, %r1705, %r237;
	add.f16x2 	%r1710, %r1706, %r238;
	add.f16x2 	%r1711, %r1707, %r239;
	add.f16x2 	%r1712, %r1708, %r240;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1713, %r1714, %r1715, %r1716}, [%r1616+8448];
	.loc	1 127 23
	add.f16x2 	%r1717, %r1713, %r245;
	add.f16x2 	%r1718, %r1714, %r246;
	add.f16x2 	%r1719, %r1715, %r247;
	add.f16x2 	%r1720, %r1716, %r248;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1721, %r1722, %r1723, %r1724}, [%r1616+12672];
	.loc	1 127 23
	add.f16x2 	%r1725, %r1721, %r253;
	add.f16x2 	%r1726, %r1722, %r254;
	add.f16x2 	%r1727, %r1723, %r255;
	.loc	1 93 22
	bar.sync 	0;
	st.shared.b32 	[%r1596], %r1633;
	st.shared.b32 	[%r1596+4224], %r1634;
	st.shared.b32 	[%r1596+64], %r1635;
	st.shared.b32 	[%r1596+4288], %r1636;
	st.shared.b32 	[%r1596+128], %r1637;
	st.shared.b32 	[%r1596+4352], %r1638;
	st.shared.b32 	[%r1596+192], %r1639;
	st.shared.b32 	[%r1596+4416], %r1640;
	st.shared.b32 	[%r1596+256], %r1641;
	st.shared.b32 	[%r1596+4480], %r1642;
	st.shared.b32 	[%r1596+320], %r1643;
	st.shared.b32 	[%r1596+4544], %r1644;
	st.shared.b32 	[%r1596+384], %r1645;
	st.shared.b32 	[%r1596+4608], %r1646;
	st.shared.b32 	[%r1596+448], %r1647;
	st.shared.b32 	[%r1596+4672], %r1648;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1728, %r1724, %r256;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1729, %r1730, %r1731, %r1732}, [%r1616];
	.loc	1 127 23
	add.f16x2 	%r1733, %r1729, %r261;
	add.f16x2 	%r1734, %r1730, %r262;
	add.f16x2 	%r1735, %r1731, %r263;
	add.f16x2 	%r1736, %r1732, %r264;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1737, %r1738, %r1739, %r1740}, [%r1616+4224];
	.loc	1 127 23
	add.f16x2 	%r1741, %r1737, %r269;
	add.f16x2 	%r1742, %r1738, %r270;
	add.f16x2 	%r1743, %r1739, %r271;
	add.f16x2 	%r1744, %r1740, %r272;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1745, %r1746, %r1747, %r1748}, [%r1616+8448];
	.loc	1 127 23
	add.f16x2 	%r1749, %r1745, %r277;
	add.f16x2 	%r1750, %r1746, %r278;
	add.f16x2 	%r1751, %r1747, %r279;
	add.f16x2 	%r1752, %r1748, %r280;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1753, %r1754, %r1755, %r1756}, [%r1616+12672];
	.loc	1 127 23
	add.f16x2 	%r1757, %r1753, %r285;
	add.f16x2 	%r1758, %r1754, %r286;
	add.f16x2 	%r1759, %r1755, %r287;
	.loc	1 93 22
	bar.sync 	0;
	st.shared.b32 	[%r1596], %r1649;
	st.shared.b32 	[%r1596+4224], %r1650;
	st.shared.b32 	[%r1596+64], %r1651;
	st.shared.b32 	[%r1596+4288], %r1652;
	st.shared.b32 	[%r1596+128], %r1653;
	st.shared.b32 	[%r1596+4352], %r1654;
	st.shared.b32 	[%r1596+192], %r1655;
	st.shared.b32 	[%r1596+4416], %r1656;
	st.shared.b32 	[%r1596+256], %r1657;
	st.shared.b32 	[%r1596+4480], %r1658;
	st.shared.b32 	[%r1596+320], %r1659;
	st.shared.b32 	[%r1596+4544], %r1660;
	st.shared.b32 	[%r1596+384], %r1661;
	st.shared.b32 	[%r1596+4608], %r1662;
	st.shared.b32 	[%r1596+448], %r1663;
	st.shared.b32 	[%r1596+4672], %r1664;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1760, %r1756, %r288;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1761, %r1762, %r1763, %r1764}, [%r1616];
	.loc	1 127 23
	add.f16x2 	%r1765, %r1761, %r293;
	add.f16x2 	%r1766, %r1762, %r294;
	add.f16x2 	%r1767, %r1763, %r295;
	add.f16x2 	%r1768, %r1764, %r296;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1769, %r1770, %r1771, %r1772}, [%r1616+4224];
	.loc	1 127 23
	add.f16x2 	%r1773, %r1769, %r301;
	add.f16x2 	%r1774, %r1770, %r302;
	add.f16x2 	%r1775, %r1771, %r303;
	add.f16x2 	%r1776, %r1772, %r304;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1777, %r1778, %r1779, %r1780}, [%r1616+8448];
	.loc	1 127 23
	add.f16x2 	%r1781, %r1777, %r309;
	add.f16x2 	%r1782, %r1778, %r310;
	add.f16x2 	%r1783, %r1779, %r311;
	add.f16x2 	%r1784, %r1780, %r312;
	.loc	1 93 22
	ld.shared.v4.b32 	{%r1785, %r1786, %r1787, %r1788}, [%r1616+12672];
	.loc	1 127 23
	add.f16x2 	%r1789, %r1785, %r317;
	add.f16x2 	%r1790, %r1786, %r318;
	add.f16x2 	%r1791, %r1787, %r319;
	add.f16x2 	%r1792, %r1788, %r320;
	.loc	1 129 21
	// begin inline asm
	@%p157 st.global.v4.b32 [ %rd116 + 0 ], { %r1669, %r1670, %r1671, %r1672 };
	// end inline asm
	// begin inline asm
	@%p158 st.global.v4.b32 [ %rd117 + 0 ], { %r1677, %r1678, %r1679, %r1680 };
	// end inline asm
	// begin inline asm
	@%p159 st.global.v4.b32 [ %rd118 + 0 ], { %r1685, %r1686, %r1687, %r1688 };
	// end inline asm
	// begin inline asm
	@%p160 st.global.v4.b32 [ %rd119 + 0 ], { %r1693, %r1694, %r1695, %r1696 };
	// end inline asm
	// begin inline asm
	@%p161 st.global.v4.b32 [ %rd120 + 0 ], { %r1701, %r1702, %r1703, %r1704 };
	// end inline asm
	// begin inline asm
	@%p162 st.global.v4.b32 [ %rd121 + 0 ], { %r1709, %r1710, %r1711, %r1712 };
	// end inline asm
	// begin inline asm
	@%p163 st.global.v4.b32 [ %rd122 + 0 ], { %r1717, %r1718, %r1719, %r1720 };
	// end inline asm
	// begin inline asm
	@%p164 st.global.v4.b32 [ %rd123 + 0 ], { %r1725, %r1726, %r1727, %r1728 };
	// end inline asm
	// begin inline asm
	@%p165 st.global.v4.b32 [ %rd124 + 0 ], { %r1733, %r1734, %r1735, %r1736 };
	// end inline asm
	// begin inline asm
	@%p166 st.global.v4.b32 [ %rd125 + 0 ], { %r1741, %r1742, %r1743, %r1744 };
	// end inline asm
	// begin inline asm
	@%p167 st.global.v4.b32 [ %rd126 + 0 ], { %r1749, %r1750, %r1751, %r1752 };
	// end inline asm
	// begin inline asm
	@%p168 st.global.v4.b32 [ %rd127 + 0 ], { %r1757, %r1758, %r1759, %r1760 };
	// end inline asm
	// begin inline asm
	@%p169 st.global.v4.b32 [ %rd128 + 0 ], { %r1765, %r1766, %r1767, %r1768 };
	// end inline asm
	// begin inline asm
	@%p170 st.global.v4.b32 [ %rd129 + 0 ], { %r1773, %r1774, %r1775, %r1776 };
	// end inline asm
	// begin inline asm
	@%p171 st.global.v4.b32 [ %rd130 + 0 ], { %r1781, %r1782, %r1783, %r1784 };
	// end inline asm
	// begin inline asm
	@%p172 st.global.v4.b32 [ %rd131 + 0 ], { %r1789, %r1790, %r1791, %r1792 };
	// end inline asm
	.loc	1 129 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/PycharmProjects/tritontest/compile_matmul_kernel_accumulate_transpose_a.py"
	.file	2 "/home/mike/PycharmProjects/tritontest/.venv/lib/python3.11/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 211
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 80
.b8 121
.b8 99
.b8 104
.b8 97
.b8 114
.b8 109
.b8 80
.b8 114
.b8 111
.b8 106
.b8 101
.b8 99
.b8 116
.b8 115
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 116
.b8 101
.b8 115
.b8 116
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 104
.b8 4
.b32 104
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 104
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 104
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_3_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_3_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_3_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_3_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_3_FUNCTION_NAME "matmul_kernel_accumulate_transpose_a"
