/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_13_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel_bias_accumulate_transpose_b
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel_bias_accumulate_transpose_b(
	.param .u64 matmul_kernel_bias_accumulate_transpose_b_param_0,
	.param .u64 matmul_kernel_bias_accumulate_transpose_b_param_1,
	.param .u64 matmul_kernel_bias_accumulate_transpose_b_param_2,
	.param .u64 matmul_kernel_bias_accumulate_transpose_b_param_3,
	.param .u32 matmul_kernel_bias_accumulate_transpose_b_param_4,
	.param .u32 matmul_kernel_bias_accumulate_transpose_b_param_5,
	.param .u32 matmul_kernel_bias_accumulate_transpose_b_param_6,
	.param .u32 matmul_kernel_bias_accumulate_transpose_b_param_7,
	.param .u32 matmul_kernel_bias_accumulate_transpose_b_param_8,
	.param .u32 matmul_kernel_bias_accumulate_transpose_b_param_9
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<160>;
	.reg .b16 	%rs<789>;
	.reg .b32 	%r<1798>;
	.reg .b64 	%rd<140>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r197, [matmul_kernel_bias_accumulate_transpose_b_param_6];
	ld.param.u32 	%r196, [matmul_kernel_bias_accumulate_transpose_b_param_5];
	ld.param.u64 	%rd33, [matmul_kernel_bias_accumulate_transpose_b_param_3];
	ld.param.u64 	%rd32, [matmul_kernel_bias_accumulate_transpose_b_param_1];
	ld.param.u64 	%rd31, [matmul_kernel_bias_accumulate_transpose_b_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r198, %ctaid.x;
	// end inline asm
	ld.param.u32 	%r391, [matmul_kernel_bias_accumulate_transpose_b_param_4];
$L__tmp1:
	.loc	2 40 22
	add.s32 	%r392, %r391, 127;
	ld.param.u64 	%rd62, [matmul_kernel_bias_accumulate_transpose_b_param_2];
	.loc	2 40 28
	shr.s32 	%r393, %r392, 31;
	shr.u32 	%r394, %r393, 25;
	add.s32 	%r395, %r392, %r394;
	shr.s32 	%r396, %r395, 7;
$L__tmp2:
	.loc	2 40 22
	add.s32 	%r397, %r196, 255;
	.loc	2 40 28
	shr.s32 	%r398, %r397, 31;
	shr.u32 	%r399, %r398, 24;
	add.s32 	%r400, %r397, %r399;
	shr.s32 	%r401, %r400, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r403, %r401, 3;
	ld.param.u32 	%r404, [matmul_kernel_bias_accumulate_transpose_b_param_7];
	ld.param.u32 	%r405, [matmul_kernel_bias_accumulate_transpose_b_param_8];
	.loc	1 61 22
	div.s32 	%r406, %r198, %r403;
	ld.param.u32 	%r407, [matmul_kernel_bias_accumulate_transpose_b_param_9];
	.loc	1 62 29
	shl.b32 	%r408, %r406, 3;
	.loc	1 63 35
	sub.s32 	%r409, %r396, %r408;
	.loc	1 63 48
	min.s32 	%r410, %r409, 8;
	.loc	1 64 33
	rem.s32 	%r411, %r198, %r410;
	.loc	1 64 27
	add.s32 	%r412, %r408, %r411;
	mul.lo.s32 	%r413, %r406, %r403;
	sub.s32 	%r414, %r198, %r413;
	.loc	1 65 40
	div.s32 	%r415, %r414, %r410;
	.loc	1 74 23
	shl.b32 	%r416, %r412, 7;
	.loc	1 74 51
	mov.u32 	%r1, %tid.x;
	and.b32  	%r2, %r1, 31;
	shr.u32 	%r417, %r1, 2;
	bfe.u32 	%r418, %r1, 2, 6;
	or.b32  	%r419, %r418, 64;
	bfe.u32 	%r3, %r1, 5, 3;
	.loc	1 74 38
	or.b32  	%r420, %r416, %r418;
	or.b32  	%r421, %r416, %r419;
	or.b32  	%r422, %r416, %r3;
	or.b32  	%r423, %r422, 8;
	or.b32  	%r424, %r422, 16;
	or.b32  	%r425, %r422, 24;
	or.b32  	%r426, %r422, 32;
	or.b32  	%r427, %r422, 40;
	or.b32  	%r428, %r422, 48;
	or.b32  	%r429, %r422, 56;
	or.b32  	%r430, %r422, 64;
	or.b32  	%r431, %r422, 72;
	or.b32  	%r432, %r422, 80;
	or.b32  	%r433, %r422, 88;
	or.b32  	%r434, %r422, 96;
	or.b32  	%r435, %r422, 104;
	or.b32  	%r436, %r422, 112;
	or.b32  	%r437, %r422, 120;
	.loc	1 74 68
	rem.s32 	%r438, %r420, %r391;
	rem.s32 	%r439, %r421, %r391;
	.loc	1 75 23
	shl.b32 	%r4, %r415, 8;
	.loc	1 75 51
	shl.b32 	%r440, %r1, 3;
	and.b32  	%r5, %r440, 24;
	and.b32  	%r441, %r440, 248;
	or.b32  	%r442, %r418, 128;
	or.b32  	%r443, %r418, 192;
	.loc	1 75 38
	or.b32  	%r444, %r4, %r441;
	or.b32  	%r445, %r4, %r418;
	or.b32  	%r446, %r4, %r419;
	or.b32  	%r447, %r4, %r442;
	or.b32  	%r448, %r4, %r443;
	.loc	1 75 68
	rem.s32 	%r449, %r445, %r196;
	rem.s32 	%r450, %r446, %r196;
	rem.s32 	%r451, %r447, %r196;
	rem.s32 	%r452, %r448, %r196;
	.loc	1 77 53
	mad.lo.s32 	%r453, %r438, %r404, %r5;
	mad.lo.s32 	%r454, %r439, %r404, %r5;
	.loc	1 77 22
	mul.wide.s32 	%rd63, %r453, 2;
	add.s64 	%rd50, %rd31, %rd63;
	mul.wide.s32 	%rd64, %r454, 2;
	add.s64 	%rd51, %rd31, %rd64;
	.loc	1 78 52
	mad.lo.s32 	%r455, %r449, %r405, %r5;
	mad.lo.s32 	%r456, %r450, %r405, %r5;
	mad.lo.s32 	%r457, %r451, %r405, %r5;
	mad.lo.s32 	%r458, %r452, %r405, %r5;
	.loc	1 78 22
	mul.wide.s32 	%rd65, %r455, 2;
	add.s64 	%rd52, %rd32, %rd65;
	mul.wide.s32 	%rd66, %r456, 2;
	add.s64 	%rd53, %rd32, %rd66;
	mul.wide.s32 	%rd67, %r457, 2;
	add.s64 	%rd54, %rd32, %rd67;
	mul.wide.s32 	%rd68, %r458, 2;
	add.s64 	%rd55, %rd32, %rd68;
	.loc	1 82 33
	mul.lo.s32 	%r459, %r422, %r407;
	shl.b32 	%r460, %r407, 3;
	add.s32 	%r461, %r459, %r460;
	add.s32 	%r462, %r461, %r460;
	add.s32 	%r463, %r462, %r460;
	add.s32 	%r464, %r463, %r460;
	add.s32 	%r465, %r464, %r460;
	add.s32 	%r466, %r465, %r460;
	add.s32 	%r467, %r466, %r460;
	add.s32 	%r468, %r467, %r460;
	add.s32 	%r469, %r468, %r460;
	add.s32 	%r470, %r469, %r460;
	add.s32 	%r471, %r470, %r460;
	add.s32 	%r472, %r471, %r460;
	add.s32 	%r473, %r472, %r460;
	add.s32 	%r474, %r473, %r460;
	add.s32 	%r475, %r474, %r460;
	.loc	1 82 21
	mul.wide.s32 	%rd69, %r459, 2;
	add.s64 	%rd70, %rd62, %rd69;
	mul.wide.s32 	%rd71, %r461, 2;
	add.s64 	%rd72, %rd62, %rd71;
	mul.wide.s32 	%rd73, %r462, 2;
	add.s64 	%rd74, %rd62, %rd73;
	mul.wide.s32 	%rd75, %r463, 2;
	add.s64 	%rd76, %rd62, %rd75;
	mul.wide.s32 	%rd77, %r464, 2;
	add.s64 	%rd78, %rd62, %rd77;
	mul.wide.s32 	%rd79, %r465, 2;
	add.s64 	%rd80, %rd62, %rd79;
	mul.wide.s32 	%rd81, %r466, 2;
	add.s64 	%rd82, %rd62, %rd81;
	mul.wide.s32 	%rd83, %r467, 2;
	add.s64 	%rd84, %rd62, %rd83;
	mul.wide.s32 	%rd85, %r468, 2;
	add.s64 	%rd86, %rd62, %rd85;
	mul.wide.s32 	%rd87, %r469, 2;
	add.s64 	%rd88, %rd62, %rd87;
	mul.wide.s32 	%rd89, %r470, 2;
	add.s64 	%rd90, %rd62, %rd89;
	mul.wide.s32 	%rd91, %r471, 2;
	add.s64 	%rd92, %rd62, %rd91;
	mul.wide.s32 	%rd93, %r472, 2;
	add.s64 	%rd94, %rd62, %rd93;
	mul.wide.s32 	%rd95, %r473, 2;
	add.s64 	%rd96, %rd62, %rd95;
	mul.wide.s32 	%rd97, %r474, 2;
	add.s64 	%rd98, %rd62, %rd97;
	mul.wide.s32 	%rd99, %r475, 2;
	add.s64 	%rd100, %rd62, %rd99;
	.loc	1 82 52
	mul.wide.s32 	%rd101, %r444, 2;
	add.s64 	%rd122, %rd70, %rd101;
	add.s64 	%rd123, %rd72, %rd101;
	add.s64 	%rd124, %rd74, %rd101;
	add.s64 	%rd125, %rd76, %rd101;
	add.s64 	%rd126, %rd78, %rd101;
	add.s64 	%rd127, %rd80, %rd101;
	add.s64 	%rd128, %rd82, %rd101;
	add.s64 	%rd129, %rd84, %rd101;
	add.s64 	%rd130, %rd86, %rd101;
	add.s64 	%rd131, %rd88, %rd101;
	add.s64 	%rd132, %rd90, %rd101;
	add.s64 	%rd133, %rd92, %rd101;
	add.s64 	%rd134, %rd94, %rd101;
	add.s64 	%rd135, %rd96, %rd101;
	add.s64 	%rd136, %rd98, %rd101;
	add.s64 	%rd137, %rd100, %rd101;
	.loc	1 83 33
	setp.lt.s32 	%p109, %r422, %r391;
	setp.lt.s32 	%p110, %r423, %r391;
	setp.lt.s32 	%p111, %r424, %r391;
	setp.lt.s32 	%p112, %r425, %r391;
	setp.lt.s32 	%p113, %r426, %r391;
	setp.lt.s32 	%p114, %r427, %r391;
	setp.lt.s32 	%p115, %r428, %r391;
	setp.lt.s32 	%p116, %r429, %r391;
	setp.lt.s32 	%p117, %r430, %r391;
	setp.lt.s32 	%p118, %r431, %r391;
	setp.lt.s32 	%p119, %r432, %r391;
	setp.lt.s32 	%p120, %r433, %r391;
	setp.lt.s32 	%p121, %r434, %r391;
	setp.lt.s32 	%p122, %r435, %r391;
	setp.lt.s32 	%p123, %r436, %r391;
	setp.lt.s32 	%p124, %r437, %r391;
	.loc	1 83 58
	setp.lt.s32 	%p125, %r444, %r196;
	.loc	1 83 39
	and.pred  	%p144, %p109, %p125;
	and.pred  	%p145, %p110, %p125;
	and.pred  	%p146, %p111, %p125;
	and.pred  	%p147, %p112, %p125;
	and.pred  	%p148, %p113, %p125;
	and.pred  	%p149, %p114, %p125;
	and.pred  	%p150, %p115, %p125;
	and.pred  	%p151, %p116, %p125;
	and.pred  	%p152, %p117, %p125;
	and.pred  	%p153, %p118, %p125;
	and.pred  	%p154, %p119, %p125;
	and.pred  	%p155, %p120, %p125;
	and.pred  	%p156, %p121, %p125;
	and.pred  	%p157, %p122, %p125;
	and.pred  	%p158, %p123, %p125;
	and.pred  	%p159, %p124, %p125;
	mov.b32 	%r1795, 0;
	.loc	1 89 30
	// begin inline asm
	mov.u32 %r199, 0x0;
	mov.u32 %r200, 0x0;
	mov.u32 %r201, 0x0;
	mov.u32 %r202, 0x0;
	@%p144 ld.global.v4.b32 { %r199, %r200, %r201, %r202 }, [ %rd122 + 0 ];
	@!%p144 mov.u32 %r199, %r1795;
	@!%p144 mov.u32 %r200, %r1795;
	@!%p144 mov.u32 %r201, %r1795;
	@!%p144 mov.u32 %r202, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r207, 0x0;
	mov.u32 %r208, 0x0;
	mov.u32 %r209, 0x0;
	mov.u32 %r210, 0x0;
	@%p145 ld.global.v4.b32 { %r207, %r208, %r209, %r210 }, [ %rd123 + 0 ];
	@!%p145 mov.u32 %r207, %r1795;
	@!%p145 mov.u32 %r208, %r1795;
	@!%p145 mov.u32 %r209, %r1795;
	@!%p145 mov.u32 %r210, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r215, 0x0;
	mov.u32 %r216, 0x0;
	mov.u32 %r217, 0x0;
	mov.u32 %r218, 0x0;
	@%p146 ld.global.v4.b32 { %r215, %r216, %r217, %r218 }, [ %rd124 + 0 ];
	@!%p146 mov.u32 %r215, %r1795;
	@!%p146 mov.u32 %r216, %r1795;
	@!%p146 mov.u32 %r217, %r1795;
	@!%p146 mov.u32 %r218, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r223, 0x0;
	mov.u32 %r224, 0x0;
	mov.u32 %r225, 0x0;
	mov.u32 %r226, 0x0;
	@%p147 ld.global.v4.b32 { %r223, %r224, %r225, %r226 }, [ %rd125 + 0 ];
	@!%p147 mov.u32 %r223, %r1795;
	@!%p147 mov.u32 %r224, %r1795;
	@!%p147 mov.u32 %r225, %r1795;
	@!%p147 mov.u32 %r226, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r231, 0x0;
	mov.u32 %r232, 0x0;
	mov.u32 %r233, 0x0;
	mov.u32 %r234, 0x0;
	@%p148 ld.global.v4.b32 { %r231, %r232, %r233, %r234 }, [ %rd126 + 0 ];
	@!%p148 mov.u32 %r231, %r1795;
	@!%p148 mov.u32 %r232, %r1795;
	@!%p148 mov.u32 %r233, %r1795;
	@!%p148 mov.u32 %r234, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r239, 0x0;
	mov.u32 %r240, 0x0;
	mov.u32 %r241, 0x0;
	mov.u32 %r242, 0x0;
	@%p149 ld.global.v4.b32 { %r239, %r240, %r241, %r242 }, [ %rd127 + 0 ];
	@!%p149 mov.u32 %r239, %r1795;
	@!%p149 mov.u32 %r240, %r1795;
	@!%p149 mov.u32 %r241, %r1795;
	@!%p149 mov.u32 %r242, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r247, 0x0;
	mov.u32 %r248, 0x0;
	mov.u32 %r249, 0x0;
	mov.u32 %r250, 0x0;
	@%p150 ld.global.v4.b32 { %r247, %r248, %r249, %r250 }, [ %rd128 + 0 ];
	@!%p150 mov.u32 %r247, %r1795;
	@!%p150 mov.u32 %r248, %r1795;
	@!%p150 mov.u32 %r249, %r1795;
	@!%p150 mov.u32 %r250, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r255, 0x0;
	mov.u32 %r256, 0x0;
	mov.u32 %r257, 0x0;
	mov.u32 %r258, 0x0;
	@%p151 ld.global.v4.b32 { %r255, %r256, %r257, %r258 }, [ %rd129 + 0 ];
	@!%p151 mov.u32 %r255, %r1795;
	@!%p151 mov.u32 %r256, %r1795;
	@!%p151 mov.u32 %r257, %r1795;
	@!%p151 mov.u32 %r258, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r263, 0x0;
	mov.u32 %r264, 0x0;
	mov.u32 %r265, 0x0;
	mov.u32 %r266, 0x0;
	@%p152 ld.global.v4.b32 { %r263, %r264, %r265, %r266 }, [ %rd130 + 0 ];
	@!%p152 mov.u32 %r263, %r1795;
	@!%p152 mov.u32 %r264, %r1795;
	@!%p152 mov.u32 %r265, %r1795;
	@!%p152 mov.u32 %r266, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r271, 0x0;
	mov.u32 %r272, 0x0;
	mov.u32 %r273, 0x0;
	mov.u32 %r274, 0x0;
	@%p153 ld.global.v4.b32 { %r271, %r272, %r273, %r274 }, [ %rd131 + 0 ];
	@!%p153 mov.u32 %r271, %r1795;
	@!%p153 mov.u32 %r272, %r1795;
	@!%p153 mov.u32 %r273, %r1795;
	@!%p153 mov.u32 %r274, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r279, 0x0;
	mov.u32 %r280, 0x0;
	mov.u32 %r281, 0x0;
	mov.u32 %r282, 0x0;
	@%p154 ld.global.v4.b32 { %r279, %r280, %r281, %r282 }, [ %rd132 + 0 ];
	@!%p154 mov.u32 %r279, %r1795;
	@!%p154 mov.u32 %r280, %r1795;
	@!%p154 mov.u32 %r281, %r1795;
	@!%p154 mov.u32 %r282, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r287, 0x0;
	mov.u32 %r288, 0x0;
	mov.u32 %r289, 0x0;
	mov.u32 %r290, 0x0;
	@%p155 ld.global.v4.b32 { %r287, %r288, %r289, %r290 }, [ %rd133 + 0 ];
	@!%p155 mov.u32 %r287, %r1795;
	@!%p155 mov.u32 %r288, %r1795;
	@!%p155 mov.u32 %r289, %r1795;
	@!%p155 mov.u32 %r290, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r295, 0x0;
	mov.u32 %r296, 0x0;
	mov.u32 %r297, 0x0;
	mov.u32 %r298, 0x0;
	@%p156 ld.global.v4.b32 { %r295, %r296, %r297, %r298 }, [ %rd134 + 0 ];
	@!%p156 mov.u32 %r295, %r1795;
	@!%p156 mov.u32 %r296, %r1795;
	@!%p156 mov.u32 %r297, %r1795;
	@!%p156 mov.u32 %r298, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r303, 0x0;
	mov.u32 %r304, 0x0;
	mov.u32 %r305, 0x0;
	mov.u32 %r306, 0x0;
	@%p157 ld.global.v4.b32 { %r303, %r304, %r305, %r306 }, [ %rd135 + 0 ];
	@!%p157 mov.u32 %r303, %r1795;
	@!%p157 mov.u32 %r304, %r1795;
	@!%p157 mov.u32 %r305, %r1795;
	@!%p157 mov.u32 %r306, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r311, 0x0;
	mov.u32 %r312, 0x0;
	mov.u32 %r313, 0x0;
	mov.u32 %r314, 0x0;
	@%p158 ld.global.v4.b32 { %r311, %r312, %r313, %r314 }, [ %rd136 + 0 ];
	@!%p158 mov.u32 %r311, %r1795;
	@!%p158 mov.u32 %r312, %r1795;
	@!%p158 mov.u32 %r313, %r1795;
	@!%p158 mov.u32 %r314, %r1795;
	// end inline asm
	// begin inline asm
	mov.u32 %r319, 0x0;
	mov.u32 %r320, 0x0;
	mov.u32 %r321, 0x0;
	mov.u32 %r322, 0x0;
	@%p159 ld.global.v4.b32 { %r319, %r320, %r321, %r322 }, [ %rd137 + 0 ];
	@!%p159 mov.u32 %r319, %r1795;
	@!%p159 mov.u32 %r320, %r1795;
	@!%p159 mov.u32 %r321, %r1795;
	@!%p159 mov.u32 %r322, %r1795;
	// end inline asm
$L__tmp4:
	.loc	2 40 22
	add.s32 	%r476, %r197, 31;
$L__tmp5:
	.loc	1 93 22
	setp.lt.s32 	%p126, %r476, 32;
	setp.gt.s32 	%p127, %r476, 31;
	.loc	1 96 72
	setp.lt.s32 	%p128, %r5, %r197;
	.loc	1 96 20
	xor.b32  	%r480, %r440, %r1;
	and.b32  	%r481, %r480, 24;
	shl.b32 	%r482, %r418, 5;
	or.b32  	%r71, %r482, %r481;
	shl.b32 	%r483, %r71, 1;
	mov.u32 	%r484, global_smem;
	add.s32 	%r327, %r484, %r483;
	shl.b32 	%r485, %r419, 5;
	or.b32  	%r72, %r485, %r481;
	shl.b32 	%r486, %r72, 1;
	add.s32 	%r329, %r484, %r486;
	selp.b32 	%r487, 16, 0, %p127;
	selp.b32 	%r330, %r487, 0, %p128;
	mov.pred 	%p97, -1;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r327 + 0 ], [ %rd50 + 0 ], 0x10, %r330;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r329 + 0 ], [ %rd51 + 0 ], 0x10, %r330;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	add.s32 	%r488, %r484, 16384;
	add.s32 	%r331, %r488, %r483;
	add.s32 	%r333, %r488, %r486;
	shl.b32 	%r489, %r442, 5;
	or.b32  	%r73, %r489, %r481;
	shl.b32 	%r490, %r73, 1;
	add.s32 	%r335, %r488, %r490;
	shl.b32 	%r491, %r443, 5;
	or.b32  	%r74, %r491, %r481;
	shl.b32 	%r492, %r74, 1;
	add.s32 	%r337, %r488, %r492;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r331 + 0 ], [ %rd52 + 0 ], 0x10, %r330;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r333 + 0 ], [ %rd53 + 0 ], 0x10, %r330;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r335 + 0 ], [ %rd54 + 0 ], 0x10, %r330;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r337 + 0 ], [ %rd55 + 0 ], 0x10, %r330;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p129, %r476, 63;
	.loc	1 102 18
	add.s64 	%rd56, %rd50, 64;
	add.s64 	%rd57, %rd51, 64;
	.loc	1 103 18
	add.s64 	%rd58, %rd52, 64;
	add.s64 	%rd59, %rd53, 64;
	add.s64 	%rd60, %rd54, 64;
	add.s64 	%rd61, %rd55, 64;
	.loc	1 96 53
	or.b32  	%r493, %r5, 32;
	.loc	1 96 72
	setp.lt.s32 	%p130, %r493, %r197;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r494, %r484, 8192;
	add.s32 	%r339, %r494, %r483;
	add.s32 	%r341, %r494, %r486;
	selp.b32 	%r495, 16, 0, %p129;
	selp.b32 	%r342, %r495, 0, %p130;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r339 + 0 ], [ %rd56 + 0 ], 0x10, %r342;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r341 + 0 ], [ %rd57 + 0 ], 0x10, %r342;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	add.s32 	%r496, %r484, 32768;
	add.s32 	%r343, %r496, %r483;
	add.s32 	%r345, %r496, %r486;
	add.s32 	%r347, %r496, %r490;
	add.s32 	%r349, %r496, %r492;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r343 + 0 ], [ %rd58 + 0 ], 0x10, %r342;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r345 + 0 ], [ %rd59 + 0 ], 0x10, %r342;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r347 + 0 ], [ %rd60 + 0 ], 0x10, %r342;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r349 + 0 ], [ %rd61 + 0 ], 0x10, %r342;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	and.b32  	%r497, %r1, 7;
	shr.u32 	%r498, %r1, 3;
	bfe.u32 	%r75, %r1, 3, 1;
	bfe.u32 	%r76, %r1, 4, 1;
	bfe.u32 	%r77, %r1, 1, 2;
	and.b32  	%r78, %r498, 16;
	shl.b32 	%r499, %r75, 3;
	or.b32  	%r500, %r499, %r78;
	or.b32  	%r501, %r500, %r497;
	xor.b32  	%r502, %r76, %r77;
	shl.b32 	%r503, %r502, 3;
	shl.b32 	%r79, %r501, 5;
	or.b32  	%r80, %r79, %r503;
	shl.b32 	%r504, %r80, 1;
	add.s32 	%r355, %r484, %r504;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1789, %r1790, %r1791, %r1792 }, [ %r355 + 0 ];
	// end inline asm
	add.s32 	%r360, %r355, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1785, %r1786, %r1787, %r1788 }, [ %r360 + 0 ];
	// end inline asm
	add.s32 	%r365, %r355, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1781, %r1782, %r1783, %r1784 }, [ %r365 + 0 ];
	// end inline asm
	add.s32 	%r370, %r355, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1777, %r1778, %r1779, %r1780 }, [ %r370 + 0 ];
	// end inline asm
	.loc	1 97 20
	shl.b32 	%r505, %r76, 5;
	and.b32  	%r97, %r417, 24;
	or.b32  	%r506, %r505, %r97;
	or.b32  	%r507, %r506, %r497;
	xor.b32  	%r508, %r75, %r77;
	shl.b32 	%r509, %r508, 3;
	shl.b32 	%r98, %r507, 5;
	or.b32  	%r99, %r98, %r509;
	shl.b32 	%r510, %r99, 1;
	add.s32 	%r375, %r488, %r510;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1773, %r1774, %r1775, %r1776 }, [ %r375 + 0 ];
	// end inline asm
	add.s32 	%r380, %r375, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1769, %r1770, %r1771, %r1772 }, [ %r380 + 0 ];
	// end inline asm
	add.s32 	%r385, %r375, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1765, %r1766, %r1767, %r1768 }, [ %r385 + 0 ];
	// end inline asm
	add.s32 	%r390, %r375, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1761, %r1762, %r1763, %r1764 }, [ %r390 + 0 ];
	// end inline asm
	mov.b16 	%rs661, 0x0000;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	.loc	1 93 22
	@%p126 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd1, %r453;
	cvt.s64.s32 	%rd2, %r454;
	cvt.s64.s32 	%rd3, %r455;
	cvt.s64.s32 	%rd4, %r456;
	cvt.s64.s32 	%rd5, %r457;
	cvt.s64.s32 	%rd6, %r458;
	shr.s32 	%r477, %r476, 31;
	shr.u32 	%r478, %r477, 27;
	add.s32 	%r479, %r476, %r478;
	shr.s32 	%r70, %r479, 5;
	add.s32 	%r116, %r70, -2;
	or.b32  	%r515, %r76, 2;
	xor.b32  	%r516, %r515, %r77;
	shl.b32 	%r517, %r516, 3;
	or.b32  	%r518, %r75, 2;
	xor.b32  	%r519, %r518, %r77;
	shl.b32 	%r520, %r519, 3;
	or.b32  	%r117, %r79, %r517;
	or.b32  	%r118, %r98, %r520;
	.loc	1 93 22
	shl.b64 	%rd103, %rd6, 1;
	add.s64 	%rd104, %rd103, %rd32;
	add.s64 	%rd23, %rd104, 128;
	shl.b64 	%rd105, %rd5, 1;
	add.s64 	%rd106, %rd105, %rd32;
	add.s64 	%rd24, %rd106, 128;
	shl.b64 	%rd107, %rd4, 1;
	add.s64 	%rd108, %rd107, %rd32;
	add.s64 	%rd25, %rd108, 128;
	shl.b64 	%rd109, %rd3, 1;
	add.s64 	%rd110, %rd109, %rd32;
	add.s64 	%rd26, %rd110, 128;
	shl.b64 	%rd111, %rd2, 1;
	add.s64 	%rd112, %rd111, %rd31;
	add.s64 	%rd27, %rd112, 128;
	shl.b64 	%rd113, %rd1, 1;
	add.s64 	%rd114, %rd113, %rd31;
	add.s64 	%rd28, %rd114, 128;
	or.b32  	%r1760, %r5, 64;
	mov.b16 	%rs661, 0x0000;
	mov.b32 	%r1796, 1;
	mov.u64 	%rd139, 0;
	shl.b32 	%r1253, %r117, 1;
	shl.b32 	%r1254, %r118, 1;
	mov.u32 	%r1793, %r488;
	mov.u32 	%r1794, %r484;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	mov.u32 	%r1797, %r1795;
$L__BB0_2:
	setp.lt.s32 	%p137, %r1797, %r116;
	.loc	1 96 20
	add.s32 	%r525, %r1794, %r1253;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r937, %r938, %r939, %r940 }, [ %r525 + 0 ];
	// end inline asm
	add.s32 	%r530, %r525, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1017, %r1018, %r1019, %r1020 }, [ %r530 + 0 ];
	// end inline asm
	add.s32 	%r535, %r525, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1097, %r1098, %r1099, %r1100 }, [ %r535 + 0 ];
	// end inline asm
	add.s32 	%r540, %r525, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1177, %r1178, %r1179, %r1180 }, [ %r540 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r545, %r1793, %r1254;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r941, %r942, %r951, %r952 }, [ %r545 + 0 ];
	// end inline asm
	add.s32 	%r550, %r545, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r961, %r962, %r971, %r972 }, [ %r550 + 0 ];
	// end inline asm
	add.s32 	%r555, %r545, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r981, %r982, %r991, %r992 }, [ %r555 + 0 ];
	// end inline asm
	add.s32 	%r560, %r545, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1001, %r1002, %r1011, %r1012 }, [ %r560 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r933, {%rs661, %rs662};
	mov.b32 	%r934, {%rs663, %rs664};
	mov.b32 	%r943, {%rs665, %rs666};
	mov.b32 	%r944, {%rs667, %rs668};
	mov.b32 	%r953, {%rs669, %rs670};
	mov.b32 	%r954, {%rs671, %rs672};
	mov.b32 	%r963, {%rs673, %rs674};
	mov.b32 	%r964, {%rs675, %rs676};
	mov.b32 	%r973, {%rs677, %rs678};
	mov.b32 	%r974, {%rs679, %rs680};
	mov.b32 	%r983, {%rs681, %rs682};
	mov.b32 	%r984, {%rs683, %rs684};
	mov.b32 	%r993, {%rs685, %rs686};
	mov.b32 	%r994, {%rs687, %rs688};
	mov.b32 	%r1003, {%rs689, %rs690};
	mov.b32 	%r1004, {%rs691, %rs692};
	mov.b32 	%r1013, {%rs693, %rs694};
	mov.b32 	%r1014, {%rs695, %rs696};
	mov.b32 	%r1023, {%rs697, %rs698};
	mov.b32 	%r1024, {%rs699, %rs700};
	mov.b32 	%r1033, {%rs701, %rs702};
	mov.b32 	%r1034, {%rs703, %rs704};
	mov.b32 	%r1043, {%rs705, %rs706};
	mov.b32 	%r1044, {%rs707, %rs708};
	mov.b32 	%r1053, {%rs709, %rs710};
	mov.b32 	%r1054, {%rs711, %rs712};
	mov.b32 	%r1063, {%rs713, %rs714};
	mov.b32 	%r1064, {%rs715, %rs716};
	mov.b32 	%r1073, {%rs717, %rs718};
	mov.b32 	%r1074, {%rs719, %rs720};
	mov.b32 	%r1083, {%rs721, %rs722};
	mov.b32 	%r1084, {%rs723, %rs724};
	mov.b32 	%r1093, {%rs725, %rs726};
	mov.b32 	%r1094, {%rs727, %rs728};
	mov.b32 	%r1103, {%rs729, %rs730};
	mov.b32 	%r1104, {%rs731, %rs732};
	mov.b32 	%r1113, {%rs733, %rs734};
	mov.b32 	%r1114, {%rs735, %rs736};
	mov.b32 	%r1123, {%rs737, %rs738};
	mov.b32 	%r1124, {%rs739, %rs740};
	mov.b32 	%r1133, {%rs741, %rs742};
	mov.b32 	%r1134, {%rs743, %rs744};
	mov.b32 	%r1143, {%rs745, %rs746};
	mov.b32 	%r1144, {%rs747, %rs748};
	mov.b32 	%r1153, {%rs749, %rs750};
	mov.b32 	%r1154, {%rs751, %rs752};
	mov.b32 	%r1163, {%rs753, %rs754};
	mov.b32 	%r1164, {%rs755, %rs756};
	mov.b32 	%r1173, {%rs757, %rs758};
	mov.b32 	%r1174, {%rs759, %rs760};
	mov.b32 	%r1183, {%rs761, %rs762};
	mov.b32 	%r1184, {%rs763, %rs764};
	mov.b32 	%r1193, {%rs765, %rs766};
	mov.b32 	%r1194, {%rs767, %rs768};
	mov.b32 	%r1203, {%rs769, %rs770};
	mov.b32 	%r1204, {%rs771, %rs772};
	mov.b32 	%r1213, {%rs773, %rs774};
	mov.b32 	%r1214, {%rs775, %rs776};
	mov.b32 	%r1223, {%rs777, %rs778};
	mov.b32 	%r1224, {%rs779, %rs780};
	mov.b32 	%r1233, {%rs781, %rs782};
	mov.b32 	%r1234, {%rs783, %rs784};
	mov.b32 	%r1243, {%rs785, %rs786};
	mov.b32 	%r1244, {%rs787, %rs788};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r933, %r934 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1773, %r1774 }, { %r933, %r934 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r943, %r944 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1775, %r1776 }, { %r943, %r944 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r953, %r954 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1769, %r1770 }, { %r953, %r954 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r963, %r964 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1771, %r1772 }, { %r963, %r964 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r973, %r974 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1765, %r1766 }, { %r973, %r974 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r983, %r984 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1767, %r1768 }, { %r983, %r984 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r993, %r994 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1761, %r1762 }, { %r993, %r994 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1003, %r1004 }, { %r1789, %r1790, %r1791, %r1792 }, { %r1763, %r1764 }, { %r1003, %r1004 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1013, %r1014 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1773, %r1774 }, { %r1013, %r1014 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1023, %r1024 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1775, %r1776 }, { %r1023, %r1024 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1033, %r1034 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1769, %r1770 }, { %r1033, %r1034 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1043, %r1044 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1771, %r1772 }, { %r1043, %r1044 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1053, %r1054 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1765, %r1766 }, { %r1053, %r1054 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1063, %r1064 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1767, %r1768 }, { %r1063, %r1064 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1073, %r1074 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1761, %r1762 }, { %r1073, %r1074 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1083, %r1084 }, { %r1785, %r1786, %r1787, %r1788 }, { %r1763, %r1764 }, { %r1083, %r1084 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1093, %r1094 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1773, %r1774 }, { %r1093, %r1094 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1103, %r1104 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1775, %r1776 }, { %r1103, %r1104 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1113, %r1114 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1769, %r1770 }, { %r1113, %r1114 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1123, %r1124 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1771, %r1772 }, { %r1123, %r1124 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1133, %r1134 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1765, %r1766 }, { %r1133, %r1134 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1143, %r1144 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1767, %r1768 }, { %r1143, %r1144 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1153, %r1154 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1761, %r1762 }, { %r1153, %r1154 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1163, %r1164 }, { %r1781, %r1782, %r1783, %r1784 }, { %r1763, %r1764 }, { %r1163, %r1164 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1173, %r1174 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1773, %r1774 }, { %r1173, %r1174 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1183, %r1184 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1775, %r1776 }, { %r1183, %r1184 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1193, %r1194 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1769, %r1770 }, { %r1193, %r1194 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1203, %r1204 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1771, %r1772 }, { %r1203, %r1204 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1213, %r1214 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1765, %r1766 }, { %r1213, %r1214 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1223, %r1224 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1767, %r1768 }, { %r1223, %r1224 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1233, %r1234 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1761, %r1762 }, { %r1233, %r1234 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1243, %r1244 }, { %r1777, %r1778, %r1779, %r1780 }, { %r1763, %r1764 }, { %r1243, %r1244 };
	// end inline asm
	.loc	1 102 18
	add.s64 	%rd115, %rd28, %rd139;
	.loc	1 103 18
	add.s64 	%rd116, %rd27, %rd139;
	add.s64 	%rd117, %rd26, %rd139;
	add.s64 	%rd118, %rd25, %rd139;
	add.s64 	%rd119, %rd24, %rd139;
	.loc	1 93 22
	add.s64 	%rd120, %rd23, %rd139;
	add.s32 	%r1319, %r1796, 1;
	setp.lt.s32 	%p138, %r1319, 2;
	selp.b32 	%r1796, %r1319, 0, %p138;
	.loc	1 96 72
	setp.lt.s32 	%p139, %r1760, %r197;
	.loc	1 96 20
	shl.b32 	%r1320, %r1796, 13;
	add.s32 	%r1322, %r484, %r1320;
	bar.sync 	0;
	add.s32 	%r881, %r1322, %r483;
	add.s32 	%r883, %r1322, %r486;
	selp.b32 	%r1325, 16, 0, %p139;
	selp.b32 	%r884, %r1325, 0, %p137;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r881 + 0 ], [ %rd115 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r883 + 0 ], [ %rd116 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	shl.b32 	%r1326, %r1796, 14;
	add.s32 	%r1328, %r488, %r1326;
	add.s32 	%r885, %r1328, %r483;
	add.s32 	%r887, %r1328, %r486;
	add.s32 	%r889, %r1328, %r490;
	add.s32 	%r891, %r1328, %r492;
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r885 + 0 ], [ %rd117 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r887 + 0 ], [ %rd118 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r889 + 0 ], [ %rd119 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	@%p97 cp.async.cg.shared.global [ %r891 + 0 ], [ %rd120 + 0 ], 0x10, %r884;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1331, %r1795, 1;
	setp.lt.s32 	%p140, %r1331, 2;
	selp.b32 	%r1795, %r1331, 0, %p140;
	.loc	1 96 20
	shl.b32 	%r1332, %r1795, 13;
	add.s32 	%r1794, %r484, %r1332;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1333, %r1795, 14;
	add.s32 	%r1793, %r488, %r1333;
	.loc	1 96 20
	add.s32 	%r897, %r1794, %r504;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1789, %r1790, %r1791, %r1792 }, [ %r897 + 0 ];
	// end inline asm
	add.s32 	%r902, %r897, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1785, %r1786, %r1787, %r1788 }, [ %r902 + 0 ];
	// end inline asm
	add.s32 	%r907, %r897, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1781, %r1782, %r1783, %r1784 }, [ %r907 + 0 ];
	// end inline asm
	add.s32 	%r912, %r897, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1777, %r1778, %r1779, %r1780 }, [ %r912 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r917, %r1793, %r510;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1773, %r1774, %r1775, %r1776 }, [ %r917 + 0 ];
	// end inline asm
	add.s32 	%r922, %r917, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1769, %r1770, %r1771, %r1772 }, [ %r922 + 0 ];
	// end inline asm
	add.s32 	%r927, %r917, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1765, %r1766, %r1767, %r1768 }, [ %r927 + 0 ];
	// end inline asm
	add.s32 	%r932, %r917, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1761, %r1762, %r1763, %r1764 }, [ %r932 + 0 ];
	// end inline asm
	.loc	1 100 35
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r933, %r934 }, { %r937, %r938, %r939, %r940 }, { %r941, %r942 }, { %r933, %r934 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r943, %r944 }, { %r937, %r938, %r939, %r940 }, { %r951, %r952 }, { %r943, %r944 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r953, %r954 }, { %r937, %r938, %r939, %r940 }, { %r961, %r962 }, { %r953, %r954 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r963, %r964 }, { %r937, %r938, %r939, %r940 }, { %r971, %r972 }, { %r963, %r964 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r973, %r974 }, { %r937, %r938, %r939, %r940 }, { %r981, %r982 }, { %r973, %r974 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r983, %r984 }, { %r937, %r938, %r939, %r940 }, { %r991, %r992 }, { %r983, %r984 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r993, %r994 }, { %r937, %r938, %r939, %r940 }, { %r1001, %r1002 }, { %r993, %r994 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1003, %r1004 }, { %r937, %r938, %r939, %r940 }, { %r1011, %r1012 }, { %r1003, %r1004 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1013, %r1014 }, { %r1017, %r1018, %r1019, %r1020 }, { %r941, %r942 }, { %r1013, %r1014 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1023, %r1024 }, { %r1017, %r1018, %r1019, %r1020 }, { %r951, %r952 }, { %r1023, %r1024 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1033, %r1034 }, { %r1017, %r1018, %r1019, %r1020 }, { %r961, %r962 }, { %r1033, %r1034 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1043, %r1044 }, { %r1017, %r1018, %r1019, %r1020 }, { %r971, %r972 }, { %r1043, %r1044 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1053, %r1054 }, { %r1017, %r1018, %r1019, %r1020 }, { %r981, %r982 }, { %r1053, %r1054 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1063, %r1064 }, { %r1017, %r1018, %r1019, %r1020 }, { %r991, %r992 }, { %r1063, %r1064 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1073, %r1074 }, { %r1017, %r1018, %r1019, %r1020 }, { %r1001, %r1002 }, { %r1073, %r1074 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1083, %r1084 }, { %r1017, %r1018, %r1019, %r1020 }, { %r1011, %r1012 }, { %r1083, %r1084 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1093, %r1094 }, { %r1097, %r1098, %r1099, %r1100 }, { %r941, %r942 }, { %r1093, %r1094 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1103, %r1104 }, { %r1097, %r1098, %r1099, %r1100 }, { %r951, %r952 }, { %r1103, %r1104 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1113, %r1114 }, { %r1097, %r1098, %r1099, %r1100 }, { %r961, %r962 }, { %r1113, %r1114 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1123, %r1124 }, { %r1097, %r1098, %r1099, %r1100 }, { %r971, %r972 }, { %r1123, %r1124 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1133, %r1134 }, { %r1097, %r1098, %r1099, %r1100 }, { %r981, %r982 }, { %r1133, %r1134 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1143, %r1144 }, { %r1097, %r1098, %r1099, %r1100 }, { %r991, %r992 }, { %r1143, %r1144 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1153, %r1154 }, { %r1097, %r1098, %r1099, %r1100 }, { %r1001, %r1002 }, { %r1153, %r1154 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1163, %r1164 }, { %r1097, %r1098, %r1099, %r1100 }, { %r1011, %r1012 }, { %r1163, %r1164 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1173, %r1174 }, { %r1177, %r1178, %r1179, %r1180 }, { %r941, %r942 }, { %r1173, %r1174 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1183, %r1184 }, { %r1177, %r1178, %r1179, %r1180 }, { %r951, %r952 }, { %r1183, %r1184 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1193, %r1194 }, { %r1177, %r1178, %r1179, %r1180 }, { %r961, %r962 }, { %r1193, %r1194 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1203, %r1204 }, { %r1177, %r1178, %r1179, %r1180 }, { %r971, %r972 }, { %r1203, %r1204 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1213, %r1214 }, { %r1177, %r1178, %r1179, %r1180 }, { %r981, %r982 }, { %r1213, %r1214 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1223, %r1224 }, { %r1177, %r1178, %r1179, %r1180 }, { %r991, %r992 }, { %r1223, %r1224 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1233, %r1234 }, { %r1177, %r1178, %r1179, %r1180 }, { %r1001, %r1002 }, { %r1233, %r1234 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1243, %r1244 }, { %r1177, %r1178, %r1179, %r1180 }, { %r1011, %r1012 }, { %r1243, %r1244 };
	// end inline asm
	mov.b32 	{%rs661, %rs662}, %r933;
	mov.b32 	{%rs663, %rs664}, %r934;
	mov.b32 	{%rs665, %rs666}, %r943;
	mov.b32 	{%rs667, %rs668}, %r944;
	mov.b32 	{%rs669, %rs670}, %r953;
	mov.b32 	{%rs671, %rs672}, %r954;
	mov.b32 	{%rs673, %rs674}, %r963;
	mov.b32 	{%rs675, %rs676}, %r964;
	mov.b32 	{%rs677, %rs678}, %r973;
	mov.b32 	{%rs679, %rs680}, %r974;
	mov.b32 	{%rs681, %rs682}, %r983;
	mov.b32 	{%rs683, %rs684}, %r984;
	mov.b32 	{%rs685, %rs686}, %r993;
	mov.b32 	{%rs687, %rs688}, %r994;
	mov.b32 	{%rs689, %rs690}, %r1003;
	mov.b32 	{%rs691, %rs692}, %r1004;
	mov.b32 	{%rs693, %rs694}, %r1013;
	mov.b32 	{%rs695, %rs696}, %r1014;
	mov.b32 	{%rs697, %rs698}, %r1023;
	mov.b32 	{%rs699, %rs700}, %r1024;
	mov.b32 	{%rs701, %rs702}, %r1033;
	mov.b32 	{%rs703, %rs704}, %r1034;
	mov.b32 	{%rs705, %rs706}, %r1043;
	mov.b32 	{%rs707, %rs708}, %r1044;
	mov.b32 	{%rs709, %rs710}, %r1053;
	mov.b32 	{%rs711, %rs712}, %r1054;
	mov.b32 	{%rs713, %rs714}, %r1063;
	mov.b32 	{%rs715, %rs716}, %r1064;
	mov.b32 	{%rs717, %rs718}, %r1073;
	mov.b32 	{%rs719, %rs720}, %r1074;
	mov.b32 	{%rs721, %rs722}, %r1083;
	mov.b32 	{%rs723, %rs724}, %r1084;
	mov.b32 	{%rs725, %rs726}, %r1093;
	mov.b32 	{%rs727, %rs728}, %r1094;
	mov.b32 	{%rs729, %rs730}, %r1103;
	mov.b32 	{%rs731, %rs732}, %r1104;
	mov.b32 	{%rs733, %rs734}, %r1113;
	mov.b32 	{%rs735, %rs736}, %r1114;
	mov.b32 	{%rs737, %rs738}, %r1123;
	mov.b32 	{%rs739, %rs740}, %r1124;
	mov.b32 	{%rs741, %rs742}, %r1133;
	mov.b32 	{%rs743, %rs744}, %r1134;
	mov.b32 	{%rs745, %rs746}, %r1143;
	mov.b32 	{%rs747, %rs748}, %r1144;
	mov.b32 	{%rs749, %rs750}, %r1153;
	mov.b32 	{%rs751, %rs752}, %r1154;
	mov.b32 	{%rs753, %rs754}, %r1163;
	mov.b32 	{%rs755, %rs756}, %r1164;
	mov.b32 	{%rs757, %rs758}, %r1173;
	mov.b32 	{%rs759, %rs760}, %r1174;
	mov.b32 	{%rs761, %rs762}, %r1183;
	mov.b32 	{%rs763, %rs764}, %r1184;
	mov.b32 	{%rs765, %rs766}, %r1193;
	mov.b32 	{%rs767, %rs768}, %r1194;
	mov.b32 	{%rs769, %rs770}, %r1203;
	mov.b32 	{%rs771, %rs772}, %r1204;
	mov.b32 	{%rs773, %rs774}, %r1213;
	mov.b32 	{%rs775, %rs776}, %r1214;
	mov.b32 	{%rs777, %rs778}, %r1223;
	mov.b32 	{%rs779, %rs780}, %r1224;
	mov.b32 	{%rs781, %rs782}, %r1233;
	mov.b32 	{%rs783, %rs784}, %r1234;
	mov.b32 	{%rs785, %rs786}, %r1243;
	mov.b32 	{%rs787, %rs788}, %r1244;
	.loc	1 93 22
	add.s32 	%r1797, %r1797, 1;
	add.s64 	%rd139, %rd139, 64;
	add.s32 	%r1760, %r1760, 32;
	setp.lt.s32 	%p141, %r1797, %r70;
	@%p141 bra 	$L__BB0_2;
$L__BB0_3:
	.loc	1 75 51
	and.b32  	%r1528, %r1, 255;
	.loc	1 75 38
	or.b32  	%r1529, %r4, %r1528;
	.loc	1 93 22
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	.loc	1 107 31
	mul.wide.s32 	%rd138, %r1529, 2;
	add.s64 	%rd121, %rd33, %rd138;
	.loc	1 108 32
	setp.lt.s32 	%p142, %r1529, %r196;
	mov.u16 	%rs388, 0;
	.loc	1 109 23
	// begin inline asm
	mov.u16 %rs387, 0x0;
	@%p142 ld.global.b16 { %rs387 }, [ %rd121 + 0 ];
	@!%p142 mov.u16 %rs387, %rs388;
	// end inline asm
	.loc	1 110 30
	shl.b32 	%r1530, %r1528, 1;
	add.s32 	%r1532, %r484, %r1530;
	st.shared.u16 	[%r1532], %rs387;
	bar.sync 	0;
	shl.b32 	%r1533, %r1, 1;
	and.b32  	%r1534, %r1533, 6;
	or.b32  	%r1535, %r97, %r1534;
	shl.b32 	%r1536, %r1535, 1;
	add.s32 	%r1537, %r484, %r1536;
	ld.shared.b32 	%r1538, [%r1537];
	mov.b32 	{%rs389, %rs390}, %r1538;
	add.s32 	%r1539, %r1537, 64;
	ld.shared.b32 	%r1540, [%r1537+64];
	mov.b32 	{%rs391, %rs392}, %r1540;
	add.s32 	%r1541, %r1537, 128;
	ld.shared.b32 	%r1542, [%r1537+128];
	mov.b32 	{%rs393, %rs394}, %r1542;
	add.s32 	%r1543, %r1537, 192;
	ld.shared.b32 	%r1544, [%r1537+192];
	mov.b32 	{%rs395, %rs396}, %r1544;
	add.s32 	%r1545, %r1537, 256;
	ld.shared.b32 	%r1546, [%r1537+256];
	mov.b32 	{%rs397, %rs398}, %r1546;
	add.s32 	%r1547, %r1537, 320;
	ld.shared.b32 	%r1548, [%r1537+320];
	mov.b32 	{%rs399, %rs400}, %r1548;
	add.s32 	%r1549, %r1537, 384;
	ld.shared.b32 	%r1550, [%r1537+384];
	mov.b32 	{%rs401, %rs402}, %r1550;
	add.s32 	%r1551, %r1537, 448;
	ld.shared.b32 	%r1552, [%r1537+448];
	mov.b32 	{%rs403, %rs404}, %r1552;
	.loc	1 111 23
	add.f16 	%rs405, %rs661, %rs389;
	add.f16 	%rs406, %rs662, %rs390;
	add.f16 	%rs407, %rs663, %rs389;
	add.f16 	%rs408, %rs664, %rs390;
	add.f16 	%rs409, %rs665, %rs391;
	add.f16 	%rs410, %rs666, %rs392;
	add.f16 	%rs411, %rs667, %rs391;
	add.f16 	%rs412, %rs668, %rs392;
	add.f16 	%rs413, %rs669, %rs393;
	add.f16 	%rs414, %rs670, %rs394;
	add.f16 	%rs415, %rs671, %rs393;
	add.f16 	%rs416, %rs672, %rs394;
	add.f16 	%rs417, %rs673, %rs395;
	add.f16 	%rs418, %rs674, %rs396;
	add.f16 	%rs419, %rs675, %rs395;
	add.f16 	%rs420, %rs676, %rs396;
	add.f16 	%rs421, %rs677, %rs397;
	add.f16 	%rs422, %rs678, %rs398;
	add.f16 	%rs423, %rs679, %rs397;
	add.f16 	%rs424, %rs680, %rs398;
	add.f16 	%rs425, %rs681, %rs399;
	add.f16 	%rs426, %rs682, %rs400;
	add.f16 	%rs427, %rs683, %rs399;
	add.f16 	%rs428, %rs684, %rs400;
	add.f16 	%rs429, %rs685, %rs401;
	add.f16 	%rs430, %rs686, %rs402;
	add.f16 	%rs431, %rs687, %rs401;
	add.f16 	%rs432, %rs688, %rs402;
	add.f16 	%rs433, %rs689, %rs403;
	add.f16 	%rs434, %rs690, %rs404;
	add.f16 	%rs435, %rs691, %rs403;
	add.f16 	%rs436, %rs692, %rs404;
	add.f16 	%rs437, %rs693, %rs389;
	add.f16 	%rs438, %rs694, %rs390;
	add.f16 	%rs439, %rs695, %rs389;
	add.f16 	%rs440, %rs696, %rs390;
	add.f16 	%rs441, %rs697, %rs391;
	add.f16 	%rs442, %rs698, %rs392;
	add.f16 	%rs443, %rs699, %rs391;
	add.f16 	%rs444, %rs700, %rs392;
	add.f16 	%rs445, %rs701, %rs393;
	add.f16 	%rs446, %rs702, %rs394;
	add.f16 	%rs447, %rs703, %rs393;
	add.f16 	%rs448, %rs704, %rs394;
	add.f16 	%rs449, %rs705, %rs395;
	add.f16 	%rs450, %rs706, %rs396;
	add.f16 	%rs451, %rs707, %rs395;
	add.f16 	%rs452, %rs708, %rs396;
	add.f16 	%rs453, %rs709, %rs397;
	add.f16 	%rs454, %rs710, %rs398;
	add.f16 	%rs455, %rs711, %rs397;
	add.f16 	%rs456, %rs712, %rs398;
	add.f16 	%rs457, %rs713, %rs399;
	add.f16 	%rs458, %rs714, %rs400;
	add.f16 	%rs459, %rs715, %rs399;
	add.f16 	%rs460, %rs716, %rs400;
	add.f16 	%rs461, %rs717, %rs401;
	add.f16 	%rs462, %rs718, %rs402;
	add.f16 	%rs463, %rs719, %rs401;
	add.f16 	%rs464, %rs720, %rs402;
	add.f16 	%rs465, %rs721, %rs403;
	add.f16 	%rs466, %rs722, %rs404;
	add.f16 	%rs467, %rs723, %rs403;
	add.f16 	%rs468, %rs724, %rs404;
	add.f16 	%rs469, %rs725, %rs389;
	add.f16 	%rs470, %rs726, %rs390;
	add.f16 	%rs471, %rs727, %rs389;
	add.f16 	%rs472, %rs728, %rs390;
	add.f16 	%rs473, %rs729, %rs391;
	add.f16 	%rs474, %rs730, %rs392;
	add.f16 	%rs475, %rs731, %rs391;
	add.f16 	%rs476, %rs732, %rs392;
	add.f16 	%rs477, %rs733, %rs393;
	add.f16 	%rs478, %rs734, %rs394;
	add.f16 	%rs479, %rs735, %rs393;
	add.f16 	%rs480, %rs736, %rs394;
	add.f16 	%rs481, %rs737, %rs395;
	add.f16 	%rs482, %rs738, %rs396;
	add.f16 	%rs483, %rs739, %rs395;
	add.f16 	%rs484, %rs740, %rs396;
	add.f16 	%rs485, %rs741, %rs397;
	add.f16 	%rs486, %rs742, %rs398;
	add.f16 	%rs487, %rs743, %rs397;
	add.f16 	%rs488, %rs744, %rs398;
	add.f16 	%rs489, %rs745, %rs399;
	add.f16 	%rs490, %rs746, %rs400;
	add.f16 	%rs491, %rs747, %rs399;
	add.f16 	%rs492, %rs748, %rs400;
	add.f16 	%rs493, %rs749, %rs401;
	add.f16 	%rs494, %rs750, %rs402;
	add.f16 	%rs495, %rs751, %rs401;
	add.f16 	%rs496, %rs752, %rs402;
	add.f16 	%rs497, %rs753, %rs403;
	add.f16 	%rs498, %rs754, %rs404;
	add.f16 	%rs499, %rs755, %rs403;
	add.f16 	%rs500, %rs756, %rs404;
	add.f16 	%rs501, %rs757, %rs389;
	add.f16 	%rs502, %rs758, %rs390;
	add.f16 	%rs503, %rs759, %rs389;
	add.f16 	%rs504, %rs760, %rs390;
	add.f16 	%rs505, %rs761, %rs391;
	add.f16 	%rs506, %rs762, %rs392;
	add.f16 	%rs507, %rs763, %rs391;
	add.f16 	%rs508, %rs764, %rs392;
	add.f16 	%rs509, %rs765, %rs393;
	add.f16 	%rs510, %rs766, %rs394;
	add.f16 	%rs511, %rs767, %rs393;
	add.f16 	%rs512, %rs768, %rs394;
	add.f16 	%rs513, %rs769, %rs395;
	add.f16 	%rs514, %rs770, %rs396;
	add.f16 	%rs515, %rs771, %rs395;
	add.f16 	%rs516, %rs772, %rs396;
	add.f16 	%rs517, %rs773, %rs397;
	add.f16 	%rs518, %rs774, %rs398;
	add.f16 	%rs519, %rs775, %rs397;
	add.f16 	%rs520, %rs776, %rs398;
	add.f16 	%rs521, %rs777, %rs399;
	add.f16 	%rs522, %rs778, %rs400;
	add.f16 	%rs523, %rs779, %rs399;
	add.f16 	%rs524, %rs780, %rs400;
	add.f16 	%rs525, %rs781, %rs401;
	add.f16 	%rs526, %rs782, %rs402;
	add.f16 	%rs527, %rs783, %rs401;
	add.f16 	%rs528, %rs784, %rs402;
	add.f16 	%rs529, %rs785, %rs403;
	add.f16 	%rs530, %rs786, %rs404;
	add.f16 	%rs531, %rs787, %rs403;
	add.f16 	%rs532, %rs788, %rs404;
	bar.sync 	0;
	shr.u32 	%r1553, %r2, 2;
	or.b32  	%r1554, %r1553, %r78;
	mul.lo.s32 	%r1555, %r1554, 528;
	add.s32 	%r1556, %r1537, %r1555;
	mov.b32 	%r1557, {%rs405, %rs406};
	st.shared.b32 	[%r1556], %r1557;
	mov.b32 	%r1558, {%rs407, %rs408};
	st.shared.b32 	[%r1556+4224], %r1558;
	mov.b32 	%r1559, {%rs409, %rs410};
	st.shared.b32 	[%r1556+64], %r1559;
	add.s32 	%r1560, %r1539, %r1555;
	mov.b32 	%r1561, {%rs411, %rs412};
	st.shared.b32 	[%r1560+4224], %r1561;
	mov.b32 	%r1562, {%rs413, %rs414};
	st.shared.b32 	[%r1556+128], %r1562;
	add.s32 	%r1563, %r1541, %r1555;
	mov.b32 	%r1564, {%rs415, %rs416};
	st.shared.b32 	[%r1563+4224], %r1564;
	mov.b32 	%r1565, {%rs417, %rs418};
	st.shared.b32 	[%r1556+192], %r1565;
	add.s32 	%r1566, %r1543, %r1555;
	mov.b32 	%r1567, {%rs419, %rs420};
	st.shared.b32 	[%r1566+4224], %r1567;
	mov.b32 	%r1568, {%rs421, %rs422};
	st.shared.b32 	[%r1556+256], %r1568;
	add.s32 	%r1569, %r1545, %r1555;
	mov.b32 	%r1570, {%rs423, %rs424};
	st.shared.b32 	[%r1569+4224], %r1570;
	mov.b32 	%r1571, {%rs425, %rs426};
	st.shared.b32 	[%r1556+320], %r1571;
	add.s32 	%r1572, %r1547, %r1555;
	mov.b32 	%r1573, {%rs427, %rs428};
	st.shared.b32 	[%r1572+4224], %r1573;
	mov.b32 	%r1574, {%rs429, %rs430};
	st.shared.b32 	[%r1556+384], %r1574;
	add.s32 	%r1575, %r1549, %r1555;
	mov.b32 	%r1576, {%rs431, %rs432};
	st.shared.b32 	[%r1575+4224], %r1576;
	mov.b32 	%r1577, {%rs433, %rs434};
	st.shared.b32 	[%r1556+448], %r1577;
	add.s32 	%r1578, %r1551, %r1555;
	mov.b32 	%r1579, {%rs435, %rs436};
	st.shared.b32 	[%r1578+4224], %r1579;
	bar.sync 	0;
	shl.b32 	%r1580, %r2, 3;
	mad.lo.s32 	%r1581, %r3, 264, %r1580;
	shl.b32 	%r1582, %r1581, 1;
	add.s32 	%r1583, %r484, %r1582;
	mov.b32 	%r1584, {%rs437, %rs438};
	mov.b32 	%r1585, {%rs439, %rs440};
	mov.b32 	%r1586, {%rs441, %rs442};
	mov.b32 	%r1587, {%rs443, %rs444};
	mov.b32 	%r1588, {%rs445, %rs446};
	mov.b32 	%r1589, {%rs447, %rs448};
	mov.b32 	%r1590, {%rs449, %rs450};
	mov.b32 	%r1591, {%rs451, %rs452};
	mov.b32 	%r1592, {%rs453, %rs454};
	mov.b32 	%r1593, {%rs455, %rs456};
	mov.b32 	%r1594, {%rs457, %rs458};
	mov.b32 	%r1595, {%rs459, %rs460};
	mov.b32 	%r1596, {%rs461, %rs462};
	mov.b32 	%r1597, {%rs463, %rs464};
	mov.b32 	%r1598, {%rs465, %rs466};
	mov.b32 	%r1599, {%rs467, %rs468};
	mov.b32 	%r1600, {%rs469, %rs470};
	mov.b32 	%r1601, {%rs471, %rs472};
	mov.b32 	%r1602, {%rs473, %rs474};
	mov.b32 	%r1603, {%rs475, %rs476};
	mov.b32 	%r1604, {%rs477, %rs478};
	mov.b32 	%r1605, {%rs479, %rs480};
	mov.b32 	%r1606, {%rs481, %rs482};
	mov.b32 	%r1607, {%rs483, %rs484};
	mov.b32 	%r1608, {%rs485, %rs486};
	mov.b32 	%r1609, {%rs487, %rs488};
	mov.b32 	%r1610, {%rs489, %rs490};
	mov.b32 	%r1611, {%rs491, %rs492};
	mov.b32 	%r1612, {%rs493, %rs494};
	mov.b32 	%r1613, {%rs495, %rs496};
	mov.b32 	%r1614, {%rs497, %rs498};
	mov.b32 	%r1615, {%rs499, %rs500};
	mov.b32 	%r1616, {%rs501, %rs502};
	mov.b32 	%r1617, {%rs503, %rs504};
	mov.b32 	%r1618, {%rs505, %rs506};
	mov.b32 	%r1619, {%rs507, %rs508};
	mov.b32 	%r1620, {%rs509, %rs510};
	mov.b32 	%r1621, {%rs511, %rs512};
	mov.b32 	%r1622, {%rs513, %rs514};
	mov.b32 	%r1623, {%rs515, %rs516};
	mov.b32 	%r1624, {%rs517, %rs518};
	mov.b32 	%r1625, {%rs519, %rs520};
	mov.b32 	%r1626, {%rs521, %rs522};
	mov.b32 	%r1627, {%rs523, %rs524};
	mov.b32 	%r1628, {%rs525, %rs526};
	mov.b32 	%r1629, {%rs527, %rs528};
	mov.b32 	%r1630, {%rs529, %rs530};
	mov.b32 	%r1631, {%rs531, %rs532};
	ld.shared.v4.b32 	{%r1632, %r1633, %r1634, %r1635}, [%r1583];
	.loc	1 127 23
	add.f16x2 	%r1636, %r1632, %r199;
	add.f16x2 	%r1637, %r1633, %r200;
	add.f16x2 	%r1638, %r1634, %r201;
	add.f16x2 	%r1639, %r1635, %r202;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1640, %r1641, %r1642, %r1643}, [%r1583+4224];
	.loc	1 127 23
	add.f16x2 	%r1644, %r1640, %r207;
	add.f16x2 	%r1645, %r1641, %r208;
	add.f16x2 	%r1646, %r1642, %r209;
	add.f16x2 	%r1647, %r1643, %r210;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1648, %r1649, %r1650, %r1651}, [%r1583+8448];
	.loc	1 127 23
	add.f16x2 	%r1652, %r1648, %r215;
	add.f16x2 	%r1653, %r1649, %r216;
	add.f16x2 	%r1654, %r1650, %r217;
	add.f16x2 	%r1655, %r1651, %r218;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1656, %r1657, %r1658, %r1659}, [%r1583+12672];
	.loc	1 127 23
	add.f16x2 	%r1660, %r1656, %r223;
	add.f16x2 	%r1661, %r1657, %r224;
	add.f16x2 	%r1662, %r1658, %r225;
	.loc	1 111 23
	bar.sync 	0;
	st.shared.b32 	[%r1556], %r1584;
	st.shared.b32 	[%r1556+4224], %r1585;
	st.shared.b32 	[%r1556+64], %r1586;
	st.shared.b32 	[%r1560+4224], %r1587;
	st.shared.b32 	[%r1556+128], %r1588;
	st.shared.b32 	[%r1563+4224], %r1589;
	st.shared.b32 	[%r1556+192], %r1590;
	st.shared.b32 	[%r1566+4224], %r1591;
	st.shared.b32 	[%r1556+256], %r1592;
	st.shared.b32 	[%r1569+4224], %r1593;
	st.shared.b32 	[%r1556+320], %r1594;
	st.shared.b32 	[%r1572+4224], %r1595;
	st.shared.b32 	[%r1556+384], %r1596;
	st.shared.b32 	[%r1575+4224], %r1597;
	st.shared.b32 	[%r1556+448], %r1598;
	st.shared.b32 	[%r1578+4224], %r1599;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1663, %r1659, %r226;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1664, %r1665, %r1666, %r1667}, [%r1583];
	.loc	1 127 23
	add.f16x2 	%r1668, %r1664, %r231;
	add.f16x2 	%r1669, %r1665, %r232;
	add.f16x2 	%r1670, %r1666, %r233;
	add.f16x2 	%r1671, %r1667, %r234;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1672, %r1673, %r1674, %r1675}, [%r1583+4224];
	.loc	1 127 23
	add.f16x2 	%r1676, %r1672, %r239;
	add.f16x2 	%r1677, %r1673, %r240;
	add.f16x2 	%r1678, %r1674, %r241;
	add.f16x2 	%r1679, %r1675, %r242;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1680, %r1681, %r1682, %r1683}, [%r1583+8448];
	.loc	1 127 23
	add.f16x2 	%r1684, %r1680, %r247;
	add.f16x2 	%r1685, %r1681, %r248;
	add.f16x2 	%r1686, %r1682, %r249;
	add.f16x2 	%r1687, %r1683, %r250;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1688, %r1689, %r1690, %r1691}, [%r1583+12672];
	.loc	1 127 23
	add.f16x2 	%r1692, %r1688, %r255;
	add.f16x2 	%r1693, %r1689, %r256;
	add.f16x2 	%r1694, %r1690, %r257;
	.loc	1 111 23
	bar.sync 	0;
	st.shared.b32 	[%r1556], %r1600;
	st.shared.b32 	[%r1556+4224], %r1601;
	st.shared.b32 	[%r1556+64], %r1602;
	st.shared.b32 	[%r1560+4224], %r1603;
	st.shared.b32 	[%r1556+128], %r1604;
	st.shared.b32 	[%r1563+4224], %r1605;
	st.shared.b32 	[%r1556+192], %r1606;
	st.shared.b32 	[%r1566+4224], %r1607;
	st.shared.b32 	[%r1556+256], %r1608;
	st.shared.b32 	[%r1569+4224], %r1609;
	st.shared.b32 	[%r1556+320], %r1610;
	st.shared.b32 	[%r1572+4224], %r1611;
	st.shared.b32 	[%r1556+384], %r1612;
	st.shared.b32 	[%r1575+4224], %r1613;
	st.shared.b32 	[%r1556+448], %r1614;
	st.shared.b32 	[%r1578+4224], %r1615;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1695, %r1691, %r258;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1696, %r1697, %r1698, %r1699}, [%r1583];
	.loc	1 127 23
	add.f16x2 	%r1700, %r1696, %r263;
	add.f16x2 	%r1701, %r1697, %r264;
	add.f16x2 	%r1702, %r1698, %r265;
	add.f16x2 	%r1703, %r1699, %r266;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1704, %r1705, %r1706, %r1707}, [%r1583+4224];
	.loc	1 127 23
	add.f16x2 	%r1708, %r1704, %r271;
	add.f16x2 	%r1709, %r1705, %r272;
	add.f16x2 	%r1710, %r1706, %r273;
	add.f16x2 	%r1711, %r1707, %r274;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1712, %r1713, %r1714, %r1715}, [%r1583+8448];
	.loc	1 127 23
	add.f16x2 	%r1716, %r1712, %r279;
	add.f16x2 	%r1717, %r1713, %r280;
	add.f16x2 	%r1718, %r1714, %r281;
	add.f16x2 	%r1719, %r1715, %r282;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1720, %r1721, %r1722, %r1723}, [%r1583+12672];
	.loc	1 127 23
	add.f16x2 	%r1724, %r1720, %r287;
	add.f16x2 	%r1725, %r1721, %r288;
	add.f16x2 	%r1726, %r1722, %r289;
	.loc	1 111 23
	bar.sync 	0;
	st.shared.b32 	[%r1556], %r1616;
	st.shared.b32 	[%r1556+4224], %r1617;
	st.shared.b32 	[%r1556+64], %r1618;
	st.shared.b32 	[%r1560+4224], %r1619;
	st.shared.b32 	[%r1556+128], %r1620;
	st.shared.b32 	[%r1563+4224], %r1621;
	st.shared.b32 	[%r1556+192], %r1622;
	st.shared.b32 	[%r1566+4224], %r1623;
	st.shared.b32 	[%r1556+256], %r1624;
	st.shared.b32 	[%r1569+4224], %r1625;
	st.shared.b32 	[%r1556+320], %r1626;
	st.shared.b32 	[%r1572+4224], %r1627;
	st.shared.b32 	[%r1556+384], %r1628;
	st.shared.b32 	[%r1575+4224], %r1629;
	st.shared.b32 	[%r1556+448], %r1630;
	st.shared.b32 	[%r1578+4224], %r1631;
	bar.sync 	0;
	.loc	1 127 23
	add.f16x2 	%r1727, %r1723, %r290;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1728, %r1729, %r1730, %r1731}, [%r1583];
	.loc	1 127 23
	add.f16x2 	%r1732, %r1728, %r295;
	add.f16x2 	%r1733, %r1729, %r296;
	add.f16x2 	%r1734, %r1730, %r297;
	add.f16x2 	%r1735, %r1731, %r298;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1736, %r1737, %r1738, %r1739}, [%r1583+4224];
	.loc	1 127 23
	add.f16x2 	%r1740, %r1736, %r303;
	add.f16x2 	%r1741, %r1737, %r304;
	add.f16x2 	%r1742, %r1738, %r305;
	add.f16x2 	%r1743, %r1739, %r306;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1744, %r1745, %r1746, %r1747}, [%r1583+8448];
	.loc	1 127 23
	add.f16x2 	%r1748, %r1744, %r311;
	add.f16x2 	%r1749, %r1745, %r312;
	add.f16x2 	%r1750, %r1746, %r313;
	add.f16x2 	%r1751, %r1747, %r314;
	.loc	1 111 23
	ld.shared.v4.b32 	{%r1752, %r1753, %r1754, %r1755}, [%r1583+12672];
	.loc	1 127 23
	add.f16x2 	%r1756, %r1752, %r319;
	add.f16x2 	%r1757, %r1753, %r320;
	add.f16x2 	%r1758, %r1754, %r321;
	add.f16x2 	%r1759, %r1755, %r322;
	.loc	1 129 21
	// begin inline asm
	@%p144 st.global.v4.b32 [ %rd122 + 0 ], { %r1636, %r1637, %r1638, %r1639 };
	// end inline asm
	// begin inline asm
	@%p145 st.global.v4.b32 [ %rd123 + 0 ], { %r1644, %r1645, %r1646, %r1647 };
	// end inline asm
	// begin inline asm
	@%p146 st.global.v4.b32 [ %rd124 + 0 ], { %r1652, %r1653, %r1654, %r1655 };
	// end inline asm
	// begin inline asm
	@%p147 st.global.v4.b32 [ %rd125 + 0 ], { %r1660, %r1661, %r1662, %r1663 };
	// end inline asm
	// begin inline asm
	@%p148 st.global.v4.b32 [ %rd126 + 0 ], { %r1668, %r1669, %r1670, %r1671 };
	// end inline asm
	// begin inline asm
	@%p149 st.global.v4.b32 [ %rd127 + 0 ], { %r1676, %r1677, %r1678, %r1679 };
	// end inline asm
	// begin inline asm
	@%p150 st.global.v4.b32 [ %rd128 + 0 ], { %r1684, %r1685, %r1686, %r1687 };
	// end inline asm
	// begin inline asm
	@%p151 st.global.v4.b32 [ %rd129 + 0 ], { %r1692, %r1693, %r1694, %r1695 };
	// end inline asm
	// begin inline asm
	@%p152 st.global.v4.b32 [ %rd130 + 0 ], { %r1700, %r1701, %r1702, %r1703 };
	// end inline asm
	// begin inline asm
	@%p153 st.global.v4.b32 [ %rd131 + 0 ], { %r1708, %r1709, %r1710, %r1711 };
	// end inline asm
	// begin inline asm
	@%p154 st.global.v4.b32 [ %rd132 + 0 ], { %r1716, %r1717, %r1718, %r1719 };
	// end inline asm
	// begin inline asm
	@%p155 st.global.v4.b32 [ %rd133 + 0 ], { %r1724, %r1725, %r1726, %r1727 };
	// end inline asm
	// begin inline asm
	@%p156 st.global.v4.b32 [ %rd134 + 0 ], { %r1732, %r1733, %r1734, %r1735 };
	// end inline asm
	// begin inline asm
	@%p157 st.global.v4.b32 [ %rd135 + 0 ], { %r1740, %r1741, %r1742, %r1743 };
	// end inline asm
	// begin inline asm
	@%p158 st.global.v4.b32 [ %rd136 + 0 ], { %r1748, %r1749, %r1750, %r1751 };
	// end inline asm
	// begin inline asm
	@%p159 st.global.v4.b32 [ %rd137 + 0 ], { %r1756, %r1757, %r1758, %r1759 };
	// end inline asm
	.loc	1 129 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/PycharmProjects/tritontest/compile_matmul_kernel_bias_accumulate_transpose_b.py"
	.file	2 "/home/mike/PycharmProjects/tritontest/.venv/lib/python3.11/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 211
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 80
.b8 121
.b8 99
.b8 104
.b8 97
.b8 114
.b8 109
.b8 80
.b8 114
.b8 111
.b8 106
.b8 101
.b8 99
.b8 116
.b8 115
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 116
.b8 101
.b8 115
.b8 116
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 104
.b8 4
.b32 104
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 104
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 104
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_13_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_13_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_13_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_13_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_13_FUNCTION_NAME "matmul_kernel_bias_accumulate_transpose_b"
