/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_4_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel_transpose_b
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel_transpose_b(
	.param .u64 matmul_kernel_transpose_b_param_0,
	.param .u64 matmul_kernel_transpose_b_param_1,
	.param .u64 matmul_kernel_transpose_b_param_2,
	.param .u32 matmul_kernel_transpose_b_param_3,
	.param .u32 matmul_kernel_transpose_b_param_4,
	.param .u32 matmul_kernel_transpose_b_param_5,
	.param .u32 matmul_kernel_transpose_b_param_6,
	.param .u32 matmul_kernel_transpose_b_param_7,
	.param .u32 matmul_kernel_transpose_b_param_8
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<62>;
	.reg .b16 	%rs<643>;
	.reg .b32 	%r<1388>;
	.reg .b64 	%rd<105>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r137, [matmul_kernel_transpose_b_param_8];
	ld.param.u32 	%r136, [matmul_kernel_transpose_b_param_5];
	ld.param.u32 	%r135, [matmul_kernel_transpose_b_param_4];
	ld.param.u32 	%r134, [matmul_kernel_transpose_b_param_3];
	ld.param.u64 	%rd17, [matmul_kernel_transpose_b_param_2];
	ld.param.u64 	%rd16, [matmul_kernel_transpose_b_param_1];
	ld.param.u64 	%rd15, [matmul_kernel_transpose_b_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r138, %ctaid.x;
	// end inline asm
$L__tmp1:
	.loc	2 40 22
	add.s32 	%r203, %r134, 127;
	.loc	2 40 28
	shr.s32 	%r204, %r203, 31;
	shr.u32 	%r205, %r204, 25;
	add.s32 	%r206, %r203, %r205;
	shr.s32 	%r207, %r206, 7;
$L__tmp2:
	.loc	2 40 22
	add.s32 	%r208, %r135, 255;
	.loc	2 40 28
	shr.s32 	%r209, %r208, 31;
	shr.u32 	%r210, %r209, 24;
	add.s32 	%r211, %r208, %r210;
	shr.s32 	%r212, %r211, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r214, %r212, 3;
	ld.param.u32 	%r215, [matmul_kernel_transpose_b_param_6];
	ld.param.u32 	%r216, [matmul_kernel_transpose_b_param_7];
	.loc	1 61 22
	div.s32 	%r217, %r138, %r214;
	.loc	1 62 29
	shl.b32 	%r218, %r217, 3;
	.loc	1 63 35
	sub.s32 	%r219, %r207, %r218;
	.loc	1 63 48
	min.s32 	%r220, %r219, 8;
	.loc	1 64 33
	rem.s32 	%r221, %r138, %r220;
	.loc	1 64 27
	add.s32 	%r222, %r218, %r221;
	mul.lo.s32 	%r223, %r217, %r214;
	sub.s32 	%r224, %r138, %r223;
	.loc	1 65 40
	div.s32 	%r225, %r224, %r220;
	.loc	1 74 23
	shl.b32 	%r1, %r222, 7;
	.loc	1 74 51
	mov.u32 	%r2, %tid.x;
	and.b32  	%r3, %r2, 31;
	shr.u32 	%r4, %r2, 5;
	shr.u32 	%r226, %r2, 2;
	bfe.u32 	%r227, %r2, 2, 6;
	or.b32  	%r228, %r227, 64;
	.loc	1 74 38
	or.b32  	%r229, %r1, %r227;
	or.b32  	%r230, %r1, %r228;
	.loc	1 74 68
	rem.s32 	%r231, %r229, %r134;
	rem.s32 	%r232, %r230, %r134;
	.loc	1 75 23
	shl.b32 	%r5, %r225, 8;
	.loc	1 75 51
	or.b32  	%r233, %r227, 128;
	or.b32  	%r234, %r227, 192;
	shl.b32 	%r6, %r2, 3;
	and.b32  	%r7, %r6, 24;
	.loc	1 75 38
	or.b32  	%r235, %r5, %r227;
	or.b32  	%r236, %r5, %r228;
	or.b32  	%r237, %r5, %r233;
	or.b32  	%r238, %r5, %r234;
	.loc	1 75 68
	rem.s32 	%r239, %r235, %r135;
	rem.s32 	%r240, %r236, %r135;
	rem.s32 	%r241, %r237, %r135;
	rem.s32 	%r242, %r238, %r135;
	.loc	1 77 53
	mad.lo.s32 	%r243, %r231, %r215, %r7;
	mad.lo.s32 	%r244, %r232, %r215, %r7;
	.loc	1 77 22
	mul.wide.s32 	%rd30, %r243, 2;
	add.s64 	%rd18, %rd15, %rd30;
	mul.wide.s32 	%rd31, %r244, 2;
	add.s64 	%rd19, %rd15, %rd31;
	.loc	1 78 52
	mad.lo.s32 	%r245, %r239, %r216, %r7;
	mad.lo.s32 	%r246, %r240, %r216, %r7;
	mad.lo.s32 	%r247, %r241, %r216, %r7;
	mad.lo.s32 	%r248, %r242, %r216, %r7;
	.loc	1 78 22
	mul.wide.s32 	%rd32, %r245, 2;
	add.s64 	%rd20, %rd16, %rd32;
	mul.wide.s32 	%rd33, %r246, 2;
	add.s64 	%rd21, %rd16, %rd33;
	mul.wide.s32 	%rd34, %r247, 2;
	add.s64 	%rd22, %rd16, %rd34;
	mul.wide.s32 	%rd35, %r248, 2;
	add.s64 	%rd23, %rd16, %rd35;
$L__tmp4:
	.loc	2 40 22
	add.s32 	%r249, %r136, 31;
$L__tmp5:
	.loc	1 93 22
	setp.lt.s32 	%p13, %r249, 32;
	setp.gt.s32 	%p14, %r249, 31;
	.loc	1 96 72
	setp.lt.s32 	%p15, %r7, %r136;
	.loc	1 96 20
	xor.b32  	%r253, %r6, %r2;
	and.b32  	%r254, %r253, 24;
	shl.b32 	%r255, %r227, 5;
	or.b32  	%r9, %r255, %r254;
	shl.b32 	%r256, %r9, 1;
	mov.u32 	%r257, global_smem;
	add.s32 	%r139, %r257, %r256;
	shl.b32 	%r258, %r228, 5;
	or.b32  	%r10, %r258, %r254;
	shl.b32 	%r259, %r10, 1;
	add.s32 	%r141, %r257, %r259;
	selp.b32 	%r260, 16, 0, %p14;
	selp.b32 	%r142, %r260, 0, %p15;
	mov.pred 	%p1, -1;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r139 + 0 ], [ %rd18 + 0 ], 0x10, %r142;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r141 + 0 ], [ %rd19 + 0 ], 0x10, %r142;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	add.s32 	%r261, %r257, 16384;
	add.s32 	%r143, %r261, %r256;
	add.s32 	%r145, %r261, %r259;
	shl.b32 	%r262, %r233, 5;
	or.b32  	%r11, %r262, %r254;
	shl.b32 	%r263, %r11, 1;
	add.s32 	%r147, %r261, %r263;
	shl.b32 	%r264, %r234, 5;
	or.b32  	%r12, %r264, %r254;
	shl.b32 	%r265, %r12, 1;
	add.s32 	%r149, %r261, %r265;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r143 + 0 ], [ %rd20 + 0 ], 0x10, %r142;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r145 + 0 ], [ %rd21 + 0 ], 0x10, %r142;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r147 + 0 ], [ %rd22 + 0 ], 0x10, %r142;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r149 + 0 ], [ %rd23 + 0 ], 0x10, %r142;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p16, %r249, 63;
	.loc	1 102 18
	add.s64 	%rd24, %rd18, 64;
	add.s64 	%rd25, %rd19, 64;
	.loc	1 103 18
	add.s64 	%rd26, %rd20, 64;
	add.s64 	%rd27, %rd21, 64;
	add.s64 	%rd28, %rd22, 64;
	add.s64 	%rd29, %rd23, 64;
	.loc	1 96 53
	or.b32  	%r266, %r7, 32;
	.loc	1 96 72
	setp.lt.s32 	%p17, %r266, %r136;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r267, %r257, 8192;
	add.s32 	%r151, %r267, %r256;
	add.s32 	%r153, %r267, %r259;
	selp.b32 	%r268, 16, 0, %p16;
	selp.b32 	%r154, %r268, 0, %p17;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r151 + 0 ], [ %rd24 + 0 ], 0x10, %r154;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r153 + 0 ], [ %rd25 + 0 ], 0x10, %r154;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	add.s32 	%r269, %r257, 32768;
	add.s32 	%r155, %r269, %r256;
	add.s32 	%r157, %r269, %r259;
	add.s32 	%r159, %r269, %r263;
	add.s32 	%r161, %r269, %r265;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r155 + 0 ], [ %rd26 + 0 ], 0x10, %r154;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r157 + 0 ], [ %rd27 + 0 ], 0x10, %r154;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r159 + 0 ], [ %rd28 + 0 ], 0x10, %r154;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r161 + 0 ], [ %rd29 + 0 ], 0x10, %r154;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	and.b32  	%r270, %r2, 7;
	shr.u32 	%r271, %r2, 3;
	bfe.u32 	%r13, %r2, 3, 1;
	bfe.u32 	%r14, %r2, 4, 1;
	bfe.u32 	%r15, %r2, 1, 2;
	and.b32  	%r16, %r271, 16;
	shl.b32 	%r272, %r13, 3;
	or.b32  	%r273, %r272, %r16;
	or.b32  	%r274, %r273, %r270;
	xor.b32  	%r275, %r14, %r15;
	shl.b32 	%r276, %r275, 3;
	shl.b32 	%r17, %r274, 5;
	or.b32  	%r18, %r17, %r276;
	shl.b32 	%r277, %r18, 1;
	add.s32 	%r167, %r257, %r277;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1379, %r1380, %r1381, %r1382 }, [ %r167 + 0 ];
	// end inline asm
	add.s32 	%r172, %r167, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1375, %r1376, %r1377, %r1378 }, [ %r172 + 0 ];
	// end inline asm
	add.s32 	%r177, %r167, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1371, %r1372, %r1373, %r1374 }, [ %r177 + 0 ];
	// end inline asm
	add.s32 	%r182, %r167, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1367, %r1368, %r1369, %r1370 }, [ %r182 + 0 ];
	// end inline asm
	.loc	1 97 20
	shl.b32 	%r278, %r14, 5;
	and.b32  	%r35, %r226, 24;
	or.b32  	%r279, %r278, %r35;
	or.b32  	%r280, %r279, %r270;
	xor.b32  	%r281, %r13, %r15;
	shl.b32 	%r282, %r281, 3;
	shl.b32 	%r36, %r280, 5;
	or.b32  	%r37, %r36, %r282;
	shl.b32 	%r283, %r37, 1;
	add.s32 	%r187, %r261, %r283;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1363, %r1364, %r1365, %r1366 }, [ %r187 + 0 ];
	// end inline asm
	add.s32 	%r192, %r187, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1359, %r1360, %r1361, %r1362 }, [ %r192 + 0 ];
	// end inline asm
	add.s32 	%r197, %r187, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1355, %r1356, %r1357, %r1358 }, [ %r197 + 0 ];
	// end inline asm
	add.s32 	%r202, %r187, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1351, %r1352, %r1353, %r1354 }, [ %r202 + 0 ];
	// end inline asm
	mov.b16 	%rs515, 0x0000;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	.loc	1 93 22
	@%p13 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd1, %r243;
	cvt.s64.s32 	%rd2, %r244;
	cvt.s64.s32 	%rd3, %r245;
	cvt.s64.s32 	%rd4, %r246;
	cvt.s64.s32 	%rd5, %r247;
	cvt.s64.s32 	%rd6, %r248;
	shr.s32 	%r250, %r249, 31;
	shr.u32 	%r251, %r250, 27;
	add.s32 	%r252, %r249, %r251;
	shr.s32 	%r8, %r252, 5;
	add.s32 	%r54, %r8, -2;
	or.b32  	%r288, %r14, 2;
	xor.b32  	%r289, %r288, %r15;
	shl.b32 	%r290, %r289, 3;
	or.b32  	%r291, %r13, 2;
	xor.b32  	%r292, %r291, %r15;
	shl.b32 	%r293, %r292, 3;
	or.b32  	%r55, %r17, %r290;
	or.b32  	%r56, %r36, %r293;
	.loc	1 93 22
	shl.b64 	%rd37, %rd6, 1;
	add.s64 	%rd38, %rd37, %rd16;
	add.s64 	%rd7, %rd38, 128;
	shl.b64 	%rd39, %rd5, 1;
	add.s64 	%rd40, %rd39, %rd16;
	add.s64 	%rd8, %rd40, 128;
	shl.b64 	%rd41, %rd4, 1;
	add.s64 	%rd42, %rd41, %rd16;
	add.s64 	%rd9, %rd42, 128;
	shl.b64 	%rd43, %rd3, 1;
	add.s64 	%rd44, %rd43, %rd16;
	add.s64 	%rd10, %rd44, 128;
	shl.b64 	%rd45, %rd2, 1;
	add.s64 	%rd46, %rd45, %rd15;
	add.s64 	%rd11, %rd46, 128;
	shl.b64 	%rd47, %rd1, 1;
	add.s64 	%rd48, %rd47, %rd15;
	add.s64 	%rd12, %rd48, 128;
	or.b32  	%r1350, %r7, 64;
	mov.b16 	%rs515, 0x0000;
	mov.b32 	%r1386, 1;
	mov.b32 	%r1385, 0;
	mov.u64 	%rd104, 0;
	shl.b32 	%r1026, %r55, 1;
	shl.b32 	%r1027, %r56, 1;
	mov.u32 	%r1383, %r261;
	mov.u32 	%r1384, %r257;
	mov.u16 	%rs516, %rs515;
	mov.u16 	%rs517, %rs515;
	mov.u16 	%rs518, %rs515;
	mov.u16 	%rs519, %rs515;
	mov.u16 	%rs520, %rs515;
	mov.u16 	%rs521, %rs515;
	mov.u16 	%rs522, %rs515;
	mov.u16 	%rs523, %rs515;
	mov.u16 	%rs524, %rs515;
	mov.u16 	%rs525, %rs515;
	mov.u16 	%rs526, %rs515;
	mov.u16 	%rs527, %rs515;
	mov.u16 	%rs528, %rs515;
	mov.u16 	%rs529, %rs515;
	mov.u16 	%rs530, %rs515;
	mov.u16 	%rs531, %rs515;
	mov.u16 	%rs532, %rs515;
	mov.u16 	%rs533, %rs515;
	mov.u16 	%rs534, %rs515;
	mov.u16 	%rs535, %rs515;
	mov.u16 	%rs536, %rs515;
	mov.u16 	%rs537, %rs515;
	mov.u16 	%rs538, %rs515;
	mov.u16 	%rs539, %rs515;
	mov.u16 	%rs540, %rs515;
	mov.u16 	%rs541, %rs515;
	mov.u16 	%rs542, %rs515;
	mov.u16 	%rs543, %rs515;
	mov.u16 	%rs544, %rs515;
	mov.u16 	%rs545, %rs515;
	mov.u16 	%rs546, %rs515;
	mov.u16 	%rs547, %rs515;
	mov.u16 	%rs548, %rs515;
	mov.u16 	%rs549, %rs515;
	mov.u16 	%rs550, %rs515;
	mov.u16 	%rs551, %rs515;
	mov.u16 	%rs552, %rs515;
	mov.u16 	%rs553, %rs515;
	mov.u16 	%rs554, %rs515;
	mov.u16 	%rs555, %rs515;
	mov.u16 	%rs556, %rs515;
	mov.u16 	%rs557, %rs515;
	mov.u16 	%rs558, %rs515;
	mov.u16 	%rs559, %rs515;
	mov.u16 	%rs560, %rs515;
	mov.u16 	%rs561, %rs515;
	mov.u16 	%rs562, %rs515;
	mov.u16 	%rs563, %rs515;
	mov.u16 	%rs564, %rs515;
	mov.u16 	%rs565, %rs515;
	mov.u16 	%rs566, %rs515;
	mov.u16 	%rs567, %rs515;
	mov.u16 	%rs568, %rs515;
	mov.u16 	%rs569, %rs515;
	mov.u16 	%rs570, %rs515;
	mov.u16 	%rs571, %rs515;
	mov.u16 	%rs572, %rs515;
	mov.u16 	%rs573, %rs515;
	mov.u16 	%rs574, %rs515;
	mov.u16 	%rs575, %rs515;
	mov.u16 	%rs576, %rs515;
	mov.u16 	%rs577, %rs515;
	mov.u16 	%rs578, %rs515;
	mov.u16 	%rs579, %rs515;
	mov.u16 	%rs580, %rs515;
	mov.u16 	%rs581, %rs515;
	mov.u16 	%rs582, %rs515;
	mov.u16 	%rs583, %rs515;
	mov.u16 	%rs584, %rs515;
	mov.u16 	%rs585, %rs515;
	mov.u16 	%rs586, %rs515;
	mov.u16 	%rs587, %rs515;
	mov.u16 	%rs588, %rs515;
	mov.u16 	%rs589, %rs515;
	mov.u16 	%rs590, %rs515;
	mov.u16 	%rs591, %rs515;
	mov.u16 	%rs592, %rs515;
	mov.u16 	%rs593, %rs515;
	mov.u16 	%rs594, %rs515;
	mov.u16 	%rs595, %rs515;
	mov.u16 	%rs596, %rs515;
	mov.u16 	%rs597, %rs515;
	mov.u16 	%rs598, %rs515;
	mov.u16 	%rs599, %rs515;
	mov.u16 	%rs600, %rs515;
	mov.u16 	%rs601, %rs515;
	mov.u16 	%rs602, %rs515;
	mov.u16 	%rs603, %rs515;
	mov.u16 	%rs604, %rs515;
	mov.u16 	%rs605, %rs515;
	mov.u16 	%rs606, %rs515;
	mov.u16 	%rs607, %rs515;
	mov.u16 	%rs608, %rs515;
	mov.u16 	%rs609, %rs515;
	mov.u16 	%rs610, %rs515;
	mov.u16 	%rs611, %rs515;
	mov.u16 	%rs612, %rs515;
	mov.u16 	%rs613, %rs515;
	mov.u16 	%rs614, %rs515;
	mov.u16 	%rs615, %rs515;
	mov.u16 	%rs616, %rs515;
	mov.u16 	%rs617, %rs515;
	mov.u16 	%rs618, %rs515;
	mov.u16 	%rs619, %rs515;
	mov.u16 	%rs620, %rs515;
	mov.u16 	%rs621, %rs515;
	mov.u16 	%rs622, %rs515;
	mov.u16 	%rs623, %rs515;
	mov.u16 	%rs624, %rs515;
	mov.u16 	%rs625, %rs515;
	mov.u16 	%rs626, %rs515;
	mov.u16 	%rs627, %rs515;
	mov.u16 	%rs628, %rs515;
	mov.u16 	%rs629, %rs515;
	mov.u16 	%rs630, %rs515;
	mov.u16 	%rs631, %rs515;
	mov.u16 	%rs632, %rs515;
	mov.u16 	%rs633, %rs515;
	mov.u16 	%rs634, %rs515;
	mov.u16 	%rs635, %rs515;
	mov.u16 	%rs636, %rs515;
	mov.u16 	%rs637, %rs515;
	mov.u16 	%rs638, %rs515;
	mov.u16 	%rs639, %rs515;
	mov.u16 	%rs640, %rs515;
	mov.u16 	%rs641, %rs515;
	mov.u16 	%rs642, %rs515;
	mov.u32 	%r1387, %r1385;
$L__BB0_2:
	setp.lt.s32 	%p24, %r1387, %r54;
	.loc	1 96 20
	add.s32 	%r298, %r1384, %r1026;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r710, %r711, %r712, %r713 }, [ %r298 + 0 ];
	// end inline asm
	add.s32 	%r303, %r298, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r790, %r791, %r792, %r793 }, [ %r303 + 0 ];
	// end inline asm
	add.s32 	%r308, %r298, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r870, %r871, %r872, %r873 }, [ %r308 + 0 ];
	// end inline asm
	add.s32 	%r313, %r298, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r950, %r951, %r952, %r953 }, [ %r313 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r318, %r1383, %r1027;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r714, %r715, %r724, %r725 }, [ %r318 + 0 ];
	// end inline asm
	add.s32 	%r323, %r318, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r734, %r735, %r744, %r745 }, [ %r323 + 0 ];
	// end inline asm
	add.s32 	%r328, %r318, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r754, %r755, %r764, %r765 }, [ %r328 + 0 ];
	// end inline asm
	add.s32 	%r333, %r318, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r774, %r775, %r784, %r785 }, [ %r333 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r706, {%rs515, %rs516};
	mov.b32 	%r707, {%rs517, %rs518};
	mov.b32 	%r716, {%rs519, %rs520};
	mov.b32 	%r717, {%rs521, %rs522};
	mov.b32 	%r726, {%rs523, %rs524};
	mov.b32 	%r727, {%rs525, %rs526};
	mov.b32 	%r736, {%rs527, %rs528};
	mov.b32 	%r737, {%rs529, %rs530};
	mov.b32 	%r746, {%rs531, %rs532};
	mov.b32 	%r747, {%rs533, %rs534};
	mov.b32 	%r756, {%rs535, %rs536};
	mov.b32 	%r757, {%rs537, %rs538};
	mov.b32 	%r766, {%rs539, %rs540};
	mov.b32 	%r767, {%rs541, %rs542};
	mov.b32 	%r776, {%rs543, %rs544};
	mov.b32 	%r777, {%rs545, %rs546};
	mov.b32 	%r786, {%rs547, %rs548};
	mov.b32 	%r787, {%rs549, %rs550};
	mov.b32 	%r796, {%rs551, %rs552};
	mov.b32 	%r797, {%rs553, %rs554};
	mov.b32 	%r806, {%rs555, %rs556};
	mov.b32 	%r807, {%rs557, %rs558};
	mov.b32 	%r816, {%rs559, %rs560};
	mov.b32 	%r817, {%rs561, %rs562};
	mov.b32 	%r826, {%rs563, %rs564};
	mov.b32 	%r827, {%rs565, %rs566};
	mov.b32 	%r836, {%rs567, %rs568};
	mov.b32 	%r837, {%rs569, %rs570};
	mov.b32 	%r846, {%rs571, %rs572};
	mov.b32 	%r847, {%rs573, %rs574};
	mov.b32 	%r856, {%rs575, %rs576};
	mov.b32 	%r857, {%rs577, %rs578};
	mov.b32 	%r866, {%rs579, %rs580};
	mov.b32 	%r867, {%rs581, %rs582};
	mov.b32 	%r876, {%rs583, %rs584};
	mov.b32 	%r877, {%rs585, %rs586};
	mov.b32 	%r886, {%rs587, %rs588};
	mov.b32 	%r887, {%rs589, %rs590};
	mov.b32 	%r896, {%rs591, %rs592};
	mov.b32 	%r897, {%rs593, %rs594};
	mov.b32 	%r906, {%rs595, %rs596};
	mov.b32 	%r907, {%rs597, %rs598};
	mov.b32 	%r916, {%rs599, %rs600};
	mov.b32 	%r917, {%rs601, %rs602};
	mov.b32 	%r926, {%rs603, %rs604};
	mov.b32 	%r927, {%rs605, %rs606};
	mov.b32 	%r936, {%rs607, %rs608};
	mov.b32 	%r937, {%rs609, %rs610};
	mov.b32 	%r946, {%rs611, %rs612};
	mov.b32 	%r947, {%rs613, %rs614};
	mov.b32 	%r956, {%rs615, %rs616};
	mov.b32 	%r957, {%rs617, %rs618};
	mov.b32 	%r966, {%rs619, %rs620};
	mov.b32 	%r967, {%rs621, %rs622};
	mov.b32 	%r976, {%rs623, %rs624};
	mov.b32 	%r977, {%rs625, %rs626};
	mov.b32 	%r986, {%rs627, %rs628};
	mov.b32 	%r987, {%rs629, %rs630};
	mov.b32 	%r996, {%rs631, %rs632};
	mov.b32 	%r997, {%rs633, %rs634};
	mov.b32 	%r1006, {%rs635, %rs636};
	mov.b32 	%r1007, {%rs637, %rs638};
	mov.b32 	%r1016, {%rs639, %rs640};
	mov.b32 	%r1017, {%rs641, %rs642};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r706, %r707 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1363, %r1364 }, { %r706, %r707 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r716, %r717 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1365, %r1366 }, { %r716, %r717 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r726, %r727 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1359, %r1360 }, { %r726, %r727 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r736, %r737 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1361, %r1362 }, { %r736, %r737 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r746, %r747 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1355, %r1356 }, { %r746, %r747 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r756, %r757 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1357, %r1358 }, { %r756, %r757 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r766, %r767 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1351, %r1352 }, { %r766, %r767 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r776, %r777 }, { %r1379, %r1380, %r1381, %r1382 }, { %r1353, %r1354 }, { %r776, %r777 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r786, %r787 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1363, %r1364 }, { %r786, %r787 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r796, %r797 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1365, %r1366 }, { %r796, %r797 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r806, %r807 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1359, %r1360 }, { %r806, %r807 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r816, %r817 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1361, %r1362 }, { %r816, %r817 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r826, %r827 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1355, %r1356 }, { %r826, %r827 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r836, %r837 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1357, %r1358 }, { %r836, %r837 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r846, %r847 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1351, %r1352 }, { %r846, %r847 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r856, %r857 }, { %r1375, %r1376, %r1377, %r1378 }, { %r1353, %r1354 }, { %r856, %r857 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r866, %r867 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1363, %r1364 }, { %r866, %r867 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r876, %r877 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1365, %r1366 }, { %r876, %r877 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r886, %r887 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1359, %r1360 }, { %r886, %r887 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r896, %r897 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1361, %r1362 }, { %r896, %r897 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r906, %r907 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1355, %r1356 }, { %r906, %r907 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r916, %r917 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1357, %r1358 }, { %r916, %r917 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r926, %r927 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1351, %r1352 }, { %r926, %r927 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r936, %r937 }, { %r1371, %r1372, %r1373, %r1374 }, { %r1353, %r1354 }, { %r936, %r937 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r946, %r947 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1363, %r1364 }, { %r946, %r947 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r956, %r957 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1365, %r1366 }, { %r956, %r957 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r966, %r967 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1359, %r1360 }, { %r966, %r967 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r976, %r977 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1361, %r1362 }, { %r976, %r977 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r986, %r987 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1355, %r1356 }, { %r986, %r987 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r996, %r997 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1357, %r1358 }, { %r996, %r997 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1006, %r1007 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1351, %r1352 }, { %r1006, %r1007 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1016, %r1017 }, { %r1367, %r1368, %r1369, %r1370 }, { %r1353, %r1354 }, { %r1016, %r1017 };
	// end inline asm
	.loc	1 102 18
	add.s64 	%rd49, %rd12, %rd104;
	.loc	1 103 18
	add.s64 	%rd50, %rd11, %rd104;
	add.s64 	%rd51, %rd10, %rd104;
	add.s64 	%rd52, %rd9, %rd104;
	add.s64 	%rd53, %rd8, %rd104;
	.loc	1 93 22
	add.s64 	%rd54, %rd7, %rd104;
	add.s32 	%r1092, %r1386, 1;
	setp.lt.s32 	%p25, %r1092, 2;
	selp.b32 	%r1386, %r1092, 0, %p25;
	.loc	1 96 72
	setp.lt.s32 	%p26, %r1350, %r136;
	.loc	1 96 20
	shl.b32 	%r1093, %r1386, 13;
	add.s32 	%r1095, %r257, %r1093;
	bar.sync 	0;
	add.s32 	%r654, %r1095, %r256;
	add.s32 	%r656, %r1095, %r259;
	selp.b32 	%r1098, 16, 0, %p26;
	selp.b32 	%r657, %r1098, 0, %p24;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r654 + 0 ], [ %rd49 + 0 ], 0x10, %r657;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r656 + 0 ], [ %rd50 + 0 ], 0x10, %r657;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 20
	shl.b32 	%r1099, %r1386, 14;
	add.s32 	%r1101, %r261, %r1099;
	add.s32 	%r658, %r1101, %r256;
	add.s32 	%r660, %r1101, %r259;
	add.s32 	%r662, %r1101, %r263;
	add.s32 	%r664, %r1101, %r265;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r658 + 0 ], [ %rd51 + 0 ], 0x10, %r657;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r660 + 0 ], [ %rd52 + 0 ], 0x10, %r657;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r662 + 0 ], [ %rd53 + 0 ], 0x10, %r657;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r664 + 0 ], [ %rd54 + 0 ], 0x10, %r657;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1104, %r1385, 1;
	setp.lt.s32 	%p27, %r1104, 2;
	selp.b32 	%r1385, %r1104, 0, %p27;
	.loc	1 96 20
	shl.b32 	%r1105, %r1385, 13;
	add.s32 	%r1384, %r257, %r1105;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1106, %r1385, 14;
	add.s32 	%r1383, %r261, %r1106;
	.loc	1 96 20
	add.s32 	%r670, %r1384, %r277;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1379, %r1380, %r1381, %r1382 }, [ %r670 + 0 ];
	// end inline asm
	add.s32 	%r675, %r670, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1375, %r1376, %r1377, %r1378 }, [ %r675 + 0 ];
	// end inline asm
	add.s32 	%r680, %r670, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1371, %r1372, %r1373, %r1374 }, [ %r680 + 0 ];
	// end inline asm
	add.s32 	%r685, %r670, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1367, %r1368, %r1369, %r1370 }, [ %r685 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r690, %r1383, %r283;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1363, %r1364, %r1365, %r1366 }, [ %r690 + 0 ];
	// end inline asm
	add.s32 	%r695, %r690, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1359, %r1360, %r1361, %r1362 }, [ %r695 + 0 ];
	// end inline asm
	add.s32 	%r700, %r690, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1355, %r1356, %r1357, %r1358 }, [ %r700 + 0 ];
	// end inline asm
	add.s32 	%r705, %r690, 12288;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1351, %r1352, %r1353, %r1354 }, [ %r705 + 0 ];
	// end inline asm
	.loc	1 100 35
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r706, %r707 }, { %r710, %r711, %r712, %r713 }, { %r714, %r715 }, { %r706, %r707 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r716, %r717 }, { %r710, %r711, %r712, %r713 }, { %r724, %r725 }, { %r716, %r717 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r726, %r727 }, { %r710, %r711, %r712, %r713 }, { %r734, %r735 }, { %r726, %r727 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r736, %r737 }, { %r710, %r711, %r712, %r713 }, { %r744, %r745 }, { %r736, %r737 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r746, %r747 }, { %r710, %r711, %r712, %r713 }, { %r754, %r755 }, { %r746, %r747 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r756, %r757 }, { %r710, %r711, %r712, %r713 }, { %r764, %r765 }, { %r756, %r757 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r766, %r767 }, { %r710, %r711, %r712, %r713 }, { %r774, %r775 }, { %r766, %r767 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r776, %r777 }, { %r710, %r711, %r712, %r713 }, { %r784, %r785 }, { %r776, %r777 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r786, %r787 }, { %r790, %r791, %r792, %r793 }, { %r714, %r715 }, { %r786, %r787 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r796, %r797 }, { %r790, %r791, %r792, %r793 }, { %r724, %r725 }, { %r796, %r797 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r806, %r807 }, { %r790, %r791, %r792, %r793 }, { %r734, %r735 }, { %r806, %r807 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r816, %r817 }, { %r790, %r791, %r792, %r793 }, { %r744, %r745 }, { %r816, %r817 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r826, %r827 }, { %r790, %r791, %r792, %r793 }, { %r754, %r755 }, { %r826, %r827 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r836, %r837 }, { %r790, %r791, %r792, %r793 }, { %r764, %r765 }, { %r836, %r837 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r846, %r847 }, { %r790, %r791, %r792, %r793 }, { %r774, %r775 }, { %r846, %r847 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r856, %r857 }, { %r790, %r791, %r792, %r793 }, { %r784, %r785 }, { %r856, %r857 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r866, %r867 }, { %r870, %r871, %r872, %r873 }, { %r714, %r715 }, { %r866, %r867 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r876, %r877 }, { %r870, %r871, %r872, %r873 }, { %r724, %r725 }, { %r876, %r877 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r886, %r887 }, { %r870, %r871, %r872, %r873 }, { %r734, %r735 }, { %r886, %r887 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r896, %r897 }, { %r870, %r871, %r872, %r873 }, { %r744, %r745 }, { %r896, %r897 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r906, %r907 }, { %r870, %r871, %r872, %r873 }, { %r754, %r755 }, { %r906, %r907 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r916, %r917 }, { %r870, %r871, %r872, %r873 }, { %r764, %r765 }, { %r916, %r917 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r926, %r927 }, { %r870, %r871, %r872, %r873 }, { %r774, %r775 }, { %r926, %r927 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r936, %r937 }, { %r870, %r871, %r872, %r873 }, { %r784, %r785 }, { %r936, %r937 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r946, %r947 }, { %r950, %r951, %r952, %r953 }, { %r714, %r715 }, { %r946, %r947 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r956, %r957 }, { %r950, %r951, %r952, %r953 }, { %r724, %r725 }, { %r956, %r957 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r966, %r967 }, { %r950, %r951, %r952, %r953 }, { %r734, %r735 }, { %r966, %r967 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r976, %r977 }, { %r950, %r951, %r952, %r953 }, { %r744, %r745 }, { %r976, %r977 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r986, %r987 }, { %r950, %r951, %r952, %r953 }, { %r754, %r755 }, { %r986, %r987 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r996, %r997 }, { %r950, %r951, %r952, %r953 }, { %r764, %r765 }, { %r996, %r997 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1006, %r1007 }, { %r950, %r951, %r952, %r953 }, { %r774, %r775 }, { %r1006, %r1007 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r1016, %r1017 }, { %r950, %r951, %r952, %r953 }, { %r784, %r785 }, { %r1016, %r1017 };
	// end inline asm
	mov.b32 	{%rs515, %rs516}, %r706;
	mov.b32 	{%rs517, %rs518}, %r707;
	mov.b32 	{%rs519, %rs520}, %r716;
	mov.b32 	{%rs521, %rs522}, %r717;
	mov.b32 	{%rs523, %rs524}, %r726;
	mov.b32 	{%rs525, %rs526}, %r727;
	mov.b32 	{%rs527, %rs528}, %r736;
	mov.b32 	{%rs529, %rs530}, %r737;
	mov.b32 	{%rs531, %rs532}, %r746;
	mov.b32 	{%rs533, %rs534}, %r747;
	mov.b32 	{%rs535, %rs536}, %r756;
	mov.b32 	{%rs537, %rs538}, %r757;
	mov.b32 	{%rs539, %rs540}, %r766;
	mov.b32 	{%rs541, %rs542}, %r767;
	mov.b32 	{%rs543, %rs544}, %r776;
	mov.b32 	{%rs545, %rs546}, %r777;
	mov.b32 	{%rs547, %rs548}, %r786;
	mov.b32 	{%rs549, %rs550}, %r787;
	mov.b32 	{%rs551, %rs552}, %r796;
	mov.b32 	{%rs553, %rs554}, %r797;
	mov.b32 	{%rs555, %rs556}, %r806;
	mov.b32 	{%rs557, %rs558}, %r807;
	mov.b32 	{%rs559, %rs560}, %r816;
	mov.b32 	{%rs561, %rs562}, %r817;
	mov.b32 	{%rs563, %rs564}, %r826;
	mov.b32 	{%rs565, %rs566}, %r827;
	mov.b32 	{%rs567, %rs568}, %r836;
	mov.b32 	{%rs569, %rs570}, %r837;
	mov.b32 	{%rs571, %rs572}, %r846;
	mov.b32 	{%rs573, %rs574}, %r847;
	mov.b32 	{%rs575, %rs576}, %r856;
	mov.b32 	{%rs577, %rs578}, %r857;
	mov.b32 	{%rs579, %rs580}, %r866;
	mov.b32 	{%rs581, %rs582}, %r867;
	mov.b32 	{%rs583, %rs584}, %r876;
	mov.b32 	{%rs585, %rs586}, %r877;
	mov.b32 	{%rs587, %rs588}, %r886;
	mov.b32 	{%rs589, %rs590}, %r887;
	mov.b32 	{%rs591, %rs592}, %r896;
	mov.b32 	{%rs593, %rs594}, %r897;
	mov.b32 	{%rs595, %rs596}, %r906;
	mov.b32 	{%rs597, %rs598}, %r907;
	mov.b32 	{%rs599, %rs600}, %r916;
	mov.b32 	{%rs601, %rs602}, %r917;
	mov.b32 	{%rs603, %rs604}, %r926;
	mov.b32 	{%rs605, %rs606}, %r927;
	mov.b32 	{%rs607, %rs608}, %r936;
	mov.b32 	{%rs609, %rs610}, %r937;
	mov.b32 	{%rs611, %rs612}, %r946;
	mov.b32 	{%rs613, %rs614}, %r947;
	mov.b32 	{%rs615, %rs616}, %r956;
	mov.b32 	{%rs617, %rs618}, %r957;
	mov.b32 	{%rs619, %rs620}, %r966;
	mov.b32 	{%rs621, %rs622}, %r967;
	mov.b32 	{%rs623, %rs624}, %r976;
	mov.b32 	{%rs625, %rs626}, %r977;
	mov.b32 	{%rs627, %rs628}, %r986;
	mov.b32 	{%rs629, %rs630}, %r987;
	mov.b32 	{%rs631, %rs632}, %r996;
	mov.b32 	{%rs633, %rs634}, %r997;
	mov.b32 	{%rs635, %rs636}, %r1006;
	mov.b32 	{%rs637, %rs638}, %r1007;
	mov.b32 	{%rs639, %rs640}, %r1016;
	mov.b32 	{%rs641, %rs642}, %r1017;
	.loc	1 93 22
	add.s32 	%r1387, %r1387, 1;
	add.s64 	%rd104, %rd104, 64;
	add.s32 	%r1350, %r1350, 32;
	setp.lt.s32 	%p28, %r1387, %r8;
	@%p28 bra 	$L__BB0_2;
$L__BB0_3:
	.loc	1 74 51
	and.b32  	%r1237, %r4, 7;
	.loc	1 74 38
	or.b32  	%r1238, %r1237, %r1;
	or.b32  	%r1239, %r1238, 120;
	.loc	1 83 33
	setp.lt.s32 	%p45, %r1239, %r134;
	.loc	1 75 51
	and.b32  	%r1240, %r6, 248;
	.loc	1 75 38
	or.b32  	%r1241, %r5, %r1240;
	.loc	1 83 58
	setp.lt.s32 	%p46, %r1241, %r135;
	.loc	1 83 39
	and.pred  	%p44, %p45, %p46;
	.loc	1 74 38
	or.b32  	%r1242, %r1238, 112;
	.loc	1 83 33
	setp.lt.s32 	%p47, %r1242, %r134;
	.loc	1 83 39
	and.pred  	%p43, %p47, %p46;
	.loc	1 74 38
	or.b32  	%r1243, %r1238, 104;
	.loc	1 83 33
	setp.lt.s32 	%p48, %r1243, %r134;
	.loc	1 83 39
	and.pred  	%p42, %p48, %p46;
	.loc	1 74 38
	or.b32  	%r1244, %r1238, 96;
	.loc	1 83 33
	setp.lt.s32 	%p49, %r1244, %r134;
	.loc	1 83 39
	and.pred  	%p41, %p49, %p46;
	.loc	1 74 38
	or.b32  	%r1245, %r1238, 88;
	.loc	1 83 33
	setp.lt.s32 	%p50, %r1245, %r134;
	.loc	1 83 39
	and.pred  	%p40, %p50, %p46;
	.loc	1 74 38
	or.b32  	%r1246, %r1238, 80;
	.loc	1 83 33
	setp.lt.s32 	%p51, %r1246, %r134;
	.loc	1 83 39
	and.pred  	%p39, %p51, %p46;
	.loc	1 74 38
	or.b32  	%r1247, %r1238, 72;
	.loc	1 83 33
	setp.lt.s32 	%p52, %r1247, %r134;
	.loc	1 83 39
	and.pred  	%p38, %p52, %p46;
	.loc	1 74 38
	or.b32  	%r1248, %r1238, 64;
	.loc	1 83 33
	setp.lt.s32 	%p53, %r1248, %r134;
	.loc	1 83 39
	and.pred  	%p37, %p53, %p46;
	.loc	1 74 38
	or.b32  	%r1249, %r1238, 56;
	.loc	1 83 33
	setp.lt.s32 	%p54, %r1249, %r134;
	.loc	1 83 39
	and.pred  	%p36, %p54, %p46;
	.loc	1 74 38
	or.b32  	%r1250, %r1238, 48;
	.loc	1 83 33
	setp.lt.s32 	%p55, %r1250, %r134;
	.loc	1 83 39
	and.pred  	%p35, %p55, %p46;
	.loc	1 74 38
	or.b32  	%r1251, %r1238, 40;
	.loc	1 83 33
	setp.lt.s32 	%p56, %r1251, %r134;
	.loc	1 83 39
	and.pred  	%p34, %p56, %p46;
	.loc	1 74 38
	or.b32  	%r1252, %r1238, 32;
	.loc	1 83 33
	setp.lt.s32 	%p57, %r1252, %r134;
	.loc	1 83 39
	and.pred  	%p33, %p57, %p46;
	.loc	1 74 38
	or.b32  	%r1253, %r1238, 24;
	.loc	1 83 33
	setp.lt.s32 	%p58, %r1253, %r134;
	.loc	1 83 39
	and.pred  	%p32, %p58, %p46;
	.loc	1 74 38
	or.b32  	%r1254, %r1238, 16;
	.loc	1 83 33
	setp.lt.s32 	%p59, %r1254, %r134;
	.loc	1 83 39
	and.pred  	%p31, %p59, %p46;
	.loc	1 74 38
	or.b32  	%r1255, %r1238, 8;
	.loc	1 83 33
	setp.lt.s32 	%p60, %r1255, %r134;
	.loc	1 83 39
	and.pred  	%p30, %p60, %p46;
	.loc	1 83 33
	setp.lt.s32 	%p61, %r1238, %r134;
	.loc	1 83 39
	and.pred  	%p29, %p61, %p46;
	.loc	1 82 33
	mul.lo.s32 	%r1256, %r1239, %r137;
	.loc	1 82 21
	mul.wide.s32 	%rd71, %r1256, 2;
	add.s64 	%rd72, %rd17, %rd71;
	.loc	1 82 52
	mul.wide.s32 	%rd73, %r1241, 2;
	add.s64 	%rd70, %rd72, %rd73;
	.loc	1 82 33
	shl.b32 	%r1257, %r137, 3;
	sub.s32 	%r1258, %r1256, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd74, %r1258, 2;
	add.s64 	%rd75, %rd17, %rd74;
	.loc	1 82 52
	add.s64 	%rd69, %rd75, %rd73;
	.loc	1 82 33
	sub.s32 	%r1259, %r1258, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd76, %r1259, 2;
	add.s64 	%rd77, %rd17, %rd76;
	.loc	1 82 52
	add.s64 	%rd68, %rd77, %rd73;
	.loc	1 82 33
	sub.s32 	%r1260, %r1259, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd78, %r1260, 2;
	add.s64 	%rd79, %rd17, %rd78;
	.loc	1 82 52
	add.s64 	%rd67, %rd79, %rd73;
	.loc	1 82 33
	sub.s32 	%r1261, %r1260, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd80, %r1261, 2;
	add.s64 	%rd81, %rd17, %rd80;
	.loc	1 82 52
	add.s64 	%rd66, %rd81, %rd73;
	.loc	1 82 33
	sub.s32 	%r1262, %r1261, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd82, %r1262, 2;
	add.s64 	%rd83, %rd17, %rd82;
	.loc	1 82 52
	add.s64 	%rd65, %rd83, %rd73;
	.loc	1 82 33
	sub.s32 	%r1263, %r1262, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd84, %r1263, 2;
	add.s64 	%rd85, %rd17, %rd84;
	.loc	1 82 52
	add.s64 	%rd64, %rd85, %rd73;
	.loc	1 82 33
	sub.s32 	%r1264, %r1263, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd86, %r1264, 2;
	add.s64 	%rd87, %rd17, %rd86;
	.loc	1 82 52
	add.s64 	%rd63, %rd87, %rd73;
	.loc	1 82 33
	sub.s32 	%r1265, %r1264, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd88, %r1265, 2;
	add.s64 	%rd89, %rd17, %rd88;
	.loc	1 82 52
	add.s64 	%rd62, %rd89, %rd73;
	.loc	1 82 33
	sub.s32 	%r1266, %r1265, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd90, %r1266, 2;
	add.s64 	%rd91, %rd17, %rd90;
	.loc	1 82 52
	add.s64 	%rd61, %rd91, %rd73;
	.loc	1 82 33
	sub.s32 	%r1267, %r1266, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd92, %r1267, 2;
	add.s64 	%rd93, %rd17, %rd92;
	.loc	1 82 52
	add.s64 	%rd60, %rd93, %rd73;
	.loc	1 82 33
	sub.s32 	%r1268, %r1267, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd94, %r1268, 2;
	add.s64 	%rd95, %rd17, %rd94;
	.loc	1 82 52
	add.s64 	%rd59, %rd95, %rd73;
	.loc	1 82 33
	sub.s32 	%r1269, %r1268, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd96, %r1269, 2;
	add.s64 	%rd97, %rd17, %rd96;
	.loc	1 82 52
	add.s64 	%rd58, %rd97, %rd73;
	.loc	1 82 33
	sub.s32 	%r1270, %r1269, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd98, %r1270, 2;
	add.s64 	%rd99, %rd17, %rd98;
	.loc	1 82 52
	add.s64 	%rd57, %rd99, %rd73;
	.loc	1 82 33
	sub.s32 	%r1271, %r1270, %r1257;
	.loc	1 82 21
	mul.wide.s32 	%rd100, %r1271, 2;
	add.s64 	%rd101, %rd17, %rd100;
	.loc	1 82 52
	add.s64 	%rd56, %rd101, %rd73;
	.loc	1 82 33
	mul.lo.s32 	%r1272, %r1238, %r137;
	.loc	1 82 21
	mul.wide.s32 	%rd102, %r1272, 2;
	add.s64 	%rd103, %rd17, %rd102;
	.loc	1 82 52
	add.s64 	%rd55, %rd103, %rd73;
	.loc	1 93 22
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	.loc	1 129 21
	shr.u32 	%r1273, %r3, 2;
	shl.b32 	%r1274, %r2, 1;
	and.b32  	%r1275, %r1274, 6;
	or.b32  	%r1276, %r1273, %r16;
	or.b32  	%r1277, %r35, %r1275;
	mad.lo.s32 	%r1278, %r1276, 264, %r1277;
	shl.b32 	%r1279, %r1278, 1;
	add.s32 	%r1281, %r257, %r1279;
	mov.b32 	%r1282, {%rs515, %rs516};
	st.shared.b32 	[%r1281], %r1282;
	mov.b32 	%r1283, {%rs517, %rs518};
	st.shared.b32 	[%r1281+4224], %r1283;
	mov.b32 	%r1284, {%rs519, %rs520};
	st.shared.b32 	[%r1281+64], %r1284;
	mov.b32 	%r1285, {%rs521, %rs522};
	st.shared.b32 	[%r1281+4288], %r1285;
	mov.b32 	%r1286, {%rs523, %rs524};
	st.shared.b32 	[%r1281+128], %r1286;
	mov.b32 	%r1287, {%rs525, %rs526};
	st.shared.b32 	[%r1281+4352], %r1287;
	mov.b32 	%r1288, {%rs527, %rs528};
	st.shared.b32 	[%r1281+192], %r1288;
	mov.b32 	%r1289, {%rs529, %rs530};
	st.shared.b32 	[%r1281+4416], %r1289;
	mov.b32 	%r1290, {%rs531, %rs532};
	st.shared.b32 	[%r1281+256], %r1290;
	mov.b32 	%r1291, {%rs533, %rs534};
	st.shared.b32 	[%r1281+4480], %r1291;
	mov.b32 	%r1292, {%rs535, %rs536};
	st.shared.b32 	[%r1281+320], %r1292;
	mov.b32 	%r1293, {%rs537, %rs538};
	st.shared.b32 	[%r1281+4544], %r1293;
	mov.b32 	%r1294, {%rs539, %rs540};
	st.shared.b32 	[%r1281+384], %r1294;
	mov.b32 	%r1295, {%rs541, %rs542};
	st.shared.b32 	[%r1281+4608], %r1295;
	mov.b32 	%r1296, {%rs543, %rs544};
	st.shared.b32 	[%r1281+448], %r1296;
	mov.b32 	%r1297, {%rs545, %rs546};
	st.shared.b32 	[%r1281+4672], %r1297;
	bar.sync 	0;
	shl.b32 	%r1298, %r3, 3;
	mad.lo.s32 	%r1299, %r1237, 264, %r1298;
	shl.b32 	%r1300, %r1299, 1;
	add.s32 	%r1301, %r257, %r1300;
	ld.shared.v4.u32 	{%r1173, %r1174, %r1175, %r1176}, [%r1301];
	ld.shared.v4.u32 	{%r1177, %r1178, %r1179, %r1180}, [%r1301+4224];
	ld.shared.v4.u32 	{%r1181, %r1182, %r1183, %r1184}, [%r1301+8448];
	ld.shared.v4.u32 	{%r1185, %r1186, %r1187, %r1188}, [%r1301+12672];
	bar.sync 	0;
	mov.b32 	%r1302, {%rs547, %rs548};
	st.shared.b32 	[%r1281], %r1302;
	mov.b32 	%r1303, {%rs549, %rs550};
	st.shared.b32 	[%r1281+4224], %r1303;
	mov.b32 	%r1304, {%rs551, %rs552};
	st.shared.b32 	[%r1281+64], %r1304;
	mov.b32 	%r1305, {%rs553, %rs554};
	st.shared.b32 	[%r1281+4288], %r1305;
	mov.b32 	%r1306, {%rs555, %rs556};
	st.shared.b32 	[%r1281+128], %r1306;
	mov.b32 	%r1307, {%rs557, %rs558};
	st.shared.b32 	[%r1281+4352], %r1307;
	mov.b32 	%r1308, {%rs559, %rs560};
	st.shared.b32 	[%r1281+192], %r1308;
	mov.b32 	%r1309, {%rs561, %rs562};
	st.shared.b32 	[%r1281+4416], %r1309;
	mov.b32 	%r1310, {%rs563, %rs564};
	st.shared.b32 	[%r1281+256], %r1310;
	mov.b32 	%r1311, {%rs565, %rs566};
	st.shared.b32 	[%r1281+4480], %r1311;
	mov.b32 	%r1312, {%rs567, %rs568};
	st.shared.b32 	[%r1281+320], %r1312;
	mov.b32 	%r1313, {%rs569, %rs570};
	st.shared.b32 	[%r1281+4544], %r1313;
	mov.b32 	%r1314, {%rs571, %rs572};
	st.shared.b32 	[%r1281+384], %r1314;
	mov.b32 	%r1315, {%rs573, %rs574};
	st.shared.b32 	[%r1281+4608], %r1315;
	mov.b32 	%r1316, {%rs575, %rs576};
	st.shared.b32 	[%r1281+448], %r1316;
	mov.b32 	%r1317, {%rs577, %rs578};
	st.shared.b32 	[%r1281+4672], %r1317;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1189, %r1190, %r1191, %r1192}, [%r1301];
	ld.shared.v4.u32 	{%r1193, %r1194, %r1195, %r1196}, [%r1301+4224];
	ld.shared.v4.u32 	{%r1197, %r1198, %r1199, %r1200}, [%r1301+8448];
	ld.shared.v4.u32 	{%r1201, %r1202, %r1203, %r1204}, [%r1301+12672];
	bar.sync 	0;
	mov.b32 	%r1318, {%rs579, %rs580};
	st.shared.b32 	[%r1281], %r1318;
	mov.b32 	%r1319, {%rs581, %rs582};
	st.shared.b32 	[%r1281+4224], %r1319;
	mov.b32 	%r1320, {%rs583, %rs584};
	st.shared.b32 	[%r1281+64], %r1320;
	mov.b32 	%r1321, {%rs585, %rs586};
	st.shared.b32 	[%r1281+4288], %r1321;
	mov.b32 	%r1322, {%rs587, %rs588};
	st.shared.b32 	[%r1281+128], %r1322;
	mov.b32 	%r1323, {%rs589, %rs590};
	st.shared.b32 	[%r1281+4352], %r1323;
	mov.b32 	%r1324, {%rs591, %rs592};
	st.shared.b32 	[%r1281+192], %r1324;
	mov.b32 	%r1325, {%rs593, %rs594};
	st.shared.b32 	[%r1281+4416], %r1325;
	mov.b32 	%r1326, {%rs595, %rs596};
	st.shared.b32 	[%r1281+256], %r1326;
	mov.b32 	%r1327, {%rs597, %rs598};
	st.shared.b32 	[%r1281+4480], %r1327;
	mov.b32 	%r1328, {%rs599, %rs600};
	st.shared.b32 	[%r1281+320], %r1328;
	mov.b32 	%r1329, {%rs601, %rs602};
	st.shared.b32 	[%r1281+4544], %r1329;
	mov.b32 	%r1330, {%rs603, %rs604};
	st.shared.b32 	[%r1281+384], %r1330;
	mov.b32 	%r1331, {%rs605, %rs606};
	st.shared.b32 	[%r1281+4608], %r1331;
	mov.b32 	%r1332, {%rs607, %rs608};
	st.shared.b32 	[%r1281+448], %r1332;
	mov.b32 	%r1333, {%rs609, %rs610};
	st.shared.b32 	[%r1281+4672], %r1333;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1205, %r1206, %r1207, %r1208}, [%r1301];
	ld.shared.v4.u32 	{%r1209, %r1210, %r1211, %r1212}, [%r1301+4224];
	ld.shared.v4.u32 	{%r1213, %r1214, %r1215, %r1216}, [%r1301+8448];
	ld.shared.v4.u32 	{%r1217, %r1218, %r1219, %r1220}, [%r1301+12672];
	bar.sync 	0;
	mov.b32 	%r1334, {%rs611, %rs612};
	st.shared.b32 	[%r1281], %r1334;
	mov.b32 	%r1335, {%rs613, %rs614};
	st.shared.b32 	[%r1281+4224], %r1335;
	mov.b32 	%r1336, {%rs615, %rs616};
	st.shared.b32 	[%r1281+64], %r1336;
	mov.b32 	%r1337, {%rs617, %rs618};
	st.shared.b32 	[%r1281+4288], %r1337;
	mov.b32 	%r1338, {%rs619, %rs620};
	st.shared.b32 	[%r1281+128], %r1338;
	mov.b32 	%r1339, {%rs621, %rs622};
	st.shared.b32 	[%r1281+4352], %r1339;
	mov.b32 	%r1340, {%rs623, %rs624};
	st.shared.b32 	[%r1281+192], %r1340;
	mov.b32 	%r1341, {%rs625, %rs626};
	st.shared.b32 	[%r1281+4416], %r1341;
	mov.b32 	%r1342, {%rs627, %rs628};
	st.shared.b32 	[%r1281+256], %r1342;
	mov.b32 	%r1343, {%rs629, %rs630};
	st.shared.b32 	[%r1281+4480], %r1343;
	mov.b32 	%r1344, {%rs631, %rs632};
	st.shared.b32 	[%r1281+320], %r1344;
	mov.b32 	%r1345, {%rs633, %rs634};
	st.shared.b32 	[%r1281+4544], %r1345;
	mov.b32 	%r1346, {%rs635, %rs636};
	st.shared.b32 	[%r1281+384], %r1346;
	mov.b32 	%r1347, {%rs637, %rs638};
	st.shared.b32 	[%r1281+4608], %r1347;
	mov.b32 	%r1348, {%rs639, %rs640};
	st.shared.b32 	[%r1281+448], %r1348;
	mov.b32 	%r1349, {%rs641, %rs642};
	st.shared.b32 	[%r1281+4672], %r1349;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1221, %r1222, %r1223, %r1224}, [%r1301];
	ld.shared.v4.u32 	{%r1225, %r1226, %r1227, %r1228}, [%r1301+4224];
	ld.shared.v4.u32 	{%r1229, %r1230, %r1231, %r1232}, [%r1301+8448];
	ld.shared.v4.u32 	{%r1233, %r1234, %r1235, %r1236}, [%r1301+12672];
	// begin inline asm
	@%p29 st.global.v4.b32 [ %rd55 + 0 ], { %r1173, %r1174, %r1175, %r1176 };
	// end inline asm
	// begin inline asm
	@%p30 st.global.v4.b32 [ %rd56 + 0 ], { %r1177, %r1178, %r1179, %r1180 };
	// end inline asm
	// begin inline asm
	@%p31 st.global.v4.b32 [ %rd57 + 0 ], { %r1181, %r1182, %r1183, %r1184 };
	// end inline asm
	// begin inline asm
	@%p32 st.global.v4.b32 [ %rd58 + 0 ], { %r1185, %r1186, %r1187, %r1188 };
	// end inline asm
	// begin inline asm
	@%p33 st.global.v4.b32 [ %rd59 + 0 ], { %r1189, %r1190, %r1191, %r1192 };
	// end inline asm
	// begin inline asm
	@%p34 st.global.v4.b32 [ %rd60 + 0 ], { %r1193, %r1194, %r1195, %r1196 };
	// end inline asm
	// begin inline asm
	@%p35 st.global.v4.b32 [ %rd61 + 0 ], { %r1197, %r1198, %r1199, %r1200 };
	// end inline asm
	// begin inline asm
	@%p36 st.global.v4.b32 [ %rd62 + 0 ], { %r1201, %r1202, %r1203, %r1204 };
	// end inline asm
	// begin inline asm
	@%p37 st.global.v4.b32 [ %rd63 + 0 ], { %r1205, %r1206, %r1207, %r1208 };
	// end inline asm
	// begin inline asm
	@%p38 st.global.v4.b32 [ %rd64 + 0 ], { %r1209, %r1210, %r1211, %r1212 };
	// end inline asm
	// begin inline asm
	@%p39 st.global.v4.b32 [ %rd65 + 0 ], { %r1213, %r1214, %r1215, %r1216 };
	// end inline asm
	// begin inline asm
	@%p40 st.global.v4.b32 [ %rd66 + 0 ], { %r1217, %r1218, %r1219, %r1220 };
	// end inline asm
	// begin inline asm
	@%p41 st.global.v4.b32 [ %rd67 + 0 ], { %r1221, %r1222, %r1223, %r1224 };
	// end inline asm
	// begin inline asm
	@%p42 st.global.v4.b32 [ %rd68 + 0 ], { %r1225, %r1226, %r1227, %r1228 };
	// end inline asm
	// begin inline asm
	@%p43 st.global.v4.b32 [ %rd69 + 0 ], { %r1229, %r1230, %r1231, %r1232 };
	// end inline asm
	// begin inline asm
	@%p44 st.global.v4.b32 [ %rd70 + 0 ], { %r1233, %r1234, %r1235, %r1236 };
	// end inline asm
	.loc	1 129 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/PycharmProjects/tritontest/compile_matmul_kernel_transpose_b.py"
	.file	2 "/home/mike/PycharmProjects/tritontest/.venv/lib/python3.11/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 211
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 80
.b8 121
.b8 99
.b8 104
.b8 97
.b8 114
.b8 109
.b8 80
.b8 114
.b8 111
.b8 106
.b8 101
.b8 99
.b8 116
.b8 115
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 116
.b8 101
.b8 115
.b8 116
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 104
.b8 4
.b32 104
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 104
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 104
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_4_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_4_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_4_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_4_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_4_FUNCTION_NAME "matmul_kernel_transpose_b"
